### ISSUE TITLE
具体啥时间啊

### ISSUE THREAD

**Issue by yaya2212** [Qihoo360/RePlugin#1]
期待

**Comment by ownwell** [comment]
GMTC不是说是七月么

**Comment by jiongxuan** [comment]
您好，首先非常感谢您对我们RePlugin工作的关注！
我们计划在7月初开源。近期会先出一些相关的文章。敬请留意。
期待早日能一起合作！

**Comment by jiongxuan** [comment]
号外！RePlugin已经开源，欢迎阅览，提出指正建议。
