### ISSUE TITLE
能适配classpath 'com.android.tools.build:gradle:3.5.3'吗？

### ISSUE THREAD

**Issue by zhouzhuo810** [Qihoo360/RePlugin#1007]
#### 问题详细描述 Detailed description of the problem
A problem occurred configuring project ':app'.
> groovy.lang.MissingMethodException: No signature of method: com.android.build.gradle.internal.scope.VariantScopeImpl.getMergeAssetsTask() is applicable for argument types: () values: []

#### 复现问题步骤 Steps to reproduce the problem
1. classpath 'com.android.tools.build:gradle:3.5.3'
2. distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:最新版
rePlugin-plugin-lib/gradle Version:最新版

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context

```
A problem occurred configuring project ':app'.
> groovy.lang.MissingMethodException: No signature of method: com.android.build.gradle.internal.scope.VariantScopeImpl.getMergeAssetsTask() is applicable for argument types: () values: []
```

**Comment by krubo** [comment]
已适配
