### ISSUE TITLE
使用插件版本2覆盖插件1，打开并运行插件2，然后再用插件3覆盖插件2，重启程序后仍是插件2。

### ISSUE THREAD

**Issue by SuperChandler** [Qihoo360/RePlugin#1008]
#### 问题详细描述 
    使用插件版本2覆盖插件1，打开并运行插件2，然后再用插件3覆盖插件2，重启程序后仍是插件2。

#### 复现问题步骤 Steps to reproduce the problem
1. 宿主安装插件1
2. 宿主安装插件2
3. 宿主打开插件2（即插件2正在运行）
4. 宿主安装插件3,后重启应用程序
5. 重启后，仍显示插件2.

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
    com.qihoo360.replugin:replugin-host-gradle:2.3.4
rePlugin-plugin-lib/gradle Version:
   com.qihoo360.replugin:replugin-plugin-gradle:2.3.4

Android API Version：9
Android 手机型号&ROM(Phone model & ROM):

**Comment by wangrui112211** [comment]
same problem
宿主安装插件1,更新插件1的代码，使用gradle reInstallAndRunPlungin 覆盖更新后，还是原来的代码

**Comment by krubo** [comment]
1、不能以同版本插件进行覆盖
2、新插件覆盖升级后，需要重启进程才能生效
