### ISSUE TITLE
demo host 运行失败，出现很多activity 名称问题 AAPT: error: attribute 'android:name' in <activity> tag must be a valid Java class name.

### ISSUE THREAD

**Issue by lwl49** [Qihoo360/RePlugin#1014]
#### 复现问题步骤 Steps to reproduce the problem
1.  studio  4.0.0  api  28 用了androidx
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.3.4
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context
报错的信息 loader.a.ActivityN1NRTS0 一大串，host-gradle 里面的activity 报错
<activity android:name='task &apos;:app:generateDebugBuildConfig&apos; property &apos;appPackageName&apos;.loader.a.ActivityN1NRTS0' android:configChanges='keyboard|keyboardHidden|orientation|screenSize' android:exported='false' android:screenOrientation='portrait' android:theme='@android:style/Theme.Translucent.NoTitleBar' />
  <activity android:name='task &apos;:app:generateDebugBuildConfig&apos; property &apos;appPackageName&apos;.loader.a.ActivityN1NRTS1' android:configChanges='keyboard|keyboardHidden|orientation|screenSize' android:exported='false' android:screenOrientation='portrait' android:theme='@android:style/Theme.Translucent.NoTitleBar' />

异常
F:\lwlgit\360\RePlugin\replugin-sample\host\app\build\intermediates\merged_manifests\debug\AndroidManifest.xml:288: AAPT: error: attribute 'android:name' in <activity> tag must be a valid Java class name

**Comment by chenfeichongqing** [comment]
楼主解决了，我是也是这种报错

**Comment by chenfeichongqing** [comment]
classpath "com.android.tools.build:gradle:3.4.0"  这个版本的可以

**Comment by krubo** [comment]
3.0.0版本支持了androidx

**Comment by RaymanMartin** [comment]
请问下4.1.0可以用吗？ 我切换了4.1.0之后，也会报这个异常

**Comment by krubo** [comment]
暂时未适配到4.1.0
