### ISSUE TITLE
关于后续规划的问题（是否有后期的规划）

### ISSUE THREAD

**Issue by ttxz** [Qihoo360/RePlugin#1015]
#### 问题详细描述 Detailed description of the problem
作者好，当时选用此框架，也是看360的开源力度比较高，确实对比了其他插件化开源项目，最终选择了`RePugin`框架，但是目前看已近一年没有更新了，而且许多新版本`Gradle`都不支持，不知道后续是如何考虑的，能不能说下后续的计划？如果不维护，也请说出来，我们好有替换方案！！！

**Comment by Poney1** [comment]
去搜索一下RePlugin Androidx ,有一些其他网友支持的 升级androidx的项目，可以弄过来用。

**Comment by krubo** [comment]
会继续维护

**Comment by ttxz** [comment]
@krubo 您好，终于收到回复，有什么计划可否告知一下，谢谢！
