### ISSUE TITLE
调起自己插件时报错：AppCompat does not support the current theme features

### ISSUE THREAD

**Issue by MaxWhite1** [Qihoo360/RePlugin#1016]
已经在宿主集成appcompat-v7,主题也一样
java.lang.RuntimeException: Unable to start activity ComponentInfo{platform.haohai.com.myowner/platform.haohai.com.myowner.loader.a.ActivityN1NRNTS2}: java.lang.IllegalArgumentException: AppCompat does not support the current theme features: { windowActionBar: false, windowActionBarOverlay: true, android:windowIsFloating: false, windowActionModeOverlay: false, windowNoTitle: false }

**Comment by krubo** [comment]
3.0.0版本支持了androidx
