### ISSUE TITLE
适配androidx  插件布局加载后莫名其妙的多了一些外边距

### ISSUE THREAD

**Issue by Poney1** [Qihoo360/RePlugin#1017]
#### 复现问题步骤  插件必现，宿主和插件都升级到androidx 了
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by krubo** [comment]
3.0.0版本适配了Androidx
