### ISSUE TITLE
按照快速上手集成，出现Error:Execution failed for task ':app:processDebugResources'.

### ISSUE THREAD

**Issue by xunhaifeng** [Qihoo360/RePlugin#102]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:2.1.0

**Android compile SDK version**:25

**Android ROM**:LG-H870DS

Error:Execution failed for task ':app:processDebugResources'.
> java.lang.NullPointerException (no error message)

**Comment by hezijie1234** [comment]
你的问题解决了吗？如果解决了帮帮我

**Comment by kezhijie** [comment]
将classpath 'com.qihoo360.replugin:replugin-host-gradle:2.1.1'换成classpath 'com.qihoo360.replugin:replugin-host-gradle:2.1.0'

**Comment by xunhaifeng** [comment]
更换完'com.qihoo360.replugin:replugin-host-gradle:2.1.0'，还是出现同一个问题的

**Comment by kezhijie** [comment]
我更换之后就好了，我再看看

**Comment by kezhijie** [comment]
你assets目录加plugins了吗

**Comment by xunhaifeng** [comment]
没加plugins,应该加吗

**Comment by kezhijie** [comment]
加

**Comment by xunhaifeng** [comment]
没效果滴

**Comment by hezijie1234** [comment]
嗯嗯，确实这个问题不知道怎么搞得！希望能尽快完善。

**Comment by xunhaifeng** [comment]
apply plugin: 'replugin-host-gradle'
apply plugin: 'com.android.application'  app/build 中这两个调下顺序就好了，不用改成2.1.0

**Comment by hezijie1234** [comment]
给一个大拇指，真的ok了。
