### ISSUE TITLE
Gradle Plugin 能同步更新到 7.0+么？

### ISSUE THREAD

**Issue by ArthurL602** [Qihoo360/RePlugin#1021]
#### 问题详细描述 Detailed description of the problem
现在 Gradle 已经7.0+了，Replugin gradle plugin 已经无法运行在新版本 Gradle 上了，请问有计划将 Replugin 的 Gradle Plugin 更新到 7.0+ 么？

#### 复现问题步骤 Steps to reproduce the problem
1.  无
2. 

#### 其它重要信息 Other important information
无

**Comment by ttxz** [comment]
支持一下，希望可以继续维护

**Comment by daosanqing** [comment]
支持一下，希望可以继续维护

**Comment by fenghuilu** [comment]
+1

**Comment by krubo** [comment]
后续会逐步升级

**Comment by heweimxcz** [comment]
+1
