### ISSUE TITLE
插件加载耗时

### ISSUE THREAD

**Issue by chy116449859** [Qihoo360/RePlugin#1022]
#### 问题详细描述 Detailed description of the problem
1.自己基于2.3修改源码适配androidx
2.加载远程下载的插件耗时比较长10-15秒，不管插件大小5M-50M基本都15秒左右。本地assets的内置插件加载速度比较快。
3.我们这边必现，minsdk是21，compiletool 29 30的都试过，androidgradle版本是3.5.3

#### 其它重要信息 Other important information
初步排除耗时有2个地方，一是RePlugin.getConfig().getCallbacks().createPluginClassLoader耗时大约5秒，二是PluginManagerProxy.updateUsedIfNeeded大约耗时10秒。

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by shmilx** [comment]
想请问一下 。怎么修改适配到androidx的？有发布吗？可以提供个链接吗

**Comment by krubo** [comment]
3.0.0版本已适配androidx
