### ISSUE TITLE
apply plugin: 'replugin-plugin-gradle' 2.3.4 版本，编译没有问题，插件未生效

### ISSUE THREAD

**Issue by aiqq** [Qihoo360/RePlugin#1028]
apply plugin: 'replugin-plugin-gradle' 2.3.4 版本，编译没有问题，插件未生效
打包后反编译发现类继承Activity未被替换为PluginActivity
Why？？

rePlugin-plugin-lib/gradle Version: 3.5.4/5.4.1

Android API Version：31
Android 手机型号: 模拟器

**Comment by liuchenx** [comment]
gradle 3.5以上android gradle api 有改动，老的代码不能适配
