### ISSUE TITLE
在主程序中接入RePlugin的时候报错，配置文件都会报错吗？

### ISSUE THREAD

**Issue by hezijie1234** [Qihoo360/RePlugin#103]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:2.1

**Android compile SDK version**:25

**Android ROM**:接入都失败了，哪里有ROM

**Comment by hezijie1234** [comment]
Error:Execution failed for task ':app:processDebugResources'.
> java.lang.NullPointerException (no error message)

**Comment by kezhijie** [comment]
将classpath 'com.qihoo360.replugin:replugin-host-gradle:2.1.1'换成
 将classpath 'com.qihoo360.replugin:replugin-host-gradle:2.1.0'

**Comment by hezijie1234** [comment]
按照你的方法又报了新的错误，我还没添加assets目录。
Error:A problem occurred configuring root project 'RepluginApplication'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find com.qihoo360.replugin:replugin-host-gradle:2.1.0.
     Searched in the following locations:
         file:/D:/android-studio/android-studio/gradle/m2repository/com/qihoo360/replugin/replugin-host-gradle/2.1.0/replugin-host-gradle-2.1.0.pom
         file:/D:/android-studio/android-studio/gradle/m2repository/com/qihoo360/replugin/replugin-host-gradle/2.1.0/replugin-host-gradle-2.1.0.jar
         https://jcenter.bintray.com/com/qihoo360/replugin/replugin-host-gradle/2.1.0/replugin-host-gradle-2.1.0.pom
         https://jcenter.bintray.com/com/qihoo360/replugin/replugin-host-gradle/2.1.0/replugin-host-gradle-2.1.0.jar
     Required by:
         :RepluginApplication:unspecified

**Comment by kezhijie** [comment]
在assets加plugins目录就ok了

**Comment by wangyupeng1-iri** [comment]
`repositories {
        jcenter()
        maven {
            url  "https://dl.bintray.com/qihoo360/replugin"
        }
    }`

**Comment by hezijie1234** [comment]
repositories { jcenter() maven { url "https://dl.bintray.com/qihoo360/replugin" } }这个添加到哪，有2个位置可以添加这行代码。

**Comment by wangyupeng1-iri** [comment]
你可以看下sample里面的host @hezijie1234

**Comment by hezijie1234** [comment]
buildscript {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            url  "https://dl.bintray.com/qihoo360/replugin"
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.0'
        classpath 'com.qihoo360.replugin:replugin-host-gradle:2.1.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            url  "https://dl.bintray.com/qihoo360/replugin"
        }
    }
}
这是我的配置信息，然而还是报错。下面是错误信息
Error:Execution failed for task ':app:processDebugResources'.
> java.lang.NullPointerException (no error message)
