### ISSUE TITLE
这是完全放弃了吗？？？？一堆bug，根本无法用

### ISSUE THREAD

**Issue by withyi9223** [Qihoo360/RePlugin#1030]
#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by krubo** [comment]
会继续维护
