### ISSUE TITLE
鸿蒙手机textview , edittext会崩溃

### ISSUE THREAD

**Issue by shadow520** [Qihoo360/RePlugin#1032]
#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by BangAiN** [comment]
定位到原因没

**Comment by ttxz** [comment]
之前有人提过，参考下他们的解决方案。
#1001 

继承EditText重写一下崩溃的方法就行了，设置正确的上下文即可。
android.widget.TextView.getTextSelectHandle(TextView.java:3727)这个方法是android10的一本版本引入的，之前没有。
很小的问题。

**Comment by withyi9223** [comment]
> 之前有人提过，参考下他们的解决方案。 #1001
> 
> 继承EditText重写一下崩溃的方法就行了，设置正确的上下文即可。 android.widget.TextView.getTextSelectHandle(TextView.java:3727)这个方法是android10的一本版本引入的，之前没有。 很小的问题。

别像一个机器人一样，什么崩溃方法，你倒是说出来呀，代码贴出来，会不会？？？？
