### ISSUE TITLE
关于以后是否恢复维护的问题

### ISSUE THREAD

**Issue by marufei** [Qihoo360/RePlugin#1034]
#### 问题详细描述 Detailed description of the problem
我看2022.03.25 下午六点又提交了代码，是否代表着咱们这个插件要开始恢复维护了呢？
希望官方维护人员给个回答呗，嘿嘿~

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by marufei** [comment]
@goodev @erhu @hyongbai @kevinfen9

**Comment by krubo** [comment]
会一直维护
