### ISSUE TITLE
插件中怎么实现皮肤切换呢，这个有现成的方案么

### ISSUE THREAD

**Issue by shiyutian123** [Qihoo360/RePlugin#104]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:

**Android compile SDK version**:

**Android ROM**:

**Comment by jiongxuan** [comment]
手机助手就是自己研发了一套换肤View，并作为公共View放到宿主中，供插件使用。

您可以参考Sample中的Fragment示例来了解用法。
