### ISSUE TITLE
华为mate50，鸿蒙系统，使用replugin，包含EditText的Activity，在点击EditText的时候直接崩溃

### ISSUE THREAD

**Issue by foreverflame** [Qihoo360/RePlugin#1046]
# main(1)

android.content.res.Resources$NotFoundException

Resource ID #0x0

解析原始
1
android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:308)
2
android.content.res.Resources.getDrawableForDensity(Resources.java:1073)
3
android.content.res.Resources.getDrawable(Resources.java:1013)
4
library.d.getDrawable(Unknown Source:13)
5
android.content.Context.getDrawable(Context.java:630)
6
android.widget.TextView.getTextSelectHandle(TextView.java:3659)
7
android.widget.Editor.loadHandleDrawables(Editor.java:7488)
8
android.widget.Editor$InsertionPointCursorController.getHandle(Editor.java:6906)
9
android.widget.Editor$InsertionPointCursorController.access$900(Editor.java:6881)
10
android.widget.Editor.updateCursorPosition(Editor.java:2151)
11
android.widget.TextView.getUpdatedHighlightPath(TextView.java:7529)
12
android.widget.TextView.onDraw(TextView.java:7728)
13
android.view.View.draw(View.java:20635)
14
android.view.View.updateDisplayListIfDirty(View.java:19446)
15
android.view.View.draw(View.java:20363)
16
android.view.ViewGroup.drawChild(ViewGroup.java:4404)
17
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
18
androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2070)
19
android.view.View.updateDisplayListIfDirty(View.java:19437)
20
android.view.View.draw(View.java:20363)
21
android.view.ViewGroup.drawChild(ViewGroup.java:4404)
22
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
23
android.view.View.draw(View.java:20638)
24
androidx.viewpager.widget.ViewPager.draw(ViewPager.java:2426)
25
android.view.View.updateDisplayListIfDirty(View.java:19446)
26
android.view.View.draw(View.java:20363)
27
android.view.ViewGroup.drawChild(ViewGroup.java:4404)
28
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
29
androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2070)
30
android.view.View.updateDisplayListIfDirty(View.java:19437)
31
android.view.View.draw(View.java:20363)
32
android.view.ViewGroup.drawChild(ViewGroup.java:4404)
33
androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.java:235)
34
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
35
androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.java:223)
36
android.view.View.updateDisplayListIfDirty(View.java:19437)
37
android.view.View.draw(View.java:20363)
38
android.view.ViewGroup.drawChild(ViewGroup.java:4404)
39
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
40
androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2070)
41
android.view.View.draw(View.java:20638)
42
android.view.View.updateDisplayListIfDirty(View.java:19446)
43
android.view.View.draw(View.java:20363)
44
android.view.ViewGroup.drawChild(ViewGroup.java:4404)
45
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
46
android.view.View.updateDisplayListIfDirty(View.java:19437)
47
android.view.View.draw(View.java:20363)
48
android.view.ViewGroup.drawChild(ViewGroup.java:4404)
49
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
50
android.view.View.updateDisplayListIfDirty(View.java:19437)
51
android.view.View.draw(View.java:20363)
52
android.view.ViewGroup.drawChild(ViewGroup.java:4404)
53
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
54
android.view.View.updateDisplayListIfDirty(View.java:19437)
55
android.view.View.draw(View.java:20363)
56
android.view.ViewGroup.drawChild(ViewGroup.java:4404)
57
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
58
android.view.View.updateDisplayListIfDirty(View.java:19437)
59
android.view.View.draw(View.java:20363)
60
android.view.ViewGroup.drawChild(ViewGroup.java:4404)
61
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
62
android.view.View.draw(View.java:20638)
63
com.android.internal.policy.DecorView.draw(DecorView.java:928)
64
android.view.View.updateDisplayListIfDirty(View.java:19446)
65
android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:740)
66
android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:746)
67
android.view.ThreadedRenderer.draw(ThreadedRenderer.java:861)
68
android.view.ViewRootImpl.draw(ViewRootImpl.java:3627)
69
android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3423)
70
android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2755)
71
android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1677)
72
android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7987)
73
android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
74
android.view.Choreographer.doCallbacks(Choreographer.java:893)
75
android.view.Choreographer.doFrame(Choreographer.java:812)
76
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
77
android.os.Handler.handleCallback(Handler.java:907)
78
android.os.Handler.dispatchMessage(Handler.java:105)
79
android.os.Looper.loop(Looper.java:216)
80
android.app.ActivityThread.main(ActivityThread.java:7779)
81
java.lang.reflect.Method.invoke(Native Method)
82
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
83
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:990)
# ReferenceQueueDaemon(462)

1
java.lang.Object.wait(Native Method)
2
java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:178)
3
java.lang.Daemons$Daemon.run(Daemons.java:103)
4
java.lang.Thread.run(Thread.java:784)

咋解决啊

**Comment by krubo** [comment]
用的哪个版本的replugin？

**Comment by krubo** [comment]
最新版本已解决

**Comment by withyi9223** [comment]
> 最新版本已解决

用了最新版本3.0.0的，一样的错误，根本没有解决
