### ISSUE TITLE
主程序接入指南是否可更新下

### ISSUE THREAD

**Issue by guogailee** [Qihoo360/RePlugin#105]
工程主目录引入classpath 'com.qihoo360.replugin:replugin-host-gradle:2.1.1' 会报错，这个已经有其他issues了，最好的方式就是更新下wiki，这样可以方便开发者快速尝试。

**Comment by guogailee** [comment]
@wangyupeng1-iri

**Comment by wangyupeng1-iri** [comment]
@guogailee 现在已经有replugin-host-gradle:2.1.2。wiki我也更新了，谢谢！

**Comment by jiongxuan** [comment]
感谢提醒，已经更新。
