### ISSUE TITLE
replugin.install()方法加载外置插件无反应，有人实现了吗

### ISSUE THREAD

**Issue by aBenVip** [Qihoo360/RePlugin#106]

**Comment by goodev** [comment]
宿主程序 attachBaseContext 中设置插件参数为不验证签名：
`
public class SampleApplication extends Application {

    private static final String TAG = "SampleApplication";
    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);

        // ======= REPLUGIN =======
        //-------------- 开发的时候不验证签名 -----------
        RePluginConfig config = new RePluginConfig();
        config.setVerifySign(!BuildConfig.DEBUG);
        RePlugin.App.attachBaseContext(this, config);
        // ========================
    }
`

如果插件是在 SDCard 上，注意授权宿主程序的 SDCard 读写权限。

**Comment by qq634421026** [comment]
@goodev  这么修改之后还是不好使

**Comment by goodev** [comment]
SDcard 访问权限有没有授权？
