### ISSUE TITLE
replugin-plugin-gradle 什么时候能够支持gradle plugin 2.3.2及gradle 3.3版本

### ISSUE THREAD

**Issue by Hiram-Y** [Qihoo360/RePlugin#107]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:

**Android compile SDK version**:

**Android ROM**:

**Comment by goodev** [comment]
新的代码已经可以了，下载最新的代码，改动下插件的版本号，自己编译到 maven local 仓库中，然后使用新的本地版本插件即可。

**Comment by lizhangqu** [comment]
see #96

**Comment by wangyupeng1-iri** [comment]
请切换到最新的版本see[发行版本](https://github.com/Qihoo360/RePlugin/wiki/%E5%8F%91%E8%A1%8C%E7%89%88%E6%9C%AC)
