### ISSUE TITLE
请问横屏的怎么配置不起作用呢

### ISSUE THREAD

**Issue by ningzha** [Qihoo360/RePlugin#1073]
#### 问题详细描述 Detailed description of the problem
我看有横屏的坑位了，在host上配置不起作用呢

#### 复现问题步骤 Steps to reproduce the problem
1. repluginHostConfig {
    useAppCompat = true
    useAndroidX = true
    useOccupyLand = true
}

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:3.1.0
rePlugin-plugin-lib/gradle Version:3.1.0

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by renjinlong** [comment]
插件的Activity要配置成横屏的
类似demo1中的StandardActivity
        <activity
            android:name=".activity.standard.StandardActivity"
            android:exported="false"
            android:screenOrientation="landscape" /> 

 android:screenOrientation="landscape"这个很重要

**Comment by ningzha** [comment]
> 插件的Activity要配置成横屏的 类似demo1中的StandardActivity
> 
> android:screenOrientation="landscape"这个很重要

感谢，解决了，之前写成reverseLandscape
