### ISSUE TITLE
Error:Could not find com.qihoo.gradle:replugin-host-gradle:2.1.0. 

### ISSUE THREAD

**Issue by NightFarmer** [Qihoo360/RePlugin#11]
插件同步不下来
现在用不了吗？还是说要加特殊的repositories？
```
Error:Could not find com.qihoo.gradle:replugin-host-gradle:2.1.0.
Searched in the following locations:
    file:/home/xxx/Program/AS2.3/android-studio/gradle/m2repository/com/qihoo/gradle/replugin-host-gradle/2.1.0/replugin-host-gradle-2.1.0.pom
    file:/home/xxx/Program/AS2.3/android-studio/gradle/m2repository/com/qihoo/gradle/replugin-host-gradle/2.1.0/replugin-host-gradle-2.1.0.jar
    https://jcenter.bintray.com/com/qihoo/gradle/replugin-host-gradle/2.1.0/replugin-host-gradle-2.1.0.pom
    https://jcenter.bintray.com/com/qihoo/gradle/replugin-host-gradle/2.1.0/replugin-host-gradle-2.1.0.jar
Required by:
    project :
```

**Comment by l123456789jy** [comment]
他这个还没发布啊

**Comment by jiongxuan** [comment]
感谢您的关注。我们还在审核，很快就放出。敬请期待

**Comment by lvtanxi** [comment]
真的是坐等。有了插件化，感觉原生发展的空间又很大了

**Comment by tomasky** [comment]
何时发布？，给个jar或aar下载也行啊

**Comment by GJson** [comment]
不是说 30号开源的吗

**Comment by jiongxuan** [comment]
您好，首先非常感谢您们的持续关注！

我们的代码已在30日晚11点全部放出。所有工程均已通过自测，确保没有问题。欢迎大家指正。

此外，看到Sample代码后，您们可能好奇，为什么我们在Build.gradle中有这么一段话：

    repositories {
        jcenter()
        maven {
            url "https://dl.bintray.com/qihoo360/replugin"
        }
    }
这是因为，我们的开源项目在昨天晚上11点才通过公司严苛但很有必要的安全审核，其AAR和Source也在今天凌晨提交到JCenter上。但由于时间关系，他们目前还没有给予我们回应（预计1~2个工作日）。

所以为了不影响您们运行Sample，就先放到JCenter上的“用户仓库”上，待JCenter审核通过后再行切换到公共库上。所以，还请看下Sample是否有修改过的情况。若问题仍存在，则请继续反馈（还请提供更完整的Gradle编译信息）。

最后，感谢您们的反馈，让RePlugin更好！

**Comment by hunanzjjhy** [comment]
Error:Could not find com.qihoo360.replugin:replugin-host-gradle:2.2.2.
Searched in the following locations:
    file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/qihoo360/replugin/replugin-host-gradle/2.2.2/replugin-host-gradle-2.2.2.pom
    file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/qihoo360/replugin/replugin-host-gradle/2.2.2/replugin-host-gradle-2.2.2.jar
    file:/C:/Users/huyong/.m2/repository/com/qihoo360/replugin/replugin-host-gradle/2.2.2/replugin-host-gradle-2.2.2.pom
    file:/C:/Users/huyong/.m2/repository/com/qihoo360/replugin/replugin-host-gradle/2.2.2/replugin-host-gradle-2.2.2.jar
    https://jcenter.bintray.com/com/qihoo360/replugin/replugin-host-gradle/2.2.2/replugin-host-gradle-2.2.2.pom
    https://jcenter.bintray.com/com/qihoo360/replugin/replugin-host-gradle/2.2.2/replugin-host-gradle-2.2.2.jar
    https://dl.bintray.com/qihoo360/replugin/com/qihoo360/replugin/replugin-host-gradle/2.2.2/replugin-host-gradle-2.2.2.pom
    https://dl.bintray.com/qihoo360/replugin/com/qihoo360/replugin/replugin-host-gradle/2.2.2/replugin-host-gradle-2.2.2.jar
Required by:
    project :

**Comment by hunanzjjhy** [comment]
还没发布吗

**Comment by Joyce1991** [comment]
目前看确实只有2.2.1还
https://dl.bintray.com/qihoo360/replugin/com/qihoo360/replugin/replugin-host-gradle/
