### ISSUE TITLE
library版本号统一及gradle脚本代码收敛

### ISSUE THREAD

**Issue by lizhangqu** [Qihoo360/RePlugin#113]
现状：各个项目独立，版本号各项目自己管理，bintray.gradle等gradle代码各个项目保持一份

希望能达到以下效果：
1：根目录下建立公共目录，内放bintray.gradle等gradle脚本代码，其他项目通过apply from该文件进行引用
2：根目录下建立common_version.gradle，内放各项目版本号，其他项目通过apply from该文件进行引用

**Comment by wangyupeng1-iri** [comment]
@lizhangqu 其实是我们想解耦，各个模块尽量独立些。方便各个模块独立维护。

**Comment by goodev** [comment]
RePlugin 里面包含四个项目，这四个项目需要配合使用，如果每个项目的版本号都不一样，后期使用会带来非常大的问题，比如host-gradle 版本是2.1.0，对应的 host-lib 可以为2.1.0 也可以为 2.X.X 等， 同理对应 plugin-gradle 和 plugin-lib 也是一样，这样的话，如果四个项目中出现版本号不兼容的情况，使用起来就非常头疼了。需要知道每个版本号直接的区别，应该使用哪个子项目的版本和另外一个子项目的某个版本一起使用。。。 等等问题。

**Comment by wangyupeng1-iri** [comment]
版本号兼容管理方案可以有多种，你的意见我们可以参考，后面我们内部团队先讨论下。谢谢你的提议！
