### ISSUE TITLE
外置插件安装成功后，执行卸载uninstall()方法，move到data目录下的jar文件依旧存在

### ISSUE THREAD

**Issue by aBenVip** [Qihoo360/RePlugin#114]
现在每次安装外置插件都会copy一个jar到data目录，更新外置插件不是覆盖原有的jar文件，是不是改为覆盖jar文件会更好一点

**Comment by lvtanxi** [comment]
我执行了RePlugin.uninstall方法之后，就无法重新再安装了插件了

**Comment by jiongxuan** [comment]
@lvtanxi 您是说卸载后无法再安装吗？如果重启进程以后呢？

**Comment by aBenVip** [comment]
卸载后无法重新安装，然后看了下是因为卸载后没删除之前的jar文件 @jiongxuan

**Comment by lvtanxi** [comment]
@jiongxuan 杀了进程以后也是，安装不成功。像是aBenVip 说的那样之前的jar文件没被删除

**Comment by maning0303** [comment]
@lvtanxi 插件版本升级了吗 ？ 没有升级就安装不了！

**Comment by lvtanxi** [comment]
@maning0303 升级了的。用的是replugin-host-gradle:2.1.2与replugin-plugin-gradle:2.1.2'版本都升级了的。但是卸载之后就是不能安装

**Comment by lvtanxi** [comment]
@maning0303 还有一种情况，插件中的toast不起效果了

**Comment by maning0303** [comment]
@lvtanxi 我试了Toast是没有问题的，前面说的插件版本升级是插件工程的Manifest里面配置的插件版本号升级：
```
        <meta-data
            android:name="com.qihoo360.plugin.name"
            android:value="plugin01"/>
        <meta-data
            android:name="com.qihoo360.plugin.version.ver"
            android:value="100"/>
```

**Comment by lvtanxi** [comment]
@maning0303 
![qq 20170705160816](https://user-images.githubusercontent.com/16009130/27855332-b051f170-619c-11e7-9bf2-9b21ef12c73c.png)
这是我Toast的错。后面我做了如下处理：
`
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.SYSTEM_OVERLAY_WINDOW" />
`
。升级了自己插件的版本可以安装了。还是希望下个版本在卸载插件的时候把这个问题处理一下：
![qq 20170705160831](https://user-images.githubusercontent.com/16009130/27855386-f2cea71e-619c-11e7-9767-b7f1a2d6a7ef.png)
。另外非常感谢大神的耐心回复。
