### ISSUE TITLE
关于插件引用宿主的类和方法，以及插件与宿主的通信

### ISSUE THREAD

**Issue by AliMaster** [Qihoo360/RePlugin#118]
请问插件里如何引用宿主的类和方法，以及插件何如与宿主通信，能否在demo写一下示例？
我这边拿sample 试了下将host中的部分类导出jar包，在plugin中以provided方式引用jar包；运行host中的plugin虽然没有报错，但是插件中也没有执行jar包总代码的逻辑。

**Comment by AliMaster** [comment]
“host中打出jar包，然后在plugin中以provided方式引用”是行得通的，我这一直没生效时因为没有清理host app的缓存导致的。调试插件的时候，每次都卸载host app吧…

**Comment by carlzhao** [comment]
等待作者补充文档，现在只能自己看代码

**Comment by weikano** [comment]
应该已经改好了吧，PluginDexClassLoader.loadClass里面super.loadClass没有catch异常。

**Comment by jiongxuan** [comment]
此问题已经由 @JavenCoder 修复了。现在应该没有这个问题了。

谢谢反馈！
