### ISSUE TITLE
RePlugin与DroidPlugin有什么区别？

### ISSUE THREAD

**Issue by godwilling** [Qihoo360/RePlugin#12]
你好，请问Replugin与原先的DroidPlugin有什么区别？

**Comment by smartOf360** [comment]
这个问题很好， 其实我们在gmtc的时候，炅轩同学已经做了一次比较，表格很清晰，我从我的观点在解答一下，有什么不对的地方咱们在进行讨论：
1、解决问题的场景是有区别的：
     Replugin解决的是各个功能模块能独立升级，还需要和宿主之间有一定交互；
     DroidPlugin解决的是各个独立功能拼装在一起，能够快速发布，不需要有任何的交互；
2、稳定性的区别：
     Replugin只有一个hook点，崩溃率低；
     DroidPlugin的hook点非常多，崩溃率很高；
3、兼容性的区别：
     Replugin支持2.x以上的任意android系统，可以完美支持四大组件；
     DroidPlugin对于不同android系统稳定性差异较大，像最新的android7.0、android8.0都存在着需要适配的问题，像复杂的有native的代码的apk想集成使用，那必须要自己实现对应的arm inline hook方案；

**Comment by jiongxuan** [comment]
是的，正如 @smartOf360  刚哥所述。

其实归根结底，最主要的区别就一个：Hook点的多少。
DroidPlugin要Hook的点非常多，代价是失去了一定的稳定性（这点非常关键），而好处是APK可以“直接运行在主程序中”。
相反，RePlugin只Hook了ClassLoader，所以极为稳定，且同样支持绝大多数单品的特性。而APK只需要通过我们的Gradle编译，无需开发者修改Java Code，即可运行在主程序中。但出于稳定性考虑，我们不支持（也不打算支持）“直接将APK，不经修改就放到主程序中”。

此外，DroidPlugin是360手机助手团队做的，和我们不是一个Team，且比我们要晚一年半，才用于自己的产品，我们是2014年中旬做的（完整占坑类方案），相对更早。还有，我们的插件数量很多，总计达102个。

哦，再顺便说一句，现在助手已经将DroidPlugin切换到RePluign上了。
