### ISSUE TITLE
近期是否会做插件版本升级相关的东西

### ISSUE THREAD

**Issue by lxfeng** [Qihoo360/RePlugin#120]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:

**Android compile SDK version**:

**Android ROM**:

**Comment by jiongxuan** [comment]
插件版本升级一直都是支持的。请参见《插件的管理》和《插件的信息》一文（在WiKi上）
