### ISSUE TITLE
demo的assets下的目录和文档不太一致

### ISSUE THREAD

**Issue by qq634421026** [Qihoo360/RePlugin#122]
demo中采用内置插件assets下文件名为plugins,但是文档上说内置插件应该是replugin_plns,

经测试内置插件因该是plugins，而采用外置插件形式的时候也要在assets里创建一个空的文件名为replugin_plns，不知道我说是否正确，如果不对，请指正

**Comment by wangyupeng1-iri** [comment]
@qq634421026 多谢提醒，我这就去改下

**Comment by Jeremydcx** [comment]
@qq634421026  "而采用外置插件形式的时候也要在assets里创建一个空的文件名为replugin_plns" ,外置的不用在assets下面创建replugin_pln 文件夹。我试过也是可以的

**Comment by jiongxuan** [comment]
谢谢 @wangyupeng1-iri 兄的修改
