### ISSUE TITLE
外置插件安装不行

### ISSUE THREAD

**Issue by zSenT1100** [Qihoo360/RePlugin#124]
按照教程来，这个外置插件失败的，每次都是安装失败，能否在demo里包含外置插件的写法

**Comment by EvilBT** [comment]
@zSenT1100 注意是不是没有添加读写外置内存卡权限问题，等sample更新的话应该会有更多的示例的

**Comment by zSenT1100** [comment]
有的

**Comment by zSenT1100** [comment]
而且在demo想改成外置插件的 也不行

**Comment by EvilBT** [comment]
@zSenT1100  #65 去这个Issues看一下，debug版本还要关掉签名验证的，还可以在Application设置一下权限监听

**Comment by jiongxuan** [comment]
谢谢 @EvilBT 帮忙解答。

新Sample已经默认关闭了签名（Debug下），应该不会有这个问题了。
