### ISSUE TITLE
内置插件怎么热更新呢，推荐那一种方案，模块间跳转有哪些方案呢，arouter?

### ISSUE THREAD

**Issue by krmao** [Qihoo360/RePlugin#127]
内置插件怎么热更新呢，推荐那一种方案，模块间跳转有哪些方案呢，arouter?

**Comment by maning0303** [comment]
这个不支持热更新吧 ！

**Comment by zhaolei9527** [comment]
内置插件热更新？那要外置插件有什么用?

**Comment by sam-long-li** [comment]
应该是支持热更新的，这个应该也是RePlugin的优势，不过热更新方案没有提及

**Comment by jiongxuan** [comment]
RePlugin的优势在于“稳定和灵活兼得”，既没有BinderHook，又能让插件做到和单品类似的效果，并提供了插件和宿主、插件间的一些交互。但“热更新”（不用重启进程就能让插件和资源生效）涉及到Hook，这不是RePlugin的主要目标。

当然，虽然我们没有试过，但热更新也许能和RePlugin找到相应的结合点。您们可以尝试下。

**Comment by carlzhao** [comment]
现有的热更新方案大部分都还是要重启的吧

**Comment by jiongxuan** [comment]
一些热更新方案是可以不需要重启的
