### ISSUE TITLE
不会是KPI吧，希望能维护下去。

### ISSUE THREAD

**Issue by l123456789jy** [Qihoo360/RePlugin#13]

**Comment by smartOf360** [comment]
我们没有这样的kpi，如果有也是持续维护的kpi，请放心 :)

**Comment by jiongxuan** [comment]
是的，正如 @smartOf360 刚哥所述。

其实换个思路，仅从开源前的RePlugin来看，我们的方案已经肩负起了**整个360公司各亿级别以上安卓App的插件化使命**。
这意味着，无论是否为KPI（何况还不是），我们都必须坚持做下去，而且还要做好，毕竟这些项目都是商业级的，容不得半点马虎。

当然，RePlugin的理想也绝不仅仅于此，而是让所有人都能享受到“全面插件化”的意义。于情于理，我们都会持续维护下去的。

**Comment by ouer1994** [comment]
坐等7月初 开源

**Comment by xiangou** [comment]
你是个好人
