### ISSUE TITLE
插件没有继承PluginAppCompatActivity

### ISSUE THREAD

**Issue by Hiram-Y** [Qihoo360/RePlugin#130]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:2.1.2

**Android compile SDK version**:25

**Android ROM**:

![image](https://user-images.githubusercontent.com/7044188/27899650-a7bacaca-625d-11e7-8310-18c9e9f37b3e.png)

如果插件中添加 me.tatarka:gradle-retrolambda不会替换activity

**Comment by aBenVip** [comment]
@Hiram-Y 你好，你这个继承关系实在那儿看的呢？gradle吗？

**Comment by Hiram-Y** [comment]
@aBenVip AS3.0以上自带了这个功能，能直接查看apk的class   ，我也用log的方式打出来，getSuperclass().getSimpleName()，也是继承的AppCompateActivity

**Comment by jiongxuan** [comment]
您好，请您先使用RePlugin 2.1.4版本试试（解决了Instant Run的问题）。

如果仍有问题，可以把您的Gradle日志上传上来，同时，也请附上您的插件根目录的build.gradle文件，这样我们可以进一步看看。

**Comment by zzz40500** [comment]
这个问题, 应该是RxAppCompatActivity 所在class.jar 不存在项目目录结构下导致的,从日志上看gradle 多次设置RxAppCompatActivity 为PluginAppCompatActivity, 这是因为
~~~
  ctCls.writeFile(CommonData.getClassPath(ctCls.name))
~~~
这个CommonData.getClassPath(ctCls.name)返回为空, 无法写入导致的.
总体就是 #166  的表现

**Comment by Hiram-Y** [comment]
@jiongxuan @zzz40500 https://github.com/Hiram-Y/TestRePlugin   这个是demo 还是没有替换插件的Activity

**Comment by jiongxuan** [comment]
@zzz40500 太赞了！非常感谢！

我们今天会发出2.1.5版本，将 @zzz40500 大神的改动体现出来。届时您可以看看效果 @Hiram-Y 。

**Comment by Hiram-Y** [comment]
@jiongxuan 好的，持续关注中

**Comment by Hiram-Y** [comment]
@jiongxuan @zzz40500 2.1.5版本已经测试成功，没问题了，多谢了！
