### ISSUE TITLE
宿主打开插件的Activity的方法是否支持startActivityForResult？

### ISSUE THREAD

**Issue by fourmigh** [Qihoo360/RePlugin#134]
在文档和代码里，都只看到RePlugin.startActivity，而没有startActivityForResult，是否不支持？
或者是有其他方法让宿主获得插件Activity的返回结果？

**Comment by jiongxuan** [comment]
宿主打开插件的已经支持了，我们的RP组成员已经提交了PR。正在Review和最终测试。
插件打开插件的之前就OK了。

请耐心等待

**Comment by jiongxuan** [comment]
已经支持了。请参考Sample用法，谢谢！
