### ISSUE TITLE
怎样生成插件的apk？

### ISSUE THREAD

**Issue by LuoGuoXin** [Qihoo360/RePlugin#137]
是通过 gradle clean assemblePlugin 这个命令打嘛？

**Comment by jiongxuan** [comment]
不用的。直接编译即可。

**Comment by LuoGuoXin** [comment]
有区分debug和release的吗

**Comment by aBenVip** [comment]
使用debug需要关闭签名校验，在application中处理RepluginConfig @LuoGuoXin
