### ISSUE TITLE
大赞，不过貌似用了这种技术的app不能上google play？

### ISSUE THREAD

**Issue by jtyang** [Qihoo360/RePlugin#14]
rt

**Comment by smartOf360** [comment]
上gp可以使用这样的策略，当你的插件apk需要更新时， 提示跳到gp进行更新就可以了。

**Comment by jtyang** [comment]
意思是开发的时候以插件化的方式，然后所有插件都内置到主apk中，以后每次都直接更新整个apk么？

**Comment by jiongxuan** [comment]
@jtyang 至少这样做不会违反GP的“动态更新”的规则。GP不限制加载Dex，但要求Dex需要内置。

而RePlugin是支持“内置插件”方案的，拆箱即用。您可以体验一下

**Comment by jtyang** [comment]
好的，thanks！

**Comment by smartOf360** [comment]
@jtyang 可以以另外一种方式，你的子模块apk（dex）以资源的形式也上传到gp，之后你的插件需要更新时，跳到gp进行更新就可以了。

**Comment by jiongxuan** [comment]
@smartOf360 好的，这个问题我到时候会放到FAQ中，供大家参阅。感谢支持！
