### ISSUE TITLE
插件中的application会不会执行？插件和宿主相同的依赖包或者资源怎么处理比较好？

### ISSUE THREAD

**Issue by LuoGuoXin** [Qihoo360/RePlugin#141]
如果插件中有application，里面需要做一些操作初始化的。然后宿主跳到插件的MainActivity的时候，那个application会不会初始化？第二个问题，如果宿主和插件中都要依赖某些相同的包，或者相同的资源的时候，怎样处理比较好，只能重复吗？毕竟是打成apk的方式了

**Comment by aBenVip** [comment]
@LuoGuoXin 
①：通过classLoader
②：通过aidl
③：通过宿主生成jar，插件provided

**Comment by weikano** [comment]
Application会通过RePlugin.callAppLocked调用onCreate
