### ISSUE TITLE
plugins-builtin使用方法

### ISSUE THREAD

**Issue by whosmyqueen** [Qihoo360/RePlugin#142]
集成后replugin后,host里面生成的plugins-builtin.json文件怎么使用,还是没有用

**Comment by aBenVip** [comment]
内置的这个json才有用，专门配置内置插件的

**Comment by weikano** [comment]
加载内置插件FinderBuiltin.readConfig()

**Comment by aBenVip** [comment]
你这是内部调用的，开发者用的时候不需要自己去加载内置插件吧 @weikano

**Comment by weikano** [comment]
@aBenVip 这不是了解用法么

**Comment by whosmyqueen** [comment]
具体怎么配置呢,demo里面没有写 @aBenVip @jiongxuan

**Comment by jiongxuan** [comment]
这个是Gradle插件自动生成的。您无需人工干预这个过程。
