### ISSUE TITLE
外置插件没有安装后的回调？

### ISSUE THREAD

**Issue by LuoGuoXin** [Qihoo360/RePlugin#143]
外置插件，我下载到内存卡后，调安装方法，没有回调？怎么知道是否安装成功了，得安装成功了才能启动插件的Activity吧

**Comment by weikano** [comment]
继承DefaultRePluginEventCallbacks。
设置给RePluginConfig

**Comment by aBenVip** [comment]
①：安装成功PluginInfo不为空，根据这个可以判断
②：可以在application的attachBaseContext方法中给RePluginConfig设置RePluginEventCallbacks监听是否安装成功

**Comment by EvilBT** [comment]
@LuoGuoXin 可以看下QQ群上的FAQ呢，另外，调用安装前其实应该先调用判断是否已经安装了才更合适。

**Comment by whosmyqueen** [comment]
@EvilBT QQ群在哪?

**Comment by erhu** [comment]
QQ Group: 653205923

**Comment by jiongxuan** [comment]
您好，您提的问题已经整合到WiKi上，应该能解决您的疑惑。

同时我们很快会完善带Install的Sample代码，敬请期待。
