### ISSUE TITLE
从jcenter上拉取的replugin-plugin-lib:2.1.0的是经过混淆的，不知道是否可以提供未混淆的

### ISSUE THREAD

**Issue by weikano** [Qihoo360/RePlugin#144]
aar是混淆过的，但是源码又是未混淆的。debug的时候跟踪代码有点不方便。
不知道能否提供未混淆过的aar。

虽然也可以修改replugin-plugin-library把生成的aar放到demo

**Comment by aBenVip** [comment]
那儿混淆了啊？我这边都没注意

**Comment by weikano** [comment]
去gradle缓存目录下看看就知道了……
不是宿主用的lib，是plugin用的lib

**Comment by EvilBT** [comment]
@weikano 前期直接引入源码Debug更好吧，把仓库下的module引入到工程上去，这代码还比jcenter的新

**Comment by weikano** [comment]
@EvilBT 额，明白了。thx。
