### ISSUE TITLE
请问子应用的样式怎么处理？

### ISSUE THREAD

**Issue by godwilling** [Qihoo360/RePlugin#150]
我看demo1中没有设置应用的主题，并且MainActivity是继承的Activity。而且通过host启动demo1后，demo1是没有Theme的。我自己写了个简单的demo，并且设置了Theme，但是通过host启动后，Theme不起作用。我用的机器是红米4X，MIUI8.5稳定版。
并且在控制台显示如下错误：
07-07 16:53:55.961 18182-18182/com.sxstudio.repluginhostiii W/ResourceType: No package identifier when getting value for resource number 0x00000000
07-07 16:53:55.961 18182-18182/com.sxstudio.repluginhostiii D/RePlugin.activity-injector: 获取 ai.icon 失败
07-07 16:53:55.961 18182-18182/com.sxstudio.repluginhostiii W/System.err: android.content.res.Resources$NotFoundException: Resource ID #0x0
07-07 16:53:55.962 18182-18182/com.sxstudio.repluginhostiii W/System.err:     at android.content.res.Resources.getValue(Resources.java:1369)
07-07 16:53:55.962 18182-18182/com.sxstudio.repluginhostiii W/System.err:     at android.content.res.Resources.getDrawable(Resources.java:822)
07-07 16:53:55.962 18182-18182/com.sxstudio.repluginhostiii W/System.err:     at android.content.res.Resources.getDrawable(Resources.java:789)
07-07 16:53:55.962 18182-18182/com.sxstudio.repluginhostiii W/System.err:     at com.qihoo360.replugin.component.activity.ActivityInjector.getIcon(ActivityInjector.java:199)
07-07 16:53:55.962 18182-18182/com.sxstudio.repluginhostiii W/System.err:     at com.qihoo360.replugin.component.activity.ActivityInjector.injectTaskDescription(ActivityInjector.java:113)
07-07 16:53:55.962 18182-18182/com.sxstudio.repluginhostiii W/System.err:     at com.qihoo360.replugin.component.activity.ActivityInjector.inject(ActivityInjector.java:80)
07-07 16:53:55.962 18182-18182/com.sxstudio.repluginhostiii W/System.err:     at com.qihoo360.replugin.component.activity.ActivityInjector.inject(ActivityInjector.java:73)
07-07 16:53:55.962 18182-18182/com.sxstudio.repluginhostiii W/System.err:     at com.qihoo360.loader2.PmInternalImpl.handleActivityCreate(PmInternalImpl.java:433)
07-07 16:53:55.962 18182-18182/com.sxstudio.repluginhostiii W/System.err:     at com.qihoo360.i.Factory2.handleActivityCreate(Factory2.java:67)
07-07 16:53:55.962 18182-18182/com.sxstudio.repluginhostiii W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-07 16:53:55.962 18182-18182/com.sxstudio.repluginhostiii W/System.err:     at library.g.a(Unknown Source)
07-07 16:53:55.962 18182-18182/com.sxstudio.repluginhostiii W/System.err:     at com.qihoo360.replugin.b.a(Unknown Source)
07-07 16:53:55.962 18182-18182/com.sxstudio.repluginhostiii W/System.err:     at com.qihoo360.replugin.e.b(Unknown Source)
07-07 16:53:55.962 18182-18182/com.sxstudio.repluginhostiii W/System.err:     at com.qihoo360.replugin.loader.a.PluginActivity.onCreate(Unknown Source)
07-07 16:53:55.962 18182-18182/com.sxstudio.repluginhostiii W/System.err:     at com.sxstudio.repluginsubi.MainActivity.onCreate(MainActivity.java:11)
07-07 16:53:55.962 18182-18182/com.sxstudio.repluginhostiii W/System.err:     at android.app.Activity.performCreate(Activity.java:6303)
07-07 16:53:55.962 18182-18182/com.sxstudio.repluginhostiii W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
07-07 16:53:55.962 18182-18182/com.sxstudio.repluginhostiii W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402)
07-07 16:53:55.962 18182-18182/com.sxstudio.repluginhostiii W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
07-07 16:53:55.962 18182-18182/com.sxstudio.repluginhostiii W/System.err:     at android.app.ActivityThread.access$1000(ActivityThread.java:153)
07-07 16:53:55.963 18182-18182/com.sxstudio.repluginhostiii W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
07-07 16:53:55.963 18182-18182/com.sxstudio.repluginhostiii W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-07 16:53:55.963 18182-18182/com.sxstudio.repluginhostiii W/System.err:     at android.os.Looper.loop(Looper.java:154)
07-07 16:53:55.963 18182-18182/com.sxstudio.repluginhostiii W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5524)
07-07 16:53:55.963 18182-18182/com.sxstudio.repluginhostiii W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-07 16:53:55.963 18182-18182/com.sxstudio.repluginhostiii W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
07-07 16:53:55.963 18182-18182/com.sxstudio.repluginhostiii W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

RePlugin的demo能否有详细的说明，大家看你们的说明都是东看一下，西看一下。不连贯。导致问题频发，能够在Replugin稳定后，可以提供详细的接入和使用说明。

**Comment by jiongxuan** [comment]
您好，感谢反馈！编写和整理文档确实是一件比较费力的事情。我们正在完善，请耐心等待。谢谢理解

**Comment by jiongxuan** [comment]
至于Theme的问题，您可以看下Sample是否在您手机上OK？
