### ISSUE TITLE
对RePlugin接入过程的疑问

### ISSUE THREAD

**Issue by ChanJLee** [Qihoo360/RePlugin#16]
引用一下 @jiongxuan 的comment：

相反，RePlugin只Hook了ClassLoader，所以极为稳定，且同样支持绝大多数单品的特性。而APK只需要通过我们的Gradle编译，无需开发者修改Java Code，即可运行在主程序中。

我是否可以理解为借助gradle的transform？那么如果这时候存在多个transform且它们都会修改字节码，是否会对插件造成影响？

**Comment by erhu** [comment]
RePlugin 的确是通过 transform 来修改字节码的。至于多个 transform 是否会对插件造成影响，要视具体情况而定，如果后续的操作没有和 RePlugin 所做的修改冲突，是不会影响插件正常运行的 ，至于 RePlugin 对字节码做了哪些操作，后续官方的文档中会有详细说明~

**Comment by jiongxuan** [comment]
是的，正如 @erhu 俊杰所述。

如果您们在接入过程当中出现Transform冲突的问题，欢迎随时给我们反馈。
