### ISSUE TITLE
宿主跳入插件activity就报错，说找不到activity

### ISSUE THREAD

**Issue by yqjroy** [Qihoo360/RePlugin#163]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:

**Android compile SDK version**:

**Android ROM**:

android.content.ActivityNotFoundException: Unable to find explicit activity class {/.loader.a.ActivityN1NRNTS5}; have you declared this activity in your AndroidManifest.xml?

**Comment by CSDgod** [comment]
你没在你androidmanifest.xml里配置你的activity吧？

**Comment by yqjroy** [comment]
配置了呀。插件里配置了。我连宿主里面都配进去了

**Comment by CSDgod** [comment]
@yqjroy  我也遇到了和你一样的问题 解决了吗

**Comment by fengruisd** [comment]
@yqjroy @CSDgod ，用./gradlew aDebug来编apk试试，不要直接点Android Studio的run，我遇到同样的问题，是这么解决的。
AS直接运行的时候，用apktook反编译看manifest没有activity声明，在as的Instant Run下面看生成的manifest里也没有，但是在full下面有，所以怀疑是AS/Instant Run影响了360的gradle插件

**Comment by yqjroy** [comment]
我用命令也不行

**Comment by jiongxuan** [comment]
请使用最新的Sample来试下

**Comment by jueduiyheng** [comment]
> 我用命令也不行

问题处理了吗，一直没找到问题啊。。。。
