### ISSUE TITLE
这又是什么错误呢？

### ISSUE THREAD

**Issue by yqjroy** [Qihoo360/RePlugin#164]
07-09 15:18:05.460 15691-15691/com.bozhong.nurse I/RePlugin.ws000: loadLocked(): Initialized, is loaded = false
07-09 15:18:05.462 15691-15691/com.bozhong.nurse E/ws001: pmb.lp: f to l. lt=3; i=PInfo { <train:47(4)> [P-N] [USING] js={"pkgname":"train","ali":"train","name":"train","low":10,"high":10,"ver":47,"verv":2814792716779567,"path":"\/data\/user\/0\/com.bozhong.nurse\/app_plugins_v3\/train-10-10-47.jar","type":1,"v5type":0,"v5index":-1,"v5offset":-1,"v5length":-1,"frm_ver":4} dex=/data/user/0/com.bozhong.nurse/app_plugins_v3_odex/train-10-10-47.dex nlib=/data/user/0/com.bozhong.nurse/app_plugins_v3_libs/train-10-10-47 }

点击启动插件activity的时候报的。也不崩溃了。但是一直报这个错

**Comment by jiongxuan** [comment]
您是否成功启动了这个插件呢？

此外，该问题是否和 #165 是一回事儿？

**Comment by yqjroy** [comment]
没成功启动插件，和165是同一个

**Comment by jiongxuan** [comment]
好的
