### ISSUE TITLE
plugin gradle 注入代码失败的

### ISSUE THREAD

**Issue by zzz40500** [Qihoo360/RePlugin#166]
在replugin-plugin-gradle 处理需要注入的jar 中
在方法 `com.qihoo360.replugin.gradle.plugin.inner. Util. getProjectClassPath(xx)`
~~~
// 不处理 Project 之外的文件
  | if (!jarPath.contains(projectDir)) {
  | classPath << jarPath
  | println ">>> Skip ${jarPath}"
  | } 
~~~
 这里的逻辑是你的jar不在项目的目录结构下, 不被处理. 
存在的情况如下
1. 当你的引用的android gradle 版本较高的是时候,.你的aar依赖包不会放置在项目中的exploded-aar  中,而是有一个全局的Cache目录下.
2. 你依赖的是一个jar 而不是aar 的时候.
3. 你依赖的是一个project lib  .当这个project lib 不在目录下的时候. 

上面3种情况都会导致你的 jar 不在项目目录结构下. 导致你的代码注入失败.或者有别的问题.

**Comment by jiongxuan** [comment]
您好，非常感谢您发现的问题。

还请问下，您上述提到的这几点，是否已经试过，发现确实有问题呢？
（@erhu 兄，一起关注下吧）

**Comment by zzz40500** [comment]
验证过的

**Comment by lizhangqu** [comment]
确实存在这种情况，尤其是高版本的gradle存在build cache，dim威武

**Comment by jiongxuan** [comment]
感谢 @zzz40500 的给力提交哈！

@lizhangqu 方便的话Review下改动哈。确保没问题后麻烦回复一声，我就直接Merge了。辛苦！

**Comment by lizhangqu** [comment]
@jiongxuan 没问题

**Comment by jiongxuan** [comment]
@zzz40500 您的代码已合入Master。非常感谢！在下一版（2.1.5）中将体现。
