### ISSUE TITLE
RePlugin插件不支持gradle多渠道打包吗

### ISSUE THREAD

**Issue by xushihai** [Qihoo360/RePlugin#171]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**宿主： classpath 'com.qihoo360.replugin:replugin-host-gradle:2.1.2'，
               compile 'com.qihoo360.replugin:replugin-host-lib:2.1.3'
 插件：   classpath 'com.qihoo360.replugin:replugin-host-gradle:2.1.2'，
               compile 'com.qihoo360.replugin:replugin-plugin-lib:2.1.3'**:

**Android compile SDK version   23**:
**Android ROM  22**:
**Android studio 2.3.3**:
**gradle 3.3**:

1.编写一个最简单的插件(使用Appcompat)能正常启动；

2.在1的基础上，在build.gradle文件中加入 flavorDimensions 和 productFlavors来实现gradle多渠道打包，启动这个插件时就会报java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.异常。

**Comment by wangyupeng1-iri** [comment]
支持，请切换到2.1.5版本，或者即将发版的2.1.6版本
