### ISSUE TITLE
宿主与插件之间可以用Intent传递数据吗

### ISSUE THREAD

**Issue by VeryCure** [Qihoo360/RePlugin#172]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:

**Android compile SDK version**:

**Android ROM**:

如题，可以在插件获取宿主得数据吗？比如userId之类的

**Comment by yibaimishenlan** [comment]
本人亲测过， 可以的， 如果是对象、集合等啥的， 建议用  aidl 方式。

**Comment by VeryCure** [comment]
@yibaimishenlan 就像平常那样传递就行了吗？
Intent intent = RePlugin.createIntent("demo1", "com" +
                        ".qihoo360.replugin.sample" +
                        ".demo1.MainActivity");
                intent.putExtra("haha","哈哈哈");
                RePlugin.startActivity(MainActivity.this,intent );
插件怎么接收呢？谢谢解答哈

**Comment by yibaimishenlan** [comment]
@VeryCure 对的，在所需要接收的Activity 中  getIntent().getXXX(key);

**Comment by VeryCure** [comment]
@yibaimishenlan 试过，不可以

**Comment by VeryCure** [comment]
@yibaimishenlan 可以了，谢谢
