### ISSUE TITLE
继承BaseActivity不会替换成PluginActivity！！！

### ISSUE THREAD

**Issue by CSDgod** [Qihoo360/RePlugin#173]
1.A继承BaseActivity  BaseActivity继承Activity 运行后 A和Base都不会被替换成pluginactivity
2.app工程中的activity去继承依赖的submodule里的BaseActivity 一样也不能替换成pluginactivity。
但是没有这些继承关系 就能被替换。。。求解

app-build.gradle: 2.13
build.gradle: 2.14

**Comment by jiongxuan** [comment]
您好。

1. 正常情况下，替换完成后，A仍然继承自BaseActivity，而BaseActivity会被替换成PluginActivity，这个是经过验证的。但听群里的同学说有可能出现通过Maven依赖的时候，高版本Gradle可能会替换失败，这可能是一种原因。
2. 方便的话您把所有依赖的Gradle插件列表发出来，我们看看是不是和别的替换方案冲突了。

**Comment by CSDgod** [comment]
@jiongxuan 
![tcdevl0 sfqbhzej 43fxp6](https://user-images.githubusercontent.com/14586630/28103417-351d184c-6708-11e7-8220-916583623ae7.png)
![9 z5 xv 3vvb4k1 _s1lho](https://user-images.githubusercontent.com/14586630/28103433-4857a5da-6708-11e7-9839-000add40484b.png)

**Comment by jiongxuan** [comment]
您可以试下最新的2.1.6版本，有同学对Gradle AAR替换策略做了更多的支持，应该能解决您的问题了。
