### ISSUE TITLE
WebView读取asserts中的html文件，提示:ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by bensanpast** [Qihoo360/RePlugin#177]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:com.qihoo360.replugin:replugin-host-gradle:2.1.2
                                com.qihoo360.replugin:replugin-host-lib:2.1.1

**Android compile SDK version**:25

**Android ROM**:红米4x, MIUI8.2.18.0,Android6.0.1

插件工程的WebView通过 mWebView.loadUrl("file:///android_asset/1.html");方式读取asserts中的html文件，提示网页无法加载。错误信息：    ERR_FILE_NOT_FOUND

**Comment by fourmigh** [comment]
我也遇到了类似问题，需要WebView加载assets下的js、html等文件，是否插件还不支持该功能？

**Comment by jiongxuan** [comment]
您好，这个Context是插件的Context吗？

**Comment by bensanpast** [comment]
@jiongxuan 您好，非常感谢您的帮助。您指的Context是哪一个，应该如何正确使用WebView。
插件程序只用到了两行代码：
mWebView= (WebView) findViewById(R.id.webview);
mWebView.loadUrl("file:///android_asset/1.html");
插件单独运行可以正常加载，显示。
集成到宿主里（内置插件），宿主启动插件后，网页无法打开，提示：
位于file:///android_asset/1.html的网页无法加载，因为：net：ERR_FILE_NOT_FOUND

**Comment by jiongxuan** [comment]
好的，这个我们先看看。我们有个WebView插件是不会有这个问题的，但我忘了是不是做了什么特殊处理

**Comment by SkyEric** [comment]
@bensanpast 你好，不知道你有没有设置webview的允许使用File协议，使你能访问asset加载本地的HTML文件。即：WebView.getSettings().setAllowFileAccess(true)，不过会存在WebView跨源攻击问题，你可以做一些相关的安全策略；
另外，采用插件化后，WebView并不能完美地读取主程序和插件内的assets中Html文件，其中android api < 19 只能读取插件assets中的html文件，而api >= 19 只能读取主程序assets中的html文件，具体原因就是，在api 19后，webview内核由WebKit过渡到了Chromium，其内部的getAssets方法的Context由mContext改成ApplicationContext。问题修改建议：将assets中的Html等文件提出到File System中（如插件的cache中）。

**Comment by jiongxuan** [comment]
非常感谢 @SkyEric 兄的建议。我觉得可以整理到FAQ上，提醒后来人。

**Comment by bensanpast** [comment]
@ 刘志伟您好，非常感谢您百忙之中给我回复，按照您的建议我的问题已经得到解决。
我们现在的需求是在项目中引入现有的Cordova工程（用replugin实现），刚开始就遇到下面那个问题。不知replugin是否支持Cordova工程作为插件。



---------------------------
liguang_liang@163.com
 
发件人： 刘志伟
发送时间： 2017-08-07 15:42
收件人： Qihoo360/RePlugin
抄送： bensanpast; Mention
主题： Re: [Qihoo360/RePlugin] WebView读取asserts中的html文件，提示:ERR_FILE_NOT_FOUND (#177)
@bensanpast 你好，不知道你有没有设置webview的允许使用File协议，使你能访问asset加载本地的HTML文件。即：WebView.getSettings().setAllowFileAccess(true)，不过会存在WebView跨源攻击问题，你可以做一些相关的安全策略；
另外，采用插件化后，WebView并不能完美地读取主程序和插件内的assets中Html文件，其中android api < 19 只能读取插件assets中的html文件，而api >= 19 只能读取主程序assets中的html文件，具体原因就是，在api 19后，webview内核由WebKit过渡到了Chromium，其内部的getAssets方法的Context由mContext改成ApplicationContext。问题修改建议：将assets中的Html等文件提出到File System中（如插件的cache中）。

**Comment by jiongxuan** [comment]
这个没有尝试过，我们没用到过Cordova。

**Comment by jiongxuan** [comment]
@SkyEric 兄，写个WebView的Sample吧，这样大家以后也能减少类似的困惑。

把Sample直接写到Demo2中，让Demo1去使用它。当然Demo2也可以唤起自己的WebView页面（例如网页内跳转）。

**Comment by kylin17** [comment]
@SkyEric 那么对于API>=19的插件中，都无法读到插件工程的assets文件，如何将assets文件提出到File System中呢？

**Comment by drivenwinder** [comment]
@bensanpast, 你是如何解决的？用到了cordova 插件吗?

**Comment by e9ab98e991ab** [comment]
我也遇到了这个问题 插件中的 coocs2d 游戏文件无法读取 插件本身的targetSdkVersion 是 9 
读取只能放到宿主中 那这样插件就没意义了 请问有什么方式可以解决？
