### ISSUE TITLE
[Question] 是否支持插件加固？

### ISSUE THREAD

**Issue by shaobin0604** [Qihoo360/RePlugin#179]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:

**Android compile SDK version**:

**Android ROM**:

如题，插件是否支持第三方厂商提供的加固服务，例如：
1. 360
2. 梆梆
3. 乐固
...

**Comment by jiongxuan** [comment]
您好，插件本身的加固我们没有尝试过，宿主是没问题的。您可以先试下，如果有问题咱们可以再看看如何解决。

**Comment by shaobin0604** [comment]
@jiongxuan 好的谢谢，我先测试一下
