### ISSUE TITLE
插件列表在哪儿可以看到？

### ISSUE THREAD

**Issue by Sabirjan** [Qihoo360/RePlugin#18]
插件列表在哪儿可以看到？

**Comment by jiongxuan** [comment]
您说的是“目前我们用到的插件”，还是“如何看到安装的插件信息”？

我们用到的插件：https://github.com/Qihoo360/RePlugin#已接入replugin的插件

插件的管理（含列表）：https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%92%E4%BB%B6%E7%9A%84%E7%AE%A1%E7%90%86
