### ISSUE TITLE
是否支持arr作为插件？

### ISSUE THREAD

**Issue by yeleaveszi** [Qihoo360/RePlugin#180]
如题，arr和apk都是zip结构，感觉原理应该相似，但是好像很少有arr作为插件的资料，arr更轻，而且包含了类和资源，感觉更适合作为插件，请问RePlugin可以做到吗？

**Comment by smartOf360** [comment]
arr直接引用就可以了，多方便啊，为啥要直接作为插件使用呢？

**Comment by liuqun567** [comment]
aar 里是jar包，难道要给你动态转dex？

**Comment by zzz40500** [comment]
也不是不可以, 写个插件桥接一下,再 简单点就是你建个空项目,只引入那个aar 不就好了. 多动手

**Comment by jiongxuan** [comment]
@yeleaveszi 我们很多插件都是引用了AAR，甚至有的“只有AAR”（例如桌面插件），但RP是支持的

**Comment by yeleaveszi** [comment]
@jiongxuan 谢谢回答。插件里的AAR好像不起作用吧，使用RePlugin后产生的APK，反编译以后，发现Replugin的Gradle插件并没有修改AAR里面相关的类，只能做到修改jar包里的类。另外，直接使用AAR作为插件而不是APK是不是会比较困难？Android似乎没有提供获取AAR包里信息的接口。

**Comment by qixinmin** [comment]
@yeleaveszi 你们的aar方案或者说之前之前说的写个插件桥接一下，实验是否成功了？？

**Comment by jiongxuan** [comment]
@yeleaveszi 如我刚才沟通，“直接使用AAR作为插件”是可以的，只要创建个新工程，引用这个AAR就行。当然还有一点，需要将RePlugin版本升级到2.1.7，新版解决了AAR替换可能失败的问题。

还有，AAR和APK是两个概念。RePlugin加载的是APK，AAR必须依附于APK而存在（这也符合Android的开发规范）。
