### ISSUE TITLE
如何解决插件和宿主都依赖某些公共库的 case？

### ISSUE THREAD

**Issue by nomatterhoe** [Qihoo360/RePlugin#182]
我们的宿主和插件会依赖一些公共库，比如 network，logger 库等等。原来的开发方式是它们在一个工程，都通过 compile project 的方式进行依赖。看了 #43 的问题，如果 RePlugin 不支持插件和宿主在同一个工程开发的话，该如何解决对公共库的依赖？

**Comment by shaobin0604** [comment]
@nomatterhoe 公共库打成 JAR 包，上传到 maven 仓库（公司内部可以使用 nexus），宿主使用 compile 依赖，插件使用 provided 依赖

**Comment by jiongxuan** [comment]
是的，正如 @shaobin0604 所述（多谢帮忙解答）。

我们预计这周会出一个Sample，来专门说下公共库的事儿，大家欢迎随时关注。

**Comment by shaobin0604** [comment]
@jiongxuan :smiley:

**Comment by whosmyqueen** [comment]
打jar包依赖太麻烦了吧

**Comment by shaobin0604** [comment]
@whosmyqueen 可以写一个 gradle 插件，在插件编译时将配置的不需要打包到插件中的公共库排除掉

**Comment by monty8800** [comment]
@jiongxuan 这个Sample现在有了吗？

**Comment by Tan-Tshunglee** [comment]
关注公共库sample
