### ISSUE TITLE
模块安装后是否立即生效？模块可以加固更新吗？

### ISSUE THREAD

**Issue by fangliangv587** [Qihoo360/RePlugin#183]
如题
模块安装后是否立即生效？模块可以加固更新吗？

**Comment by jiongxuan** [comment]
如果“安装”的话是立即生效，如果是“升级”的话，得看插件是否在运行。详细可参见我们的WiKi文档，有详细说明。

模块是否支持加固，这个还没有测试过。您可以尝试下看看。目前我们插件是没做加固的。
