### ISSUE TITLE
Could not get unknown property 'outputFile'

### ISSUE THREAD

**Issue by yingchen066** [Qihoo360/RePlugin#187]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:
2.1.4
**Android compile SDK version**:
20
**Android ROM**:

android studio 3.0 build tool 版本
        classpath 'com.android.tools.build:gradle:3.0.0-alpha6'
上编译的时候报错
Error:Execution failed for task ':eGovaMobile:processDebugManifest'.
> Could not get unknown property 'outputFile' for task ':eGovaMobile:processDebugManifest' of type com.android.build.gradle.tasks.MergeManifests.

**Comment by jiongxuan** [comment]
AS 3.0上我们还没有做测试。问题先记下了，我们先看看AS后期会不会有其它改动。谢谢反馈

**Comment by wangyupeng1-iri** [comment]
已经处理了，请等待马上将要发版的2.1.6版本
