### ISSUE TITLE
插件单独运行没问题，以外置插件的形式启动就报错！

### ISSUE THREAD

**Issue by CSDgod** [Qihoo360/RePlugin#188]
![i7e 40 j0 cylq5c r 5 u](https://user-images.githubusercontent.com/14586630/28113438-1600fd58-672f-11e7-96a0-cf6a599ad513.png)

一开始以为是dialog上下文传的不对，或者dialog存活比activity久的原因，最终把弹窗代码都注释了 都还是一样报这个问题，但是如果插件单独运行就没问题，求解决。

项目：公司项目，非demo
app-build.gradle:2.1.3
build.gradle.gradle:2.1.4

**Comment by jiongxuan** [comment]
看起来像是权限问题。您单品和宿主上的权限声明是否一致呢？
