### ISSUE TITLE
在汉语中“您”是复数，“您们”是错误的语法，我这是鸡蛋里挑骨头么

### ISSUE THREAD

**Issue by fanOfDemo** [Qihoo360/RePlugin#19]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:

**Android compile SDK version**:

**Android ROM**:

**Comment by jiongxuan** [comment]
这是一个很严肃又值得讨论的问题。Issue我们不关了。

等彻底开源后好好翻翻新华字典，然后全文替了。:)

感谢您的建议。
