### ISSUE TITLE
RePlugin支持“共享View”方案（例如公共UI库的使用等），这样“无缝获取资源”的场景

### ISSUE THREAD

**Issue by yingchen066** [Qihoo360/RePlugin#191]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).
共享View方案时候指什么，当宿主和插件同时引用一个基础库（包含资源文件的aar包），这种场景还有办法使用RePlugin 吗？

**Comment by jiongxuan** [comment]
您好。请参见：

https://github.com/Qihoo360/RePlugin/wiki/FAQ
