### ISSUE TITLE
插件在第三方平台加固后，宿主能不能加载这个插件？

### ISSUE THREAD

**Issue by manymore13** [Qihoo360/RePlugin#20]
1.  插件在第三方平台(360加固，梆梆加固)加固后，宿主是否支持加载这个插件？
2.  插件加不加固对于宿主有没有什么影响？或者在开发上有什么区别？

**Comment by jiongxuan** [comment]
您好，感谢问询。

目前我们的宿主是支持加固后运行插件的（我知道有的框架不行），但插件加固这块儿，老实说，我们还**没试验过**，不敢说行还是不行。

因时间关系，等我们彻底开源后，会做一次这方面的试验。到时候会把Feedback回馈给您。

**Comment by Hiram-Y** [comment]
持续关注中……

**Comment by vb0067** [comment]
关注

**Comment by jiongxuan** [comment]
我们已将“试验混淆后插件是否可用”作为下一步要测试的步骤，到时候会同步到FAQ中，欢迎大家关注。

此Issue暂时关闭。感谢理解！
