### ISSUE TITLE
application初始化报错The class must not be null

### ISSUE THREAD

**Issue by junge89221** [Qihoo360/RePlugin#200]
05-30 13:58:04.563 23198-23198/com.yishengyue.lifetime W/System.err: java.lang.IllegalArgumentException: The class must not be null
05-30 13:58:04.563 23198-23198/com.yishengyue.lifetime W/System.err:     at com.qihoo360.replugin.ext.lang3.Validate.isTrue(Validate.java:167)
05-30 13:58:04.563 23198-23198/com.yishengyue.lifetime W/System.err:     at com.qihoo360.replugin.ext.lang3.reflect.FieldUtils.getField(FieldUtils.java:85)
05-30 13:58:04.563 23198-23198/com.yishengyue.lifetime W/System.err:     at com.qihoo360.replugin.ext.lang3.reflect.FieldUtils.readStaticField(FieldUtils.java:337)
05-30 13:58:04.563 23198-23198/com.yishengyue.lifetime W/System.err:     at com.qihoo360.replugin.helper.HostConfigHelper.readField(HostConfigHelper.java:154)
05-30 13:58:04.563 23198-23198/com.yishengyue.lifetime W/System.err:     at com.qihoo360.replugin.helper.HostConfigHelper.<clinit>(HostConfigHelper.java:126)
05-30 13:58:04.563 23198-23198/com.yishengyue.lifetime W/System.err:     at com.qihoo360.replugin.RePlugin$App.attachBaseContext(RePlugin.java:866)
05-30 13:58:04.563 23198-23198/com.yishengyue.lifetime W/System.err:     at com.qihoo360.replugin.RePlugin$App.attachBaseContext(RePlugin.java:818)
05-30 13:58:04.563 23198-23198/com.yishengyue.lifetime W/System.err:     at com.yishengyue.lifetime.YSYApplication.attachBaseContext(YSYApplication.java:36)
05-30 13:58:04.563 23198-23198/com.yishengyue.lifetime W/System.err:     at android.app.Application.attach(Application.java:181)
05-30 13:58:04.563 23198-23198/com.yishengyue.lifetime W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:992)
05-30 13:58:04.563 23198-23198/com.yishengyue.lifetime W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:976)
05-30 13:58:04.563 23198-23198/com.yishengyue.lifetime W/System.err:     at android.app.LoadedApk.makeApplication(LoadedApk.java:503)
05-30 13:58:04.563 23198-23198/com.yishengyue.lifetime W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4481)
05-30 13:58:04.563 23198-23198/com.yishengyue.lifetime W/System.err:     at android.app.ActivityThread.access$1500(ActivityThread.java:142)
05-30 13:58:04.563 23198-23198/com.yishengyue.lifetime W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1273)
05-30 13:58:04.563 23198-23198/com.yishengyue.lifetime W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
05-30 13:58:04.563 23198-23198/com.yishengyue.lifetime W/System.err:     at android.os.Looper.loop(Looper.java:142)
05-30 13:58:04.563 23198-23198/com.yishengyue.lifetime W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5217)
05-30 13:58:04.563 23198-23198/com.yishengyue.lifetime W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
05-30 13:58:04.563 23198-23198/com.yishengyue.lifetime W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
05-30 13:58:04.563 23198-23198/com.yishengyue.lifetime W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
05-30 13:58:04.563 23198-23198/com.yishengyue.lifetime W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
05-30 13:58:04.563 23198-23198/com.yishengyue.lifetime W/System.err:     at dalvik.system.NativeStart.main(Native Method)

![image](https://user-images.githubusercontent.com/12729702/28160241-24a2c698-67f2-11e7-8d92-f528718ea60e.png)

**Comment by jiongxuan** [comment]
您好，这应该只是个Warning，不是报错。不过我们也已经将其做了屏蔽。这样不会对未来的同学造成困扰。
