### ISSUE TITLE
主程序调插件出如下问题，插件可以跳主程序。

### ISSUE THREAD

**Issue by sw950729** [Qihoo360/RePlugin#204]
start activity: intent=Intent { cmp=demo/com.angel.replugin2.MainActivity } plugin=demo activity=com.angel.replugin2.MainActivity process=-2147483648
07-14 11:47:12.489 31236-31236/com.angel.replugin D/RePlugin.ws001: start activity: intent=Intent { cmp=demo/com.angel.replugin2.MainActivity } plugin=demo activity=com.angel.replugin2.MainActivity process=-2147483648 download=true
07-14 11:47:12.489 31236-31236/com.angel.replugin D/RePlugin.ws001: plugin=demo not found, start download ...
07-14 11:47:12.489 31236-31236/com.angel.replugin D/RePlugin.ws001: isNeedToDownload(): V5 file not exists. Plugin = demo

**Comment by xiaozhilaoliu** [comment]
问题解决了吗？

**Comment by jiongxuan** [comment]
虽然您截出来的Log并没有出现真正的错误原因，但可以使用最新版（2.1.7）来试试
