### ISSUE TITLE
PluginInfo 空指针

### ISSUE THREAD

**Issue by KS-S** [Qihoo360/RePlugin#208]
内置插件 已经成功  但是外置插件一直都是报null
<img width="431" alt="sd" src="https://user-images.githubusercontent.com/28801554/28204906-683d79c8-68b2-11e7-8423-623b2c874b6f.png">
<img width="389" alt="ss" src="https://user-images.githubusercontent.com/28801554/28204909-69fb96c8-68b2-11e7-8bb4-1f771cd4e90a.png">
<img width="717" alt="ff" src="https://user-images.githubusercontent.com/28801554/28204910-6cf4ee60-68b2-11e7-8b49-a6e49c1a5d57.png">

**Android ROM**:
<img width="1126" alt="qq20170714-163136 2x" src="https://user-images.githubusercontent.com/28801554/28204852-2b222a84-68b2-11e7-9a58-6f548a8b9411.png">

**Comment by KS-S** [comment]
<img width="428" alt="sdas" src="https://user-images.githubusercontent.com/28801554/28204970-ad4f1ba2-68b2-11e7-9fb8-142bd6a55f96.png">
传错了一张图

**Comment by jiongxuan** [comment]
您好，您的RePlugin版本是？是否做过rebuild呢？
