### ISSUE TITLE
请问有没有可能支持桌面版本

### ISSUE THREAD

**Issue by thexinchen** [Qihoo360/RePlugin#21]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:

**Android compile SDK version**:

**Android ROM**:

**Comment by jiongxuan** [comment]
您说的桌面是指“Launcher”呢？还是Linux桌面呢？

如果是Launcher的话，是没问题的。我们完美支持。不仅Launcher可以支持插件化，而且Launcher还能变成桌面插件。

若为Linux桌面的话，我们确实没尝试过。不过如果用的是Android系统的话，那肯定是没问题的

**Comment by thexinchen** [comment]
指的是PC软件的插件吧，目前还没有一个好用的插件框架，360安全卫士PC版本没有用插件框架吗？

**Comment by thexinchen** [comment]
目前PC端有个类似简化版OSGi的实现，cppmicroservice可以做这个，但不够成熟

**Comment by jiongxuan** [comment]
360安全卫士是有一套动态加载的方案，但和安卓的显然是两套，而且尚未提出公开计划。

所以我们不是很清楚这块儿。还请理解哈。
