### ISSUE TITLE
onInstallPluginFailed: Failed! path=/sdcard/dht/androidhelper.apk; r=V5_FILE_BUILD_FAIL

### ISSUE THREAD

**Issue by fishsoft** [Qihoo360/RePlugin#211]
安装外置插件时，PluginInfo为空，一直输出日志：onInstallPluginFailed: Failed! path=/sdcard/dht/androidhelper.apk; r=V5_FILE_BUILD_FAIL；
onInstallPluginFailed: Failed! path=/sdcard/dht/androidhelper.apk; r=VERIFY_VER_FAIL
请问一下，这个是怎么回事呢？在群里面问，一直没人为我解答！！！！

**Comment by jiongxuan** [comment]
您好，不好意思，因为群里的人很多，加上我们时间有限，无法一一回复问题。还请理解。

V5_FILE_BUILD_FAIL这个可以忽略，我们下一版会去掉这个输出
而VERIFY_VER_FAIL才是问题的根本原因，说白了就是“插件签名校验失败”，请参考《插件的管理》中会有详述：

https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%92%E4%BB%B6%E7%9A%84%E7%AE%A1%E7%90%86
