### ISSUE TITLE
java.lang.IllegalArgumentException: AppCompat does not support the current theme features

### ISSUE THREAD

**Issue by yu876835398** [Qihoo360/RePlugin#213]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:

**Android compile SDK version**:

**Android ROM**:

**Comment by jiongxuan** [comment]
您好，请参考《主程序接入指南》中关于AppCompat的描述：

https://github.com/Qihoo360/RePlugin/wiki/%E4%B8%BB%E7%A8%8B%E5%BA%8F%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97
