### ISSUE TITLE
replugin-plugin-library 2.1.5 插件引用 jar 失败

### ISSUE THREAD

**Issue by gunC** [Qihoo360/RePlugin#219]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**: 2.1.5

**Android compile SDK version**:25

**Android ROM**:-

2.1.5 的 插件 会把 libs 下的 jar 包解开,然后编译不过..

![tim 20170717165817](https://user-images.githubusercontent.com/1253658/28261322-46163504-6b11-11e7-94c5-384b4235e1ac.png)
![tim 20170717165807](https://user-images.githubusercontent.com/1253658/28261327-495e21ae-6b11-11e7-9f16-ebb8704f4170.png)
![tim 20170717165812](https://user-images.githubusercontent.com/1253658/28261324-477b9bd2-6b11-11e7-9db4-058515ffda92.png)

**Comment by gunC** [comment]
:libraries:serviceNo:transformClassesWith___ReClass___ForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':libraries:serviceNo:transformClassesWith___ReClass___ForDebug'.
> java.nio.file.NoSuchFileException: D:\app\libraries\serviceNo\build\intermediates\exploded-aar\4a7c1714500c9d9fbbc4301934e7a1818c6c03ab\class

**Comment by gunC** [comment]
那个 jar 包是个空包来的

**Comment by gunC** [comment]
应该是空的 jar 包解压后路径不存在...
但是我没试过编译 gradle 插件..

![tim 20170718174620](https://user-images.githubusercontent.com/1253658/28311084-1d9c1b4a-6be1-11e7-87b8-118c59c5faf5.png)

@zzz40500 @jiongxuan

**Comment by gunC** [comment]
可能出现空包的情况 , 引入没 java 代码的依赖库.
例如 bugly crash report

**Comment by wangyupeng1-iri** [comment]
请使用2.1.6版本
