### ISSUE TITLE
是否支持MultiDex方案

### ISSUE THREAD

**Issue by qq8803128** [Qihoo360/RePlugin#22]
你好，我方是做游戏SDK的，由于我方无法预知上游游戏厂商的游戏母包是否超过了65535方法数量限制而采用Multidex方案
1.replugin支持宿主使用Multidex方案
`
public class MultiDexApplication extends Application {
    public MultiDexApplication() {
    }

//写法有问题吗？
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        RePlugin.App.attachBaseContext(this);
        MultiDex.install(this);
    }
}

`

2 不支持宿主使用Multidex方案
可以告诉下吗

**Comment by jiongxuan** [comment]
您好，我们有App是同时使用了MultiDex方案，目前没有收到“问题”反馈。

然而，RePlugin不仅仅是解决了灵活与自由发版的问题，同样的，我们也间接解决了MultiDex的问题。所以老实说，我们对宿主接入MultiDex这块儿，确实没有做特别充分的测试。

如果您在使用当中遇到了问题，欢迎随时与我们联系。谢谢支持！

**Comment by a247124718** [comment]
都插件化了 怎么还有这种问题吖

**Comment by qq8803128** [comment]
我们的游戏是游戏厂商打的包 我们是二次修改 所以又这个问题 @a247124718

**Comment by jiongxuan** [comment]
@qq8803128 您可以试下把Sample工程里的host接入Multidex，看是否有问题。

**Comment by chenhui3014** [comment]
@jiongxuan 你好，Application 我们使用非继承模式，提示65535 的错误，是不是非继承模式不支持 MultiDex
