### ISSUE TITLE
activity hook

### ISSUE THREAD

**Issue by liuqun567** [Qihoo360/RePlugin#225]
系统的 Activity 我发现的目前有如下： 

"android/app/ActivityGroup",
            "android/app/TabActivity",
            "android/app/AliasActivity",
            "android/app/ExpandableListActivity",
            "android/app/ListActivity",
			"android/app/LauncherActivity", 
			"android/app/NativeActivity", 
			"android/accounts/AccountAuthenticatorActivity",
			"android/preference/PreferenceActivity",
			"android/support/v4/app/FragmentActivity",  
			"android/support/v4/app/BaseFragmentActivityDonut", 
			"android/support/v7/app/ActionBarActivity",
			"android/support/v7/app/AppCompatActivity",

**Comment by jiongxuan** [comment]
您好，请问是遇到什么问题了吗？
