### ISSUE TITLE
appt报错

### ISSUE THREAD

**Issue by myhonior** [Qihoo360/RePlugin#227]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin 2.1.5**:

**Android compile SDK 22**:
demo编译不过，build/intermediates/manifests/full/debug/AndroidManifest.xml 报错，No resource identifier found for attribute"roudnIcon" in package 'android',finished with no-zero exit value 1

**Comment by jiongxuan** [comment]
您好，请rebuild以后再试下，看是否仍有问题。此外这个roundIcon应该不在Demo1里，不知道是不是您自己添加进来了？

**Comment by myhonior** [comment]
rebuild过了，还是依然编译不过，生成的AndroidManifest.xml里，命名空间找不到，导致很多属性报错。demo 是从官网下载，原封未动

**Comment by myhonior** [comment]
是否对buildToos/sdk/gradle版本有要求？我用的是SDK是22，buildtool版本是22.0.1，gradle版本是2.14.1

**Comment by jiongxuan** [comment]
我们都试过的，这块儿是肯定没有问题的，毕竟是Sample。如有问题通常社区里面的人，会有很多这方面的反馈。

您看看把各版本升级到最新后再试试吧。
