### ISSUE TITLE
插件中使用getApplication().startActivity(intent)崩溃

### ISSUE THREAD

**Issue by icesunboy** [Qihoo360/RePlugin#228]
测试机型：小米2  安卓5.0.2   miui8.2
replugin版本：2.1.5

测试发现在插件activity中调用如下两个方法会崩溃，插件activity都是使用的PluginAppCompatActivity
getApplication().startActivity(intent);//崩溃
getApplicationContext().startActivity(intent);//崩溃

崩溃堆栈如下：
![default](https://user-images.githubusercontent.com/5178523/28309022-a2725ed0-6bda-11e7-8c59-9349c0295836.png)

直接在activity中使用this.startActivity没问题，能正常呼起

**Comment by jiongxuan** [comment]
您好，这个问题我已经修复了。在2.1.6版本（预计明天发布）会有显现。

**Comment by jiongxuan** [comment]
问题已解决，请升级到2.1.6版本即可（两周前发的）
