### ISSUE TITLE
支持插件间的资源 和 类的调用吗

### ISSUE THREAD

**Issue by skylz** [Qihoo360/RePlugin#23]
支持插件间的资源和类的调用吗？e.g. 公共基础库 打成插架供其他插架调用

**Comment by jiongxuan** [comment]
是的，我们是支持的。我们现在有很多插件，如WebView、ProtoBuf，都是这样的。比如WebView就有自己的资源，而Protobuf就有很多类。

**Comment by ab503044120** [comment]
@jiongxuan 
1.那怎么样调用其他库的class文件呢
2.如果我有一些基类什么的做成了lib,怎么样每个插件都能用上呢
3.我在host application中声明的变量在其他插件怎么拿到呢

**Comment by flynihao53** [comment]
我也想问这个问题

**Comment by jiongxuan** [comment]
可以通过反射来实现。我们本周会出个Sample，内附使用其它库Class文件的使用办法，欢迎参考。
