### ISSUE TITLE
2.1.5 插件gradle 当插件依赖库稍多时 , 编译时间相当长了

### ISSUE THREAD

**Issue by gunC** [Qihoo360/RePlugin#230]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:2.1.5

**Android compile SDK version**:25

**Android ROM**:-

```
Total time: 1 mins 56.644 secs
            Task timings:
            .....
            99455ms  :libraries:serviceNo:transformClassesWith___ReClass___ForDebug
            ....
```

2.1.5之后 , 因为每次编译都会去 unzip 依赖库 , 修改后再 ZIP 到 exploded-aar.
能否不要每次都这样操作

**Comment by jiongxuan** [comment]
您好，感谢您的建议。我们会考虑优化这块儿的。

当然如果您有更好的思路，欢迎随时提出您的PR，我们会经严格验证后会合入Master。谢谢理解

**Comment by zzz40500** [comment]
可以让,让ReClassTransform 支持增量特性.但是还是有一些额外的情况,需要特殊处理.
