### ISSUE TITLE
插件调用 host 资源 , R文件存在过时情况

### ISSUE THREAD

**Issue by gunC** [Qihoo360/RePlugin#232]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**: 2.1.5

**Android compile SDK version**: 25

**Android ROM**: -

我目前插件调用host资源的姿势是:
- 编译 host
- 把 host 的 class 打包jar
- 插件 `provided host.jar`
- 插件中调用 `RePlugin.getHostContext().getResources().getString(host_package.string.R.hello_world)` 获取资源

但是 R 文件的值在不同版本的 App 并不稳定..
或是我调用的姿势不对..

**Comment by jiongxuan** [comment]
建议采用getIdentifier来获取资源，当然，还可以用反射R文件来做。

R的ID会随着宿主的资源变化而变化，所以不能单纯以这种方式来获取。

**Comment by gunC** [comment]
嗯,我目前也是改成用 getIdentifier 的方式 .
我觉得可能要加入Demo , 声明一下对应的资源不能进行 [资源混淆](https://github.com/shwenzhang/AndResGuard)

**Comment by shibenli** [comment]
```
mPackageName = getPackageName();
int layout = getResources().getIdentifier("oliveapp_activity_liveness_detection_main", "layout", mPackageName);
```
在插件中这样获取自己的layout也不行呢，拿到了0。但是在自主安装插件apk中却是能够拿到的，是这里mPackageName 的原因吗

**Comment by shibenli** [comment]
是不是这里的Context是宿主的
