### ISSUE TITLE
统一各个模块版本号

### ISSUE THREAD

**Issue by goodev** [Qihoo360/RePlugin#235]
之前在QQ群中提到过，在这里也有人开了一个 Issue 不过被关闭了，再次提议一下版本号统一的议题，目前的版本号为：
        replugin-host-gradle:2.1.3
        replugin-host-lib:2.1.4
        replugin-plugin-gradle:2.1.4
        replugin-plugin-lib:2.1.3

可以看到 host 插件和lib版本号都不一样，使用起来是相当的不方便。

所以版本号不统一有如下问题：

1. 如上所示使用不便
2. 版本发布无法在 Git 中打 tag，这个问题更严重，比如以后 3.0 版本出现了不兼容性改动，但是很多用户不想升级 3.0 还在使用 2.X 的版本，这个时候如果 2.X 的版本有问题，想修复bug都不知道代码应该从哪里 checkout。

希望 RePlugin 插件开发团队可以考虑一下。

**Comment by gunC** [comment]
当前都是 2.1.5 
https://github.com/Qihoo360/RePlugin/wiki/%E5%8F%91%E8%A1%8C%E7%89%88%E6%9C%AC

**Comment by jiongxuan** [comment]
感谢Goodev的提示。这个我们在内部也讨论很久。我比较倾向于统一版本，这样好管理，也好打Tag，当然，统一的缺点是有些库可能“没有任何改动”，但也会“被迫升一个版本”。总之，这确实是个两难问题。

我们从2.1.5版本开始，将会统一起来。毕竟这也是大家反馈中都提到的。另外，多谢反馈！
