### ISSUE TITLE
已按文档实现 , 但依然出现错误 You need to use a Theme.AppCompat theme (or descendant) with this activity.

### ISSUE THREAD

**Issue by gunC** [Qihoo360/RePlugin#236]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**: 2.1.5

**Android compile SDK version**: 25

**Android ROM**:

- 已配置
```
       repluginHostConfig {
		useAppCompat = true
	}
```
- 已卸载重装 

但依然出现 ` You need to use a Theme.AppCompat theme (or descendant) with this activity.`

发现有人说插件的application不能设置主题,要在 Activity 设置
https://github.com/Qihoo360/RePlugin/issues/72#issuecomment-312787742

不知道以后是否会完善文档 or 修复?

**Comment by jiongxuan** [comment]
您好，感谢提问。文档已经完善了，在FAQ中。

至于修复，由于Theme这块儿机制极其复杂，我们不能承诺何时修复此问题。现在已有社区爱好者在看了。所以请先按照文档所述来做即可。谢谢！
