### ISSUE TITLE
牛逼，作为一个插件化的支持者，表示非常激动

### ISSUE THREAD

**Issue by a247124718** [Qihoo360/RePlugin#24]
准备赶紧接入试试。之前项目就是复用了DroidPlugin的核心技术，现在360又来了一个这么叼的。大赞。

**Comment by jiongxuan** [comment]
您好，非常感谢您的鼓励和支持！请相信，我们以及联合开源社区的力量，会持续的完善RePlugin，让其变得越来越好！

RePlugin已经开源，欢迎阅览，提出指正建议。也欢迎您为RePlugin做下宣传，让大家一起为“全面插件化”而努力！
