### ISSUE TITLE
应用第三方activity的theme为null

### ISSUE THREAD

**Issue by istarvip** [Qihoo360/RePlugin#246]
插件中用了第三方扫码的库  
[链接](https://github.com/yipianfengye/android-zxingLibrary)

打开其中的一个扫码的activity：
![image](https://user-images.githubusercontent.com/12675437/28447303-86924a20-6e02-11e7-830e-1834f703cb16.png)

插件自己运行不会报错，用的宿主中打开（第三方的activity指的是CaptureActivity）就会报错（其他插件中定义的activity都可正常打开）。

 
![image](https://user-images.githubusercontent.com/12675437/28447451-615421b0-6e03-11e7-88a4-36735083ea6c.png)

加入了下面的代码亦不会生效：
repluginHostConfig {
    useAppCompat = true
}

下面是安装成功后打开插件时打印的日志：

![image](https://user-images.githubusercontent.com/12675437/28447400-14d9f44a-6e03-11e7-8bcf-7718fff3e94f.png)

其中在清单文件中设置的除了name的值外，其他都成了null。

**Comment by erhu** [comment]
请参看FAQ：https://github.com/Qihoo360/RePlugin/wiki/FAQ#qjavalangillegalstateexception-you-need-to-use-a-themeappcompat-theme-or-descendant-with-this-activity

在 Manifest 中将 CaptureActivity 的主题声明为 @style/Theme.AppCompat 应该就OK了。

**Comment by jiongxuan** [comment]
辛苦 @erhu 兄的解答。
