### ISSUE TITLE
插件引用aar，aar中有so库，启动插件报java.lang.UnsatisfiedLinkError异常

### ISSUE THREAD

**Issue by xushihai** [Qihoo360/RePlugin#248]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version：2.1.6**:

**Android compile SDK version：23**:

**Android ROM：华为**:

插件引用aar，aar中有so库，启动插件报java.lang.UnsatisfiedLinkError异常

异常详情：
java.lang.UnsatisfiedLinkError: com.qihoo360.replugin.PluginDexClassLoader[DexPathList[[zip file "/data/user/0/com.qihoo360.replugin.sample.host/app_p_a/243047317.jar"],nativeLibraryDirectories=[/data/user/0/com.qihoo360.replugin.sample.host/app_p_n/243047317, /vendor/lib64, /system/lib64]]] couldn't find "libyuv.so"

为啥显示的/data/user路径而不是/data/data？

**Comment by keyescgm** [comment]
大佬，你这边解决了吗？
