### ISSUE TITLE
关于SharedPreferences的共享

### ISSUE THREAD

**Issue by flyingwh** [Qihoo360/RePlugin#249]
![replugin](https://user-images.githubusercontent.com/6701327/28509625-1b2d3cd8-7076-11e7-8398-90285a0bd720.png)
这里是不是给用户一个选择会更好一点，让用户来决定是否完全隔离SharedPreferences，很多情况下还是有通过SharedPreferences来共享数据的情况存在的

**Comment by jiongxuan** [comment]
您好，这个问题我们是Won't Fix的。

开发者可以通过Context来自由选择是使用“宿主”的，还是“插件”的。是有选择权的。

不过我们可以在文档中简单说明一下，避免以后有人询问。

**Comment by flyingwh** [comment]
假如说有十几个插件，每个插件的preference前面都加一个“plugin“的前缀好像没有什么意义吧，因为前缀并不是用的插件名称，并没有达到区分的效果啊

**Comment by jiongxuan** [comment]
前缀是要加的，这样能准确区分哪些是插件的SharedPref，哪些不是，即便现在用不到，但为了以后考虑也需要写

**Comment by zhaojunying0503** [comment]
那请问如果我个人想混着调用app 的配置，怎么解决呢？

**Comment by terrychao2013** [comment]
一些第三方的sdk会使用到context，比如监听application 对于activity的回调，系统会传回plugincontext，导致一些错误，这种情况要如何处理呢？
