### ISSUE TITLE
能不能建个QQ群

### ISSUE THREAD

**Issue by Hiram-Y** [Qihoo360/RePlugin#25]
能不能建个QQ群，一旦发布了直接在群里同步一下消息就行了

**Comment by zourb** [comment]
赞楼上，类似tinker群一样，有新的版本发布信息在群里也实时同步

**Comment by jiongxuan** [comment]
不好意思，我们这段时间一直忙开源的事情，没公开。其实我们有一个RePlugin微信群。
等今晚开源后，我们会放到WiKi上。

谢谢理解。

**Comment by tokiii** [comment]
今晚就开源啊，刚用了滴滴的VirtualAPK 感觉体验不太好

**Comment by jiongxuan** [comment]
是的，RePlugin已经开源。欢迎大家参阅，并提出宝贵的指正建议。

微信群已经建立，稍后我会上传到WiKi上，欢迎大家加入探讨！

**Comment by Hiram-Y** [comment]
没有在WiKi找到公开的微信群和qq群呢？

**Comment by ysrfeng** [comment]
@jiongxuan 没找到微信群，可以在这里发下？

**Comment by jiongxuan** [comment]
好的，我这就发一下。

微信号：
![weixingroup](https://user-images.githubusercontent.com/4717125/27798520-21404bde-6044-11e7-804d-fc19867c2851.jpg)

**Comment by jiongxuan** [comment]
QQ群也建好了，欢迎大家访问：653205923
