### ISSUE TITLE
插件工程assets里的文件读取不到

### ISSUE THREAD

**Issue by fourmigh** [Qihoo360/RePlugin#252]
我原先的工程里有资源文件是放在assets里，比如html、js等。
但把工程改为plugin后，用host调起后就读不到这些文件了，比如WebView会报“Not allowed to load local resource”之类的错。
将文件拷贝至host工程里后，就能读到了。
这算是一个BUG吧？

**Comment by yunTerry** [comment]
我也遇到同样的问题，宿主打开插件时插件APP里面assets中的文件读不到了
![log](https://user-images.githubusercontent.com/15991012/28560047-a90c1fbc-714b-11e7-96d5-d4f6ef902d66.png)

**Comment by jiongxuan** [comment]
和 #177 应该是同一问题，我们合并到单独Issue里吧
