### ISSUE TITLE
4.4手机通过Intent传递序列化参数的问题

### ISSUE THREAD

**Issue by flyingwh** [Qihoo360/RePlugin#257]
4.4的系统上，通过Intent传递序列化参数，接收不到，在高版本是正常的，基本的参数类型也都是正常的 @jiongxuan

**Comment by jiongxuan** [comment]
您说的是Parcelable还是Serializable？

**Comment by wardenlzr** [comment]
Serializable

**Comment by jessehev** [comment]
@wardenlzr  传递的对象类名需要和接受时的对象全类名一样

**Comment by jessehev** [comment]
@wardenlzr 传递的对象全类名需要和接受时的对象全类名一样

**Comment by wardenlzr** [comment]
我宿主和插件使用的是同一个moudle（library）里面的bean对象 @jessehev
