### ISSUE TITLE
RePlugin.startActivity执行时报

### ISSUE THREAD

**Issue by T-BayMax** [Qihoo360/RePlugin#258]
Didn't find class "com.qihoo360.replugin.Entry" on path: DexPathList[[zip file "/data/user/0/com.ike.communityalliance/app_p_a/419924309.jar"],nativeLibraryDirectories=[/data/user/0/com.ike.communityalliance/app_p_n/419924309, /system/lib, /vendor/lib]]
                                                                  java.lang.ClassNotFoundException: Didn't find class "com.qihoo360.replugin.Entry" on path: DexPathList[[zip file "/data/user/0/com.ike.communityalliance/app_p_a/419924309.jar"],nativeLibraryDirectories=[/data/user/0/com.ike.communityalliance/app_p_n/419924309, /system/lib, /vendor/lib]]

**Comment by byecode** [comment]
1.看下插件工程的包是否包含类com.qihoo360.replugin.Entry
2.如果包含，看下是否开启了multidex。如果开启了是有几率触发次问题的。

**Comment by T-BayMax** [comment]
multidex我设置为false，我用的是高德地图估计是lib有问题，abi都设置为'x86',  'armeabi', 'armeabi-v7a'

**Comment by jiongxuan** [comment]
感谢 @byecode 回答。高德地图我们在卫士插件中是确认过，没有问题的。

通常出现Entry的原因是没有引入replugin-plugin-gradle，请参见FAQ中的详细说明。

**Comment by T-BayMax** [comment]
还有个问题就是包有点大使用了com.ceabie.dextools:gradle-dexknife-plugin:1.6.1分包，com.qihoo360.replugin放在了主包中还是报这个错误

**Comment by T-BayMax** [comment]
应该是com.ceabie.dextools:gradle-dexknife-plugin:1.6.1分包的问题，打包后虽然有主classes有找到com.qihoo360.replugin.Entry但还是报错，自己手动添加maindexlist.txt在里面添加com.qihoo360.replugin打包进去就好了，具体操作请参考http://blog.csdn.net/gaozhan_csdn/article/details/52024497，感谢博主

**Comment by jiongxuan** [comment]
非常感谢 @T-BayMax 的建议。如咱们在Q群中所述，出现这个问题很可能是因为分包导致的。
同时我也将其同步到FAQ上，提醒后来者。

**Comment by YuDongZhang** [comment]
@T-BayMax  你提供的博客的连接不能用了

**Comment by miLLlulei** [comment]
> @T-BayMax 你提供的博客的连接不能用了
链接里没有 "感谢博主"
http://blog.csdn.net/gaozhan_csdn/article/details/52024497

**Comment by YuDongZhang** [comment]
我还发现了一个问题 , 在打包的时候 一定要打开 gradle console  , 只要有问题即使包成功了也不行 , 没有连续多行的报红才是 合格的包  , 自己亲测 ,  同样的代码 , 只要是报红就有问题
