### ISSUE TITLE
在插件中使用 LocalBroadcastManager 报错

### ISSUE THREAD

**Issue by zhangkangbin** [Qihoo360/RePlugin#259]
**RePlugin version**:2.16

**Android compile SDK version**:25

**Android ROM**:三星s8
在我的小米上面也报错。
使用 LocalBroadcastManager 报错
大约如下：
java.lang.ClassCastException: android.support.v4.content.LocalBroadcastManager cannot be cast to com.qihoo360.replugin.loader.b.PluginLocalBroadcastManager  at com.qihoo360.replugin.loader.b.PluginLocalBroadcastManager.registerReceiver(Unknown Source)

插件中生成的代码：
     BroadcastReceiver var3 = this.broadcastReceiver;
     LocalBroadcastManager var2 = this.localBroadcastManager;
     PluginLocalBroadcastManager.registerReceiver(var2, var3, filter);

**Comment by zhangkangbin** [comment]
估计是插件的类替换失败了 ，我瞎猜的。android.support.v4.content.LocalBroadcastManager.getInstance() <With> com.qihoo360.replugin.loader.b.PluginLocalBroadcastManager.getInstance()

**Comment by jiongxuan** [comment]
能留下具体的Logcat吗？

**Comment by zhangkangbin** [comment]
我这this.localBroadcastManager是个常量，源码里面只替换方法里面的方法。所以这个就没有被替换。

**Comment by wangfuda** [comment]
这个问题可以关掉了吧，因为plugin-gradle只替换方法体，不替换变量方式定义的代码，把定义放到方法中即可替换了。

**Comment by jiongxuan** [comment]
结合 @wangfuda 所说，我大概理解是怎么回事了。

PluginLocalBroadcastManager和LocalBroadcastManager是平行关系（而非继承），如果尝试用var2（LocalBroadcastManager）来作为参数传入PluginLocalBroadcastManager的话，则必然会报错。

所以，必须要做到，要么全部用PluginLocalBroadcastManager，要么全部用LocalBroadcastManager，不能混用。
