### ISSUE TITLE
在插件的Application的onCreate方法中调用startService方法启动一个服务,RePlugin报错

### ISSUE THREAD

**Issue by jiashilei-1985** [Qihoo360/RePlugin#260]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).
我在插件工程的Application中的onCreate方法中通过startService启动了一个服务(每隔30秒打印一行字符),
RePlugin报错,日志太多,控制台也显示不全

07-27 09:31:04.920 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.replugin.component.service.PluginServiceClient.startService(PluginServiceClient.java:106)

07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.loader2.PluginContext.startService(PluginContext.java:500)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at android.content.ContextWrapper.startService(ContextWrapper.java:494)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.example.kcmds.pluginclient.MyApplication.onCreate(MyApplication.java:22)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.replugin.component.app.PluginApplicationClient.callOnCreate(PluginApplicationClient.java:225)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.loader2.Plugin.callAppLocked(Plugin.java:905)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.loader2.Plugin.callApp(Plugin.java:884)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.loader2.Plugin.load(Plugin.java:435)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.loader2.PmBase.loadPlugin(PmBase.java:1045)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.loader2.PmBase.loadAppPlugin(PmBase.java:1030)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.loader2.PluginCommImpl.queryPluginContext(PluginCommImpl.java:196)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.i.Factory.queryPluginContext(Factory.java:184)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.replugin.component.service.server.PluginServiceServer.installServiceLocked(PluginServiceServer.java:384)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.replugin.component.service.server.PluginServiceServer.access$000(PluginServiceServer.java:58)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.replugin.component.service.server.PluginServiceServer$2.call(PluginServiceServer.java:365)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.replugin.component.service.server.PluginServiceServer$2.call(PluginServiceServer.java:362)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.replugin.base.ThreadUtils.syncToMainThread(ThreadUtils.java:50)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.replugin.component.service.server.PluginServiceServer.installServiceIfNeededLocked(PluginServiceServer.java:362)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.replugin.component.service.server.PluginServiceServer.startServiceLocked(PluginServiceServer.java:98)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.replugin.component.service.server.PluginServiceServer$Stub.startService(PluginServiceServer.java:512)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.replugin.component.service.PluginServiceClient.startService(PluginServiceClient.java:106)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.loader2.PluginContext.startService(PluginContext.java:500)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at android.content.ContextWrapper.startService(ContextWrapper.java:494)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.example.kcmds.pluginclient.MyApplication.onCreate(MyApplication.java:22)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.replugin.component.app.PluginApplicationClient.callOnCreate(PluginApplicationClient.java:225)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.loader2.Plugin.callAppLocked(Plugin.java:905)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.loader2.Plugin.callApp(Plugin.java:884)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.loader2.Plugin.load(Plugin.java:435)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.loader2.PmBase.loadPlugin(PmBase.java:1045)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.loader2.PmBase.loadAppPlugin(PmBase.java:1030)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.loader2.PluginCommImpl.queryPluginContext(PluginCommImpl.java:196)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.i.Factory.queryPluginContext(Factory.java:184)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.replugin.component.service.server.PluginServiceServer.installServiceLocked(PluginServiceServer.java:384)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.replugin.component.service.server.PluginServiceServer.access$000(PluginServiceServer.java:58)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.replugin.component.service.server.PluginServiceServer$2.call(PluginServiceServer.java:365)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.replugin.component.service.server.PluginServiceServer$2.call(PluginServiceServer.java:362)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.replugin.base.ThreadUtils.syncToMainThread(ThreadUtils.java:50)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.replugin.component.service.server.PluginServiceServer.installServiceIfNeededLocked(PluginServiceServer.java:362)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.replugin.component.service.server.PluginServiceServer.startServiceLocked(PluginServiceServer.java:98)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.replugin.component.service.server.PluginServiceServer$Stub.startService(PluginServiceServer.java:512)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.replugin.component.service.PluginServiceClient.startService(PluginServiceClient.java:106)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.loader2.PluginContext.startService(PluginContext.java:500)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at android.content.ContextWrapper.startService(ContextWrapper.java:494)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.example.kcmds.pluginclient.MyApplication.onCreate(MyApplication.java:22)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.replugin.component.app.PluginApplicationClient.callOnCreate(PluginApplicationClient.java:225)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.loader2.Plugin.callAppLocked(Plugin.java:905)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.loader2.Plugin.callApp(Plugin.java:884)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.loader2.Plugin.load(Plugin.java:435)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.loader2.PmBase.loadPlugin(PmBase.java:1045)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.loader2.PmBase.loadAppPlugin(PmBase.java:1030)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.loader2.PluginCommImpl.getActivityInfo(PluginCommImpl.java:561)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.loader2.PluginCommImpl.loadPluginActivity(PluginCommImpl.java:411)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.loader2.PluginLibraryInternalProxy.startActivity(PluginLibraryInternalProxy.java:266)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.loader2.PluginCommImpl.startActivity(PluginCommImpl.java:380)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:327)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:238)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.example.kcmds.pluginhost.MainActivity.onClick(MainActivity.java:48)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at android.view.View$1.onClick(View.java:3826)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at android.view.View.performClick(View.java:4446)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at android.view.View$PerformClick.run(View.java:18485)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at android.os.Handler.handleCallback(Handler.java:733)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at android.os.Looper.loop(Looper.java:136)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5290)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:859)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:675)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err:     at dalvik.system.NativeStart.main(Native Method)
07-27 09:31:05.380 9093-9093/com.example.kcmds.pluginhost W/System.err: Caused by: java.lang.IllegalStateException: Base context already set
07-27 09:31:05.400 9093-9093/com.example.kcmds.pluginhost W/System.err:     at android.content.ContextWrapper.attachBaseContext(ContextWrapper.java:69)
07-27 09:31:05.400 9093-9093/com.example.kcmds.pluginhost W/System.err:     at android.app.Application.attach(Application.java:200)
07-27 09:31:05.400 9093-9093/com.example.kcmds.pluginhost W/System.err: 	... 549 more
07-27 09:31:05.400 9093-9093/com.example.kcmds.pluginhost E/PluginClientApplication: onCreate: 0000000000000000000

**RePlugin version**:
从官网下载的最新版本
**Android compile SDK version**:
 compileSdkVersion 26
**Android ROM**:
android 4.4.2

**Comment by byecode** [comment]
目前这个bug我也遇到了。不会检测正在运行的服务。导致循环创建
application->服务。

**Comment by jiongxuan** [comment]
您好，这个问题我也发现了。我正在尝试看看怎么修复（当然，改动量尽可能小，免得对其它的造成影响）。预计在2.1.7的下一版中体现（2.1.7马上就要发了，为防止出现别的情况可能先不解决）。

现阶段您可以先将这块儿临时通过Handler给Post出去，这样就不会有这个问题了。

**Comment by jiongxuan** [comment]
您好，这个问题我刚才已经提交了PR，修复了这个问题。等OK后会合入主干，在217上体现。

@byecode @jiashilei-1985

**Comment by jiashilei-1985** [comment]
好的,thank you!!!

**Comment by jiongxuan** [comment]
问题已在2.1.7上解决。欢迎试用
