### ISSUE TITLE
Proguard rules for host and plugin?

### ISSUE THREAD

**Issue by Zhaoyy** [Qihoo360/RePlugin#266]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:

**Android compile SDK version**:

**Android ROM**:

**Comment by jiongxuan** [comment]
您直接引入AAR即可，自带混淆效果。关于这一点我刚才在WiKi中补充了，希望能帮助到新人
