### ISSUE TITLE
火钳刘明！刚收到消息就过来围观了！

### ISSUE THREAD

**Issue by MoNodin** [Qihoo360/RePlugin#27]
作为一个致力于插件化和热更新工作的Developer，非常支持360的这次开源行动！
拜读源码中……

**Comment by JerryBluesnow** [comment]
me too, 拜读源码中……

**Comment by jiongxuan** [comment]
您好，感谢您的鼓励和支持，您的火钳刘明对我们而言是不小的鼓励啊。

RePlugin已经开源，欢迎阅览，提出指正建议。
