### ISSUE TITLE
请问插件可以复用主程序的资源吗?请简单的说一下怎么复用? 

### ISSUE THREAD

**Issue by zhangchenzhou** [Qihoo360/RePlugin#270]
我看到 #10 已经提问了这个问题但是我想了解具体过程.比如说插件想共用主程序的一张资源图片,这个该如何操作?

**Comment by jiongxuan** [comment]
您好，Sample中有详细的实例，此外FAQ中也有说明。

还有，我们不建议直接共用资源图片，因为图片一旦发生删改则会导致比较严重的问题，可以见FAQ中的说明。
