### ISSUE TITLE
运行 host, 先点击 start plugin demo1, 然后 点击 install external kotlin plugin(from assets) ，再次点击start plugin demo1 进不去了

### ISSUE THREAD

**Issue by yibaimishenlan** [Qihoo360/RePlugin#271]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**: 2.1.6

**Android compile SDK version**: 25

**Android ROM**: Meizu M5 Note

**Android Version**: 6.0

具体是这样的， 我运行host, 先点击 start plugin demo1, 然后 点击 install external Kotlin plugin(from assets) ，再次点击start plugin demo1 进不去了, 稍微打印了下 plugin demo1 中代码：
 
findViewById(R.id.btn_start_demo1).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                // 刻意以“包名”来打开
                boolean isStart = RePlugin.startActivity(MainActivity.this,
                        RePlugin.createIntent("com.qihoo360.replugin.sample.demo1",
                                "com.qihoo360.replugin.sample.demo1.MainActivity"));
                Log.d(TAG, "btn_start_demo1 isStart = " + isStart);
            }
        });

发现 未点击 install external Kotlin plugin(from assets) 该按钮， isStart 返回的都是 true， 而点击过 install external Kotlin plugin(from assets)   按钮之后，isStart 就返回 false 了，求解

**Comment by yibaimishenlan** [comment]
貌似 只要点击了 install external Kotlin plugin from assets 之后， 再次点击 Start plugin demo1 就进不去 demo1 的 MainActivity 了

**Comment by yibaimishenlan** [comment]
补下 log:
08-01 18:46:23.442 13557-13557/com.qihoo360.replugin.sample.host D/RePlugin.ws001: start activity: intent=Intent { cmp=com.qihoo360.replugin.sample.demo1/.MainActivity } plugin=com.qihoo360.replugin.sample.demo1 activity=com.qihoo360.replugin.sample.demo1.MainActivity process=-2147483648
08-01 18:46:23.442 13557-13557/com.qihoo360.replugin.sample.host D/RePlugin.ws001: start activity: intent=Intent { cmp=com.qihoo360.replugin.sample.demo1/.MainActivity } plugin=com.qihoo360.replugin.sample.demo1 activity=com.qihoo360.replugin.sample.demo1.MainActivity process=-2147483648 download=true
08-01 18:46:23.442 13557-13557/com.qihoo360.replugin.sample.host D/RePlugin.loadClass: isHookingClass(com.qihoo360.replugin.sample.demo1 , com.qihoo360.replugin.sample.demo1.MainActivity) = false
08-01 18:46:23.443 13557-13557/com.qihoo360.replugin.sample.host D/RePlugin.ws001: PStatusC.getStatus(): ps is null. pn=com.qihoo360.replugin.sample.demo1
08-01 18:46:23.443 13557-13557/com.qihoo360.replugin.sample.host D/RePlugin.ws001: PStatusC.getStatus(): ps is null. pn=demo3
08-01 18:46:23.443 13557-13557/com.qihoo360.replugin.sample.host I/RePlugin.ws000: loadLocked(): Initialized, is loaded = true
08-01 18:46:23.443 13557-13557/com.qihoo360.replugin.sample.host D/RePlugin.ws001: PAC.create(): Already Loaded.com.qihoo360.replugin.PluginDexClassLoader[DexPathList[[zip file "/data/user/0/com.qihoo360.replugin.sample.host/app_p_a/58116215.jar"],nativeLibraryDirectories=[/data/user/0/com.qihoo360.replugin.sample.host/app_p_n/58116215, /vendor/lib64, /system/lib64]]]
08-01 18:46:23.444 13557-13557/com.qihoo360.replugin.sample.host D/RePlugin.ws001: PACM: bindActivity: activity not found
08-01 18:46:23.444 13557-13557/com.qihoo360.replugin.sample.host D/RePlugin.ws001: plugin cn not found: intent=Intent { cmp=com.qihoo360.replugin.sample.demo1/.MainActivity } plugin=com.qihoo360.replugin.sample.demo1 activity=com.qihoo360.replugin.sample.demo1.MainActivity process=-2147483648

**Comment by jiongxuan** [comment]
您好，这个是我们已知的问题，说白了就是Sample中的Demo3其包名写成了和demo1一样的了。这块儿 @wangyupeng1-iri 兄正在改，预计随今天的2.1.7版本发出。

**Comment by yibaimishenlan** [comment]
哦，thx
