### ISSUE TITLE
你好，app_p_c/-1465713339.dex' does not exist

### ISSUE THREAD

**Issue by wardenlzr** [Qihoo360/RePlugin#274]
在宿主APP里面按照wiki 全部配好了，并且使用demo3也都可以正常打开；自己写的Demo包如下错误：

W/System.err: java.io.FileNotFoundException: Source '/data/user/0/com.tengdi.mobilelaw.android/app_p_c/-1465713339.dex' does not exist
W/System.err:     at com.qihoo360.replugin.utils.FileUtils.checkFileRequirements(FileUtils.java:528)
W/System.err:     at com.qihoo360.replugin.utils.FileUtils.copyFile(FileUtils.java:436)
W/System.err:     at com.qihoo360.replugin.utils.FileUtils.copyFile(FileUtils.java:431)
W/System.err:     at com.qihoo360.replugin.packages.PluginManagerServer.move(PluginManagerServer.java:419)
W/System.err:     at com.qihoo360.replugin.packages.PluginManagerServer.updateNow(PluginManagerServer.java:396)
W/System.err:     at com.qihoo360.replugin.packages.PluginManagerServer.updateOrLater(PluginManagerServer.java:312)
W/System.err:     at com.qihoo360.replugin.packages.PluginManagerServer.installLocked(PluginManagerServer.java:180)
W/System.err:     at com.qihoo360.replugin.packages.PluginManagerServer.access$200(PluginManagerServer.java:60)
W/System.err:     at com.qihoo360.replugin.packages.PluginManagerServer$Stub.install(PluginManagerServer.java:595)
W/System.err:     at com.qihoo360.loader2.PmHostSvc.pluginDownloaded(PmHostSvc.java:327)
W/System.err:     at com.qihoo360.loader2.IPluginHost$Stub.onTransact(IPluginHost.java:281)
W/System.err:     at android.os.Binder.execTransact(Binder.java:404)
W/System.err:     at dalvik.system.NativeStart.run(Native Method)
I/RePlugin.PluginManagerServer: updateNow: Update. pn=1; cur_ver=1; update_ver=1

**Comment by wardenlzr** [comment]
这个问题解决了；插件要打签名包才可以。。。
`private void simulateInstallExternalPlugin(String pluginName) {
        PluginInfo info = RePlugin.getPluginInfo(pluginName);
        if (info == null) {
            String pluginFilePath = ((MainActivity)mContext).getFilesDir().getAbsolutePath() + File.separator + pluginName+".apk";
            File pluginFile = new File(pluginFilePath);
            if (!pluginFile.exists()) {
                copyAssetsFileToAppFiles("external/helloplugin.apk", "helloplugin.apk");
                if (pluginFile.exists()) {
                    info = RePlugin.install(pluginFilePath);
                }
            }
        }

        if (info != null) {
            Intent intent = RePlugin.createIntent(info.getName(), "com.tengdi.mobilelaw.helloplugin.MainActivity");
            RePlugin.startActivity(((MainActivity)mContext), intent);
        } else {
            Toast.makeText(((MainActivity)mContext), "install external plugin failed", Toast.LENGTH_SHORT).show();
        }
    }`

出现install external plugin failed
断点的时候发现PluginInfo info = RePlugin.getPluginInfo(pluginName);这里为null
 if (!pluginFile.exists())   这一行条件为false  也就是pluginFile是存在的

**Comment by jiongxuan** [comment]
好的，谢谢分享。确实必须要加上签名才行，因为RePlugin加载的是APK而非里面的内容。
