### ISSUE TITLE
PluginInfo info = RePlugin.getPluginInfo(pluginName);//第三次为null

### ISSUE THREAD

**Issue by wardenlzr** [Qihoo360/RePlugin#275]
PluginInfo info = RePlugin.getPluginInfo(pluginName);//第三次为null

提示install external plugin failed

**Comment by jiongxuan** [comment]
您好，请提供完整的Logcat信息，方便我们定位问题。谢谢

**Comment by jiongxuan** [comment]
您好，大概知道您说的意思了。我已修复了这个问题（ #285 ），预计在2.2.0上体现。

**Comment by wardenlzr** [comment]
好的，非常感谢
