### ISSUE TITLE
插件共享资源支持？

### ISSUE THREAD

**Issue by whuthj** [Qihoo360/RePlugin#278]
您好：目前这个插件化框架是否支持插件在layout文件中“provided”的方式使用共享资源（就是资源不会编译到本插件Apk中，而是运行的时候去共享库中获取），这样就避免了重复资源，极大减少了体积

**Comment by T-BayMax** [comment]
请查看FAQ

**Comment by jiongxuan** [comment]
Sample中正好有实例，关于Layout的，您可以看下
