### ISSUE TITLE
瑟瑟发抖的小菜鸡前来围观，支持支持！

### ISSUE THREAD

**Issue by and-oneone** [Qihoo360/RePlugin#28]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:

**Android compile SDK version**:

**Android ROM**:

**Comment by jiongxuan** [comment]
非常感谢您的给力支持哈！RePlugin已经开源，欢迎阅览。
