### ISSUE TITLE
对于安装的过程好懵逼啊

### ISSUE THREAD

**Issue by VipMinF** [Qihoo360/RePlugin#282]
即使看了wiki也懵逼
版本2.1.7
好像Install 并不是真的Install，对于install   fetchContext 那个是耗时的操作，需要在线程执行
我现在的逻辑好像有问题，加载插件完全看心情 ，我现在的逻辑是 进入程序 不会加载程序，然后我获取p.l文件的版本号像服务器询问是否有新版本，如果有调用 RePlugin.install(path)  然后等待RePluginEventCallbacks.onInstallPluginSucceed, 真的回调真的看心情，时有时无。回调后我 使用RePlugin.fetchContext() 获取Context。因为我的插件不是四大组件 ，只是一个ViewGroup。所以需要插件的上下文，然后 我发现 RePlugin.fetchContext() 不是每次都能获取成功，偶尔为null，当在 存在旧版本，插件未启动 情况下 升级插件( RePlugin.install(path) )，这个时候RePlugin.fetchContext()   100%   为null。这样子好郁闷。本来不升级 还没获取成功 升级就获取不成功 需要重启app （但是插件还没有启动，不需要重启才对），好像还报了一个错
 PStatusC.getStatus(): ps is null. pn=gamePlugin
I/RePlugin.ws001: java.lang.Thread.getStackTrace(Thread.java:580)
I/RePlugin.ws001: com.qihoo360.loader2.Plugin.loadLocked(Plugin.java:572)
I/RePlugin.ws001: com.qihoo360.loader2.Plugin.load(Plugin.java:431)
I/RePlugin.ws001: com.qihoo360.loader2.PmBase.loadPlugin(PmBase.java:1045)
I/RePlugin.ws001: com.qihoo360.loader2.PmBase.loadAppPlugin(PmBase.java:1030)
I/RePlugin.ws001: com.qihoo360.loader2.PluginCommImpl.queryPluginContext(PluginCommImpl.java:196) I/RePlugin.ws001: com.qihoo360.i.Factory.queryPluginContext(Factory.java:184)
I/RePlugin.ws001: com.qihoo360.replugin.RePlugin.fetchContext(RePlugin.java:421)

RePlugin.fetchContext 获取不成功会有哪些情况？
拜托大神们解答下， 我看了两三天无果

**Comment by jiongxuan** [comment]
你好，还请把问题分拆成，以项目符号的方式来写一下。我感觉直接这么看有些不知所措。
而且还请注意：
1. “回调看心情”这个肯定不是这样的。我觉得你还是得单步跟一下这块儿的逻辑，看看是不是安装失败，或者已经安装过才会出现这种情况。**建议在叙述问题时，能提供单步调试后的结果，而非笼统的描述**，以更方便的定位问题
2. “fetchContext不是每次都成功”，请说下哪几次是成功，哪几次是不成功，其中不成功的条件是什么。因为这套方案大家都在用，目前还没遇到过类似反馈。所以想了解下相对极端的情况，而且还要具体问题具体分析。
3. 那个栈信息不是报错，只是提示哪个地方开始加载了插件，方便定位问题
4. RePlugin是完全开源的，毫无保留。而我们大家的精力也有限，无法一一定位所有问题。建议遇到情况时做下单步，在**找到现象**和定位到出错代码后，再商量如何解决，这样效率更高。

**Comment by VipMinF** [comment]
谢谢你的回答，现在我已经解决，虽然还不知道对不对，也许是我理解上的问题。
1.我没有统计过没有回调这个有几次没有出现，步骤是这样的， 我升级后，重启后。没有回调，再重启，还
  是没有回调，再重启，就有了。后来我发现，仅仅是调用Install是好像是不会有这个回答，所以我现在重新
  写了逻辑，这种情况几乎没有出现了。
2.“fetchContext不是每次都成功”，这个原因，我找到了，是因为我升级了。接着调用fetchContext 就不行
  了。一开始我是这样认为的，我先是不加载插件，然后升级（调用Install），接着去获取fetchContext ，即
  使不能热更新，还是能拿到上一个版本的fetchContext。但这个想法是错的，所以我重新写了逻辑，程序进
  来的第一步就是去fetchContext ，结束后，我才去检查更新。
3.目前发现一个问题，app安装变慢了。我开启了打印日志。发现app在安装的过程中，一直在打印日志，在
   统计耗时，好像在处理什么。

**Comment by jiongxuan** [comment]
好的，我先验证下你说的几个问题。如果确定存在的话会尝试去修复。

当然，你提到了“重新写了逻辑”，这些逻辑是修改了host-lib了吗？如果是，欢迎提PR给我们~

**Comment by VipMinF** [comment]
重新写了逻辑，只是修改了我的程序的逻辑。也许是因为我一开始的理解就是错的，所以才会出现这些问题。在wiki上也没有提到如install 只是解压 fetchContext是安装，所以存在一些误以为。虽然不知道现在是否理解正确，但插件的使用已经趋向稳定。现在由于要快速开发，所以没有太多时间去看源码，之后我会去吃透这些，谢谢你的帮助。
