### ISSUE TITLE
 插件使用provided方式调用宿主方法传入当前activity报null

### ISSUE THREAD

**Issue by T-BayMax** [Qihoo360/RePlugin#283]
插件使用provided方式调用宿主方法传入当前activity报null，改成compile单独运行是正常的；当调用到宿主方法时使用到activity才报错

**RePlugin version**:2.1.7

**Android compile SDK version**:25.0.3

**Android ROM**:7.0

**Comment by jiongxuan** [comment]
这个有些笼统，能发下Logcat日志吗？

**Comment by T-BayMax** [comment]
是调用的插件有问题，已联系作者修复了

**Comment by jiongxuan** [comment]
好的，谢谢
