### ISSUE TITLE
插件接入Facebook SDK出现强转错误而导致崩溃

### ISSUE THREAD

**Issue by yeleaveszi** [Qihoo360/RePlugin#291]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:
2.1.7
**Android compile SDK version**:
7.0
**Android ROM**:
EMUI

在插件里集成Facebook的登录SDK，调用到登录时会出现强转失败导致崩溃，错误信息为：
 java.lang.ClassCastException: android.support.v4.content.LocalBroadcastManager cannot be cast to com.qihoo360.replugin.loader.b.PluginLocalBroadcastManager at com.qihoo360.replugin.loader.b.PluginLocalBroadcastManager.registerReceiver(Unknown Source) at com.facebook.AccessTokenTracker.addBroadcastReceiver(AccessTokenTracker.java:116) at com.facebook.AccessTokenTracker.startTracking(AccessTokenTracker.java:72)
at com.facebook.AccessTokenTracker.<init>(AccessTokenTracker.java:61)

错误发生在在AccessTokenTracker类中的addBroadcastReceiver方法

Facebook SDK中的addBroadcastReceiver为：

```
   private void addBroadcastReceiver() {
        IntentFilter filter = new IntentFilter();
        filter.addAction(AccessTokenManager.ACTION_CURRENT_ACCESS_TOKEN_CHANGED);
        broadcastManager.registerReceiver(receiver, filter);
    }
```

通过Gradle插件修改过后的addBroadcastReceiver方法为：
```
private void addBroadcastReceiver()  {
      IntentFilter localIntentFilter = new IntentFilter();
      localIntentFilter.addAction("com.facebook.sdk.ACTION_CURRENT_ACCESS_TOKEN_CHANGED");
      PluginLocalBroadcastManager.registerReceiver(this.broadcastManager, this.receiver, localIntentFilter);
   }
```

错误出现在：
```
public static void registerReceiver(Object paramObject, BroadcastReceiver paramBroadcastReceiver, IntentFilter paramIntentFilter)
  {
    ((PluginLocalBroadcastManager)paramObject).registerReceiver(paramBroadcastReceiver, paramIntentFilter);`
  }
```
  

PluginLocalBroadcastManager中的静态方法registerReceiver会把第一个参数broadcastManager强转为PluginLocalBroadcastManager。broadcastManager的类为LocalBroadcastManager，而PluginLocalBroadcastManager没有继承LocalBroadcastManager，导致强制类型转换错误。
请问这个问题如何解决？
谢谢。

**Comment by zhangkangbin** [comment]
你把broadcastManager 修改成  LocalBroadcastManager.getInstance(context）..

**Comment by yeleaveszi** [comment]
public AccessTokenTracker() {
        Validate.sdkInitialized();
        this.receiver = new CurrentAccessTokenBroadcastReceiver();
        this.broadcastManager = LocalBroadcastManager.getInstance(
                FacebookSdk.getApplicationContext());
        startTracking();
    }
这是Facebook SDK的构造函数，这个类中的broadcastManager 本来就是通过LocalBroadcastManager的单例方法获得的。另外，这是Facebook官方提供的SDK，尽量不去修改。 @zhangkangbin

**Comment by yeleaveszi** [comment]
参考#259，Replugin不会替换方法以外的变量。
