### ISSUE TITLE
是否支持混淆

### ISSUE THREAD

**Issue by VipMinF** [Qihoo360/RePlugin#295]
比如 A时刻发布了宿主v1 和 插件X（provider宿主【混淆后的jar】） 过了许久 发布宿主v2  会不会有问题？？？

**Comment by jiongxuan** [comment]
您好。如果有问题的话，卫士和助手都玩不转了 :-)。

但是，务必要确保你调用的，以Provided形式的Jar是被Keep住的，这个我想也是共识。
