### ISSUE TITLE
打开RePlugin类时提示library source does not match the bytecode for class RePlugin

### ISSUE THREAD

**Issue by arshcaria** [Qihoo360/RePlugin#297]
**RePlugin version**: 2.1.7
 
**Android compile SDK version**: 25 and any others

**Android ROM**: all

Android Studio打开sample host工程，在其中任何一处使用到`RePlugin`类的位置跳转到`RePlugin`，Android会提示库的源码与库的字节码不匹配。

**Comment by arshcaria** [comment]
这样debug的时候打断点会有困扰。
我的workaround就是把`RePlugin/replugin-host-library/replugin-host-lib`作为module引入到宿主project。
这样无论debug还是修改RePlugin源码并查看效果，都会更方便。

**Comment by arshcaria** [comment]
引入module的时候，还要修改下宿主project的gradle，
```
buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.1'
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.6' // 添加这两行
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.4.1'  // 添加这两行
    }
}
```

**Comment by jiongxuan** [comment]
这个应该不需要吧。我们自己在Sample中试了下是没问题的。它会自动从网上下replugin-host-lib-2.1.7-sources.jar，这样就可以看到源码了。

**Comment by arshcaria** [comment]
Not necessary indeed. 
问题是我这边从网上repo下载下来的sources.jar和aar不匹配。sources看上去也是正常的，有注释。但是AS一直提示和字节码不匹配。我也纳闷，不知道是什么原因。

**Comment by jiongxuan** [comment]
建议把您用户目录下的.gradle（或者叫gradle）和.m2（或者叫m2）清除掉再试。

举例：
Win：C:\Users\zhangjiongxuan\.gradle
Mac/Linux：/home/zhangjiongxuan/.gradle

**Comment by arshcaria** [comment]
谢谢回复。清除gradle repo缓存后就ok了。
