### ISSUE TITLE
Android 4.4手机不能通过intent传Serializable对象

### ISSUE THREAD

**Issue by holysun0811** [Qihoo360/RePlugin#299]
在Android 4.4手机上通过intent传Serializable对象，拿到的是null
传Parcelable对象没问题

**Comment by wangfuda** [comment]
@holysun0811 是序列号id问题，加上public static final long serialVersionUID = xxxx；应该就可以用了。如果使用eclipse，做序列化会提示加这个变量。另外建议使用android为android优化的Parcelable序列化方式。

**Comment by jerryliuinfo** [comment]
为啥我加了public static final long serialVersionUID 还是获取不到啊 ？

**Comment by linchangjian** [comment]
Serializable 在4.4上是有问题的，5.0以上没有问题，原因就是Parcel有改动，建议使用Parcelable
