### ISSUE TITLE
相互通信问题

### ISSUE THREAD

**Issue by liaction** [Qihoo360/RePlugin#30]
宿主和插件之间，插件和宿主之间，插件和插件之间，这些方面的通信有什么限制吗？（毕竟单纯的插件还是很少的，双方甚至多方之间进行通信是免不了的，由于业务需要，单纯的提取出一个插件也看似不怎么现实，现在比较关心的还是相互通信方面。）

**Comment by appledong** [comment]
顶，楼主解决了，有比较好的方案么？双方通信通过广播不是太好

**Comment by fengbenpaao** [comment]
AIDL试试，或者用反射；
