### ISSUE TITLE
插件activity的设为横屏，宿主启动该activity时，却是竖屏

### ISSUE THREAD

**Issue by BaoJiajing** [Qihoo360/RePlugin#303]
首先，在插件中注册一个横屏activity
 <activity
            android:name="xxxActivity"
            android:launchMode="singleTop"
            android:screenOrientation="landscape"
            android:configChanges="keyboardHidden|orientation|screenSize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

然后，单独以应用形式安装运行该插件，确实是横屏；

最后，利用宿主安装该插件，并启动该activity，却变成了竖屏。插件中注册的android:screenOrientation没用吗？
注：插件中actvitivity对应坑位：RePlugin.ws001: activity create: name=YCHZ activity=com.acmedcare.im.p_consulation.consulationlist.ConsulationListActivity process=-2147483648 container=com.acmedcare.im.pad.loader.a.ActivityN1STPTS0 counter=0

**Comment by ab6326795** [comment]
这种情况估计是replugin 有bug， 可以先尝试代码中设置横竖屏，而非xml而中定义。 replugin的实现也应该是读取这个配置然后代码中做横竖屏切换的。

**Comment by cundong** [comment]
@ab6326795 @BaoJiajing 这个不是BUG，是为了让宿主尽量简单而故意这样设计的。

请参考：
https://github.com/Qihoo360/RePlugin/issues/342
