### ISSUE TITLE
请问下你们这个插件化方案能不能加载其他第三方的app如QQ等

### ISSUE THREAD

**Issue by langwan1314** [Qihoo360/RePlugin#305]
#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by closedevice** [comment]
如果你想这么做的话,更适合使用dp或者virtualApp,而非RePlugin
