### ISSUE TITLE
关于Replugin功能方面问题

### ISSUE THREAD

**Issue by ShengJunHu** [Qihoo360/RePlugin#315]
1、使用RePlugin升级应用时，可采用apk版本打补丁的方式升级吗
2、支持静默安装吗，我记得DroidPlugin是可以的。

**Comment by ShengJunHu** [comment]
RePlugin是否支持安装、更新、卸载插件
有没有关于应用升级这方面的文档说明

**Comment by cundong** [comment]
你问的两个问题都和 RePlugin 没什么关系，这两件事和插件化本身也没关系。
