### ISSUE TITLE
判断当前应用是否是在插件状态下运行

### ISSUE THREAD

**Issue by arshcaria** [Qihoo360/RePlugin#316]
比如某一个插件APK，怎么在运行时判断自己是独立应用还是处于插件状态？

现在用的是`RePlugin.isHostInitialized()`，返回`true`说明是在插件状态，反之是独立应用。

不知道这个方法是否在各种情景下都是准确的？有没有更好的方法？

**Comment by closedevice** [comment]
可以通过获取宿主Classloader,为null的是作为单品运行,否则是为插件

**Comment by cundong** [comment]
最简单的办法，是通过获取当前 packageName 来获取，插件状态，返回的是宿主的 packageName
