### ISSUE TITLE
启动内置插件时报错

### ISSUE THREAD

**Issue by WeJoy** [Qihoo360/RePlugin#317]
Intent intent = RePlugin.createIntent("plugin1", "<宿主包名>.MainActivity");

然后报错：

08-25 16:57:57.275 10316-10316/<宿主包名> E/InstantRun: Failed to create directory /data/data/<插件包名>/files/instant-run/dex

疑问：

宿主包代码怎么会去操作 插件包名的/data/data。。。。这个怎么处理？

**Comment by fanrenyi** [comment]
你看下是不是SD卡权限没加
