### ISSUE TITLE
自定义进程名匹配问题

### ISSUE THREAD

**Issue by leojiang** [Qihoo360/RePlugin#319]
代码版本2.1.7

我在读代码的时候，在Loader.adjustPluginProcess中有看到这样一段逻辑
if (to.contains("$" + PluginProcessHost.PROCESS_PLUGIN_SUFFIX)) {
       to = PluginProcessHost.PROCESS_ADJUST_MAP.get(to);
}
这里PluginProcessHost.PROCESS_PLUGIN_SUFFIX 的值就是  p
 但是实际上常驻进程名用户是可以自己指定的， 如果用户不小心指定了一个以小些字母 p 开头的进程名， 就会出问题啦～

**Comment by cundong** [comment]
@leojiang 您再看下代码哈。

这个是： **to**.contains("$" + PluginProcessHost.PROCESS_PLUGIN_SUFFIX)

to，是谁呢？是用户自定义的进程映射表(原先进程名字->to)，并不是自己真正的进程名字。
