### ISSUE TITLE
android 8.0运行不了“大”插件。

### ISSUE THREAD

**Issue by fanrenyi** [Qihoo360/RePlugin#321]
#### 复现问题步骤 Steps to reproduce the problem
1. 将插件配置成大插件。
2. 运行插件的activity。

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.0
rePlugin-plugin-lib/gradle Version:2.2.0

Android API Version：8.0
Android 手机型号&ROM(Phone model & ROM): 任何手机

**Comment by jiongxuan** [comment]
您好，请提供具体的Logcat信息，方便定位

**Comment by fanrenyi** [comment]
这个不是崩溃，具体原因已经调研出来了。原因是android 8.0 执行代码
mClassLoader = RePlugin.getConfig().getCallbacks().createPluginClassLoader(mPluginObj.mInfo, mPath, out, soDir, parent);

不会再out目录下面生成.dex文件。

**Comment by dreamDemo** [comment]
碰到了相同的 问题希望可以早点解决~

**Comment by wangzhengyi** [comment]
我们项目也遇到同样的问题了，麻烦作者修复一下，跪求。

**Comment by hqwang** [comment]
感谢，看到了之后，刷了一下8.0，果然是有这个问题。。

**Comment by lichuan0217** [comment]
同样有问题～跪求解决方案～～

**Comment by jiongxuan** [comment]
好的，这个问题我们会着重关注下

**Comment by closedevice** [comment]
不出意外,是selinux的权限问题导致.

**Comment by closedevice** [comment]
不出意外,应该是selinux权限导致.

**Comment by a1018875550** [comment]
VirtualAPK新版本已经支持大插件了，可以参考下

**Comment by gordonpro** [comment]
@a1018875550 弱弱问下，什么是大插件

**Comment by cundong** [comment]
v2.2.1 已经适配Android O
https://github.com/Qihoo360/RePlugin/releases/tag/v2.2.1

谢谢各位了。
