### ISSUE TITLE
不支持布局文件中写点击方法

### ISSUE THREAD

**Issue by xushihai** [Qihoo360/RePlugin#326]
#### 问题详细描述 Detailed description of the problem
在activity的布局文件中，给一个按钮添加onClick属性，并在activity中实现该方法。在使用这个插件的时候报出could not find a method in the activity class
#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.1.6 
rePlugin-plugin-lib/gradle Version: 2.1.6

Android API Version：android 5,android6.0
Android 手机型号&ROM(Phone model & ROM): 华为mate8 mate9 海信等

**Comment by cundong** [comment]
你写错了。

我们的插件-demo1中就有这种例子，请参考。
https://github.com/Qihoo360/RePlugin/blob/dev/replugin-sample/plugin/plugin-demo1/app/src/main/res/layout/simple.xml
