### ISSUE TITLE
外置插件编译出来为什么会有1.6MB这么大

### ISSUE THREAD

**Issue by woolly-headed** [Qihoo360/RePlugin#328]
我就是简单的一个Activity，可编译出来的插件都有1.6M。这个不知道能不能精简一下，或者将一些RePlugin的组件提前放在Host中呢。
毕竟插件更新的话，小一点速度也快一些

**Comment by jonyChina162** [comment]
因为你自己 compile 了 support 库吧，你可以试试 provided support 库，然后依赖主工程的 support 库这样应该就 ok 的

**Comment by lizhanzhishang** [comment]
是滴，可以用provided 试试，骗过编译器。

**Comment by cundong** [comment]
感谢 @jonyChina162 的回答，@woolly-headed 你可以反编译一下你你刚刚编译出来的APK，肯定是compile 了一堆库在里面。

**Comment by woolly-headed** [comment]
是的，我看了就是很多库，多谢
