### ISSUE TITLE
共享宿主资源

### ISSUE THREAD

**Issue by Aimn** [Qihoo360/RePlugin#329]
#### 问题详细描述 Detailed description of the problem
求问，插件中需要引用宿主资源，比如宿主资源中有个static字段为hostUrl，插件中访问的为hostUrl+api，这样的逻辑如何实现？不然每次都需要重新单独打包插件，不能多系统使用同一个插件。

**Comment by Aimn** [comment]
实现思路考虑xml或者contentprovider，但是感觉有点绕，不知道是否有什么更好的方法？

**Comment by lizhanzhishang** [comment]
demo1  有相关示例  
`    compile 'com.qihoo360.replugin:replugin-plugin-lib:2.2.0'
    provided files('libs/fragment.jar')//这个jar就是从Support-fragment中提取出来的并非特制包目的是为了骗过编译期
    provided files('libs/common-utils-lib-1.0.0.jar')//这个jar就是从Host的utils中编译生成的，其目的是为了骗过编译期
    compile(name: 'plugin-library', ext: 'aar')//sample:compile aar`
