### ISSUE TITLE
东莞小菜鸡来踩一下

### ISSUE THREAD

**Issue by moziqi** [Qihoo360/RePlugin#33]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:

**Android compile SDK version**:

**Android ROM**:

**Comment by jiongxuan** [comment]
您好，感谢您的鼓励和支持。RePlugin已经开源，欢迎阅览，提出指正建议。

**Comment by moziqi** [comment]
膜拜大神
