### ISSUE TITLE
关于Issue #87的深入提问

### ISSUE THREAD

**Issue by Aimn** [Qihoo360/RePlugin#334]
#### 问题详细描述 Detailed description of the problem
首先感谢lizhanzhishang昨天的热心回答，本来想测试一下，资源共享，可昨天一下午就在研究Issue #87 的问题，首先，我application放到了包的根目录下面，然后配置文件如下
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion '25.0.0'
    defaultConfig {
        applicationId "net.xxxx.aoc"
        minSdkVersion 21
        targetSdkVersion 25
        versionCode 20005
        versionName "2.0.5"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    useLibrary 'org.apache.http.legacy'
}
apply plugin: 'replugin-host-gradle'

repluginHostConfig {
    useAppCompat = true
}
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.alibaba:fastjson:1.1.34.android'
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:support-v4:25.3.1'
    compile 'com.android.support:design:25.3.1'
    compile 'org.apache.httpcomponents:httpcore:4.3.2'
    compile project(':PullToRefresh_Library')
    compile project(':SlidingMenu_Library')
    compile project(':ViewPagerIndicator_Library')
    compile project(':androidpicker_library')
    compile files('libs/jg_filter_sdk_1.1.jar')
    compile files('libs/wup-1.0.0.E-SNAPSHOT.jar')
    compile files('libs/Xg_sdk_v3.0_20170301_1733.jar')
    compile files('libs/jg_filter_sdk_1.1.jar')
    compile files('libs/mid-core-sdk-3.7.2.jar')
    compile files('libs/wup-1.0.0.E-SNAPSHOT.jar')
    compile files('libs/wheelview_1.3.3.jar')
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.prolificinteractive:material-calendarview:1.4.2'
    compile 'com.qihoo360.replugin:replugin-host-lib:2.2.0'

}
但是执行到 cursor = context.getContentResolver().query(uri, PROJECTION_MAIN, selection, null, null);
cursor还是没有查出东西来，考虑不知道哪里出错正在排查中，uri为content://net.xxxxx.aoc.loader.p.main/main

不知道是否是因为其它library或者引入包造成的，慢慢排查一下

**Comment by Aimn** [comment]
主要考虑因素是是因为昨天新建项目测试，这个地方可以查到，但是移入到已有项目里面，就开始找不到了

**Comment by Aimn** [comment]
你们对包名有特殊校验？包名末尾为aoc，查询不到，包名为testrepugin就可以查得到，包名前面都是一致的

**Comment by Aimn** [comment]
经多机子测试，真的和包名有关，测试了华为5台不同设备，小米5台不同设备，2台oppo，末尾为aoc的cursor = context.getContentResolver().query(uri, PROJECTION_MAIN, selection, null, null);cursor永远为null，其它的名字的没有任何问题，求大神解答

**Comment by Aimn** [comment]
貌似和aoc又没有关联了，这个问题让我好纠结。。。

**Comment by cundong** [comment]
问题详见：https://github.com/Qihoo360/RePlugin/issues/338
