### ISSUE TITLE
宿主工程里的类继承插件工程里的类

### ISSUE THREAD

**Issue by faip520** [Qihoo360/RePlugin#336]
#### 问题详细描述 Detailed description of the problem
把某个插件编译成jar包，provided给宿主。宿主里的某个类A继承了插件里的某个类B
这种情况下即使插件已经被加载，还是会报无法找到类A的父类B

#### 复现问题步骤 Steps to reproduce the problem
1. 把某个插件编译成jar包，provided给宿主
2. 宿主里的某个类A继承了插件里的某个类B

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.1.7
rePlugin-plugin-lib/gradle Version:2.1.7

Android API Version：4.2.2
Android 手机型号&ROM(Phone model & ROM): 锤子T1

#### Logcat上下文 Logcat context
Unable to resolve superclass of A；
Link of class 'A' failed

**Comment by cundong** [comment]
replugin中采用平行ClassLoader方案，插件与插件之间是兄弟关系，插件与宿主也是兄弟关系。

你这样做：

> 把某个插件编译成jar包，provided给宿主，宿主中类A继承插件中的类B。

最终，你相当于强行用A的ClassLoder去加载B中的类，肯定是不行的。

我们是提供了插件和插件，插件和宿主之间的通信方式的，可以参考我们的WiKi的demo
