### ISSUE TITLE
Android 4.4手机不能通过intent传Serializable对象

### ISSUE THREAD

**Issue by gokuo** [Qihoo360/RePlugin#337]
#### 复现问题步骤 Steps to reproduce the problem
1. 在Android 4.4手机上通过intent传Serializable对象，拿到的是null
传Parcelable对象没问题，已经加上了public static final long serialVersionUID = xxxx，但还是不行 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.0
rePlugin-plugin-lib/gradle Version:2.2.0

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by cundong** [comment]
https://github.com/Qihoo360/RePlugin/issues/415
