### ISSUE TITLE
神奇的bug，RePlugin和ACRA冲突

### ISSUE THREAD

**Issue by Aimn** [Qihoo360/RePlugin#338]
#### 问题详细描述 Detailed description of the problem
先简单介绍一下ACRA，android崩溃日志收集组件
github：https://github.com/ACRA/acra
之前提的问题Iusse #334 
经过不断的测试，终于发现是因为RePlugin和ACRA冲突了，至于为什么冲突不得而知
报的错误java.lang.StackOverflowError: stack size 8MB
但是又个疑问，RePlugin.App.attachBaseContext(this);是在ACRA.init(this,config)之前执行的，按照常理来说并不影响Repluagin的注册，但是Replugin就一直在报cursor为null，cursor = context.getContentResolver().query(uri, PROJECTION_MAIN, selection, null, null)，Failed to find provider info for 。
希望能解决这些冲突，希望replugin能兼容

**Comment by Aimn** [comment]
貌似问题在于，如果在   @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);

    }
里面写入其它初始化都不行，比如initImageLoader(base);
 public static void initImageLoader(Context context) {
        // This configuration tuning is custom. You can tune every option, you may tune some of them,
        // or you can create default configuration by
        //  ImageLoaderConfiguration.createDefault(this);
        // method.
        ImageLoaderConfiguration config = new ImageLoaderConfiguration.Builder(context)
                .imageDownloader(new HeadImageDownloader(context))
                .threadPriority(Thread.NORM_PRIORITY - 2)
                .denyCacheImageMultipleSizesInMemory()
                .discCacheFileNameGenerator(new Md5FileNameGenerator())
                .tasksProcessingOrder(QueueProcessingType.LIFO)
                .writeDebugLogs() // Remove for release app
                .build();
        // Initialize ImageLoader with configuration.
        ImageLoader.getInstance().init(config);
    }
然后cursor就会报错，求解释

**Comment by cundong** [comment]
你的Application中是这样写的：

    @Override
    public void registerActivityLifecycleCallbacks(ActivityLifecycleCallbacks callback) {
        this.registerActivityLifecycleCallbacks(callback);
    }

你在初始化ACRA的时候，调用了：

ACRA.init(this, config);

这里，最终会调用到ACRA源码中：

org.acra.ErrorReporter:
final LastActivityManager lastActivityManager = new LastActivityManager(this.context);

这里面干了什么呢？
这里调用了application的：

application.registerActivityLifecycleCallbacks(new Application.ActivityLifecycleCallbacks() {
所以就会自己调自己，一直调用到堆栈溢出。

修改方式：
@Override
    public void registerActivityLifecycleCallbacks(ActivityLifecycleCallbacks callback) {
        super.registerActivityLifecycleCallbacks(callback);
 }
