### ISSUE TITLE
attachBaseContext里初始化其它组件报错，cursor为null，

### ISSUE THREAD

**Issue by Aimn** [Qihoo360/RePlugin#340]
#### 问题详细描述 Detailed description of the problem
经过两天的探索和研究，之前两个问题 #338 和 #334  定位都不是很准确，加上官方群里朋友们的讨论，现在准确定位在attachBaseContext初始化任何其它组件，RP就会报错，具体报错地方在PluginProviderStub.class里的proxyFetchHostBinder方法内，cursor = context.getContentResolver().query(uri, PROJECTION_MAIN, selection, null, null);执行查询为null，Failed to find provider info for com.ss.android.auto.loader.p.main

#### 复现问题步骤 Steps to reproduce the problem
1. 写一个初始化imageloder的方法，不要问为啥初始化imageloader要在attachBaseContext里面，我只是举个简单的例子，很多组件都需要在attachBaseContext里面初始化，所以我好奇的是为啥其它组件不能和RP一起在attachBaseContext里面初始化
   public static void initImageLoader(Context context) {
        // This configuration tuning is custom. You can tune every option, you may tune some of them,
        // or you can create default configuration by
        //  ImageLoaderConfiguration.createDefault(this);
        // method.
        ImageLoaderConfiguration config = new ImageLoaderConfiguration.Builder(context)
                .imageDownloader(new HeadImageDownloader(context))
                .threadPriority(Thread.NORM_PRIORITY - 2)
                .denyCacheImageMultipleSizesInMemory()
                .discCacheFileNameGenerator(new Md5FileNameGenerator())
                .tasksProcessingOrder(QueueProcessingType.LIFO)
                .writeDebugLogs() // Remove for release app
                .build();
        // Initialize ImageLoader with configuration.
        ImageLoader.getInstance().init(config);
    }
2. 在attachBaseContext初始化imageloader，两种Appliaction都测试过
   2.1、继承RePluginApplication
 @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        initImageLoader(base);
    }
2.2、不继承RePluginApplication
   @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        RePlugin.App.attachBaseContext(this);
        initImageLoader(base);
    }
3、执行到cursor = context.getContentResolver().query(uri, PROJECTION_MAIN, selection, null, null)，cursor都会为null

**Comment by cundong** [comment]
@Aimn 你可以加 QQ：251306994

**Comment by cundong** [comment]
1. 该问题和replugin无关，是 @Aimn  自己写的业务代码有错导致的。
2.imageLoader不能在attachBaseContext中初始化，详细原因见imageLoader源码；

**Comment by Aimn** [comment]
谢谢大神回复了
