### ISSUE TITLE
插件编译偶现的问题repluginPluginConfig 配置

### ISSUE THREAD

**Issue by RunningShu** [Qihoo360/RePlugin#341]
#### 问题详细描述 Detailed description of the problem
此问题比较奇怪，插件编译几次后（成功），会出现如下问题（出现该问题后，一直是这样），但是我重启as后，未经更改又可以正常编译了。插件配置按照文档来的

我的配置：
apply plugin: 'replugin-plugin-gradle'
repluginPluginConfig {
//插件名
    pluginName = "home"
//宿主app的包名
    hostApplicationId = "com.tianque.ecommunity"
//宿主app的启动activity
    hostAppLauncherActivity = "com.tianque.ecommunity.common.view.module.enter.WelcomeActivity"
}

错误提示：
Add repluginPluginConfig to your build.gradle to enable this plugin:

repluginPluginConfig {
    // Name of 'App Module'，use '' if root dir is 'App Module'. ':app' as default.
    appModule = ':app'

    // Injectors ignored
    // LoaderActivityInjector: Replace Activity to LoaderActivity
    // ProviderInjector: Inject provider method call.
    ignoredInjectors = ['LoaderActivityInjector']
}

>>> rootLocation: E:\pingantong_replugin\plugins\plugin_home\build\intermediates\transforms\___ReClass___\zhejiang\debug
>>> variantDir: zhejiang\debug
----------------------------------------------------------------------------------------------------
>>> Unzip Jar ...
:plugins:plugin_home:transformClassesWith___ReClass___ForZhejiangDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':plugins:plugin_home:transformClassesWith___ReClass___ForZhejiangDebug'.
> java.lang.ClassCastException: org.apache.xerces.parsers.XIncludeAwareParserConfiguration cannot be cast to org.apache.xerces.xni.parser.XMLParserConfiguration

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

**Comment by cundong** [comment]
这个 log 确实是看不出问题所在来。
