### ISSUE TITLE
插件横竖屏问题

### ISSUE THREAD

**Issue by aa65431362** [Qihoo360/RePlugin#342]
#### 问题详细描述 Detailed description of the problem
插件中页面设置为横屏显示，单独安装插件，页面正确显示（横屏）。
将插件放入主程序的external中，用主程序打开该插件，结果页面竖屏显示。

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 
三星T805C

**Comment by cundong** [comment]
我们目前宿主中的坑位，默认都是竖屏的，暂时没有支持横屏坑位。

可以参考：
https://github.com/Qihoo360/RePlugin/blob/dev/replugin-host-gradle/src/main/groovy/com/qihoo360/replugin/gradle/host/handlemanifest/ComponentsGenerator.groovy

如果您想支持横屏，可以用代码实现：

> if (getRequestedOrientation() != ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE) {
            setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
  }

**Comment by fangengbiao** [comment]
有人遇到过，这样设置横屏之后，插件的Activity还是先竖屏 后 横屏么？

**Comment by xiaojie-2016** [comment]
你怕是没有试过sensor landscape，方向不对的话先竖屏再横屏再180度转，心塞。。。我手上的俩机器有先竖屏的有直接横屏的，我也很绝望啊

**Comment by wwdn** [comment]
@xiaojie-2016  我也碰到这种情况，先竖屏在横屏，这样导致从插件返回的时候，页面被重新的打开了，生命周期都不对了

**Comment by fishyuyu** [comment]
我也遇到了这个问题，不能加一个横屏的坑为么？@cundong

**Comment by zhUpUp** [comment]
@wwdn 横竖屏问题你们咋解决的？

**Comment by wwdn** [comment]
不好意思啊！好久了，也没用插件了，我也不知道当时解决没有解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Qihoo360/RePlugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月28日(星期四) 下午2:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Qihoo360/RePlugin] 插件横竖屏问题 (#342)





 
@wwdn 横竖屏问题你们咋解决的？
