### ISSUE TITLE
插件调用宿主中的资源

### ISSUE THREAD

**Issue by LiuYeAlex** [Qihoo360/RePlugin#347]
我查看文档后应该是支持反射形式获取的，以下是代码
宿主中配置了资源<string name="str_test">hello i\'m here!!!!!!</string>
插件中代码
private int getHostResId(String resName) {
        Resources res = RePlugin.getHostContext().getResources();
        String[] strs = resName.split("\\.");
        return res.getIdentifier(strs[2], strs[1], RePlugin.getHostContext().getPackageName());
    }
调用Toast.makeText(this, getHostResId("R.string.str_test"), Toast.LENGTH_LONG).show();
但是返回回来资源id是0，请问需要写才能获取到id

**Comment by hiloWang** [comment]
尝试下
Class<?> clazz = classLoader.loadClass("包名.R$string");
Field field = clazz.getField("str_test");
int identifierID = (int)field.get(null);

**Comment by sdus007** [comment]
楼上正解。实测可以拿到，注意context要使用宿主的RePlugin.getHostContext()，不要用this。
try {
//                java代码
//                Class<?> clazz = classLoader.loadClass("包名.R$string");
//                Field field = clazz.getField("str_test");
//                int identifierID = (int)field.get(null);
                val clazz = RePlugin.getHostClassLoader().loadClass("com.qihoo360.replugin.sample.host.R\$string")
                val field = clazz.getField("str4Demo3")
                val identifierID = field.get(null) as Int
                Toast.makeText(RePlugin.getHostContext(), identifierID, Toast.LENGTH_LONG).show();
            } catch (e: Exception) {
                // 有可能宿主没有这个资源
                Toast.makeText(v.context, "有可能宿主没有这个资源", Toast.LENGTH_SHORT).show()
                e.printStackTrace()
            }

**Comment by wardenlzr** [comment]
mark
