### ISSUE TITLE
请问外置插件如何调用其他外置插件？

### ISSUE THREAD

**Issue by wardenlzr** [Qihoo360/RePlugin#348]
RePlugin.startActivity(v.getContext(), new Intent(), "demo2", "com.qihoo360.replugin.sample.demo2.databinding.DataBindingActivity");

Intent intent = new Intent("com.qihoo360.replugin.sample.demo2.action.theme_fullscreen_2");
                RePlugin.startActivity(v.getContext(), intent, "demo2", null);

demo 中的这两种方式都是调 内置插件的  请问外置插件如何调用其他外置插件？

**Comment by wardenlzr** [comment]
RePlugin.ws001: start activity: intent=Intent { cmp=fieldenforcement/com.tengdi.fieldenforcement.MainActivity (has extras) } plugin=fieldenforcement activity=com.tengdi.fieldenforcement.MainActivity process=-2147483648
RePlugin.ws001: start activity: intent=Intent { cmp=fieldenforcement/com.tengdi.fieldenforcement.MainActivity (has extras) } plugin=fieldenforcement activity=com.tengdi.fieldenforcement.MainActivity process=-2147483648 download=true
RePlugin.ws001: plugin=fieldenforcement not found, start download ...
RePlugin.ws001: isNeedToDownload(): V5 file not exists. Plugin = fieldenforcement

**Comment by wardenlzr** [comment]
RePlugin.ws001: start activity: intent=Intent { cmp=fieldenforcement/com.demo.fieldenforcement.MainActivity (has extras) } plugin=fieldenforcement activity=com.demo.fieldenforcement.MainActivity process=-2147483648
RePlugin.ws001: start activity: intent=Intent { cmp=fieldenforcement/com.demo.fieldenforcement.MainActivity (has extras) } plugin=fieldenforcement activity=com.demo.fieldenforcement.MainActivity process=-2147483648 download=true
RePlugin.ws001: plugin=fieldenforcement not found, start download ...
RePlugin.ws001: isNeedToDownload(): V5 file not exists. Plugin = fieldenforcement

**Comment by cundong** [comment]
安装完成后，和内置式一样的。

**Comment by wardenlzr** [comment]
我用 
Intent intent = RePlugin.createIntent("fieldenforcement", 
    "com.demo.fieldenforcement.MainActivity");
view.getContext().startActivity(intent);
这种方式打开，报如下错误
RePlugin.ws001: start activity: intent=Intent { cmp=fieldenforcement/com.demo.fieldenforcement.MainActivity (has extras) } plugin=fieldenforcement activity=com.demo.fieldenforcement.MainActivity process=-2147483648
RePlugin.ws001: start activity: intent=Intent { cmp=fieldenforcement/com.demo.fieldenforcement.MainActivity (has extras) } plugin=fieldenforcement activity=com.demo.fieldenforcement.MainActivity process=-2147483648 download=true
RePlugin.ws001: plugin=fieldenforcement not found, start download ...
RePlugin.ws001: isNeedToDownload(): V5 file not exists. Plugin = fieldenforcement
