### ISSUE TITLE
QQ分享SDK集成到插件的问题

### ISSUE THREAD

**Issue by ADroidCoder** [Qihoo360/RePlugin#349]
#### 问题详细描述 Detailed description of the problem
我的qq分享和登录写在了插件里面，但是宿主调用登录结果qq界面提示不是应用商场正版应用，然后也没有回调。我有在宿主 registerHookingClass （两个要在清单文件注册的at）

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.2.0
rePlugin-plugin-lib/gradle Version: 2.2.0

Android API Version：19
Android 手机型号&ROM(Phone model & ROM):  NEXUS

#### Logcat上下文 Logcat context
openSDK_LOG.com.tencent.open.utils.Util: getPackageInfo has exception: com.qzone

**Comment by PhoenixGJH** [comment]
你好，我也遇到了相似的问题，请问你的问题解决了吗？

**Comment by HappysWen** [comment]
@PhoenixGJH 没有

**Comment by chris-jason1224** [comment]
我在做 qq 和微信的分享插件，也遇到了相同的问题，这篇文章应该会有些帮助
http://blog.csdn.net/leluck/article/details/50596768
