### ISSUE TITLE
加载插件的fragment时，RePlugin.getPluginContext()为空

### ISSUE THREAD

**Issue by xingxing2014** [Qihoo360/RePlugin#353]
#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by cundong** [comment]
RePlugin类中并没有getPluginContext()接口，您可以通过fetchContext接口来主动获取插件的Context，如果您的插件并没有被load过，仅仅是在宿主中使用插件的Fragment，请务必先fetchContext一次插件的Context。

关于Fragment的使用，demo中有示例，如下：

       Context pluginContext = RePlugin.fetchContext("demo1");
       if (pluginContext != null) {
            ClassLoader d1ClassLoader = RePlugin.fetchClassLoader("demo1");//获取插件的ClassLoader
            try {
                Fragment fragment =
                        d1ClassLoader
                                .loadClass("com.qihoo360.replugin.sample.demo1.fragment.DemoCodeFragment")
                                .asSubclass(Fragment.class)
                                .newInstance();                                      //使用插件的Classloader获取指定Fragment实例
                getSupportFragmentManager().beginTransaction().add(R.id.container2, fragment).commit(); //添加Fragment到UI
            } catch (InstantiationException e) {
                e.printStackTrace();
            } catch (IllegalAccessException e) {
                e.printStackTrace();
            } catch (ClassNotFoundException e) {
                e.printStackTrace();
            }
        }

**Comment by closedevice** [comment]
宿主中通过RePlugin.fetContext()获取一个未启动的内置插件的Context,此时这个Context是宿主的?
