### ISSUE TITLE
热更新插件出现so找不到的问题

### ISSUE THREAD

**Issue by byecode** [Qihoo360/RePlugin#356]
#### 问题详细描述 Detailed description of the problem
接入replugin之后发现bug统计上面出现了部分so找不到的问题。
再升级新版本插件当天问题数量飙升。
 

#### 其它重要信息 Other important information
360产品在接入中出现过此问题没有？建议出个常见坑的文档。

replugin-host-lib/gradle Version:2.1.6
rePlugin-plugin-lib/gradle Version:2.1.6

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 
全版本

#### Logcat上下文 Logcat context

java.lang.UnsatisfiedLinkError: com.qihoo360.replugin.PluginDexClassLoader[DexPathList[[zip file "/data/user/0/com.xxx.xxx/app_p_a/1319183174.jar"],nativeLibraryDirectories=[/data/user/0/com.xxx.xxx/app_p_n/1319183174, /vendor/lib, /system/lib]]] couldn't find "libffmpeg.so"

**Comment by cundong** [comment]
你应该是没处理好32位 64位 的问题，这个问题跟RePlugin插件化框架没问题。

你可以参考我们的Wiki：https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%92%E4%BB%B6%E7%9A%84%E7%BB%84%E4%BB%B6#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8so%E5%BA%93

**Comment by byecode** [comment]
so找不到问题大部分出在插件更新中。个人感觉跟上述的问题没关系，
而且插件中已经保持跟主工程中同样的so目录。
本地自测无论是插件升级还是安装新插件都没有出现crash统计上的问题。
想问问360这边有没有遇到。

**Comment by kalenty** [comment]
> @cundong
> so找不到问题大部分出在插件更新中。个人感觉跟上述的问题没关系，
> 而且插件中已经保持跟主工程中同样的so目录。
> 本地自测无论是插件升级还是安装新插件都没有出现crash统计上的问题。
> 想问问360这边有没有遇到。

我也遇到了类似的问题，在插件更新的过程中出现crash问题，但是架构是没问题的；想问下后续有解决方案么？
