### ISSUE TITLE
https://github.com/mengdd/PreferencesProvider  这个好像不兼容有解决方案不

### ISSUE THREAD

**Issue by douya40** [Qihoo360/RePlugin#357]
#### 复现问题步骤 Steps to reproduce the problem
https://github.com/mengdd/PreferencesProvider  这个好像不兼容有解决方案不

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.2.0
rePlugin-plugin-lib/gradle Version:  2.2.0

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 
小米 5

**Comment by jiongxuan** [comment]
我们没有用过这个开源项目，可以贴出具体的Logcat日志，发动大家的力量一起帮你看看。
