### ISSUE TITLE
Android7.0以上的系统，在webview中长按文字调用选中复制功能时崩溃

### ISSUE THREAD

**Issue by gokuo** [Qihoo360/RePlugin#358]
#### 复现问题步骤 Steps to reproduce the problem
1. webview中长按页面中的文字，崩溃
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.0
rePlugin-plugin-lib/gradle Version:2.2.0

Android API Version：android api>=7.0
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context
09-18 11:24:50.872 22870-22870/com.kuo.test W/ResourceType: No known package when getting value for resource number 0x020a0000
09-18 11:24:50.873 22870-22870/com.kuo.test W/ResourceType: No known package when getting value for resource number 0x020a0000
09-18 11:24:50.875 22870-22870/com.kuo.test W/System.err: android.content.res.Resources$NotFoundException: Resource ID #0x20a0000
09-18 11:24:50.877 22870-22870/com.kuo.test W/System.err:     at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:190)
09-18 11:24:50.877 22870-22870/com.kuo.test W/System.err:     at android.content.res.Resources.loadXmlResourceParser(Resources.java:2101)
09-18 11:24:50.877 22870-22870/com.kuo.test W/System.err:     at android.content.res.Resources.getLayout(Resources.java:1115)
09-18 11:24:50.877 22870-22870/com.kuo.test W/System.err:     at android.view.MenuInflater.inflate(MenuInflater.java:108)
09-18 11:24:50.877 22870-22870/com.kuo.test W/System.err:     at org.chromium.content.browser.SelectionPopupController.initializeMenu(SelectionPopupController.java:437)
09-18 11:24:50.877 22870-22870/com.kuo.test W/System.err:     at org.chromium.content.browser.SelectionPopupController.createActionMenu(SelectionPopupController.java:443)
09-18 11:24:50.877 22870-22870/com.kuo.test W/System.err:     at org.chromium.content.browser.SelectionPopupController.onCreateActionMode(SelectionPopupController.java:414)
09-18 11:24:50.877 22870-22870/com.kuo.test W/System.err:     at org.chromium.android_webview.AwActionModeCallback.onCreateActionMode(AwActionModeCallback.java:47)
09-18 11:24:50.877 22870-22870/com.kuo.test W/System.err:     at org.chromium.content.browser.FloatingActionModeCallback.onCreateActionMode(FloatingActionModeCallback.java:35)
09-18 11:24:50.877 22870-22870/com.kuo.test W/System.err:     at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onCreateActionMode(DecorView.java:2291)
09-18 11:24:50.877 22870-22870/com.kuo.test W/System.err:     at com.android.internal.policy.DecorView.startActionMode(DecorView.java:860)
09-18 11:24:50.878 22870-22870/com.kuo.test W/System.err:     at com.android.internal.policy.DecorView.startActionModeForChild(DecorView.java:816)
09-18 11:24:50.878 22870-22870/com.kuo.test W/System.err:     at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:828)
09-18 11:24:50.878 22870-22870/com.kuo.test W/System.err:     at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:828)
09-18 11:24:50.878 22870-22870/com.kuo.test W/System.err:     at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:828)
09-18 11:24:50.878 22870-22870/com.kuo.test W/System.err:     at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:828)
09-18 11:24:50.878 22870-22870/com.kuo.test W/System.err:     at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:828)
09-18 11:24:50.878 22870-22870/com.kuo.test W/System.err:     at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:828)
09-18 11:24:50.878 22870-22870/com.kuo.test W/System.err:     at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:828)
09-18 11:24:50.878 22870-22870/com.kuo.test W/System.err:     at android.view.View.startActionMode(View.java:5850)
09-18 11:24:50.878 22870-22870/com.kuo.test W/System.err:     at org.chromium.content.browser.SelectionPopupController.showActionMode$51D2IMG_(SelectionPopupController.java:2226)
09-18 11:24:50.878 22870-22870/com.kuo.test W/System.err:     at org.chromium.content.browser.ContentViewCore.onSelectionEvent(ContentViewCore.java:35781)
09-18 11:24:50.878 22870-22870/com.kuo.test W/System.err:     at org.chromium.android_webview.AwContents.nativeOnDraw(Native Method)
09-18 11:24:50.878 22870-22870/com.kuo.test W/System.err:     at org.chromium.android_webview.AwContents.access$4900(AwContents.java:103)
09-18 11:24:50.879 22870-22870/com.kuo.test W/System.err:     at org.chromium.android_webview.AwContents$AwViewMethodsImpl.onDraw(AwContents.java:3011)
09-18 11:24:50.879 22870-22870/com.kuo.test W/System.err:     at com.android.webview.chromium.WebViewChromium.onDraw(WebViewChromium.java:30342)
09-18 11:24:50.879 22870-22870/com.kuo.test W/System.err:     at android.webkit.WebView.onDraw(WebView.java:2534)
09-18 11:24:50.879 22870-22870/com.kuo.test W/System.err:     at android.view.View.draw(View.java:17237)
09-18 11:24:50.879 22870-22870/com.kuo.test W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16219)
09-18 11:24:50.879 22870-22870/com.kuo.test W/System.err:     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3718)
09-18 11:24:50.879 22870-22870/com.kuo.test W/System.err:     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3698)
09-18 11:24:50.879 22870-22870/com.kuo.test W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16182)
09-18 11:24:50.879 22870-22870/com.kuo.test W/System.err:     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3718)
09-18 11:24:50.879 22870-22870/com.kuo.test W/System.err:     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3698)
09-18 11:24:50.879 22870-22870/com.kuo.test W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16182)
09-18 11:24:50.879 22870-22870/com.kuo.test W/System.err:     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3718)
09-18 11:24:50.879 22870-22870/com.kuo.test W/System.err:     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3698)
09-18 11:24:50.879 22870-22870/com.kuo.test W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16182)
09-18 11:24:50.880 22870-22870/com.kuo.test W/System.err:     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3718)
09-18 11:24:50.880 22870-22870/com.kuo.test W/System.err:     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3698)
09-18 11:24:50.880 22870-22870/com.kuo.test W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16182)
09-18 11:24:50.880 22870-22870/com.kuo.test W/System.err:     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3718)
09-18 11:24:50.880 22870-22870/com.kuo.test W/System.err:     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3698)
09-18 11:24:50.880 22870-22870/com.kuo.test W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16182)
09-18 11:24:50.880 22870-22870/com.kuo.test W/System.err:     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3718)
09-18 11:24:50.880 22870-22870/com.kuo.test W/System.err:     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3698)
09-18 11:24:50.880 22870-22870/com.kuo.test W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16182)
09-18 11:24:50.880 22870-22870/com.kuo.test W/System.err:     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3718)
09-18 11:24:50.880 22870-22870/com.kuo.test W/System.err:     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3698)
09-18 11:24:50.880 22870-22870/com.kuo.test W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16182)
09-18 11:24:50.880 22870-22870/com.kuo.test W/System.err:     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3718)
09-18 11:24:50.880 22870-22870/com.kuo.test W/System.err:     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3698)
09-18 11:24:50.881 22870-22870/com.kuo.test W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16182)
09-18 11:24:50.881 22870-22870/com.kuo.test W/System.err:     at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
09-18 11:24:50.881 22870-22870/com.kuo.test W/System.err:     at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
09-18 11:24:50.881 22870-22870/com.kuo.test W/System.err:     at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
09-18 11:24:50.881 22870-22870/com.kuo.test W/System.err:     at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
09-18 11:24:50.881 22870-22870/com.kuo.test W/System.err:     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
09-18 11:24:50.881 22870-22870/com.kuo.test W/System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
09-18 11:24:50.881 22870-22870/com.kuo.test W/System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
09-18 11:24:50.881 22870-22870/com.kuo.test W/System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6343)
09-18 11:24:50.881 22870-22870/com.kuo.test W/System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
09-18 11:24:50.881 22870-22870/com.kuo.test W/System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:686)
09-18 11:24:50.881 22870-22870/com.kuo.test W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:621)
09-18 11:24:50.881 22870-22870/com.kuo.test W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
09-18 11:24:50.881 22870-22870/com.kuo.test W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
09-18 11:24:50.882 22870-22870/com.kuo.test W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
09-18 11:24:50.882 22870-22870/com.kuo.test W/System.err:     at android.os.Looper.loop(Looper.java:154)
09-18 11:24:50.882 22870-22870/com.kuo.test W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
09-18 11:24:50.882 22870-22870/com.kuo.test W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-18 11:24:50.882 22870-22870/com.kuo.test W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
09-18 11:24:50.882 22870-22870/com.kuo.test W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by jiongxuan** [comment]
这个问题我们之前遇到过，和Context有关，稍后我会让同事来发下解决思路，同时会整理到FAQ上提醒后来人。

**Comment by gokuo** [comment]
也可以通过重写webview的startActionMode(ActionMode.Callback callback, int type) 方法替换默认的callback解决

**Comment by chentaishan** [comment]
解决了吗

**Comment by jonyChina162** [comment]
不光是长按，涉及到 WebView 的 菜单栏问题都有可能会崩溃

**Comment by cundong** [comment]
各位，已解决。

https://github.com/Qihoo360/RePlugin/commit/2f8101f137c7b8bd86e9dc0da7b86862f2806417

@jonyChina162  @chentaishan @gokuo

**Comment by jonyChina162** [comment]
多谢~ 心里美滋滋

**Comment by fvdcx** [comment]
@cundong Hi! Could you share more details about this fix? I didn't see it in comments

**Comment by cundong** [comment]
@fvdcx 
https://github.com/Qihoo360/RePlugin/tree/dev/replugin-sample/plugin/plugin-webview

**Comment by ysy950803** [comment]
现在谷歌在源码中解决这个问题了吗？
