### ISSUE TITLE
host工程无法编译的问题

### ISSUE THREAD

**Issue by benshayu2015** [Qihoo360/RePlugin#36]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:

**Android compile SDK version**:

**Android ROM**:

Gradle sync failed: Cause: org.gradle.api.internal.tasks.DefaultTaskInputs$TaskInputUnionFileCollection cannot be cast to org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection

**Comment by benshayu2015** [comment]
自己已经解决

**Comment by 70kg** [comment]
@benshayu2015 也遇到了这个问题  请问怎么解决

**Comment by 70kg** [comment]
gradle 3.x有这个问题，改成类似gradle-2.14.1就可以了
