### ISSUE TITLE
ProcessLocker文件锁无效

### ISSUE THREAD

**Issue by wowdxn** [Qihoo360/RePlugin#361]
#### 问题详细描述 Detailed description of the problem
在ProcessLocker类中，释放锁的时候会将锁文件删除，经过测试发现，这会导致文件锁失效，帮忙验证一下。

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by cundong** [comment]
抱歉，没有找到复现路径。
