### ISSUE TITLE
关于内置插件升级无效问题

### ISSUE THREAD

**Issue by tz-xiaomage** [Qihoo360/RePlugin#362]
#### 问题详细描述 Detailed description of the problem
首页插件作为内置插件运行，在启动APP之后会去服务器拿最新的插件
一开始试了在下载完新插件之后进行install，提示正在运行，不更新
所以改成了在宿主Application的onCreate方法中进行首页插件的更新安装
日志打印是有显示成功的，（新版本号为1010）但是实际上没成功
![image](https://user-images.githubusercontent.com/12270504/30726258-5cefd560-9f7c-11e7-83db-23204d69a744.png)

真正启动插件APP的时候，日志打印出了
![image](https://user-images.githubusercontent.com/12270504/30726284-8729bb02-9f7c-11e7-8a8c-9fed1195bf87.png)
版本号是1009。

#### 其它重要信息 Other important information
replugin-host-lib/gradle Version: 2.2.0
rePlugin-plugin-lib/gradle Version: 2.2.0

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by cundong** [comment]
我们目前的逻辑是：

如果插件正在运行，那么需要进程重启后才能正确更新；
如果插件没运行，那么可以立即更新。

希望可以帮到你。

**Comment by tz-xiaomage** [comment]
经检查，是因为插件版本相同造成的
