### ISSUE TITLE
作为外置插件启动失败，作为内置插件没问题

### ISSUE THREAD

**Issue by tz-xiaomage** [Qihoo360/RePlugin#364]
#### 问题详细描述 Detailed description of the problem
清新的问题，请问，把插件放在external中，模仿外部插件，在打开的时候模仿demo 的做法，将apk复制到/data/data/package_name/files/目录下文件名
![image](https://user-images.githubusercontent.com/12270504/30732785-c82f826a-9fa6-11e7-9365-3b51d7c6be7e.png)

结果在启动的时候起不来，日志有

有一些信息
![image](https://user-images.githubusercontent.com/12270504/30732792-ce7b3de4-9fa6-11e7-9e78-0710a6897a8a.png)

(注：作为内置插件jar包形式是没问题的)

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.2.0
rePlugin-plugin-lib/gradle Version:2.2.0

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by cundong** [comment]
因为你提供的信息不全，我感觉跟这个issue是同一个问题，您先看一下：https://github.com/Qihoo360/RePlugin/issues/383

如果不是这个问题，还麻烦提提一下完整的log，以方便我们分析。
