### ISSUE TITLE
卸载外置插件的时候，无法成功卸载

### ISSUE THREAD

**Issue by njhhg** [Qihoo360/RePlugin#365]
#### 问题详细描述 Detailed description of the problem

安装一个外置插件，正常安装并启动后打开，然后返回键关闭插件，长按卸载插件无法正常卸载，定位问题是常驻进程挂了，重新修改gradle文件设置关闭常驻进程，采用单进程运行，则卸载插件可以再程序重启后才能生效，如果此时再次安装同一个插件包，则宿主程序会出现ANR/程序崩溃现象，因此感觉最好是可以立即卸载（项目要求也是这样），这个目前感觉无法满足
#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.0
rePlugin-plugin-lib/gradle Version:2.2.0

Android API Version：Android 6.0
Android 手机型号&ROM(Phone model & ROM): 
huawei MT7-TL00

**Comment by njhhg** [comment]
Waiting

**Comment by cundong** [comment]
@njhhg 试试最新的V2.2.1

**Comment by njhhg** [comment]
@cundong 验证情况基本一样，如开启常驻进程，基本卸载失败，关闭常驻进程，则还是只能重启程序生效，无法立刻卸载！

**Comment by cundong** [comment]
@njhhg 就是这样设计的。

如果一个插件已经被加载，卸载逻辑就是“暂存一个待卸载插件列表”，等进程重启后删除dex so等文件，如果没被加载，仅仅被安装，则可以直接卸载。
