### ISSUE TITLE
Error:(23, 0) Failed to apply plugin [id 'replugin-plugin-gradle']

### ISSUE THREAD

**Issue by Tailyou** [Qihoo360/RePlugin#38]
Error:(23, 0) Failed to apply plugin [id 'replugin-plugin-gradle']
<a href="openFile:E:\Github\RePlugin\replugin-sample\plugin\plugin-demo1\app\build.gradle">Open File</a>

**Comment by littlefoxtail** [comment]
+1

**Comment by yumodev** [comment]
+1

**Comment by jiongxuan** [comment]
您好，首先感谢您的回复。

我们已找了2台机器（一台Mac、一台Windows）做了试验，在不去除maven库URL的前提下，是不会有这个问题的。

您们可能好奇，为什么我们在Build.gradle中有这么一段话：

```groovy
    repositories {
        jcenter()
        maven {
            url "https://dl.bintray.com/qihoo360/replugin"
        }
    }
```

这是因为，我们的开源项目刚刚通过公司的安全审核，其AAR和Source也在今天凌晨提交到JCenter上。但由于时间关系，他们目前还没有给予我们回应（预计1~2个工作日）。

所以为了不影响您们运行Sample，就先放到JCenter上的“用户仓库”上，待JCenter审核通过后再行切换到公共库上。所以，还请看下Sample是否有修改过的情况。

最后，感谢您们的反馈，让RePlugin更好！

**Comment by EdisonChang33** [comment]
+1

**Comment by whosmyqueen** [comment]
@jiongxuan 加上
`maven {
            url "https://dl.bintray.com/qihoo360/replugin"
        }`
也没用啊,还是报这个错

**Comment by yumodev** [comment]
我把sample里面的plugin_demo1配置修改为： classpath 'com.android.tools.build:gradle:2.3.2'， gradlle为3.3时会出现这个错误。
恢复sample里面的plugin_demo1配置为：classpath 'com.android.tools.build:gradle:2.1.3'， gradlle为2.14.1时不会出现这个错误。

**Comment by jiongxuan** [comment]
@yumodev 原来如此。感谢您的耐心回答！

此外，该问题在几小时前也及时被 @lizhangqu 给修复并提交了PR，之后更新的代码应该不会再有这个问题了。在此同样表示感谢！

**Comment by chenchengyin** [comment]
我gradle 5.4.1 也出现了这个问题。。。

**Comment by xyz442** [comment]
应该是Gradle版本问题，目前测试发现仅仅支持到的Gradle插件为： classpath 'com.android.tools.build:gradle:3.5.3'，
