### ISSUE TITLE
插件mainfest中activity声明的android:windowSoftInputMode无效

### ISSUE THREAD

**Issue by cislone** [Qihoo360/RePlugin#386]
#### 问题详细描述 Detailed description of the problem
单品中的android:windowSoftInputMode有效，插件无效

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.1
rePlugin-plugin-lib/gradle Version:2.2.1

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 
all

**Comment by cundong** [comment]
您好。
可以参考：
https://github.com/Qihoo360/RePlugin/blob/dev/replugin-host-gradle/src/main/groovy/com/qihoo360/replugin/gradle/host/handlemanifest/ComponentsGenerator.groovy

这里面是Activity坑位的生成逻辑，我们只生成了基本的一些属性。“android:windowSoftInputMode”是没有设置的，您可以通过在代码动态设置。
