### ISSUE TITLE
想知道RePlugin和滴滴开源的VirtualAPK区别在哪里

### ISSUE THREAD

**Issue by niyingxunzong** [Qihoo360/RePlugin#39]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:

**Android compile SDK version**:

**Android ROM**:

**Comment by web1992** [comment]
> 自己研究下不就明白了😂

**Comment by jiongxuan** [comment]
您好，感谢问询。

首先要澄清一点，就是“两者都支持宿主和插件之间的交互”。

不同的是，RePlugin相对来说更独立一些（因采用“独立资源”方案，以确保只有1 Hook点，不改Resources）。此外，在“特性”中可以发现，RePlugin所支持的功能也是非常多的，包括“多进程分配”、“Task-Affinity”等，在实际开发中遇到较多的场景。

具体细节，可如 @web1992 所述，您们可以研究下SourceCode，相信会对您有启发的。

此问题暂时先Close，谢谢理解！
