### ISSUE TITLE
android studio 3.0  RC2 rpInstallAndRunPluginDebug 编译完成后会失败

### ISSUE THREAD

**Issue by zhangxyfs** [Qihoo360/RePlugin#391]
#### 问题详细描述 Detailed description of the problem
android studio 3.0 RC2 rpInstallAndRunPluginDebug 编译完成后会失败
显示这个
D:\software\soft\Android\sdk\platform-tools\adb.exe push E:\develop\Android_RePlugin_Things\PluginAddress\app\build\outputs\apk\app-debug.apk /sdcard/

查了下原因：正确的目录应该是：
E:\develop\Android_RePlugin_Things\PluginAddress\app\build\outputs\apk\debug\app-debug.apk 

也不算是bug，只是导致我不得不手动拷贝过去...

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.1
rePlugin-plugin-lib/gradle Version:2.2.1

Android API Version：26
Android 手机型号&ROM(Phone model & ROM): Nexus5X 模拟器

#### Logcat上下文 Logcat context
****

**Comment by xiaojie-2016** [comment]
gradle 3.0 编译的时候，默认文件夹是 ...\apk\debug(relase)\app-xxx.apk

**Comment by cundong** [comment]
最新目录：
build\outputs\apk\debug\app-debug.apk
build\outputs\apk\release\app-release-unsigned.apk

我改一下脚本。

**Comment by cundong** [comment]
done

https://github.com/Qihoo360/RePlugin/commit/f24878682c66d045ac98024f827b54ca81cee00d
