### ISSUE TITLE
宿主和插件间的Activity通过Intent传递Serializable的对象，数据丢失

### ISSUE THREAD

**Issue by huanglqweiwei** [Qihoo360/RePlugin#394]
#### 问题详细描述 Detailed description of the problem
如题，宿主方通过RePlugin.startActivity(activity, intent)方法打开插件方的Activity，其中intent对象携带了一个Serializable对象，但在插件方的目标Activity起来之后，从getIntent()中获取不到跳转前传递的Serializable对象，断点调试查看intent中的数据也确实没有，但如果将该对象改为实现Parcelable接口，就可以正常传递过来。
查看Replugin源码也没发现对发送的Intent有做替换，帮忙看下这个问题是否是IPC导致的？

**Comment by cundong** [comment]
可以参考：https://github.com/Qihoo360/RePlugin/issues/415
