### ISSUE TITLE
LowInterfaceApi 和 highInterfaceApi 的使用

### ISSUE THREAD

**Issue by Pinned** [Qihoo360/RePlugin#395]
#### 问题详细描述 Detailed description of the problem
![image](https://user-images.githubusercontent.com/8403321/32145460-0ec39588-bc97-11e7-997b-98dae7fb65c7.png)
如图，在`PluginInfo.java`中， 会读取插件Apk中的LowInterfaceApi 和 highInterfaceApi, 但这两个值只用在了文件命名上？是不是和这两个字段设计的初衷有出入啊？

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by cundong** [comment]
是的，实际上这两个可以精简为一个的，由于历史原因保留了。
