### ISSUE TITLE
升级android studio 3.0 正式版本后RePlugin项目构建编译失败

### ISSUE THREAD

**Issue by exhange** [Qihoo360/RePlugin#397]
#### 复现问题步骤 Steps to reproduce the problem
1. gradlew -p demo1 rpInstallPluginDebug
2. 

#### 其它重要信息 Other important information

F:\MyAsProject\RePlugin\Code\RePlugin_Sample>gradlew -p demo1 rpInstallPluginDebug

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'RePlugin_Sample'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.android.tools.build:gradle:3.0.0.
     Searched in the following locations:
         file:/C:/Users/jy/.m2/repository/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.pom
         file:/C:/Users/jy/.m2/repository/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.jar
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.pom
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.jar
         https://repo1.maven.org/maven2/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.pom
         https://repo1.maven.org/maven2/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.jar
     Required by:
         project :
   > Could not find com.android.tools.build:gradle:3.0.0.
     Searched in the following locations:
         file:/C:/Users/jy/.m2/repository/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.pom
         file:/C:/Users/jy/.m2/repository/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.jar
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.pom
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.jar
         https://repo1.maven.org/maven2/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.pom
         https://repo1.maven.org/maven2/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.jar
     Required by:
         project : > com.qihoo360.replugin:replugin-host-gradle:2.2.2
         project : > com.qihoo360.replugin:replugin-plugin-gradle:2.2.2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by a3349384** [comment]
Could not find com.android.tools.build:gradle:3.0.0.

看起来像你自己电脑的网络问题

**Comment by CaptainJno** [comment]
在你项目的gradle中，加入google()
