### ISSUE TITLE
插件想共用宿主中的Retrofit对象，构造api时，提示无法创建reactivex.Observable

### ISSUE THREAD

**Issue by luohaoxuan320** [Qihoo360/RePlugin#405]
#### 问题详细描述 Detailed description of the problem
宿主中有一个单例的Retrofit实例，插件中想直接使用它，避免重复创建Retrofit对象。在插件中使用反射拿到了Retrofit 实例，但是在create httpApi时提示Unable to create call adapter for io.reactivex.Observable。
断点调试对比后，发现插件中实例化的Retrofit和宿主中的Retrofit 关联的retrofit2.adapter.rxjava2.RxJava2CallAdapterFactory 的路径是不一样的
插件中：com.qihoo360.replugin.PluginDexClassLoader[DexPathList[[zip file "/data/data/com.lehow.repluginhost/app_plugins_v3/plugina-10-10-1.jar"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]]

宿主中 dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.lehow.repluginhost-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]]

如果我要实现这个效果，需要怎么做？

**Comment by byecode** [comment]
插件中 retrofit 相关的类，使用provided 方式 提供。
开启useHostClassIfNotFound选项。

**Comment by luohaoxuan320** [comment]
谢谢楼上的建议，问题已经解决了。
有同样问题的小伙伴可以看我的blog记录[RePlugin 插件共享宿主的Retrofit实例](http://www.jianshu.com/p/680d661b7834)
