### ISSUE TITLE
You need to use a Theme.AppCompat 

### ISSUE THREAD

**Issue by lwugang** [Qihoo360/RePlugin#406]
#### 问题详细描述 Detailed description of the problem
You need to use a Theme.AppCompat 

根据demo怎么试都不行，在Activity上单独使用Theme，在application 中使用Theme 都试过
exclude group: 'com.android.support', module: 'support-fragment'  不使用这个排除fragment 就不会有问题，但是 host 加载插件中的fragment 不能转换

**Comment by luohaoxuan320** [comment]
可以参考我的得实现，希望能帮到你[插件 AppCompatActivity 与 v4.Fragment共存](https://github.com/luohaoxuan320/RePluginDemo/wiki/%E6%8F%92%E4%BB%B6-AppCompatActivity-%E4%B8%8E-v4.Fragment%E5%85%B1%E5%AD%98)

**Comment by cundong** [comment]
出现这个问题，原因就是：插件中的这个Activity，继承了v7包的AppCompatActivity，但是却没有使用与其配合的AppCompat theme。
