### ISSUE TITLE
关于热修复问题

### ISSUE THREAD

**Issue by StormKid** [Qihoo360/RePlugin#410]
#### 问题详细描述 Detailed description of the problem
现在在使用这套框架搭建新的项目框架，考虑到热修复和内置外置插件问题，当前wiki上面没有相关问题的描述，故提出issues希望能够得到答案，内置和外置到底谁能热修复，然后，热修复宿主是可行的吗？

**Comment by cundong** [comment]
修复宿主是可行的，我们公司内部的产品，比如：[花椒直播](http://www.huajiao.com/)，就同时用了RePlugin（为了实现插件化）和Tinker（为了热修复宿主）。

修复插件，这个需求就有点鸡肋了，本身都已经插件化了，直接下发插件就行了，为什么还要对插件进行热修复呢。

**Comment by StormKid** [comment]
@cundong 多谢指点，有时候有的需求很奇怪，有时候也是技术问题，反正都是解决问题，尽量选择最优的

**Comment by ustcJianglong** [comment]
同时在宿主中使用Replugin和Thinker会让应用直接卡在初始界面,是不是源码还要一定的改动?

**Comment by wb1992321** [comment]
@cundong 方便说一下RePlugin和Tinker的同时集成方案么？
