### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by dongdroi** [Qihoo360/RePlugin#412]
#### 问题详细描述 Detailed description of the problem

Class not found when unmarshalling

#### 复现问题步骤 Steps to reproduce the problem
1.  使用库 provided "com.google.auto.value:auto-value:1.4-rc3" 
2.  使用在model类上使用@AutoValue注解，会自动生成final class AutoValue_XXX类
3.  内置插件无法找到AutoValue_XXX类  = ClassNotFoundException

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by cundong** [comment]
我，没有明白你描述的意思。
