### ISSUE TITLE
宿主调用插件中的Popupwindow， 需要参数Activity

### ISSUE THREAD

**Issue by xshasha521** [Qihoo360/RePlugin#414]
#### 问题详细描述 Detailed description of the problem
插件中集成了微信、QQ、微博等第三方分享，做了一个Popupwindow（排列了QQ/微信/微博的图标，以供用户选择哪种方式分享）。

因为微信需要传递当前程序的Activity作为参数，在插件中直接运行，传递插件的activity实例，运行正常。

在宿主程序中，希望直接调起插件中的Popupwindow，而非Activity，这样我需要传递一个Activity参数给Popupwindow
 1. 传递宿主中的Activity示例，报错：说是没有微信等相关的库（库在插件程序中）；
 2. 获得插件中Context，传递过去，报错：无法转成Activity

问题： 请问 应该怎么传递这个Activity参数？
                    或者应该如何做？

**Comment by cundong** [comment]
建议用Activity实现一个类Popupwindow的效果。
