### ISSUE TITLE
Dev 版本下的lib还没有发布到Jcenter上

### ISSUE THREAD

**Issue by Pinned** [Qihoo360/RePlugin#416]
classpath 'com.qihoo360.replugin:replugin-host-gradle:2.2.2'
classpath 'com.qihoo360.replugin:replugin-plugin-gradle:2.2.2'

compile 'com.qihoo360.replugin:replugin-plugin-lib:2.2.2'
compile 'com.qihoo360.replugin:replugin-host-lib:2.2.2'

gradle 插件和 lib 的2.2.2 版本都还没有发布到Jcenter,望处理。

**Comment by cundong** [comment]
现在还是测试版，等正式发布的时候才会发布到JCenter的。

如果你想使用dev分支的代码，可以自己在本地发布到 mavenLocal的。
