### ISSUE TITLE
【关于webAPP集成问题】

### ISSUE THREAD

**Issue by StormKid** [Qihoo360/RePlugin#417]
#### 问题详细描述 Detailed description of the problem
webAPP作为插件集成进宿主APP，这个问题不知道有没有实现，现在做cordova的插件化，将包导入到webAPP的项目中去，然后通过宿主插件打开webAPP的MainActivity，经过测试没有效果。原因有以下几点：1、未导入插件gradle包。在plugman 插件目录下，通过cofig.xml配置的时候虽然导入了相应的程序生成的jar包，但是：
```
buildscript {
    dependencies {
        classpath 'com.qihoo360.replugin:replugin-plugin-gradle:2.2.1'
        ...
    }
}
```
这个没办法导入进项目中，手动控制platform并修改gradle内容，打包apk也会出现找不到entity的问题。
2、猜想：就算导入完毕并且能够使用插件，调用的webAPP的MainActiviy显示的内容是否为正常功能的内容呢？不知道针对这方面的研究以及探讨。

**Comment by cundong** [comment]
不太明白， 您的webAPP，是指？
