### ISSUE TITLE
按照接入指南接入报错

### ISSUE THREAD

**Issue by whosmyqueen** [Qihoo360/RePlugin#42]
Error:Could not find com.qihoo360.replugin:replugin-host-gradle:2.1.0.
Searched in the following locations:
    file:/Applications/Android Studio 3.0 Preview.app/Contents/gradle/m2repository/com/qihoo360/replugin/replugin-host-gradle/2.1.0/replugin-host-gradle-2.1.0.pom
    file:/Applications/Android Studio 3.0 Preview.app/Contents/gradle/m2repository/com/qihoo360/replugin/replugin-host-gradle/2.1.0/replugin-host-gradle-2.1.0.jar
    https://dl.google.com/dl/android/maven2/com/qihoo360/replugin/replugin-host-gradle/2.1.0/replugin-host-gradle-2.1.0.pom
    https://dl.google.com/dl/android/maven2/com/qihoo360/replugin/replugin-host-gradle/2.1.0/replugin-host-gradle-2.1.0.jar
    https://jcenter.bintray.com/com/qihoo360/replugin/replugin-host-gradle/2.1.0/replugin-host-gradle-2.1.0.pom
    https://jcenter.bintray.com/com/qihoo360/replugin/replugin-host-gradle/2.1.0/replugin-host-gradle-2.1.0.jar
Required by:
    project :

**Comment by jiongxuan** [comment]
您好，目前这几个Jar包还在JCenter上审核（官方预计1~2个工作日，可能在下周一搞定）。

您可以参考Sample工程来配置URL，临时切换到JCenter上的用户库，待审核通过后再去掉URL，直接走公共库。

感谢您的理解！
