### ISSUE TITLE
静态广播的处理

### ISSUE THREAD

**Issue by wangzhanxian** [Qihoo360/RePlugin#422]
#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by wangzhanxian** [comment]
我觉得可以改造代理广播的PendingResult进行偷梁换柱

**Comment by cundong** [comment]
可以的，欢迎提 PR
