### ISSUE TITLE
调用插件Fragment，v4库异常

### ISSUE THREAD

**Issue by dongdroi** [Qihoo360/RePlugin#426]
#### 问题详细描述 Detailed description of the problem

1，清理自动依赖的v4库
configurations {
    all*.exclude group: 'com.android.support', module: 'support-v4'
}

2，配置Sample的v4库 
provided files('libs/fragment.jar')

在插件中继承AppCompatActivity，编译报错

Error:(22, 8) 错误: 无法访问TaskStackBuilder
找不到android.support.v4.app.TaskStackBuilder的类文件

将AppCompatActivity换成FragmentActivity就可以编译通过

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by luohaoxuan320** [comment]
可以参考我的实现，希望能帮到你 [插件 AppCompatActivity 与 v4.Fragment共存](https://github.com/luohaoxuan320/RePluginDemo/wiki/%E6%8F%92%E4%BB%B6-AppCompatActivity-%E4%B8%8E-v4.Fragment%E5%85%B1%E5%AD%98)

**Comment by cundong** [comment]
@luohaoxuan320
感谢！
