### ISSUE TITLE
插件的MainActivity中权限申请不执行

### ISSUE THREAD

**Issue by jingzhanwu** [Qihoo360/RePlugin#427]
我使用的是android studio3.0，插件Activity都继承了AppCompatActivity，插件的MainActivity中的onCreate方法中我有申请一些权限，包括定位，读写，camera等，当使用宿主apk启动插件时权限申请不起作用，请问这个问题是什么引起的，（使用andorid6.0手机测试，插件独立运行时一切正常，插件是模拟的外置插件，放置在宿主的assets/external目录下，安装和启动方法均使用demo和github文档提供的方式）

**Comment by cundong** [comment]
这个，WiKI中已经有描述了。

插件需要的静态权限，需要声明到宿主中；动态权限，则需要插件自己动态申请。

**Comment by violinday** [comment]
> 这个，WiKI中已经有描述了。
> 插件需要的静态权限，需要声明到宿主中；动态权限，则需要插件自己动态申请。

没找到 相应 wiki

**Comment by qndroid** [comment]
it's work.
