### ISSUE TITLE
插件是否不支持android.preference.PreferenceActivity的使用

### ISSUE THREAD

**Issue by lijunjieone** [Qihoo360/RePlugin#432]
#### 问题详细描述 Detailed description of the problem
插件中实现了设置功能,设置功能继承了系统的android.preference.PreferenceActivity,xml中配置了android.PreferenceActivitypreference.PreferenceScreen,插件独立运行没有问题,可以正常使用,
在宿主中调用该设置功能时,出现崩溃了.

#### 复现问题步骤 Steps to reproduce the problem
1. 插件中设置使用了android.preference.PreferenceActivity, android.PreferenceActivitypreference.PreferenceScreen
2. 在宿主中调用设置时,出现崩溃.

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.1
rePlugin-plugin-lib/gradle Version:2.2.1

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context
E/ExceptionHandler|AndroidRuntime( 3900): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mx.browser.star/com.mx.browser.star.loader.a.ActivityN1NRNTS4}: android.view.InflateException: Binary XML file line #14: Error inflating class menu
E/ExceptionHandler|AndroidRuntime( 3900): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
E/ExceptionHandler|AndroidRuntime( 3900): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
E/ExceptionHandler|AndroidRuntime( 3900): 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
E/ExceptionHandler|AndroidRuntime( 3900): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
E/ExceptionHandler|AndroidRuntime( 3900): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExceptionHandler|AndroidRuntime( 3900): 	at android.os.Looper.loop(Looper.java:135)
E/ExceptionHandler|AndroidRuntime( 3900): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/ExceptionHandler|AndroidRuntime( 3900): 	at java.lang.reflect.Method.invoke(Native Method)
E/ExceptionHandler|AndroidRuntime( 3900): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/ExceptionHandler|AndroidRuntime( 3900): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/ExceptionHandler|AndroidRuntime( 3900): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/ExceptionHandler|AndroidRuntime( 3900): Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class menu
E/ExceptionHandler|AndroidRuntime( 3900): 	at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:441)
E/ExceptionHandler|AndroidRuntime( 3900): 	at android.preference.GenericInflater.inflate(GenericInflater.java:317)
E/ExceptionHandler|AndroidRuntime( 3900): 	at android.preference.GenericInflater.inflate(GenericInflater.java:263)
E/ExceptionHandler|AndroidRuntime( 3900): 	at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:272)
E/ExceptionHandler|AndroidRuntime( 3900): 	at android.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:299)
E/ExceptionHandler|AndroidRuntime( 3900): 	at org.adblockplus.libadblockplus.android.settings.GeneralSettingsFragment.onCreate(GeneralSettingsFragment.java:92)
E/ExceptionHandler|AndroidRuntime( 3900): 	at android.app.Fragment.performCreate(Fragment.java:2031)
E/ExceptionHandler|AndroidRuntime( 3900): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:863)
E/ExceptionHandler|AndroidRuntime( 3900): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
E/ExceptionHandler|AndroidRuntime( 3900): 	at android.app.BackStackRecord.run(BackStackRecord.java:834)
E/ExceptionHandler|AndroidRuntime( 3900): 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
E/ExceptionHandler|AndroidRuntime( 3900): 	at android.app.Activity.performStart(Activity.java:6005)
E/ExceptionHandler|AndroidRuntime( 3900): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288)
E/ExceptionHandler|AndroidRuntime( 3900): 	... 10 more
E/ExceptionHandler|AndroidRuntime( 3900): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.preference.menu" on path: DexPathList[[zip file "/data/app/com.mx.browser.star-2/base.apk"],nativeLibraryDirectories=[/data/app/com.mx.browser.star-2/lib/arm, /vendor/lib, /system/lib]]
E/ExceptionHandler|AndroidRuntime( 3900): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/ExceptionHandler|AndroidRuntime( 3900): 	at com.qihoo360.replugin.RePluginClassLoader.findClass(RePluginClassLoader.java:172)
E/ExceptionHandler|AndroidRuntime( 3900): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/ExceptionHandler|AndroidRuntime( 3900): 	at com.qihoo360.replugin.RePluginClassLoader.loadClass(RePluginClassLoader.java:163)
E/ExceptionHandler|AndroidRuntime( 3900): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/ExceptionHandler|AndroidRuntime( 3900): 	at android.preference.GenericInflater.createItem(GenericInflater.java:375)
E/ExceptionHandler|AndroidRuntime( 3900): 	at android.preference.GenericInflater.onCreateItem(GenericInflater.java:417)
E/ExceptionHandler|AndroidRuntime( 3900): 	at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:428)
E/ExceptionHandler|AndroidRuntime( 3900): 	... 22 more
E/ExceptionHandler|AndroidRuntime( 3900): 	Suppressed: java.lang.ClassNotFoundException: android.preference.menu
E/ExceptionHandler|AndroidRuntime( 3900): 		at java.lang.Class.classForName(Native Method)
E/ExceptionHandler|AndroidRuntime( 3900): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/ExceptionHandler|AndroidRuntime( 3900): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/ExceptionHandler|AndroidRuntime( 3900): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/ExceptionHandler|AndroidRuntime( 3900): 		... 27 more
E/ExceptionHandler|AndroidRuntime( 3900): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
E/ExceptionHandler|Android

**Comment by cundong** [comment]
请参照dev分支，已经支持。
