### ISSUE TITLE
RePlugin.App.attachBaseContext方法调用时间长

### ISSUE THREAD

**Issue by muchenshou** [Qihoo360/RePlugin#433]
#### 问题详细描述 Detailed description of the problem

RePlugin.App.attachBaseContext方法调用花费太长时间，导致应用启动慢

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.2.1
rePlugin-plugin-lib/gradle Version: 2.2.1

**Comment by cundong** [comment]
内置了多少插件，什么手机，大约时长？

**Comment by guixiaoyuan** [comment]
手机，华为SLA-AL00，一个插件，2秒左右

**Comment by guixiaoyuan** [comment]
@cundong
