### ISSUE TITLE
Sample 工程编译报错：Error:Could not find com.qihoo360.replugin:replugin-plugin-gradle:2.2.2.

### ISSUE THREAD

**Issue by NemoHzy** [Qihoo360/RePlugin#437]
#### 问题详细描述 Detailed description of the problem
Sample 工程中无论 host 还是 plugin 编译时均报错，提示：
Error:Could not find com.qihoo360.replugin:replugin-plugin-gradle:2.2.2.
把 replugin-plugin-gradle:2.2.2. 版本号替换成 2.2.1 
并修改app build.gradle里面的 compile 'com.qihoo360.replugin:replugin-host-lib:2.2.2' 版本为2.2.1
就可以正常编译，是不是没有上传2.2.2版本到库上？

#### 复现问题步骤 Steps to reproduce the problem
1.  尝试编译 sample 就可以了

#### 其它重要信息 Other important information

Error:Could not find com.qihoo360.replugin:replugin-host-gradle:2.2.2.
Searched in the following locations:
    file:/xxxxx/Contents/gradle/m2repository/com/qihoo360/replugin/replugin-host-gradle/2.2.2/replugin-host-gradle-2.2.2.pom
    file:/xxxxx/Contents/gradle/m2repository/com/qihoo360/replugin/replugin-host-gradle/2.2.2/replugin-host-gradle-2.2.2.jar
    file:/xxxxx/.m2/repository/com/qihoo360/replugin/replugin-host-gradle/2.2.2/replugin-host-gradle-2.2.2.pom
    file:/xxxxx/.m2/repository/com/qihoo360/replugin/replugin-host-gradle/2.2.2/replugin-host-gradle-2.2.2.jar
    https://jcenter.bintray.com/com/qihoo360/replugin/replugin-host-gradle/2.2.2/replugin-host-gradle-2.2.2.pom
    https://jcenter.bintray.com/com/qihoo360/replugin/replugin-host-gradle/2.2.2/replugin-host-gradle-2.2.2.jar
Required by:
    project :

Android API Version：不涉及
Android 手机型号&ROM(Phone model & ROM): 不涉及

#### Logcat上下文 Logcat context
不涉及

**Comment by cundong** [comment]
Jcenter最新版本是：2.2.1
V2.2.2 只能你自己mavenLocal使用。

**Comment by NemoHzy** [comment]
好的，谢谢
