### ISSUE TITLE
内置插件更新后，下次启动应用读插件列表不完整

### ISSUE THREAD

**Issue by QinGeneral** [Qihoo360/RePlugin#439]
#### 问题详细描述 Detailed description of the problem

APP中有多个内置插件。
其中一个内置插件从网络下载到sdcard，安装插件后，关闭应用。
下次启动APP，使用RePlugin.getPluginList()，只能获取到刚刚更新的内置插件的信息，获取不到其他内置插件。（安装后调不调用preload都会出现问题）
再次重启应用恢复正常。可以使用RePlugin.getPluginList()读到完整插件列表。

#### 复现问题步骤 Steps to reproduce the problem
1.  网络下载内置插件新版本，进行更新
2.  重启APP
3.  RePlugin.getPluginList()，只能获取到刚刚更新的内置插件的信息
4.  再次重启APP，可以使用RePlugin.getPluginList()读到完整插件列表。

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.2.1 / 3.0.0
rePlugin-plugin-lib/gradle Version: 2.2.1 / 3.0.0

Android API Version： 
Android 手机型号&ROM(Phone model & ROM): oppo

**Comment by QinGeneral** [comment]
外置插件也会出现这个问题

**Comment by cundong** [comment]
可以使用dev分支进行测试。
