### ISSUE TITLE
支持直接启动插件中的fragment吗？

### ISSUE THREAD

**Issue by 70kg** [Qihoo360/RePlugin#44]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:

**Android compile SDK version**:

**Android ROM**:

看文档可以直接启动activity和service等组件，想了解一下可以直接启动插件中的fragment吗？

**Comment by jiongxuan** [comment]
您好，我们是完全支持的。

当然，倒是提醒了我。我会把这块儿的说明加上，让后面的人也知道。

**Comment by 70kg** [comment]
@jiongxuan 感谢回复

**Comment by tz-xiaomage** [comment]
@jiongxuan 请问一下，假如宿主Activity有多个fragment，每个fragment都经常需要修改或者多几个，  
能不能把fragment当成插件，宿主Activity经常需要切换不同的fragment，如果能把fragment当成插件来加载，然后添加到宿主Activity中去，那样就不用总为了一个新的fragment而发一个版本了
请教，不知道如上这种业务，能不能做呢？

**Comment by jiongxuan** [comment]
您可以参考下我们最新的Sample，应该能满足您的需求。
