### ISSUE TITLE
支持隐式启动Activity吗

### ISSUE THREAD

**Issue by tofaluanle** [Qihoo360/RePlugin#441]
如题，是否支持Intent使用setAction或者setData隐式启动Activity，包括下面三种情况：
1、宿主隐式启动插件的Activity
2、插件隐式启动其他插件的Activity
3、插件隐式启动宿主的Activity

**Comment by cundong** [comment]
可以参考：

com.qihoo360.replugin.component.utils.IntentMatcherHelper
