### ISSUE TITLE
内置插件提升版本号，RePlugin.install升级不成功

### ISSUE THREAD

**Issue by cxzadmini** [Qihoo360/RePlugin#442]
#### 问题详细描述 Detailed description of the problem
内置插件升级，同版本可以升级成功。提升版本号后重新打包插件，RePlugin.install安装成功，可以返回新版本的PluginInfo， 重新启动应用，再次调用插件，插件还是未升级之前的版本。

#### 复现问题步骤 Steps to reproduce the problem

1. 使用官方plugin-demo1,提升verioncode 和versionName，重新编译打包
2. 使用官方host demo，将要升级的版本放到assets/external目录下，启动host，打开插件。退出插件。
3. 点击升级，拷贝到缓存目录下，调用RePlugin.install 安装，能正常返回升级后的PluginInfo 对象。重启host，在host 启动插件，发现插件并没有升级成功

PS：若是没有提升插件版本号。直接修改插件代码，再RePlugin.install ，是可以升级成功的。  
      

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.1
rePlugin-plugin-lib/gradle Version:2.2.1

Android API Version：Android 7.0
Android 手机型号&ROM(Phone model & ROM):

**Comment by cundong** [comment]
可以使用dev分支进行测试。
