### ISSUE TITLE
插件中的ContentProvider没有走Oncreate生命周期

### ISSUE THREAD

**Issue by appledong** [Qihoo360/RePlugin#445]
#### 问题详细描述 Detailed description of the problem
如标题：插件中声明的contentprovider，集成到宿主以后，不能正常的使用，经代码跟踪是contentprovider中oncreate的初始化操作没有执行

#### 复现问题步骤 Steps to reproduce the problem
1. 插件中声明contentprovider并在oncreate方法中添加日志
2. 集成到宿主，没有打出相应的日志

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.3.3
rePlugin-plugin-lib/gradle Version: 2.3.1

Android API Version：api版本都是26
Android 手机型号&ROM(Phone model & ROM): 
小米note4a/mui

**Comment by appledong** [comment]
![Uploading image.png…]()
补充说明：加载插件的时候有这么一个提示

**Comment by appledong** [comment]
![plugin](https://user-images.githubusercontent.com/5242789/33654499-47d95cd6-daab-11e7-8967-734c6421474b.png)
补充说明

**Comment by cundong** [comment]
可以直接使用demo1中的Provider测试，onCreate是正确执行的。

**Comment by appledong** [comment]
谢谢！已解决，我的测试demo有问题

**Comment by iugg21** [comment]
怎么解决的，我现在也遇到这个问题，插件声明的ContentProvider的Oncreate方法没有被调用
