### ISSUE TITLE
关于FAQ中提到的AAR引入问题

### ISSUE THREAD

**Issue by shuimuqinghua** [Qihoo360/RePlugin#448]
最近我想在项目中引入RePlugin，公共类部分，包括一些第三方jar，第三方引用都放在公共库中，然后放到jcenter中引入。我只放入了公共库中必须用到的资源文件，而且保证不在插件项目中引用这部分资源文件。这样引入是否可行？ 
      对于这点我比较疑惑，希望360的技术大佬们能帮忙解答下，谢谢。

**Comment by cundong** [comment]
可以。
