### ISSUE TITLE
Attempt to invoke interface method 'void android.support.v7.widget.DecorContentParent.setWindowCallback(android.view.Window$Callback)' on a null object reference

### ISSUE THREAD

**Issue by shuimuqinghua** [Qihoo360/RePlugin#451]
#### 问题详细描述 Detailed description of the problem
按照文档，在宿主app中接入插件app，运行的时候，crash，日志错误显示
![image](https://user-images.githubusercontent.com/7427087/33865793-4942abc2-df2e-11e7-945e-993e47894872.png)

#### 复现问题步骤 Steps to reproduce the problem
1. 插件app打包改名为xxx.jar
2. 放入宿主appassets/plugins中，并运行

#### 其它重要信息 Other important information
1、宿主接入遵循文档要求，单独运行OK
2、插件app单独运行OK
replugin-host-lib/gradle Version:2.2.1
rePlugin-plugin-lib/gradle Version:2.2.1

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 
5.0

**Comment by shuimuqinghua** [comment]
该问题我已经解决，原因在于theme设置有问题，导致在AppCompatDelegateImplV9.java的方法createSubDecor（）中，mDecorContentParent = (DecorContentParent) subDecor
                        .findViewById(R.id.decor_content_parent);中的mDecorContentParent 为null导致

**Comment by CTO1987** [comment]
请问你是怎么解决的，我也有这个问题，你是怎么设置theme主题的

**Comment by CTO1987** [comment]
我解决了，在内置插件把AppCompatActivity改成PluginAppCompatActivity就好了！~

**Comment by chenyunecjtu** [comment]
请问 楼主是怎么解决的？
我主题改了还是没解决？如果直接继承PluginAppCompatActivity 是可以的，但是我不想这样做，想直接AppCompatActivity

**Comment by techinsight** [comment]
同求，不继承PluginAppCompatActivity 情况下如何避免
