### ISSUE TITLE
插件中集成了qq、微信分享，从宿主调用不正常

### ISSUE THREAD

**Issue by BittleDragon** [Qihoo360/RePlugin#455]
#### 问题详细描述 Detailed description of the problem
插件中集成了qq、微信分享，在作为独立app时运行正常。集成在宿主中时，运行不正常，qq能正常分享，但是回调错误，微信无法分享

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.1
rePlugin-plugin-lib/gradle Version:2.2.1

Android API Version：22
Android 手机型号&ROM(Phone model & ROM): Nubia Nx508j

**Comment by cundong** [comment]
是你的接入过程不正确导致的。

几个值得注意的点：
1. 申请各种KEY都要使用宿主的包名和签名；
2. 微信分享和微信支付(?) 都需要在宿主里面放一个回调Activity；
3. 可以在这个回调Activity中处理一下，只要收到系统回调，马上跳转到插件中；
