### ISSUE TITLE
Replugin发布的都是debug版本吗？

### ISSUE THREAD

**Issue by LiuJQ** [Qihoo360/RePlugin#457]
#### 问题详细描述 Detailed description of the problem
Replugin发布的都是debug版本吗？
> 想关闭内部日志输出，发现RepluginInternal里面读取到的buildType="debug"

#### 复现问题步骤 Steps to reproduce the problem
无

#### 其它重要信息 Other important information

下面代码也是无效的，源码里面默认值false
```java
RePluginConfig c = new RePluginConfig();
c.setPrintDetailLog(false);
```

> replugin-host-lib/gradle Version: 2.2.1
> rePlugin-plugin-lib/gradle Version:2.2.1

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by cundong** [comment]
默认是输出log的。
