### ISSUE TITLE
宿主APP与插件APP中Activity的统一堆栈管理问题

### ISSUE THREAD

**Issue by shuimuqinghua** [Qihoo360/RePlugin#460]
#### 问题详细描述 Detailed description of the problem

activity堆栈管理，我将A,B,C三个插件的Activity都放入。然后在A插件中想finish掉除了C插件中XXXActivity之外的所有activity，我该怎么写啊？

代码使用如下： 
AppManager.getAppManager().finishAllActivity(XXXActivity.class);

XXXActivity.class为不finish的目标activity。

**Comment by cundong** [comment]
请使用多Task的思路解决。
