### ISSUE TITLE
Presentation类的setContentView方法加载的R资源错误

### ISSUE THREAD

**Issue by LeungHL** [Qihoo360/RePlugin#461]
#### 问题详细描述 Detailed description of the problem
项目其中的一个内置插件，里面定义了一个独立进程的service，service里面创建了一个Presentation，在Presentation的onCreate方法中setContentView(rid)时发现R.layout.xxx的值是正确的，但取到的layout文件是错误的，请问有什么办法解决么？

**Comment by cundong** [comment]
Presentation 是什么。

**Comment by LeungHL** [comment]
Presentation是dialog的一个子类,可以指定屏幕显示,通常用来做双屏异显的
