### ISSUE TITLE
Fatal signal 11 (SIGSEGV) at 0x00000008 (code=1), thread xxx,程序崩溃

### ISSUE THREAD

**Issue by lauhwong** [Qihoo360/RePlugin#462]
#### 问题详细描述 Detailed description of the problem
4.x的手机在startActivity之后，出现Fatal signal 11 (SIGSEGV) at 0x00000008 (code=1), thread xxx,程序崩溃！5.0以后没问题

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.1
rePlugin-plugin-lib/gradle Version:2.2.1

Android API Version：4.4.2-19
Android 手机型号&ROM(Phone model & ROM): htc

#### Logcat上下文 Logcat context
RePlugin.ws000: loadLocked(): Initialized, is loaded = true

RePlugin.ws001: PACM: loadActivityClass, plugin activity loader: in=com.xx.loader.a.ActivityN1STNTS0 activity=comxx.HomeActivity

RePlugin.ws001: PACM: loadActivityClass, plugin activity loader: c=xx.HomeActivity, loader=com.qihoo360.replugin.PluginDexClassLoader[DexPathList[[zip file "/data/user/0/com.xx/app_p_a/181088705.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib, /vendor/lib]]]

A/libc: Fatal signal 11 (SIGSEGV) at 0x00000008 (code=1), thread 29822 (le.memobile.dev)

I/DEBUG: Build fingerprint: 'htc/htccn_chs_cu/htc_a5dug:4.4.2/KOT49H/332745.1:user/release-keys'
 I/DEBUG: debuggerd: checkTellHTCSettings
 V/HtcNativeCrashUtil: Read id1=-1243796867 id2=-217320719, they are start flags. This is HTC header
 I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000008

 I/DEBUG: backtrace:
I/DEBUG:     #00  pc 000153b8  /system/lib/libandroidfw.so (android::ResTable::getBagLocked(unsigned int, android::ResTable::bag_entry const**, unsigned int*) const+299)
 I/DEBUG:     #01  pc 0001588b  /system/lib/libandroidfw.so (android::ResTable::Theme::applyStyle(unsigned int, bool)+30)
 I/DEBUG:     #02  pc 0002094c  /system/lib/libdvm.so (dvmPlatformInvoke+112)
 I/DEBUG:     #03  pc 00057589  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+428)
 I/DEBUG:     #04  pc 00029de0  /system/lib/libdvm.so
 I/DEBUG:     #05  pc 000326e4  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
 I/DEBUG:     #06  pc 0002fc00  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+232)
 I/DEBUG:     #07  pc 0006d579  /system/lib/libdvm.so (dvmInvokeMethod(Object*, Method const*, ArrayObject*, ArrayObject*, ClassObject*, bool)+392)
 I/DEBUG:     #08  pc 00077119  /system/lib/libdvm.so
I/DEBUG:     #09  pc 00029de0  /system/lib/libdvm.so
 I/DEBUG:     #10  pc 000326e4  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
 I/DEBUG:     #11  pc 0002fc00  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+232)
 I/DEBUG:     #12  pc 0006d249  /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+336)
 I/DEBUG:     #13  pc 00052b2f  /system/lib/libdvm.so
 I/DEBUG:     #14  pc 0005017f  /system/lib/libandroid_runtime.so
 I/DEBUG:     #15  pc 00051341  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, char const*)+472)
 I/DEBUG:     #16  pc 000010bb  /system/bin/app_process
 I/DEBUG:     #17  pc 0000e45b  /system/lib/libc.so (__libc_init+50)
 I/DEBUG:     #18  pc 00000db8  /system/bin/app_process

**Comment by cundong** [comment]
Native Crash

**Comment by lauhwong** [comment]
@cundong 嗯，其实我想问的是是否了解可能造成这部分的原因，看着像是ResTable那部分的问题，会不会是插件潜在的针对4.x的特殊问题呢。

**Comment by chinacuizichao** [comment]
这个问题解决了么？

**Comment by chinacuizichao** [comment]
这个问题解决了么？
