### ISSUE TITLE
插件中使用MaterialDateTimePicker无法居中显示

### ISSUE THREAD

**Issue by LeungHL** [Qihoo360/RePlugin#463]
#### 问题详细描述 Detailed description of the problem
如题,在插件中使用[MaterialDateTimePicker](https://github.com/wdullaer/MaterialDateTimePicker),独立运行时是居中显示的,作为插件运行后显示在左上角

**Comment by cundong** [comment]
我试了试，没有问题，您自己检查一下自己的使用方式吧。

![430314436292597944](https://user-images.githubusercontent.com/3348483/34289711-be69f18c-e72e-11e7-96bb-ec47ebd01c0f.png)
