### ISSUE TITLE
插件对于JPush之流推送的集成

### ISSUE THREAD

**Issue by shuimuqinghua** [Qihoo360/RePlugin#466]
#### 问题详细描述 Detailed description of the problem

JPush推送如何集成？

#### 复现问题步骤 Steps to reproduce the problem

1. JPush推送配置，按照JPush要求置于宿主AndroidManifest中
2. JPush_APPKEY置于插件AndroidManifest中，采用的是宿主包名生成的key
3.运行代码，注册alias显示6009

#### 其它重要信息 Other important information
jpush jar版本：3.1.6
replugin-host-lib/gradle Version:2.2.1
rePlugin-plugin-lib/gradle Version:2.2.1

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by cundong** [comment]
晚些时候 我给你来个push plugin demo

**Comment by shuimuqinghua** [comment]
好，非常感谢 @cundong

**Comment by liuxucool163** [comment]
求demo

**Comment by cundong** [comment]
@liuxucool163  @shuimuqinghua 

推送，升级，这种基础的服务，都建议把最核心的长连接逻辑放到宿主，宿主收到push下来的消息后，把消息完整的传递给另外一个
push业务插件，该插件收到消息后可以做一些具体的弹窗，弹通知栏之类的工作，它可以独立升级。

因为，基础的长连接相关，是轻易不会变动的，而收到消息之后的逻辑确是经常变动的。
