### ISSUE TITLE
Plugin apk <meta-data> info can't read in Plugin self code.

### ISSUE THREAD

**Issue by vhly** [Qihoo360/RePlugin#468]
#### 问题详细描述 Detailed description of the problem

插件APK中自身使用到了 <meta-data> 信息，在宿主程序启动后，执行插件，
插件无法获取字段。插件获取的信息直接映射到 宿主的清单文件中。

#### 复现问题步骤 Steps to reproduce the problem
1. 使用 Cocos2dx 3.x 打包一个游戏，已插件形式在 Android Studio中进行编译；
2. Cocos 引擎中的 Java代码会获取  清单文件中的  <meta-data> 来加载指定的 so 库；
3. 将打好包的文件放入到 宿主程序中，并且以 内置插件的形式进行打包；
4. 宿主可以启动插件，但是崩溃了哦

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:       com.qihoo360.replugin:replugin-host-lib:2.2.1
rePlugin-plugin-lib/gradle Version:    com.qihoo360.replugin:replugin-plugin-lib:2.2.1

Android API Version：                  5.1
Android 手机型号&ROM(Phone model & ROM):     魅族 MX5   Flyme 6.2.0.0A

**Comment by cundong** [comment]
可以这样获取插件的meta-data

1.通过 PackageManager 接口 的 getPackageArchiveInfo 方法，获取到插件的 packageInfo；
2.拿到插件的 ApplicationInfo（packageInfo.applicationInf）；
3.再去获取插件的meta-data(appInfo.metaData)

**Comment by vhly** [comment]
不好意思，我的描述不太清楚可能，我的意思是，插件内部代码来获取自身的 meta-data，而不是宿主程序，例如一个 cocos2d-x的游戏，引擎部分获取自己的 meta-data，没有必要使用 获取archive方式这种。

**Comment by vhly** [comment]
插件的代码不应该过度的依赖与宿主程序，而是使用标准方式获取

**Comment by danny2012** [comment]
楼上的解决了么，meta-data，我的也是遇到一样的问题，插件中读取meta-data拿不到，用@cundong说的方法似乎也拿不到哦

**Comment by 1318526619** [comment]
private String getMetaDataFromApp(String key) {
        String value = "";
        ApplicationInfo appInfo =
                RePlugin.getPluginContext().getApplicationInfo();
        value = appInfo.metaData.getString(key);
        return value;
    }
亲测，可行
