### ISSUE TITLE
官方 sample demo3杀进程之后不能安装、启动

### ISSUE THREAD

**Issue by Logicxcz** [Qihoo360/RePlugin#471]
#### 问题详细描述 Detailed description of the problem

官方 sample demo3杀进程之后不能再次安装、启动

#### 复现问题步骤 Steps to reproduce the problem
1. 杀进程之后，先点击start Kolin Plugin(demo3），能启动demo3，再点击install or update external plugin 就能安装并启动demo3。
2. 再次杀进程，先点击install or update external plugin ，就不能启动demo3，再次点击start Kolin Plugin(demo3）也不能启动了。

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.0
rePlugin-plugin-lib/gradle Version:

Android API Version：4.4.4 、8.0.0
Android 手机型号&ROM(Phone model & ROM):  Chel-CL10、Pixel

#### Logcat上下文 Logcat context

01-08 11:13:02.795 1148-3638/? V/RecentTasksLoader: creating activity desc for id=56, label=RePlugin Sample
01-08 11:13:02.915 1148-1631/? V/RecentTasksLoader: creating activity desc for id=56, label=RePlugin Sample
01-08 11:13:03.295 1148-1148/? V/RecentTasksLoader: creating activity desc for id=56, label=RePlugin Sample
01-08 11:13:04.515 1148-1148/? V/RecentsPanelView: Jettison RePlugin Sample
01-08 11:13:04.525 1148-1148/? V/RecentsPanelView: Jettison RePlugin Sample
01-08 11:13:06.335 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: plugin process checker: default, index=0
01-08 11:13:06.345 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: PACM: restore table: size=1
01-08 11:13:06.345 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: PACM: restore table:  container=com.qihoo360.replugin.sample.host.loader.a.ActivityN1NRNTS3 plugin=demo3 activity=com.qihoo360.replugin.sample.demo3.MainActivity
01-08 11:13:06.345 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: list plugins from persistent process
01-08 11:13:06.405 3666-3666/? D/RePlugin.ws001: plugin process checker: non plugin process in=com.qihoo360.replugin.sample.host:GuardService
01-08 11:13:06.405 3666-3666/? D/RePlugin.ws001: search plugins from file system
01-08 11:13:06.415 3666-3666/? D/RePlugin.ws001: built-in plugins config: item: PInfo { <demo1:104(4)> [BUILTIN] js={"ali":"demo1","frm_ver":4,"name":"demo1","path":"plugins\/demo1.jar","verv":2814792716779624,"ver":104,"high":10,"type":2,"low":10,"pkgname":"com.qihoo360.replugin.sample.demo1"} dex=/data/user/0/com.qihoo360.replugin.sample.host/app_plugins_v3_odex/demo1-10-10-104.dex nlib=/data/user/0/com.qihoo360.replugin.sample.host/app_plugins_v3_libs/demo1-10-10-104 }
01-08 11:13:06.415 3666-3666/? D/RePlugin.ws001: built-in plugins config: item: PInfo { <demo2:100(4)> [BUILTIN] js={"ali":"demo2","frm_ver":4,"name":"demo2","path":"plugins\/demo2.jar","verv":2814792716779620,"ver":100,"high":10,"type":2,"low":10,"pkgname":"com.qihoo360.replugin.sample.demo2"} dex=/data/user/0/com.qihoo360.replugin.sample.host/app_plugins_v3_odex/demo2-10-10-100.dex nlib=/data/user/0/com.qihoo360.replugin.sample.host/app_plugins_v3_libs/demo2-10-10-100 }
01-08 11:13:06.415 3666-3666/? D/RePlugin.ws001: search v5 files: dir=/data/user/0/com.qihoo360.replugin.sample.host/files
01-08 11:13:06.415 3666-3666/? D/RePlugin.ws001: search plugins: dir=/data/user/0/com.qihoo360.replugin.sample.host/app_plugins_v3
01-08 11:13:06.425 3666-3666/? D/RePlugin.PluginManagerServer: updateIfNeeded: Not need to update. pn=demo3
01-08 11:13:06.425 3666-3666/? D/RePlugin.PluginManagerServer: updateAllIfNeeded: Updated 0 plugins
01-08 11:13:06.425 3666-3666/? D/RePlugin.ws001: plugin: p=PInfo { <demo3:100(4)> [APK] [DEX_EXTRACTED] [USED] js={"ali":"demo3","frm_ver":4,"name":"demo3","path":"\/data\/user\/0\/com.qihoo360.replugin.sample.host\/app_p_a\/-334910795.jar","verv":2814792716779620,"high":10,"ver":100,"low":10,"type":11,"used":true,"pkgname":"com.qihoo360.replugin.sample.demo3"} dex=/data/user/0/com.qihoo360.replugin.sample.host/app_p_od/-334910795.dex nlib=/data/user/0/com.qihoo360.replugin.sample.host/app_p_n/-334910795 }
01-08 11:13:06.425 3666-3666/? D/RePlugin.ws001: plugin: p=PInfo { <demo2:100(4)> [BUILTIN] js={"ali":"demo2","frm_ver":4,"name":"demo2","path":"plugins\/demo2.jar","verv":2814792716779620,"ver":100,"high":10,"type":2,"low":10,"pkgname":"com.qihoo360.replugin.sample.demo2"} dex=/data/user/0/com.qihoo360.replugin.sample.host/app_plugins_v3_odex/demo2-10-10-100.dex nlib=/data/user/0/com.qihoo360.replugin.sample.host/app_plugins_v3_libs/demo2-10-10-100 }
01-08 11:13:06.435 3666-3666/? D/RePlugin.ws001: plugin: p=PInfo { <demo3:100(4)> [APK] [DEX_EXTRACTED] [USED] js={"ali":"demo3","frm_ver":4,"name":"demo3","path":"\/data\/user\/0\/com.qihoo360.replugin.sample.host\/app_p_a\/-334910795.jar","verv":2814792716779620,"high":10,"ver":100,"low":10,"type":11,"used":true,"pkgname":"com.qihoo360.replugin.sample.demo3"} dex=/data/user/0/com.qihoo360.replugin.sample.host/app_p_od/-334910795.dex nlib=/data/user/0/com.qihoo360.replugin.sample.host/app_p_n/-334910795 }
01-08 11:13:06.435 3666-3666/? D/RePlugin.ws001: plugin: p=PInfo { <demo1:104(4)> [BUILTIN] js={"ali":"demo1","frm_ver":4,"name":"demo1","path":"plugins\/demo1.jar","verv":2814792716779624,"ver":104,"high":10,"type":2,"low":10,"pkgname":"com.qihoo360.replugin.sample.demo1"} dex=/data/user/0/com.qihoo360.replugin.sample.host/app_plugins_v3_odex/demo1-10-10-104.dex nlib=/data/user/0/com.qihoo360.replugin.sample.host/app_plugins_v3_libs/demo1-10-10-104 }
01-08 11:13:06.435 3666-3666/? D/RePlugin.ws001: plugin: p=PInfo { <demo2:100(4)> [BUILTIN] js={"ali":"demo2","frm_ver":4,"name":"demo2","path":"plugins\/demo2.jar","verv":2814792716779620,"ver":100,"high":10,"type":2,"low":10,"pkgname":"com.qihoo360.replugin.sample.demo2"} dex=/data/user/0/com.qihoo360.replugin.sample.host/app_plugins_v3_odex/demo2-10-10-100.dex nlib=/data/user/0/com.qihoo360.replugin.sample.host/app_plugins_v3_libs/demo2-10-10-100 }
01-08 11:13:06.435 3666-3666/? D/RePlugin.ws001: plugin: p=PInfo { <demo1:104(4)> [BUILTIN] js={"ali":"demo1","frm_ver":4,"name":"demo1","path":"plugins\/demo1.jar","verv":2814792716779624,"ver":104,"high":10,"type":2,"low":10,"pkgname":"com.qihoo360.replugin.sample.demo1"} dex=/data/user/0/com.qihoo360.replugin.sample.host/app_plugins_v3_odex/demo1-10-10-104.dex nlib=/data/user/0/com.qihoo360.replugin.sample.host/app_plugins_v3_libs/demo1-10-10-104 }
01-08 11:13:06.435 3666-3666/? D/RePlugin.RePluginClassLoader: copyFromOriginal: Fields=[private final dalvik.system.DexPathList dalvik.system.BaseDexClassLoader.pathList, 
                                                               private java.util.Map java.lang.ClassLoader.packages, 
                                                               private java.lang.ClassLoader java.lang.ClassLoader.parent]
01-08 11:13:06.435 3666-3666/? D/RePlugin.RePluginClassLoader: copyFieldValue: Copied. f=pathList; actually=DexPathList[[zip file "/data/app/com.qihoo360.replugin.sample.host-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.qihoo360.replugin.sample.host-1, /vendor/lib, /system/lib, /data/datalib]]; orig=DexPathList[[zip file "/data/app/com.qihoo360.replugin.sample.host-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.qihoo360.replugin.sample.host-1, /vendor/lib, /system/lib, /data/datalib]]
01-08 11:13:06.455 3666-3666/? D/RePlugin.ws001: generate cookie: 1515381186460
01-08 11:13:06.455 3666-3666/? D/RePlugin.ws001: initial local cookie=1515381186460
01-08 11:13:06.455 3666-3678/? D/RePlugin.ws001: stubMain projection=[main] selection=main_binder
01-08 11:13:06.455 3666-3678/? D/RePlugin.ws001: query binder = com.qihoo360.loader2.PmHostSvc@425e7f08
01-08 11:13:06.455 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: get binder = android.os.BinderProxy@42632b68
01-08 11:13:06.455 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: proxy fetch binder: binder=android.os.BinderProxy@42632b68
01-08 11:13:06.455 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: host binder = android.os.BinderProxy@42632b68
01-08 11:13:06.455 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: host binder.i = com.qihoo360.loader2.IPluginHost$Stub$Proxy@42634588
01-08 11:13:06.465 3666-3678/? D/RePlugin.ws001: attach process: pid=3651 index=-1 binder=com.qihoo360.loader2.IPluginClient$Stub$Proxy@4262a558
01-08 11:13:06.465 3666-3678/? D/RePlugin.ws001: attach process: ui
01-08 11:13:06.465 3666-3677/? D/RePlugin.ws001: build plugins
01-08 11:13:06.465 3666-3677/? D/RePlugin.ws001: build 6 plugins
01-08 11:13:06.475 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: plugin: p=PInfo { <demo3:100(4)> [APK] [DEX_EXTRACTED] [USED] js={"ali":"demo3","frm_ver":4,"name":"demo3","path":"\/data\/user\/0\/com.qihoo360.replugin.sample.host\/app_p_a\/-334910795.jar","verv":2814792716779620,"ver":100,"high":10,"used":true,"type":11,"low":10,"pkgname":"com.qihoo360.replugin.sample.demo3"} dex=/data/data/com.qihoo360.replugin.sample.host/app_p_od/-334910795.dex nlib=/data/data/com.qihoo360.replugin.sample.host/app_p_n/-334910795 }
01-08 11:13:06.475 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: plugin: p=PInfo { <demo2:100(4)> [BUILTIN] js={"ali":"demo2","frm_ver":4,"name":"demo2","path":"plugins\/demo2.jar","verv":2814792716779620,"high":10,"ver":100,"low":10,"type":2,"pkgname":"com.qihoo360.replugin.sample.demo2"} dex=/data/data/com.qihoo360.replugin.sample.host/app_plugins_v3_odex/demo2-10-10-100.dex nlib=/data/data/com.qihoo360.replugin.sample.host/app_plugins_v3_libs/demo2-10-10-100 }
01-08 11:13:06.475 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: plugin: p=PInfo { <demo3:100(4)> [APK] [DEX_EXTRACTED] [USED] js={"ali":"demo3","frm_ver":4,"name":"demo3","path":"\/data\/user\/0\/com.qihoo360.replugin.sample.host\/app_p_a\/-334910795.jar","verv":2814792716779620,"ver":100,"high":10,"used":true,"type":11,"low":10,"pkgname":"com.qihoo360.replugin.sample.demo3"} dex=/data/data/com.qihoo360.replugin.sample.host/app_p_od/-334910795.dex nlib=/data/data/com.qihoo360.replugin.sample.host/app_p_n/-334910795 }
01-08 11:13:06.475 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: plugin: p=PInfo { <demo1:104(4)> [BUILTIN] js={"ali":"demo1","frm_ver":4,"name":"demo1","path":"plugins\/demo1.jar","verv":2814792716779624,"high":10,"ver":104,"low":10,"type":2,"pkgname":"com.qihoo360.replugin.sample.demo1"} dex=/data/data/com.qihoo360.replugin.sample.host/app_plugins_v3_odex/demo1-10-10-104.dex nlib=/data/data/com.qihoo360.replugin.sample.host/app_plugins_v3_libs/demo1-10-10-104 }
01-08 11:13:06.475 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: plugin: p=PInfo { <demo2:100(4)> [BUILTIN] js={"ali":"demo2","frm_ver":4,"name":"demo2","path":"plugins\/demo2.jar","verv":2814792716779620,"high":10,"ver":100,"low":10,"type":2,"pkgname":"com.qihoo360.replugin.sample.demo2"} dex=/data/data/com.qihoo360.replugin.sample.host/app_plugins_v3_odex/demo2-10-10-100.dex nlib=/data/data/com.qihoo360.replugin.sample.host/app_plugins_v3_libs/demo2-10-10-100 }
01-08 11:13:06.475 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: plugin: p=PInfo { <demo1:104(4)> [BUILTIN] js={"ali":"demo1","frm_ver":4,"name":"demo1","path":"plugins\/demo1.jar","verv":2814792716779624,"high":10,"ver":104,"low":10,"type":2,"pkgname":"com.qihoo360.replugin.sample.demo1"} dex=/data/data/com.qihoo360.replugin.sample.host/app_plugins_v3_odex/demo1-10-10-104.dex nlib=/data/data/com.qihoo360.replugin.sample.host/app_plugins_v3_libs/demo1-10-10-104 }
01-08 11:13:06.485 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.RePluginClassLoader: copyFieldValue: Copied. f=pathList; actually=DexPathList[[zip file "/data/app/com.qihoo360.replugin.sample.host-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.qihoo360.replugin.sample.host-1, /vendor/lib, /system/lib, /data/datalib]]; orig=DexPathList[[zip file "/data/app/com.qihoo360.replugin.sample.host-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.qihoo360.replugin.sample.host-1, /vendor/lib, /system/lib, /data/datalib]]
01-08 11:13:06.485 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: plugin provider loader: not found default plugin,  in=com.qihoo360.replugin.sample.host.loader.p.ProviderN1
01-08 11:13:06.495 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: initial local cookie=0
01-08 11:13:14.125 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: MP.pluginDownloaded ... path=/data/data/com.qihoo360.replugin.sample.host/files/demo3.apk
01-08 11:13:14.125 3666-3677/com.qihoo360.replugin.sample.host:GuardService D/RePlugin.ws001: pluginDownloaded： path=/data/data/com.qihoo360.replugin.sample.host/files/demo3.apk
01-08 11:13:14.175 3666-3677/com.qihoo360.replugin.sample.host:GuardService I/RePlugin.PluginManagerServer: installLocked: Info=PInfo { <demo3:100(4)> [APK] [DEX_EXTRACTED] [USED] js={"ali":"demo3","frm_ver":4,"name":"demo3","path":"\/data\/data\/com.qihoo360.replugin.sample.host\/files\/demo3.apk","verv":2814792716779620,"ver":100,"high":10,"type":10,"low":10,"pkgname":"com.qihoo360.replugin.sample.demo3"} dex=/data/user/0/com.qihoo360.replugin.sample.host/app_p_od/-334910795.dex nlib=/data/user/0/com.qihoo360.replugin.sample.host/app_p_n/-334910795 }
01-08 11:13:14.175 3666-3677/com.qihoo360.replugin.sample.host:GuardService I/RePlugin.PluginManagerServer: installLocked: Has installed plugin. current=PInfo { <demo3:100(4)> [APK] [DEX_EXTRACTED] [USED] js={"ali":"demo3","frm_ver":4,"name":"demo3","path":"\/data\/user\/0\/com.qihoo360.replugin.sample.host\/app_p_a\/-334910795.jar","verv":2814792716779620,"high":10,"ver":100,"low":10,"type":11,"used":true,"pkgname":"com.qihoo360.replugin.sample.demo3"} dex=/data/user/0/com.qihoo360.replugin.sample.host/app_p_od/-334910795.dex nlib=/data/user/0/com.qihoo360.replugin.sample.host/app_p_n/-334910795 }
01-08 11:13:14.175 3666-3677/com.qihoo360.replugin.sample.host:GuardService D/RePlugin.PluginManagerServer: isSameVersion: same version. inst_ver=100; cur_ver=100
01-08 11:13:14.185 3666-3677/com.qihoo360.replugin.sample.host:GuardService D/RePlugin.PluginManagerServer: updateOrLater: Need update. pn=demo3; cur_ver=100; update_ver=100
01-08 11:13:14.185 3666-3677/com.qihoo360.replugin.sample.host:GuardService I/RePlugin.PluginManagerServer: updateOrLater: Not running. Update now! pn=demo3
01-08 11:13:14.195 3666-3677/com.qihoo360.replugin.sample.host:GuardService I/RePlugin.PluginManagerServer: updateNow: Update. pn=100; cur_ver=100; update_ver=100
01-08 11:13:14.195 3666-3677/com.qihoo360.replugin.sample.host:GuardService D/RePlugin.ws001: update plugin table: info=PInfo { <demo3:100(4)> [APK] [USED] js={"cover":true,"ali":"demo3","frm_ver":4,"name":"demo3","path":"\/data\/user\/0\/com.qihoo360.replugin.sample.host\/app_p_c\/-334910795.jar","verv":2814792716779620,"ver":100,"high":10,"type":11,"low":10,"pkgname":"com.qihoo360.replugin.sample.demo3"} dex=/data/user/0/com.qihoo360.replugin.sample.host/app_p_c/-334910795.dex nlib=/data/user/0/com.qihoo360.replugin.sample.host/app_p_c/-334910795 }
01-08 11:13:14.195 3666-3677/com.qihoo360.replugin.sample.host:GuardService D/RePlugin.ws001: insert new plugin: info=PInfo { <demo3:100(4)> [APK] js={"cover":true,"ali":"demo3","frm_ver":4,"name":"demo3","path":"\/data\/user\/0\/com.qihoo360.replugin.sample.host\/app_p_c\/-334910795.jar","verv":2814792716779620,"ver":100,"high":10,"type":11,"low":10,"pkgname":"com.qihoo360.replugin.sample.demo3"} dex=/data/user/0/com.qihoo360.replugin.sample.host/app_p_c/-334910795.dex nlib=/data/user/0/com.qihoo360.replugin.sample.host/app_p_c/-334910795 }
01-08 11:13:14.195 3666-3677/com.qihoo360.replugin.sample.host:GuardService D/RePlugin.ws001: insert new plugin: ok: plugin=PInfo { <demo3:100(4)> [APK] js={"cover":true,"ali":"demo3","frm_ver":4,"name":"demo3","path":"\/data\/user\/0\/com.qihoo360.replugin.sample.host\/app_p_c\/-334910795.jar","verv":2814792716779620,"ver":100,"high":10,"type":11,"low":10,"pkgname":"com.qihoo360.replugin.sample.demo3"} dex=/data/user/0/com.qihoo360.replugin.sample.host/app_p_c/-334910795.dex nlib=/data/user/0/com.qihoo360.replugin.sample.host/app_p_c/-334910795 }
01-08 11:13:14.195 3666-3677/com.qihoo360.replugin.sample.host:GuardService D/RePlugin.ws001: PStatusC.setStatus(): Status is OK, Clear. pn=demo3; ver=100
01-08 11:13:14.205 3666-3677/com.qihoo360.replugin.sample.host:GuardService D/RePlugin.IPC: sendLocalBroadcast2AllSync: intent=Intent { act=ACTION_NEW_PLUGIN (has extras) }
01-08 11:13:14.205 3666-3677/com.qihoo360.replugin.sample.host:GuardService D/RePlugin.ws001: sendIntent2Process target=null intent=Intent { act=ACTION_NEW_PLUGIN (has extras) }
01-08 11:13:14.205 3666-3677/com.qihoo360.replugin.sample.host:GuardService D/RePlugin.ws001: sendIntent2Process name=com.qihoo360.replugin.sample.host
01-08 11:13:14.205 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: sendIntent pr=com.qihoo360.replugin.sample.host intent=Intent { act=ACTION_NEW_PLUGIN (has extras) }
01-08 11:13:14.215 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: update plugin table: info=PInfo { <demo3:100(4)> [APK] [USED] js={"ali":"demo3","cover":true,"frm_ver":4,"name":"demo3","path":"\/data\/user\/0\/com.qihoo360.replugin.sample.host\/app_p_c\/-334910795.jar","verv":2814792716779620,"high":10,"ver":100,"low":10,"type":11,"pkgname":"com.qihoo360.replugin.sample.demo3"} dex=/data/data/com.qihoo360.replugin.sample.host/app_p_c/-334910795.dex nlib=/data/data/com.qihoo360.replugin.sample.host/app_p_c/-334910795 }
01-08 11:13:14.215 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: insert new plugin: info=PInfo { <demo3:100(4)> [APK] js={"ali":"demo3","cover":true,"frm_ver":4,"name":"demo3","path":"\/data\/user\/0\/com.qihoo360.replugin.sample.host\/app_p_c\/-334910795.jar","verv":2814792716779620,"high":10,"ver":100,"low":10,"type":11,"pkgname":"com.qihoo360.replugin.sample.demo3"} dex=/data/data/com.qihoo360.replugin.sample.host/app_p_c/-334910795.dex nlib=/data/data/com.qihoo360.replugin.sample.host/app_p_c/-334910795 }
01-08 11:13:14.215 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: insert new plugin: ok: plugin=PInfo { <demo3:100(4)> [APK] js={"ali":"demo3","cover":true,"frm_ver":4,"name":"demo3","path":"\/data\/user\/0\/com.qihoo360.replugin.sample.host\/app_p_c\/-334910795.jar","verv":2814792716779620,"high":10,"ver":100,"low":10,"type":11,"pkgname":"com.qihoo360.replugin.sample.demo3"} dex=/data/data/com.qihoo360.replugin.sample.host/app_p_c/-334910795.dex nlib=/data/data/com.qihoo360.replugin.sample.host/app_p_c/-334910795 }
01-08 11:13:14.215 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: PStatusC.setStatus(): Status is OK, Clear. pn=demo3; ver=100
01-08 11:13:14.225 3666-3677/com.qihoo360.replugin.sample.host:GuardService D/RePlugin.task-affinity: syncPluginInfo2All: Sync complete! syncPi=PInfo { <demo3:100(4)> [APK] js={"cover":true,"ali":"demo3","frm_ver":4,"name":"demo3","path":"\/data\/user\/0\/com.qihoo360.replugin.sample.host\/app_p_c\/-334910795.jar","verv":2814792716779620,"ver":100,"high":10,"type":11,"low":10,"pkgname":"com.qihoo360.replugin.sample.demo3"} dex=/data/user/0/com.qihoo360.replugin.sample.host/app_p_c/-334910795.dex nlib=/data/user/0/com.qihoo360.replugin.sample.host/app_p_c/-334910795 }
01-08 11:13:14.225 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: start activity: intent=Intent { cmp=demo3/com.qihoo360.replugin.sample.demo3.MainActivity } plugin=demo3 activity=com.qihoo360.replugin.sample.demo3.MainActivity process=-2147483648
01-08 11:13:14.225 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: start activity: intent=Intent { cmp=demo3/com.qihoo360.replugin.sample.demo3.MainActivity } plugin=demo3 activity=com.qihoo360.replugin.sample.demo3.MainActivity process=-2147483648 download=true
01-08 11:13:14.225 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.loadClass: isHookingClass(demo3 , com.qihoo360.replugin.sample.demo3.MainActivity) = false
01-08 11:13:14.225 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: PStatusC.getStatus(): ps is null. pn=demo3
01-08 11:13:14.225 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: PStatusC.getStatus(): ps is null. pn=demo3
01-08 11:13:14.225 3651-3651/com.qihoo360.replugin.sample.host I/RePlugin.ws001: loadLocked(): Ready to lock! logtag = try1; pn = demo3
01-08 11:13:14.255 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: get package archive info null
01-08 11:13:14.255 3651-3651/com.qihoo360.replugin.sample.host I/RePlugin.ws001: load /data/user/0/com.qihoo360.replugin.sample.host/app_p_c/-334910795.jar 1116197376 c=3 rc=false delta=27
01-08 11:13:14.255 3651-3651/com.qihoo360.replugin.sample.host I/RePlugin.ws001: loadLocked(): Unlock! logtag = try1; pn = demo3
01-08 11:13:14.255 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: get package archive info null
01-08 11:13:14.255 3651-3651/com.qihoo360.replugin.sample.host I/RePlugin.ws001: load2 /data/user/0/com.qihoo360.replugin.sample.host/app_p_c/-334910795.jar 1116197376 c=3 rc=false delta=0
01-08 11:13:14.255 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: PACM: bindActivity: may be invalid plugin name or load plugin failed: plugin=null
01-08 11:13:14.255 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: PACM: bindActivity: activity not found
01-08 11:13:14.255 3651-3651/com.qihoo360.replugin.sample.host D/RePlugin.ws001: plugin cn not found: intent=Intent { cmp=demo3/com.qihoo360.replugin.sample.demo3.MainActivity } plugin=demo3 activity=com.qihoo360.replugin.sample.demo3.MainActivity process=-2147483648

**Comment by SkyEric** [comment]
问题未复现，日志显示插件加载失败，并显示：“get package archive info null”。 可参照issues[https://github.com/Qihoo360/RePlugin/issues/489](url)
