### ISSUE TITLE
从插件A经过多次跳转，再跳转到插件B中，跳转后插件A中第一个Activity被销毁

### ISSUE THREAD

**Issue by zhangchao0916** [Qihoo360/RePlugin#476]
从插件A经过多次跳转，再跳转到插件B中，跳转后有时候到时插件A中第一个Activity被销毁

步骤：
1. 宿主中集成了A,B,C多个插件；
2. 之后从A经过多次跳转，再跳转到插件B中，继续执行；
3. 之后导致A中第一个Activity被销毁了

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.2.1
rePlugin-plugin-lib/gradle Version: 2.2.1

多个手机均出现以上bug

相关log:

01-10 17:33:27.347 21273-21273/com.udd.travel D/RePlugin.ws001: start context: intent=Intent { cmp=com.udd.travel/.pay.activity.PayErrorActivity }
01-10 17:33:27.347 21273-21273/com.udd.travel D/RePlugin.ws001: start context: custom context=com.udd.travel.pay.activity.PayActivity@2bec3142
01-10 17:33:27.347 21273-21273/com.udd.travel D/RePlugin.loadClass: isHookingClass(null,com.udd.travel.pay.activity.PayErrorActivity) = false
01-10 17:33:27.348 21273-21273/com.udd.travel D/RePlugin.ws001: found: ActivityState {container=com.udd.travel.loader.a.ActivityN1NRNTS0 state=occupied plugin=payPlugin activity=com.udd.travel.pay.activity.PayActivity size=1}
01-10 17:33:27.348 21273-21273/com.udd.travel D/RePlugin.ws001: start context: custom plugin is empty, query plugin=payPlugin
01-10 17:33:27.348 21273-21273/com.udd.travel D/RePlugin.ws001: start activity: intent=Intent { cmp=com.udd.travel/.pay.activity.PayErrorActivity } plugin=payPlugin activity=com.udd.travel.pay.activity.PayErrorActivity process=-2147483648
01-10 17:33:27.348 21273-21273/com.udd.travel D/RePlugin.ws001: start activity: intent=Intent { cmp=com.udd.travel/.pay.activity.PayErrorActivity } plugin=payPlugin activity=com.udd.travel.pay.activity.PayErrorActivity process=-2147483648 download=true
01-10 17:33:27.348 21273-21273/com.udd.travel D/RePlugin.loadClass: isHookingClass(payPlugin , com.udd.travel.pay.activity.PayErrorActivity) = false
01-10 17:33:27.348 21273-21273/com.udd.travel D/RePlugin.ws001: PStatusC.getStatus(): ps is null. pn=payPlugin
01-10 17:33:27.349 21273-21273/com.udd.travel D/RePlugin.ws001: PStatusC.getStatus(): ps is null. pn=payPlugin
01-10 17:33:27.349 21273-21273/com.udd.travel I/RePlugin.ws000: loadLocked(): Initialized, is loaded = true
01-10 17:33:27.349 21273-21273/com.udd.travel D/RePlugin.theme: intent.putExtra(com.udd.travel.pay.activity.PayErrorActivity, 0);
01-10 17:33:27.350 21273-21273/com.udd.travel D/RePlugin.ws001: PStatusC.getStatus(): ps is null. pn=payPlugin
01-10 17:33:27.350 21273-21273/com.udd.travel I/RePlugin.ws000: loadLocked(): Initialized, is loaded = true
01-10 17:33:27.351 21273-21273/com.udd.travel D/RePlugin.task-affinity: originTaskAffinity is com.udd.travel.pay
01-10 17:33:27.351 21273-21273/com.udd.travel W/RePlugin.ws001: PACM: force alloc container=com.udd.travel.loader.a.ActivityN1NRNTS2
01-10 17:33:27.361 21273-21273/com.udd.travel W/RePlugin.ws001: PACM: clean refs: exist a=com.travel.airticket.uddairticketplugin.activity.AirTicketsHomeActivity@a58fbf8
01-10 17:33:27.361 21273-21273/com.udd.travel D/RePlugin.ws001: PACM: save 2 pref: k=com.udd.travel.loader.a.ActivityN1NRNTS2 v=payPlugin:com.udd.travel.pay.activity.PayErrorActivity:1515576807361
01-10 17:33:27.375 21273-21273/com.udd.travel D/RePlugin.ws001: PACM: bindActivity: lookup activity container: container=com.udd.travel.loader.a.ActivityN1NRNTS2
01-10 17:33:27.375 21273-21273/com.udd.travel D/RePlugin.ws001: PACM: eval plugin payPlugin, target=com.udd.travel.pay.activity.PayErrorActivity, container=com.udd.travel.loader.a.ActivityN1NRNTS2
01-10 17:33:27.375 21273-21273/com.udd.travel I/RePlugin.ws001: alloc success: container=com.udd.travel.loader.a.ActivityN1NRNTS2 plugin=payPlugin activity=com.udd.travel.pay.activity.PayErrorActivity
01-10 17:33:27.375 21273-21273/com.udd.travel D/RePlugin.ws001: start activity: real intent=Intent { cat=[process:-2147483648,plugin:payPlugin,activity:com.udd.travel.pay.activity.PayErrorActivity,counter:0,container:com.udd.travel.loader.a.ActivityN1NRNTS2] cmp=com.udd.travel/.loader.a.ActivityN1NRNTS2 (has extras) }
01-10 17:33:27.376 21273-21273/com.udd.travel D/RePlugin.ws001: start context: intent=Intent { cat=[process:-2147483648,plugin:payPlugin,activity:com.udd.travel.pay.activity.PayErrorActivity,counter:0,container:com.udd.travel.loader.a.ActivityN1NRNTS2] cmp=com.udd.travel/.loader.a.ActivityN1NRNTS2 (has extras) }
01-10 17:33:27.376 21273-21273/com.udd.travel D/RePlugin.ws001: start context: custom context=com.udd.travel.pay.activity.PayActivity@2bec3142
01-10 17:33:27.376 21273-21273/com.udd.travel D/RePlugin.ws001: start context: context is container, direct start
01-10 17:33:27.376 21273-21273/com.udd.travel D/RePlugin.ws001: start activity with startActivityForResult: intent=Intent { cat=[process:-2147483648,plugin:payPlugin,activity:com.udd.travel.pay.activity.PayErrorActivity,counter:0,container:com.udd.travel.loader.a.ActivityN1NRNTS2] cmp=com.udd.travel/.loader.a.ActivityN1NRNTS2 (has extras) }
01-10 17:33:27.376 21273-21273/com.udd.travel D/RePlugin.ws001: PStatusC.getStatus(): ps is null. pn=payPlugin
01-10 17:33:27.376 21273-21273/com.udd.travel I/RePlugin.ws000: loadLocked(): Initialized, is loaded = true
01-10 17:33:27.376 21273-21273/com.udd.travel D/RePlugin.ws001: PACM: bindActivity: activity not found
01-10 17:33:27.376 21273-21273/com.udd.travel I/Timeline: Timeline: Activity_launch_request id:com.udd.travel time:243439105
01-10 17:33:27.380 21273-24331/com.udd.travel W/Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
01-10 17:33:27.398 21273-21292/com.udd.travel I/art: Background sticky concurrent mark sweep GC freed 103033(5MB) AllocSpace objects, 35(568KB) LOS objects, 10% free, 46MB/52MB, paused 4.757ms total 158.751ms

**Comment by cundong** [comment]
增加该类型坑位数量。

通过Gradle配置
