### ISSUE TITLE
插件收到Notification通知，却不能跳转到插件相应的界面

### ISSUE THREAD

**Issue by harvey-ren** [Qihoo360/RePlugin#479]
#### 问题详细描述 Detailed description of the problem

插件收到Notification通知，却不能跳转到插件相应的界面

#### 复现问题步骤 Steps to reproduce the problem
1. 插件收到Notification通知
2. 点击通知，却不能跳转到插件相应的界面

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.2.1
rePlugin-plugin-lib/gradle Version:2.2.1

Android API Version：25
Android 手机型号&ROM(Phone model & ROM):小米note

**Comment by cundong** [comment]
一个DEMO ：
https://github.com/Qihoo360/RePlugin/pull/501

可以参照一下
