### ISSUE TITLE
引用库之后一直提示这个错误？如何解决？

### ISSUE THREAD

**Issue by hanxiaofeng** [Qihoo360/RePlugin#48]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:

**Android compile SDK version**:

**Android ROM**:

`
buildscript {
    repositories {
        jcenter()
        maven {
            url  "https://dl.bintray.com/qihoo360/replugin"
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'com.qihoo360.replugin:replugin-host-gradle:2.1.0'
    }
}

allprojects {
    repositories {
        jcenter()
        maven {
            url  "https://dl.bintray.com/qihoo360/replugin"
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}`

错误提示：

Error:Execution failed for task ':app:processDebugResources'.
> D:\xinshiyunProject\gitClone2\RePluginMainDemo\app\src\main\assets\plugins

**Comment by skygzs** [comment]
在 assets 下新建文件夹  plugins   就可以了

**Comment by wangyupeng1-iri** [comment]
I have made PR compatible with this scene

**Comment by jiongxuan** [comment]
您好，感谢回复！

我们RePlugin是支持“内置插件”的，目前360旗下所有接入RePlugin的应用均含有“内置插件”。但我们在开发Gradle插件时，可能没有考虑到“不带内置插件”的情况，导致出现这个问题。

@wangyupeng1-iri 兄已针对此问题做了修复。稍后我们会提交到Master上。预计在2.1.1版本（因为2.1.0已经送审）上解决。

现阶段还请按照 @skygzs 所述，新建一个plugins目录即可。感谢您的热心回复！

**Comment by wangyupeng1-iri** [comment]
The PR had been merged into the master master，thanks！ @hanxiaofeng @skygzs @jiongxuan
