### ISSUE TITLE
Replugin 的plugin-list.json文件

### ISSUE THREAD

**Issue by RichsJeson** [Qihoo360/RePlugin#480]
Replugin 的plugin-list.json文件是什么时候生成的，一直找不到生成的地方，这个文件里面有标注replugin插件是否是大插件。还有请问下，replugin是在哪个地方去验证插件是大插件？我看到地方是解包的时候验证插件是否超过2G

**Comment by cundong** [comment]
关于“大插件”的逻辑，可以从这个类开始看：https://github.com/Qihoo360/RePlugin/blob/639ef5f1c33b4a12736d090d9e349a699af07473/replugin-host-library/replugin-host-lib/src/main/java/com/qihoo360/loader2/PluginDesc.java

plugin-list.json文件，是host-gradle插件生成的，逻辑在：https://github.com/Qihoo360/RePlugin/tree/dev/replugin-host-gradle/src/main/groovy/com/qihoo360/replugin/gradle/host/creator/impl/json
