### ISSUE TITLE
跳转到插件Activity时，宿主的Activity的Label属性会强加给插件Activity

### ISSUE THREAD

**Issue by JasMSS** [Qihoo360/RePlugin#481]
**#问题描述#**
插件Activity的Label属性已经设置为“”，也就是空。但是当我从宿主Activity中启动该插件Activity的时候，插件Activity的toolbar标题栏，显示了宿主Application的Label。

**#问题解决方法#**
在插件Activity中手动修改Title为“"。

**#问题原因分析#**
当我从宿主Activity跳转到插件Activity时，宿主的App的Label属性会强加给插件App和Activity。

**#希望如何改正#**
宿主Activity的label等属性，不要影响到插件Activity的同名属性。

**Comment by SkyEric** [comment]
建议Activity不使用Label 属性，并且不展示标题栏，即requestWindowFeature(Window.FEATURE_NO_TITLE);
另外，可自定义TitleBar部分，如自定义Titlebar组件，各插件各自处理标题栏即可。
