### ISSUE TITLE
用Replugin启动插件Activity后，其中的NFC消息监听失效了

### ISSUE THREAD

**Issue by JasMSS** [Qihoo360/RePlugin#482]
#### 问题详细描述 Detailed description of the problem
插件app中需要监听NFC刷卡。 当单独调试时，NFC刷卡正常，当作为插件App时，NFC刷卡无效。无异常log。

#### 复现问题步骤 Steps to reproduce the problem
1.插件Activity中实现NFC刷卡监听的逻辑 
2. 从宿主中启动插件Activity

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.2.1
rePlugin-plugin-lib/gradle Version: 2.2.1

Android API Version：21
Android 手机型号&ROM(Phone model & ROM):  msm8909 & 5.1.1

#### Logcat上下文 Logcat context
无error级别日志，NFC刷卡日志较长-1300行，若有需要，请联系我，我给你发文件。
我的邮箱692646235@qq.com

**Comment by cundong** [comment]
NFC刷卡 ?

**Comment by JasMSS** [comment]
是的，就是一种<intent-filter>，可以监听NFC刷卡

**Comment by cundong** [comment]
你可以提供一个简单demo

**Comment by JasMSS** [comment]
这个需要能读NFC卡的安卓设备，普通手机不行，但还是简单发一下核心代码……   

下面是nfc监听的代码（kotlin）：
监听的acitivity
`    


    private var pi: PendingIntent? = null
    private var mNfcAdapter:NfcAdapter? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        //初始化NFC监听
        pi = PendingIntent.getActivity(this, 0, Intent(this, javaClass)
                .addFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP), 0)
        mNfcAdapter = NfcAdapter.getDefaultAdapter(this);
    }

    override fun onResume() {
        super.onResume()
        //启用NFC监听
        mNfcAdapter!!.enableForegroundDispatch(this, pi, null, null);
    }
    override fun onPause() {
        super.onPause()
       //禁用NFC监听
        mNfcAdapter!!.disableForegroundDispatch(this);
    }

    override fun onNewIntent(intent: Intent?) {
        super.onNewIntent(intent)
        if (NfcAdapter.ACTION_TAG_DISCOVERED.equals(intent!!.getAction())) {
             //检测到NFC刷卡
            processIntent(intent);
        }
    }
`  

下面是manifest.xml的相关内容：
` 


        <activity android:name=".ui.MainActivity"
            android:label="">
            <intent-filter>
                <action android:name="android.nfc.action.TAG_DISCOVERED" />
                <data android:mimeType="text/plain" />
            </intent-filter>
        </activity>
` 


群里有老哥说，他也遇到了类似NFC这种的“特殊intent-filter监听不到”的问题，
所以问题简单来说，就是对于类似NFC之类的特殊intent-filter，我要如何入手修改。

感谢大佬关注这个问题

**Comment by cundong** [comment]
要是我这边无法用正常手机复现的问题，我建议，你能否把你的问题，抽象成一个简单的demo？

比如，你提到的特殊intent-filter ？

**Comment by JasMSS** [comment]
emmm， 这一块我也是小白…… 不太懂哪些intent-filter能算是同类的intent，我喊下群里那个老哥来回答下吧。

**Comment by xiaojie-2016** [comment]
你说的intent-filter是这个吗？我的项目也需要nfc只不过还没接入插件化。。        
<activity android:name=".ui.shouyin.test.TestActivity">
            <intent-filter>
                <action android:name="android.nfc.action.TECH_DISCOVERED" />

                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>

            <meta-data
                android:name="android.nfc.action.TECH_DISCOVERED"
                android:resource="@xml/nfc_tech_filter" />
        </activity>    

<resources>
  <tech-list>
    <tech>android.nfc.tech.IsoDep</tech>
    <tech>android.nfc.tech.NfcA</tech>
    <tech>android.nfc.tech.NfcB</tech>
    <tech>android.nfc.tech.NfcF</tech>
    <tech>android.nfc.tech.NfcV</tech>
    <tech>android.nfc.tech.Ndef</tech>
    <tech>android.nfc.tech.NdefFormatable</tech>
    <tech>android.nfc.tech.MifareClassic</tech>
    <tech>android.nfc.tech.MifareUltralight</tech>
    </tech-list>
</resources>

**Comment by 13691525793** [comment]
已发一个简单的测试nfc的demo，请查收一下邮件。 @cundong

**Comment by xiazunyang** [comment]
请问这个问题解决了吗？我也遇到了相同的问题。

**Comment by cundong** [comment]
这个问题的原因就在于：

宿主 Gradle 插件，生成的Activity坑位，默认是不包含NFC所需要的标签的（如：intent-filter），所以，你的插件中NFC功能肯定就不能被系统识别了。

要解决这个问题，建议：

参考“在插件中实现微信分享”这个功能，在宿主中做一个类似 ProxyNFCActivity，注册在宿主中（当然，肯定是包含了NFC功能锁需要的一切标签），然后再这个Proxy Activity onCreate()的时候，调用RePlugin.startActivity，打开一个用于提供NFC具体实现逻辑的插件Activity。

换句话说，这个解决思路，就是：用宿主中 AndroidMainfest.xml 中支持NFC功能的Activity壳，但是具体实现逻辑在插件中。
