### ISSUE TITLE
插件theme中的：<item name="android:windowIsTranslucent">true</item>失效

### ISSUE THREAD

**Issue by T-mans** [Qihoo360/RePlugin#484]
#### 问题详细描述 Detailed description of the problem
我的插件的搜索activity使用的theme配置有背景透明，但是作为插件就无法正确的展现这个主题，背景变成了黑色。

#### 复现问题步骤 Steps to reproduce the problem
在小米，魅族，360，华为手机上均表现如此，应该是共性的东西
#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.1
rePlugin-plugin-lib/gradle Version:2.2.1

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 
小米4 MIUI8.5
小米5 MIUI8.1
360Q5Plus 安卓6.0.1
魅族 M6 Note 安卓7.1.2
#### Logcat上下文 Logcat context
所以我觉得这是一个普遍的问题吧，还是我对于插件的主题需要做设置？但是我在WIKI没有找到类似的设置。所以我能做什么吗？
Thanks

**Comment by cundong** [comment]
关于透明主题，请看这边：https://github.com/Qihoo360/RePlugin/wiki/FAQ

打开这个 Url，然后搜索 透明 。
