### ISSUE TITLE
使用react-native生成的APK无法被唤起

### ISSUE THREAD

**Issue by Xiemarc** [Qihoo360/RePlugin#487]
#### 问题详细描述 Detailed description of the problem
插件apk为react-native打包的apk。宿主为原生apk。一直唤起不了插件apk

#### 复现问题步骤 Steps to reproduce the problem
插件中：
1. react-native项目的MainApplication中的oncreate方法会中
        SoLoader.init(this, false);
   这行代码出错。
2. 如果改成SoLoader.init(RePlugin.getHostContext(),  false);
会报强制转换类型错误。

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.1.6
rePlugin-plugin-lib/gradle Version:2.1.6

Android API Version：4.4 和7.1
Android 手机型号&ROM(Phone model & ROM):  小米mix2  模拟器
出现问题：
1：
java.lang.RuntimeException: java.io.IOException: cannot mkdir: /data/data/com.cmos.customManagerApp/lib-main
2：同样会出现
could't find DSO to load:libreactnative jni.so。
这个问题也没解决。

想问下咱们360replugin框架对react-native框架的支持度

**Comment by a1018875550** [comment]
请问你解决了么，最近想要把项目中的RN部分拿出来用 插件化方式加载。所以同问咱们的replugin框架对react-native框架的支持度？谢谢

**Comment by boyrt** [comment]
我也有这么个需求啊，同问啊

**Comment by a1018875550** [comment]
@smartOf360 大佬求助

**Comment by Xiemarc** [comment]
@boyrt @a1018875550 @smartOf360 大佬们，求怎么解决

**Comment by bnotebook** [comment]
目前我们对RN不会做特殊的适配工作，插件化框架和RN本质上解决问题都有类似性，如果有该类需求可以自行修改框架进行适配。

**Comment by sunfengbiao** [comment]
此问题有俩种解决方案：第一修改replugin源码，处理classloader；第二 不修改源码，只需要在宿主的Application中处理 RePluginConfig.setUseHostClassIfNotFound(true) ,把所有的ReactNative资源都放到宿主中，插件compileOnly RN相关资源，达到所有插件共享宿主中一套RN相关资源的目的 ，此方法我已经验证通过。

**Comment by fupSZ** [comment]
@sunfengbiao 请问方案2，共享宿主中一套RN相关资源，是怎么解决资源id的问题，宿主和插件是分开编译的，虽然采用compileOnly 的方式，对于某个资源来说，其在宿主和插件 分别编译在R.java中生成的id是不一样的，拿插件的id 在宿主中找资源，不就会发生找错的情况
