### ISSUE TITLE
在4.x版本上启动插件activity屏幕会90度旋转

### ISSUE THREAD

**Issue by guofucheng** [Qihoo360/RePlugin#488]
#### 问题详细描述 Detailed description of the problem
在4.x版本上启动插件activity屏幕会90度旋转

#### 复现问题步骤 Steps to reproduce the problem
1. 在Freescale 主板上运行宿主程序
2. 在宿主上安装插件并打开

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.1
rePlugin-plugin-lib/gradle Version:2.2.1

Android API Version：19
Android 手机型号&ROM(Phone model & ROM): Freescale Android4.4.2

**Comment by cundong** [comment]
Freescale 主板 ？

**Comment by cundong** [comment]
这种 **Freescale 主板**（不知道是个什么） 适配问题，可以在代码中强制社祝竖屏
