### ISSUE TITLE
关于启动外置插件问题

### ISSUE THREAD

**Issue by luoxiaohui** [Qihoo360/RePlugin#489]
#### 问题详细描述 Detailed description of the problem
我公司项目工程宿主能加载内置插件，但按照demo方式，模拟加载外置插件却不行，RePlugin.startActivity()提示找不到插件，为什么我宿主需要加载两次插件，然后杀掉进程，再加载插件才可以加载成功。而我另外新建工程宿主也能加载外置插件。会有哪些原因会造成这种问题？

#### 复现问题步骤 Steps to reproduce the problem
1. 新建工程生成一个replugin插件A
2. 新建工程生成一个replugin宿主项目，此时能正常加载内置和外置的插件A
3. 让我公司项目成为replugin宿主项目，此时只能加载内置插件A，加载外置插件时，需要重启两次app，然后杀掉进程，再次重启，才可以成功加载外置插件。对照了好几次，配置都是一样的，我Application没继承RepluginApplication，但在application的onCreate()中也把RePlugin.App.onCreate();放在super.onCreate()之后的最前面，现在真不知道出现什么问题，特来求救。

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context
01-24 10:03:36.198 14948-14948/com.financeyun.maizi V/BoostFramework: mAcquireFunc method = public int com.qualcomm.qti.Performance.perfLockAcquire(int,int[])
01-24 10:03:36.199 14948-14948/com.financeyun.maizi V/BoostFramework: mReleaseFunc method = public int com.qualcomm.qti.Performance.perfLockRelease()
01-24 10:03:36.199 14948-14948/com.financeyun.maizi V/BoostFramework: mAcquireTouchFunc method = public int com.qualcomm.qti.Performance.perfLockAcquireTouch(android.view.MotionEvent,android.util.DisplayMetrics,int,int[])
01-24 10:03:36.199 14948-14948/com.financeyun.maizi V/BoostFramework: mIOPStart method = public int com.qualcomm.qti.Performance.perfIOPrefetchStart(int,java.lang.String)
01-24 10:03:36.199 14948-14948/com.financeyun.maizi V/BoostFramework: mIOPStop method = public int com.qualcomm.qti.Performance.perfIOPrefetchStop()
01-24 10:03:36.203 14948-14948/com.financeyun.maizi V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@e8b060
01-24 10:03:36.203 14948-14948/com.financeyun.maizi V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@3108919
01-24 10:03:37.241 14948-14948/com.financeyun.maizi E/SplashActivity: 1
01-24 10:03:37.242 14948-14948/com.financeyun.maizi E/SplashActivity: 2
01-24 10:03:37.357 14948-14948/com.financeyun.maizi D/RePlugin.ws001: MP.pluginDownloaded ... path=/data/user/0/com.financeyun.maizi/files/guide.apk
01-24 10:03:37.421 14948-14948/com.financeyun.maizi D/RePlugin.ws001: sendIntent pr=com.financeyun.maizi intent=Intent { act=ACTION_NEW_PLUGIN (has extras) }
01-24 10:03:37.423 14948-14948/com.financeyun.maizi D/RePlugin.ws001: update plugin table: info=PInfo { <com.financeyun.maizi.guide:1(4)> [APK] processes=[] js={"pkgname":"com.financeyun.maizi.guide","name":"com.financeyun.maizi.guide","low":10,"high":10,"ver":1,"verv":2814792716779521,"path":"\/data\/user\/0\/com.financeyun.maizi\/app_p_a\/1933822396.jar","type":11,"frm_ver":4} dex=/data/user/0/com.financeyun.maizi/app_p_od/1933822396.dex nlib=/data/user/0/com.financeyun.maizi/app_p_n/1933822396 }
01-24 10:03:37.424 14948-14948/com.financeyun.maizi D/RePlugin.ws001: insert new plugin: info=PInfo { <com.financeyun.maizi.guide:1(4)> [APK] processes=[] js={"pkgname":"com.financeyun.maizi.guide","name":"com.financeyun.maizi.guide","low":10,"high":10,"ver":1,"verv":2814792716779521,"path":"\/data\/user\/0\/com.financeyun.maizi\/app_p_a\/1933822396.jar","type":11,"frm_ver":4} dex=/data/user/0/com.financeyun.maizi/app_p_od/1933822396.dex nlib=/data/user/0/com.financeyun.maizi/app_p_n/1933822396 }
01-24 10:03:37.424 14948-14948/com.financeyun.maizi D/RePlugin.ws001: insert new plugin: ok: plugin=PInfo { <com.financeyun.maizi.guide:1(4)> [APK] processes=[] js={"pkgname":"com.financeyun.maizi.guide","name":"com.financeyun.maizi.guide","low":10,"high":10,"ver":1,"verv":2814792716779521,"path":"\/data\/user\/0\/com.financeyun.maizi\/app_p_a\/1933822396.jar","type":11,"frm_ver":4} dex=/data/user/0/com.financeyun.maizi/app_p_od/1933822396.dex nlib=/data/user/0/com.financeyun.maizi/app_p_n/1933822396 }
01-24 10:03:37.424 14948-14948/com.financeyun.maizi D/RePlugin.ws001: PStatusC.setStatus(): Status is OK, Clear. pn=com.financeyun.maizi.guide; ver=1
01-24 10:03:37.427 14948-14948/com.financeyun.maizi I/ws001: p.m. n p f n=com.financeyun.maizi.guide b1=false b2=false
01-24 10:03:37.428 14948-14948/com.financeyun.maizi E/SplashActivity: 3
01-24 10:03:37.428 14948-14948/com.financeyun.maizi E/SplashActivity: 4
01-24 10:03:37.428 14948-14948/com.financeyun.maizi D/RePlugin.ws001: start activity: intent=Intent { cmp=com.financeyun.maizi.guide/.GuideActivity } plugin=com.financeyun.maizi.guide activity=com.financeyun.maizi.guide.GuideActivity process=-2147483648
01-24 10:03:37.428 14948-14948/com.financeyun.maizi D/RePlugin.ws001: start activity: intent=Intent { cmp=com.financeyun.maizi.guide/.GuideActivity } plugin=com.financeyun.maizi.guide activity=com.financeyun.maizi.guide.GuideActivity process=-2147483648 download=true
01-24 10:03:37.428 14948-14948/com.financeyun.maizi D/RePlugin.loadClass: isHookingClass(com.financeyun.maizi.guide , com.financeyun.maizi.guide.GuideActivity) = false
01-24 10:03:37.429 14948-14948/com.financeyun.maizi D/RePlugin.ws001: PStatusC.getStatus(): ps is null. pn=com.financeyun.maizi.guide
01-24 10:03:37.429 14948-14948/com.financeyun.maizi D/PluginDesc: load(): Change, Ready to load
01-24 10:03:37.430 14948-14948/com.financeyun.maizi I/PackageFilesUtil: plugins-list.json in files directory not found, skip.
01-24 10:03:37.430 14948-14948/com.financeyun.maizi D/RePlugin.ws001: PStatusC.getStatus(): ps is null. pn=com.financeyun.maizi.guide
01-24 10:03:37.431 14948-14948/com.financeyun.maizi I/RePlugin.ws001: loadLocked(): Ready to lock! logtag = try1; pn = com.financeyun.maizi.guide
01-24 10:03:37.432 14948-14948/com.financeyun.maizi W/asset: Asset path /data/user/0/com.financeyun.maizi/app_p_a/1933822396.jar is neither a directory nor file (type=1).
01-24 10:03:37.433 14948-14948/com.financeyun.maizi D/RePlugin.ws001: get package archive info null
01-24 10:03:37.433 14948-14948/com.financeyun.maizi I/RePlugin.ws001: load /data/user/0/com.financeyun.maizi/app_p_a/1933822396.jar 137947785 c=3 rc=false delta=2
01-24 10:03:37.433 14948-14948/com.financeyun.maizi I/RePlugin.ws001: loadLocked(): Unlock! logtag = try1; pn = com.financeyun.maizi.guide
01-24 10:03:37.433 14948-14948/com.financeyun.maizi E/ws001: try1: loading fail1
01-24 10:03:37.434 14948-14948/com.financeyun.maizi W/asset: Asset path /data/user/0/com.financeyun.maizi/app_p_a/1933822396.jar is neither a directory nor file (type=1).
01-24 10:03:37.434 14948-14948/com.financeyun.maizi D/RePlugin.ws001: get package archive info null
01-24 10:03:37.434 14948-14948/com.financeyun.maizi I/RePlugin.ws001: load2 /data/user/0/com.financeyun.maizi/app_p_a/1933822396.jar 137947785 c=3 rc=false delta=1
01-24 10:03:37.434 14948-14948/com.financeyun.maizi E/ws001: try2: loading fail2
01-24 10:03:37.435 14948-14948/com.financeyun.maizi E/ws001: pmb.lp: f to l. lt=3; i=PInfo { <com.financeyun.maizi.guide:1(4)> [APK] processes=[] js={"pkgname":"com.financeyun.maizi.guide","name":"com.financeyun.maizi.guide","low":10,"high":10,"ver":1,"verv":2814792716779521,"path":"\/data\/user\/0\/com.financeyun.maizi\/app_p_a\/1933822396.jar","type":11,"frm_ver":4} dex=/data/user/0/com.financeyun.maizi/app_p_od/1933822396.dex nlib=/data/user/0/com.financeyun.maizi/app_p_n/1933822396 }
01-24 10:03:37.436 14948-14948/com.financeyun.maizi D/RePlugin.ws001: PACM: bindActivity: may be invalid plugin name or load plugin failed: plugin=null
01-24 10:03:37.436 14948-14948/com.financeyun.maizi D/RePlugin.ws001: PACM: bindActivity: activity not found
01-24 10:03:37.436 14948-14948/com.financeyun.maizi D/RePlugin.ws001: plugin cn not found: intent=Intent { cmp=com.financeyun.maizi.guide/.GuideActivity } plugin=com.financeyun.maizi.guide activity=com.financeyun.maizi.guide.GuideActivity process=-2147483648

**Comment by cundong** [comment]
可以在我们的host中直接试

**Comment by cundong** [comment]
@luoxiaohui  确认下，是否 Android 6.0 后， 没有动态申请权限？

**Comment by luoxiaohui** [comment]
@cundong @SkyEric 确认申请了动态权限，在我项目的MainActivity里是可以使用外置插件的，我现在想做到的是，从Splash页面->导航页面->MainActivity，而导航页面用外置插件，这里却不行。

**Comment by cundong** [comment]
可以提供一个简单的demo 出来么，
