### ISSUE TITLE
将已有工程做为插件，启动后报错，无法加载插件中的so库

### ISSUE THREAD

**Issue by qinyang1018** [Qihoo360/RePlugin#49]
![image](https://user-images.githubusercontent.com/15726024/27767270-f31449c0-5f23-11e7-8027-4f8a0c0b327f.png)

**Comment by jiongxuan** [comment]
您好，从Logcat的描述上来看，应该是SO库的“32/64位”混用导致。

简单来说，如果您的主程序被运行在64位手机上，则插件内的SO也务必是64位的（这和插件化框架无关，是系统行为），因为Android系统不允许在一个进程内混用32/64位（毕竟Zygote64进程和Zygote不一样）。

如果您要解决这个问题，可以有两种办法：

* 将每个插件内的SO库同时放入32和64位
这样两种位数的手机均可支持，且充分发挥各自的优势
* 主程序内“任意添加”一个32位的SO，但不添加64位的
这样系统在安装主程序时，会默认其为“32位兼容程序”。最终的效果是：插件和宿主同时在32位APK中运行，自然不会出现这个问题了。目前360手机卫士、手机助手、影视大全等产品就是这么做的

以上仅供您参考。另外此“经典问题”我会放到FAQ中，供后面的人参考。

**Comment by qinyang1018** [comment]
很感谢你的回答。
插件作为apk单独运行在相同手机是没问题的。

**Comment by jiongxuan** [comment]
嗯，不客气

**Comment by xiaoli-style** [comment]
@jiongxuan 你好，请问下插件如何调用宿主so库？

**Comment by flycumt** [comment]
请问，只支持64位，插件内和宿主内必须各放一份64位的so吗，我试了如果只在宿主中放64的so, 插件中不放任何so，则运行时插件中会报找不到so的错误，且错误信息是：/data/user/0/com.xxxx.xxx/app_plugins_v3_libs/plugin-home-10-10-1, /system/lib, /vendor/lib]]] couldn't find "libiconv.so"
