### ISSUE TITLE
app作为插件被加载：Activity透明主题失效。

### ISSUE THREAD

**Issue by T-mans** [Qihoo360/RePlugin#492]
问题详细描述 Detailed description of the problem
公司项目全部使用了继承AppCompatActivity的activity，这是针对搜索界面的半透明的配置
`<style name="SearchTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:windowBackground">@color/transparent</item>
        <item name="android:windowIsTranslucent">true</item>
        <item name="android:backgroundDimEnabled">true</item>
        <item name="android:windowSoftInputMode">stateVisible|adjustNothing</item>
        <item name="android:windowFullscreen">true</item>
    </style>`
作为独立的app运行的时候，这个界面是正常的，但是作为插件window的颜色变成了黑色。
尝试修改theme配置,对android:windowBackground不再使用透明色，改用黄色
`<style name="SearchTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:windowBackground">@color/yellow</item>
        <item name="android:windowIsTranslucent">true</item>
        <item name="android:backgroundDimEnabled">true</item>
        <item name="android:windowSoftInputMode">stateVisible|adjustNothing</item>
        <item name="android:windowFullscreen">true</item>
    </style>`
作为单独的app或者作为插件均能正常显示黄色。测试其他非透明颜色结果也是正常的。
所以我猜测;作为插件运行，是不是对于window的alpha支持无效。
所以我在activity的onCreate方法，设置window的alpha属性
@override
protected void onCreate(@nullable Bundle savedInstanceState) {
WindowManager.LayoutParams attributes = getWindow().getAttributes();
attributes.alpha = 0.0f;
getWindow().setAttributes(attributes);
｝
作为单独的app运行，可以正常的看到alpha效果，但是作为插件的时候，背景再次变为全黑色。

所以：这个是不是插件化加载之后的一个bug？

复现问题步骤 Steps to reproduce the problem
测试了小米，魅族，中兴，华为多个品牌，覆盖安卓4.2-7.0均有这个问题

其它重要信息 Other important information
replugin-host-lib/gradle Version:2.2.2
rePlugin-plugin-lib/gradle Version:2.2.2

Android API Version：4.2-7.0
Android 手机型号&ROM(Phone model & ROM): 小米，华为，360

**Comment by T-mans** [comment]
追加测试了不使用AppCompat下的主题，改用Theme.Translucent.NoTitleBar.Fullscreen。最终的结果仍然是：插件app单独运营正常，但是作为插件被加载运行，则窗体window表现为黑色。

所以这个是不是RePlugin的一个bug？360的大大请看看。

thanks.

**Comment by cundong** [comment]
您好。

https://github.com/Qihoo360/RePlugin/wiki/FAQ 中对透明主题使用有过说明。

如果要使用透明样式，插件 manifest 中必须声明为以下四种主题之一：
/**
     * 手动判断主题是否是透明主题
     */
    public static boolean isTranslucentTheme(int theme) {
        return theme == android.R.style.Theme_Translucent
                || theme == android.R.style.Theme_Dialog
                || theme == android.R.style.Theme_Translucent_NoTitleBar
                || theme == android.R.style.Theme_Translucent_NoTitleBar_Fullscreen;
    }

**Comment by jianiuqi** [comment]
可参考解决方式：
步骤1.将AndroidMainifest.xml的Activity主题设置为android.R.style.Theme_Translucent、 android.R.style.Theme_Dialog、android.R.style.Theme_Translucent_NoTitleBar、android.R.style.Theme_Translucent_NoTitleBar_Fullscreen这四个主题之一，这是官方要求的透明样式。
步骤2：在Activity代码中设置自定义的theme
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setTheme(R.style.Custom_Translucent_Theme); // Set here
    setContentView(...)
}

**Comment by 15130140362** [comment]
是用了上面的四种主题，还是不能透明啊

**Comment by 15130140362** [comment]
不能继承上面的四个透明主题，需要直接使用上面的透明主题，才可以
