### ISSUE TITLE
so文件路径的获取方法

### ISSUE THREAD

**Issue by LeungHL** [Qihoo360/RePlugin#493]
如题, 没看到相关的api, wiki只找到如下说明:
外置插件>> Native存放路径：主程序路径/app_p_n
内置插件>> Native存放路径：主程序路径/app_plugin_v3_libs
实测对照过这两个路径下还有插件名和版本号组成的子目录, 再下一级才是插件的so文件, 我想知道如何获取插件的so文件的绝对路径.

**Comment by cundong** [comment]
在这里：

com.qihoo360.replugin.model.PluginInfo

getNativeLibsDir()方法。
