### ISSUE TITLE
先给来一些预热文章解解馋

### ISSUE THREAD

**Issue by wzfyang** [Qihoo360/RePlugin#5]
大牛们先给来点RePlugin的干货文章吧，或者原理的，或者开发经历之类的，让大家解解馋，太期待啦

**Comment by CreateChance** [comment]
文章近期会退出哦，敬请期待哈～～

**Comment by jiongxuan** [comment]
这个很快就有了。我们近期会在InfoQ上发表一篇文章，介绍下RePlugin的一些原理。到时候会有链接给到您们。
感谢您对RePlugin的关注。

**Comment by wzfyang** [comment]
感谢感谢

**Comment by jiongxuan** [comment]
号外！RePlugin已经开源，欢迎阅览，提出指正建议。
