### ISSUE TITLE
内置插件加载的时候别名是有的，但是变成外置插件加载的时候别名就没了，从而导致用别名打开插件无反应

### ISSUE THREAD

**Issue by lphgithub** [Qihoo360/RePlugin#500]
#### 复现问题步骤 Steps to reproduce the problem
1. 先内置在assets/plugins下面，然后打开后，debug跟踪，发现PmBase类里面
 private void putPluginObject(PluginInfo info, Plugin plugin)方法 的值为
PInfo { <cairh-rec-ydbs:1(4)> [BUILTIN] processes=[] js={"pkgname":"com.cairh.app.plugin.rec.ydbs","ali":"cairh-rec-ydbs","name":"cairh-rec-ydbs","low":10,"high":10,"ver":1,"verv":2814792716779521,"path":"plugins\/cairh-rec-ydbs.jar","type":2,"frm_ver":4} dex=/data/user/0/com.cairh.app/app_plugins_v3_odex/cairh-rec-ydbs-10-10-1.dex nlib=/data/user/0/com.cairh.app/app_plugins_v3_libs/cairh-rec-ydbs-10-10-1 }
2.将内置插件删除掉，重新安装apk，将外置插件放到SDcard中，后缀改为.apk，在进入应用的时候
  PluginInfo ydbsPlugin = RePlugin.install("/sdcard/cairh-rec-ydbs.apk");
                    if (ydbsPlugin != null) {
                        RePlugin.preload(ydbsPlugin);
                    }
然后debug跟踪发现
com.qihoo360.loader2.Plugin@a76f3db {info=PInfo { <com.cairh.app.plugin.rec.ydbs:1(4)> [APK] processes=[] js={"pkgname":"com.cairh.app.plugin.rec.ydbs","name":"com.cairh.app.plugin.rec.ydbs","low":10,"high":10,"ver":1,"verv":2814792716779521,"path":"\/data\/user\/0\/com.cairh.app\/app_p_a\/-1210962601.jar","type":11,"frm_ver":4} dex=/data/user/0/com.cairh.app/app_p_od/-1210962601.dex nlib=/data/user/0/com.cairh.app/app_p_n/-1210962601 }}

字段,"ali" 没有了，导致使用别名打开插件的时候失败
replugin-host-lib/gradle 2.2.2:
rePlugin-plugin-lib/gradle 2.2.2:

Android API Version：24
Android 手机型号&ROM(Phone model & ROM): 
huawei nxt-al10 7.0
#### Logcat上下文 Logcat context
: p.m. n p f n=com.cairh.app.plugin.rec.ydbs b1=false b2=false
02-06 10:29:17.649 11742-11742/com.cairh.app I/RePlugin.ws001: loadLocked(): Ready to lock! logtag = try1; pn = com.cairh.app.plugin.rec.ydbs
02-06 10:29:17.683 11742-11747/com.cairh.app I/art: Do full code cache collection, code=109KB, data=118KB
02-06 10:29:17.684 11742-11747/com.cairh.app I/art: After code cache collection, code=92KB, data=78KB
02-06 10:29:17.788 11742-11742/com.cairh.app I/dex: load /data/user/0/com.cairh.app/app_p_a/-1210962601.jar ...
02-06 10:29:24.224 11742-11742/com.cairh.app I/dex: load /data/user/0/com.cairh.app/app_p_a/-1210962601.jar = com.qihoo360.replugin.PluginDexClassLoader[DexPathList[[zip file "/data/user/0/com.cairh.app/app_p_a/-1210962601.jar"],nativeLibraryDirectories=[/data/user/0/com.cairh.app/app_p_n/-1210962601, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]]
02-06 10:29:24.230 11742-11742/com.cairh.app I/RePlugin.PluginInfoUpdater: onReceiveUpdateInfo: in=Intent { act=com.qihoo360.replugin.pms.ACTION_UPDATE_INFO (has extras) }
02-06 10:29:24.231 11742-11742/com.cairh.app I/RePlugin.PluginInfoUpdater: onReceiveUpdateInfo: pn=com.cairh.app.plugin.rec.ydbs; setIsUsed=true
02-06 10:29:24.232 11742-11742/com.cairh.app I/RePlugin.ws001: load /data/user/0/com.cairh.app/app_p_a/-1210962601.jar 27888994 c=2 rc=true delta=6582
02-06 10:29:24.233 11742-11742/com.cairh.app I/RePlugin.ws001: loadLocked(): Unlock! logtag = try1; pn = com.cairh.app.plugin.rec.ydbs
02-06 10:29:24.241 11742-11742/com.cairh.app I/RePlugin.PluginFastInstallPr: install: Install. pi=PInfo { <com.cairh.app.plugin.rec.ydbs:1(4)> [APK] [DEX_EXTRACTED] [RUNNING] processes=[com.cairh.app] js={"pkgname":"com.cairh.app.plugin.rec.ydbs","name":"com.cairh.app.plugin.rec.ydbs","low":10,"high":10,"ver":1,"verv":2814792716779521,"path":"\/data\/user\/0\/com.cairh.app\/app_p_a\/-1210962601.jar","type":11,"frm_ver":4} dex=/data/user/0/com.cairh.app/app_p_od/-1210962601.dex nlib=/data/user/0/com.cairh.app/app_p_n/-1210962601 }; result=1
02-06 10:29:24.242 11742-11742/com.cairh.app I/Choreographer: Skipped 6523 frames!  The application may be doing too much work on its main thread.

**Comment by cundong** [comment]
参照demo2

外置插件，想设置别名，需要配置：
<meta-data
            android:name="com.qihoo360.plugin.name"
            android:value="demo2" />
