### ISSUE TITLE
插件中使用notifcation崩溃

### ISSUE THREAD

**Issue by bxjxxyy** [Qihoo360/RePlugin#502]
#### 问题详细描述 Detailed description of the problem
插件程序是一个腾讯云通信的demo，里面用到了推送以及通知栏消息提醒。启动插件时报错如下

#### 复现问题步骤 Steps to reproduce the problem
1. 宿主程序启动插件程序，然后就崩溃

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.2
rePlugin-plugin-lib/gradle Version:2.2.2

#### Logcat上下文 Logcat context
android.app.RemoteServiceException: Bad notification posted from package com.test.demo: Couldn't create icon: StatusBarIcon(pkg=com.test.demo=0 id=0x7f030001 level=0 visible=true num=0 )
02-06 14:49:11.260 12633-12633/com.test.demo I/System.out:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
02-06 14:49:11.260 12633-12633/com.test.demo I/System.out:     at android.os.Handler.dispatchMessage(Handler.java:102)
02-06 14:49:11.260 12633-12633/com.test.demo I/System.out:     at android.os.Looper.loop(Looper.java:136)
02-06 14:49:11.260 12633-12633/com.test.demo I/System.out:     at android.app.ActivityThread.main(ActivityThread.java:5113)
02-06 14:49:11.260 12633-12633/com.test.demo I/System.out:     at java.lang.reflect.Method.invokeNative(Native Method)
02-06 14:49:11.260 12633-12633/com.test.demo I/System.out:     at java.lang.reflect.Method.invoke(Method.java:515)
02-06 14:49:11.260 12633-12633/com.test.demo I/System.out:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:780)
02-06 14:49:11.260 12633-12633/com.test.demo I/System.out:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:596)
02-06 14:49:11.260 12633-12633/com.test.demo I/System.out:     at dalvik.system.NativeStart.main(Native Method)

**Comment by SkyEric** [comment]
首先确认下插件弹通知时是否用到宿主的icon资源，若用到需显式的keep，另外确认下插件内Context的使用有没有问题。具体可参考issues#479

**Comment by bxjxxyy** [comment]
没有用到宿主资源

**Comment by hackerAvengers** [comment]
请问大佬们这个问题解决了没有？我也遇到相同的问题了

**Comment by 15130140362** [comment]
+1我也遇到这个问题了，有解决办法吗
