### ISSUE TITLE
ActivityLifecycleCallbacks 没有回调

### ISSUE THREAD

**Issue by Whoisurdady** [Qihoo360/RePlugin#509]
#### 问题详细描述 Detailed description of the problem
插件Application中，注册ActivityLifceCirlceCallbacks
mApplication.registerActivityLifecycleCallbacks
在Activity启动后，没有对应的回调

#### 复现问题步骤 Steps to reproduce the problem
1. 启动插件activity，没有对应的回调

**Comment by wogenhaosini** [comment]
插件中「Application」的 「ActivityLifecycleCallbacks」回调，请使用 「Host 宿主」的「Application」进行注册，即可正常拿到回调。
