### ISSUE TITLE
无法启动activity-alias指定的Activity

### ISSUE THREAD

**Issue by gam2046** [Qihoo360/RePlugin#514]
#### 问题详细描述 Detailed description of the problem
插件中，在AndroidManifest.xml通过activity-alias为一个Activity指定别名，宿主程序无法启动这个别名Activity（直接指定原来的Activity名称可启动）

#### 复现问题步骤 Steps to reproduce the problem
0.  在插件AndroidManifest.xml申明 
```
<activity-alias
            android:name="com.example.A"
            android:targetActivity="com.example.B"/>
```
1.  通过`RePlugin.fetchPackageInfo("package name").activities` 可以确认别名的Activity(com.example.A)是存在的，并且targetActiviry属性(指向com.example.B)是正确的
2. 但是通过这个别名的Activity无法启动，启动的代码：`RePlugin.startActivity(context, RePlugin.createIntent(pluginNameOrPackageName, activityClassName))`

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.1
rePlugin-plugin-lib/gradle Version:2.2.1

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by cundong** [comment]
不支持 activity-alias
