### ISSUE TITLE
宿主程序切换wifi开关GuardService被ActivityManager杀死

### ISSUE THREAD

**Issue by zxm8241213zxm** [Qihoo360/RePlugin#515]
#### 问题详细描述 Detailed description of the problem
华为Al00 Android 6.0

#### 复现问题步骤 Steps to reproduce the problem
1. 宿主接入replugin2.2.4
2. 启动应用程序。
应用启动后检测GuardService存活状态：存活。
3.关闭wifi开关。
检测GuardService存活状态：DEAD！！。

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.2.4
rePlugin-plugin-lib/gradle Version: 2.2.4

Android API Version：6.0
Android 手机型号&ROM(Phone model & ROM): 华为AL00

**Comment by cundong** [comment]
先确认一下，这个 “:GuardService” 进程，是个空进程吗？
有没有servcie运行在这个进程下？

**Comment by zxm8241213zxm** [comment]
:GuardService进程是replugin默认的。我这边没有添加任何东西进入这个进程。程序一启动。切换wifi开关:GuardService进程就挂了

**Comment by zxm8241213zxm** [comment]
@cundong :GuardService进程是replugin默认的。我这边没有添加任何东西进入这个进程。程序一启动。切换wifi开关:GuardService进程就挂了

**Comment by cundong** [comment]
空进程当然被杀的可能性极大了，这是系统原因。

可以参考我们的文档，我们的初衷，是用你们APP的现有常驻进程来承载这个 “:GuardService” 进程。
如果你们的APP是单进程模型，那么可以参照文档，把RePlugin修改为单进程模型。

**Comment by zxm8241213zxm** [comment]
@cundong 问题是我的手机连着电脑debug，进程除非强杀，系统基本不会强制回收的呀。    只要切换wifi开关进程就自动挂死，然后又会被拉起。进程id就会发生变化~
