### ISSUE TITLE
Android 9.0将禁止非SDK接口的使用，是否会影响到Replugin

### ISSUE THREAD

**Issue by leojiang** [Qihoo360/RePlugin#516]
最近google官方已经透露了一些消息，将在9.0禁止非SDK接口的使用，不能在使用反射的方式去访问一些没有在SDK中暴露的方法和成员，那么Replugin中对于classloader的hook是否会受到影响？

附上链接 
https://android-developers.googleblog.com/2018/02/improving-stability-by-reducing-usage.html
翻译版本：
https://mp.weixin.qq.com/s/gICH9osyIzz9WerXO1C_8g

**Comment by lijunjieone** [comment]
同问

**Comment by liyanlei666** [comment]
同问

**Comment by chenlongkk** [comment]
![deepinscreenshot_select-area_20180309155940](https://user-images.githubusercontent.com/11960505/37196745-f64eebd2-23b2-11e8-9d79-6bf676f5ebd6.png)
在9.0的模拟器上试了一下反射拿ContextWrapper的mBase变量，已经有警告了。

**Comment by Visualrainy** [comment]
同问

**Comment by TheoTian** [comment]
hook非SDK API都是将是不安全的，利用该原理实现的方案都将受到影响，包括VisualApp这些
https://developer.android.com/preview/restrictions-non-sdk-interfaces.html

**Comment by williamsim** [comment]
肯定有影响的，这是一个非常不好的消息

**Comment by Tan-Tshunglee** [comment]
难道是官方要出一个插件方案吗？

**Comment by chinacuizichao** [comment]
同样关心这个问题

**Comment by thinkhy** [comment]
类似的问题 #580

**Comment by Visualrainy** [comment]
classloader应该是属于light gray list，应该只是提示warning

**Comment by bnotebook** [comment]
replugin已经完全适配了Android p(9.0)，更新框架到最新版本即可。
