### ISSUE TITLE
什么时候会彻底开源啊==

### ISSUE THREAD

**Issue by GHYOWEE** [Qihoo360/RePlugin#52]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:

**Android compile SDK version**:

**Android ROM**:

**Comment by jiongxuan** [comment]
早在6月30日就已经“彻底开源”了。您现在看到的就是完整的源代码。

谢谢关注。
