### ISSUE TITLE
捕获的异常如何确定是插件里调用崩溃还是宿主的？

### ISSUE THREAD

**Issue by walksin** [Qihoo360/RePlugin#521]
#### 问题详细描述 Detailed description of the problem
Thread.setDefaultUncaughtExceptionHandler(handler)

在回调 void uncaughtException(Thread t, Throwable e); 中 handler 会接收到全部的崩溃，无法区分

#### 复现问题步骤 Steps to reproduce the problem
1、插件启动的时候 Application  onCreate 设置 Thread.setDefaultUncaughtExceptionHandler(handler)
2、在宿主制造一个崩溃
3、插件的 UncaughtExceptionHandler 收到了改崩溃

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.2.4
rePlugin-plugin-lib/gradle Version: 2.2.4

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by cundong** [comment]
你好，

可以通过混淆配置，来区分的。

参考：
https://github.com/Qihoo360/RePlugin/blob/dev/replugin-sample/plugin/plugin-demo1/app/proguard-rules.pro

自己造一个崩溃你就全懂了。
