### ISSUE TITLE
启动插件Activity黑屏 ，切换后台在切回来就正常了

### ISSUE THREAD

**Issue by devisz** [Qihoo360/RePlugin#523]
#### 问题详细描述 Detailed description of the problem
插件内部A activity 启动B Activity，启动后B Activity黑了，前后台切换后B activity就正常展示了

**Comment by jamin918** [comment]
遇到同样的问题，怎么没有回复就关闭了这个问题呢？？

**Comment by lookingforwt** [comment]
很多issue管理者二话不说直接close，去用鹅厂开源的shadow吧

**Comment by ftyan805614** [comment]
> 遇到同样的问题，怎么没有回复就关闭了这个问题呢？？

跳转的时候activity不能加动画
