### ISSUE TITLE
Replugin 卸载插件，恒为false

### ISSUE THREAD

**Issue by shenpeibao** [Qihoo360/RePlugin#525]
#### 问题详细描述 Detailed description of the problem
1 、 RePlugin.install 安装apk
2、  RePlugin.startActivity  启动插件
3、  插件关闭，返回到宿主APP
4、 宿主执行  RePlugin.uninstall ，期望插件apk已卸载

5.   期望返回 true，但是一直都是flase

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.2.4
rePlugin-plugin-lib/gradle Version: 2.2.4
 
Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by cundong** [comment]
建议 阅读下代码：com.qihoo360.replugin.packages.PluginManagerServer

**卸载插件逻辑：**

先判断插件是否正在运行？

**是：**记录“卸载状态”，推迟到到常驻进程重启的时执行卸载，此时返回 false(因为本次只记录了状态，并没有真正卸载)

**否：**直接卸载，此时返回 true

**Comment by shenpeibao** [comment]
你的意思是只要 RePlugin.startActivity 启动过插件，RePlugin.uninstall就返回false吗？为什么不把插件的运行状态逻辑 放在RePlugin.uninstall中判断，如果插件正在运行，先停止，再卸载？你这样设置卸载逻辑的应用场景是什么？

**Comment by shenpeibao** [comment]
插件只要判定为running，如果宿主进程不死，uninstall一直为false
