### ISSUE TITLE
集成百度语音合成报错

### ISSUE THREAD

**Issue by wx2013** [Qihoo360/RePlugin#526]
#### 问题详细描述 Detailed description of the problem
不采用插件模式的话(即不使用replugin,单独的作为一个普通的 APP),测试没问题
集成百度语音合成后,在离线模式下不能进行语音合成,在线没有问题
集成后离线语音合成显示如下错误
(-102)(-102)offline engine download license failure[(-1)appCode=1809625--licensePath=/data/data/ 包名/files/plugins_v3_data/包名/files/baidu_tts_license]

未集成的没有如上错误,一切正常

怀疑问题:
1.是否内部更改了插件包名
2.是否写入文件失败
#### 复现问题步骤 Steps to reproduce the problem
1. 集成百度语音合成
2. 联网进行语音合成发现没问题
3.关闭网络或将网络速度进行限制

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.4
rePlugin-plugin-lib/gradle Version:2.2.4

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by wx2013** [comment]
已经解决
百度听书传递 context 的时候,需要传递宿主的(gethotscontext),不能用 this

**Comment by aifengshen** [comment]
兄弟，留个联系方式。
