### ISSUE TITLE
关于填坑的建议

### ISSUE THREAD

**Issue by ttlinux** [Qihoo360/RePlugin#539]
#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context
建议在填坑的时候，activity有横屏的坑。

**Comment by cundong** [comment]
现在暂时不会增加横屏的坑位，因为坑位的增加会导致AndroidMainfext.xml的膨胀，进而诱发 Binder 1M 缓存用尽的问题。

如果您的应用有该需求，建议自己修改Gradle插件，删除您不需要的坑位，增加您需要的坑位。
