### ISSUE TITLE
是否考虑做一个pluginWrapper,把host,lib的插件包裹起来

### ISSUE THREAD

**Issue by jiedang** [Qihoo360/RePlugin#54]
类似于small 的实现 通过外部配置Extension 告知 host,lib 对应的project Name，在根目录 打入rootPlugin,动态去apply plugin （host,or lib）。引入统一 又方便于其他项目引入

**Comment by wangyupeng1-iri** [comment]
Your idea is very good, I can optimize the next. @jiedang

**Comment by jiongxuan** [comment]
谢谢 @jiedang 的建议。 

@wangyupeng1-iri 兄，交给你了~:-)
