### ISSUE TITLE
插件同版本的覆盖安装，需要重启多次才能成功

### ISSUE THREAD

**Issue by hwldzh** [Qihoo360/RePlugin#541]
#### 问题详细描述 Detailed description of the problem
两个不同的插件，版本是一样的。使用Replugin.install进行覆盖安装，可以看到安装成功返回的PluginInfo信息。重启APP后，看到的插件还是原来的旧插件。经过多次重启后，才能看到新插件。

#### 复现问题步骤 Steps to reproduce the problem
1. 放一个内置插件A到宿主中。
2. 放一个外置插件B到SD卡中。插件A和插件B的版本是一样的。
3.在Application中使用Replugin.install安装B插件。
4.重启APP，看是否安装成功。

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.2
rePlugin-plugin-lib/gradle Version:2.2.2

Android API Version：23
Android 手机型号&ROM(Phone model & ROM): 小米Max 1

**Comment by cundong** [comment]
需要重启常驻进程（插件管理进程）才可以。
