### ISSUE TITLE
插件和宿主可以共享静态变量吗？

### ISSUE THREAD

**Issue by LiuJQ** [Qihoo360/RePlugin#543]
#### 问题详细描述 Detailed description of the problem
插件和宿主共用一个Assist辅助类，该辅助类有一个static静态变量，每次（宿主或插件都可以）调用Assist某方法时会执行刷新该static变量操作。
貌似这种操作在插件中是不生效的，也就是说插件中更新不了static静态变量，只能读取？

**Comment by cundong** [comment]
ClassLoader 都不一样了。。
