### ISSUE TITLE
关于插件中exported="true"属性的问题

### ISSUE THREAD

**Issue by kylin17** [Qihoo360/RePlugin#546]
#### 问题详细描述 Detailed description of the problem
由于RePlugin采用的是“占坑”方式预埋四大组件，外部app需要调起插件中的Activity或Service就无法成功，除了在host中使用代理Activity或Service中转之后，有没有其他较好的实践方案？

**Comment by cundong** [comment]
这个问题，我们目前是把插件中所有Activity或Service的exported属性设置为false。

之所以这样做，是因为：

插件中的Activity或Service，都会被映射到宿主中的一个坑位Activity或Service，同时，这个坑位是动态分配的，所以，设置为exported=true也是无用的。

再者：
按照我们的设计理念，插件中的四大组件，是一个应用私有的，对外不可见的。

想实现您这个需求，建议的做法，是在宿主中做一个代理，让调用方去调用这个宿主中的代理，然后 通过这个代理，分发到具体插件中。
