### ISSUE TITLE
是否支持插件包的增量更新

### ISSUE THREAD

**Issue by fupSZ** [Qihoo360/RePlugin#548]
#### 问题详细描述 Detailed description of the problem
目前大插件，每次更新下载下来挺耗费时间的，是否支持插件包的增量更新，这样只下载增量包，然后本地合成。

**Comment by cundong** [comment]
对 RePlugin 来说，插件是否增量更新，都可以，但这个增量更新逻辑并不是RePlugin的工作范围，建议自己是实现一套自己的插件下发（带增量更新的）逻辑，或者说，请持续关注 360官方的插件下发更新平台：https://dc.360.cn/
