### ISSUE TITLE
打release包,application后走两次,第一次安装进入程序后点击home然后再次进入程序会走一遍启动页

### ISSUE THREAD

**Issue by yangxuqiang9** [Qihoo360/RePlugin#554]
#### 打release包,application后走两次,第一次安装进入程序后点击home然后再次进入程序会走一遍启动页

replugin-host-lib/gradle Version:2.2.1/4.1
rePlugin-plugin-lib/gradle Version:2.2.1

Android API Version：26
Android 手机型号&ROM(Phone model & ROM): 7.0

**Comment by cundong** [comment]
建议看一下Android应用进程的进程启动逻辑，您就明白了。
