### ISSUE TITLE
插件的Application何时启动呢

### ISSUE THREAD

**Issue by Altaica81** [Qihoo360/RePlugin#561]
#### 问题详细描述 Detailed description of the problem
刚开始玩RePlugin，想在插件的Application里初始化些东西，发现没有调用。于是我在官方的demo1插件的Application的onCreate()里加了log，发现也没有打印出，请问如何使Application启动呢？

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.4
rePlugin-plugin-lib/gradle Version:2.2.4

Android API Version：23
Android 手机型号&ROM(Phone model & ROM):

**Comment by cundong** [comment]
加载插件的时候，可以看：Plugin.java
