### ISSUE TITLE
gradle高版本问题

### ISSUE THREAD

**Issue by whosmyqueen** [Qihoo360/RePlugin#57]
@jiongxuan 有些第三方库需要gradle3.5,咱们replugin有支持gradle高版本的打算吗

**Comment by jiongxuan** [comment]
有的。目前Gradle工程在3.x版本支持上可能有瑕疵（毕竟Gradle版本跨度太大）。我们预计近期会开始跟进，并尝试支持高版本。

如果大家有意向修复的话，欢迎提出您的PR。在此感谢！

**Comment by whosmyqueen** [comment]
好的👌

**Comment by 154034532** [comment]
求修复高版本的问题

**Comment by wangyupeng1-iri** [comment]
replugin-host-gradle:2.1.2  试试
