### ISSUE TITLE
关于自定义多进程限制为3个的原因

### ISSUE THREAD

**Issue by gam2046** [Qihoo360/RePlugin#571]
在PluginProcessHost文件中有硬编码，限制自定义插件的数量，只有3个。

https://github.com/Qihoo360/RePlugin/blob/615cabf1b9d0e1f3e0d38c1ef1bb5a08dffa0ce5/replugin-host-library/replugin-host-lib/src/main/java/com/qihoo360/replugin/component/process/PluginProcessHost.java#L37

请问这是有什么特殊的考虑吗？在宿主程序编译过程中，可以自定义进程的数量
```
repluginHostConfig {
    countProcess = 8
}
```

因为在尝试静态指派时发现，无论我怎么指派，插件都运行在UI进程中，随后一步步步进，发现是上面的文件定义死了，只有3，从而导致https://github.com/Qihoo360/RePlugin/blob/615cabf1b9d0e1f3e0d38c1ef1bb5a08dffa0ce5/replugin-host-library/replugin-host-lib/src/main/java/com/qihoo360/replugin/component/process/PluginProcessHost.java#L75

循环时，不论我在编译时期，指定的countProcess为多少，最终能用的只有p0-p2三个进程。

因此，当初这样设计，是否有其他我没有考虑到的情况？

**Comment by cundong** [comment]
刻意设计如此。

1.
我们设计的是：除了UI进程，常驻进程外，最多**同时**可存在三个进程（P0 P1 P1）。
除了UI进程， 常驻进程，一般的应用，再同时运行三个进程，加起来一共5个进程在运行了，已经很可怕的规模了，再多了不建议。

2.
进程是可复用的，插件中的进程，都会被映射到宿主中。

详细，可以参考：https://mp.weixin.qq.com/s/IpNcyTjML16og4LrxjxFmQ
