### ISSUE TITLE
请问插件和插件之间怎么通信呢？

### ISSUE THREAD

**Issue by qmqsyz** [Qihoo360/RePlugin#575]
#### 问题详细描述 Detailed description of the problem
现在有个需求，就是想把公共库做成一个插件，不放到宿主里面去，其它的插件都会用到这个公共库。看了Replugin的说明，如果公共库在宿主的话可以setUseHostClassIfNotFound(true)，但是现在公共库是独立的插件要怎么设置呢？

#### 复现问题步骤 Steps to reproduce the problem
无

#### 其它重要信息 Other important information
无

#### Logcat上下文 Logcat context
无

**Comment by cundong** [comment]
可以借鉴我们 DMEO 中的 WebView 插件共享方式。
