### ISSUE TITLE
请教下 RePlugin 对 Android P 是否支持？

### ISSUE THREAD

**Issue by walksin** [Qihoo360/RePlugin#580]
由于 Android P 对反射进行了很多限制，请问当前 RePlugin 当前是否支持 Android P，如果不支持，未来是否有计划支持？多谢

**Comment by tdounnyy** [comment]
[Android P 对 Non-SDK Interface 的限制](https://developer.android.com/preview/restrictions-non-sdk-interfaces)，是否会成为一个 blocking issue？

**Comment by 15198184721** [comment]
这个问题android P只是灰度限制了。浅灰色的 还是可以用的 后续版本估计就不行了，但是360不是也用的这个么。怕啥，肯定会有后续解决办法的，google不是也说了。对于sdk没有的方法可以提的啊 。他说会把加进去呢做成SDK对外接口呢

**Comment by csdnail** [comment]
关注

**Comment by 736870598** [comment]
8.1试了，正常使用没任何问题

**Comment by walksin** [comment]
8.1 不是 Android P ...

**Comment by 736870598** [comment]
好尴尬

**Comment by 15198184721** [comment]
群里已经说了。已经有了适配方案了。你可以放心使用

**Comment by seventhmoon** [comment]
不兼容！
會報ClassNotFoundException.

**Comment by bnotebook** [comment]
已经对Android P做了支持。并且我们已经和Google Android团队进行了沟通，目前来看直到下个版本Q，Replugin应该都不会产生什么问题。
