### ISSUE TITLE
内置插件,外置插件(install成功后) Replugin.startActivity后Crash...

### ISSUE THREAD

**Issue by LaLaTiao** [Qihoo360/RePlugin#582]
#### 问题详细描述 Detailed description of the problem

内置插件,外置插件(install成功后) Replugin.startActivity后Crash...

#### 复现问题步骤 Steps to reproduce the problem
1. 内置插件打好 插件名.jar
2. 外置插件install成功后

内置插件/外置插件 调用  RePlugin.startActivity(SttingMenu.this, RePlugin.createIntent("rfid", "com.hccx.demo.MainActivity")); 然后程序宿主程序就crash了.

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.2.4
rePlugin-plugin-lib/gradle Version: 2.2.4

Android API Version：15
Android 手机型号&ROM(Phone model & ROM):  4.2.2

#### Logcat上下文 Logcat context
内置插件/外置插件都是报同样的错.
**Could not find class 'android.app.ActivityManager$TaskDescription', referenced from method com.qihoo360.replugin.component.activity.ActivityInjector.injectTaskDescription**

第一次接入,麻烦了.

**Comment by LaLaTiao** [comment]
我将插件的app ==> build.gradle内的配置
apply plugin: 'replugin-plugin-gradle'
repluginPluginConfig {
    pluginName = "rfid"
    hostApplicationId = "包名"
    hostAppLauncherActivity = "包名.activity.MainActivity"
}
提到了apply plugin: 'com.android.application'前面,就不报错了.
但是又出现了新的问题.

java.lang.RuntimeException: Unable to start activity ComponentInfo{包名包名.loader.a.ActivityN1NRNTS0}: java.lang.NullPointerException

Caused by: java.lang.NullPointerException
at com.hccx.demo.MainActivity.onCreate(MainActivity.java:25)

指向的是我插件的MainActivity.onCreate的25行,但是25行只是普通的findviewbyid后的组件的setOnClicklistener,我尝试过注释掉,报错指向的还是这一行.

**Comment by YuTianTina** [comment]
> 我将插件的app ==> build.gradle内的配置
> apply plugin: 'replugin-plugin-gradle'
> repluginPluginConfig {
> pluginName = "rfid"
> hostApplicationId = "包名"
> hostAppLauncherActivity = "包名.activity.MainActivity"
> }
> 提到了apply plugin: 'com.android.application'前面,就不报错了.
> 但是又出现了新的问题.
> 
> java.lang.RuntimeException: Unable to start activity ComponentInfo{包名包名.loader.a.ActivityN1NRNTS0}: java.lang.NullPointerException
> 
> Caused by: java.lang.NullPointerException
> at com.hccx.demo.MainActivity.onCreate(MainActivity.java:25)
> 
> 指向的是我插件的MainActivity.onCreate的25行,但是25行只是普通的findviewbyid后的组件的setOnClicklistener,我尝试过注释掉,报错指向的还是这一行.

我也遇见控件报NPE的错误, 请问你后来有找出原因吗?

**Comment by ryan-yuan** [comment]
> > 我将插件的app ==> build.gradle内的配置
> > apply plugin: 'replugin-plugin-gradle'
> > repluginPluginConfig {
> > pluginName = "rfid"
> > hostApplicationId = "包名"
> > hostAppLauncherActivity = "包名.activity.MainActivity"
> > }
> > 提到了apply plugin: 'com.android.application'前面,就不报错了.
> > 但是又出现了新的问题.
> > java.lang.RuntimeException: Unable to start activity ComponentInfo{包名包名.loader.a.ActivityN1NRNTS0}: java.lang.NullPointerException
> > Caused by: java.lang.NullPointerException
> > at com.hccx.demo.MainActivity.onCreate(MainActivity.java:25)
> > 指向的是我插件的MainActivity.onCreate的25行,但是25行只是普通的findviewbyid后的组件的setOnClicklistener,我尝试过注释掉,报错指向的还是这一行.
> 
> 我也遇见控件报NPE的错误, 请问你后来有找出原因吗?

我也是，嵌入了插件的Fragment，但启动插件Activity出现了findViewById返回null，卡了好几天了没解决
