### ISSUE TITLE
使用replugin后，插件上多个界面显示不正常

### ISSUE THREAD

**Issue by wojason** [Qihoo360/RePlugin#584]
#### 问题详细描述 Detailed description of the problem
![image](https://user-images.githubusercontent.com/39614119/40530282-bebd7904-602a-11e8-80fc-228b611a0b4d.png)
如图所示，有多个界面出现类似这种问题，没有靠上面，而是居中。
未用replugin之前，显示都正常。
在清理掉宿主的一些资源（多国语言相关的string定义）后，以上问题消失。
不知道为什么会出现这样的问题？

#### 复现问题步骤 Steps to reproduce the problem
1. host调用插件上的activity
2. 插件上activity又调用插件上的activity

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.1
rePlugin-plugin-lib/gradle Version: 2.2.4

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 
所有手机型号出现

#### Logcat上下文 Logcat context
无

**Comment by cundong** [comment]
这种问题，一般是因为插件中使用上下文不当，导致的获取资源不对，引发的。可以查查，让插件中所有获取资源的地方，都使用插件上下文（可以通过打印上下文对象来看的）。
