### ISSUE TITLE
宿主有.so库，插件loadLibiary报java.lang.UnsatisfiedLinkError异常

### ISSUE THREAD

**Issue by starchen84** [Qihoo360/RePlugin#587]
#### 问题详细描述 Detailed description of the problem
宿主有.so库，插件loadLibiary报java.lang.UnsatisfiedLinkError异常

#### 复现问题步骤 Steps to reproduce the problem
1. 宿主有.so库
2. 插件loadLibiary该.so库

#### 其它重要信息 Other important information
插件还有其他.so库

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by BlackC0** [comment]
4848
