### ISSUE TITLE
宿主打开插件activity时，丢失intent中的数据

### ISSUE THREAD

**Issue by Luckflower** [Qihoo360/RePlugin#588]
#### 问题详细描述 Detailed description of the problem
宿主通过  RePlugin.startActivity(this,jumpIntent); 去打开插件activity时，插件activity可以跳转成功，但在插件activity中获取不到宿主之前传入的intent中的参数，参数通过下面方式传递
jumpIntent.putExtra("uri", uristring);
我在插件中通过String uri = intent.getStringExtra("uri"); 去获取，但总是为空，请问这是为什么？ 源码中replugin似乎没有对intent做修改， 

#### 复现问题步骤 Steps to reproduce the problem
必先，并且尝试传入更多参数，最终没有一个参数能够传递成功， 但是jumpIntent.setAction(Intent.ACTION_VIEW); 是没有问题的，在插件中能够正常获取

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.2.4
rePlugin-plugin-lib/gradle Version: 2.2.4

Android API Version：25
Android 手机型号&ROM(Phone model & ROM):  小米6

**Comment by cundong** [comment]
请参考一下我们的DEMO，这种场景很多。
