### ISSUE TITLE
插件更新问题

### ISSUE THREAD

**Issue by whosmyqueen** [Qihoo360/RePlugin#59]
我把每个业务拆分出来，如果需要单独更新某个插件，怎么做

**Comment by jiongxuan** [comment]
您好，请参考：https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%92%E4%BB%B6%E7%9A%84%E7%AE%A1%E7%90%86#%E5%A4%96%E7%BD%AE%E6%8F%92%E4%BB%B6
