### ISSUE TITLE
支持android P有没有计划

### ISSUE THREAD

**Issue by megahertz0** [Qihoo360/RePlugin#596]
#### 问题详细描述 Detailed description of the problem
android p系统无法使用，loadLocked(): Initialized, is loaded = true

#### 复现问题步骤 Steps to reproduce the problem
1. 启动应用
2. 打开插件

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.4
rePlugin-plugin-lib/gradle Version:2.2.4

Android API Version：27
Android 手机型号&ROM(Phone model & ROM): google pixel android P

**Comment by 15198184721** [comment]
我试过。在androidP里没问题的。只是会有警告而已。google说的是后续版本可能将会限制非sdk接口调用。群里已经说过了。目前适配方案已经出来了。就等后续版本如果限制了就应用适配方案进去

**Comment by megahertz0** [comment]
我的问题，其他原因导致的。抱歉
