### ISSUE TITLE
Activity被回收，无法重新建立activity

### ISSUE THREAD

**Issue by jaydon** [Qihoo360/RePlugin#599]
android:launchMode="standard"
A->B->C三个activity,按返回键，只能回退到B，然后直接到主工程，因为A被onDestroy掉了，但正常逻辑这时应该是重走A的onCreate()流程，必现的，跟机型无关。

**Comment by cundong** [comment]
修改一下 坑位数量就可以了。

详见：
https://github.com/Qihoo360/RePlugin/blob/dev/replugin-host-gradle/src/main/groovy/com/qihoo360/replugin/gradle/host/handlemanifest/ComponentsGenerator.groovy
