### ISSUE TITLE
插件需要用到宿主的资源

### ISSUE THREAD

**Issue by JsonYuu** [Qihoo360/RePlugin#60]
在插件中需要用到宿主里面的 public static final 变量，以前用别人的插件化框架是把宿主打成jar 包，给插件引用，那RePlugin 是怎么处理的啊？求大大帮解答下。

**Comment by flynihao53** [comment]
+1

**Comment by JsonYuu** [comment]
+10086

**Comment by PengJunJun** [comment]
+1008611

**Comment by jiongxuan** [comment]
您好。该问题和 #34  是重复的，请以那个Issue的回答为准。

我们在首页中已添加了这块儿的说明，以方便后来人去理解。
