### ISSUE TITLE
是不是 插件 只能一个dex?

### ISSUE THREAD

**Issue by flowerflowerflower** [Qihoo360/RePlugin#604]
#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by cundong** [comment]
支持多 DEX，但要保证 Entry 相关（replugin-plugin-library）类，在主 DEX 中。
