### ISSUE TITLE
No static method getInstance(Landroid/content/Context;)Lcom/qihoo360/replugin/loader/b/PluginLocalBroadcastManager

### ISSUE THREAD

**Issue by luoshengbo** [Qihoo360/RePlugin#605]
#### 问题详细描述 Detailed description of the problem
Replugin加载Facebooksdk，在我反编译，然后修改了smali之后。

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by luoshengbo** [comment]
请问一下，该如何解决Replugin加载Facebook导致闪退的问题呢

**Comment by cundong** [comment]
Replugin 不是用来加载Facebook的。
