### ISSUE TITLE
使用AS 2.3.3版本报错Failed to resolve: com.qihoo360.replugin:replugin-host-lib:2.1.0，再次点击同步还是报这个错

### ISSUE THREAD

**Issue by flynihao53** [Qihoo360/RePlugin#61]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:

**Android compile SDK version**:

**Android ROM**:

**Comment by whosmyqueen** [comment]
在root build.gradle里面加上`repositories {
        jcenter()
        mavenCentral()
        maven {
            url "https://dl.bintray.com/qihoo360/replugin"
        }
    }`

**Comment by jiongxuan** [comment]
是的，JCenter即将上线，很快就不会有这个问题了。

非常感谢 @whosmyqueen 的解答！

**Comment by flynihao53** [comment]
@whosmyqueen 谢谢解答

**Comment by wangyupeng1-iri** [comment]
@flynihao53 看#53针对这个问题[解决方案](https://github.com/Qihoo360/RePlugin/issues/53)

**Comment by jiongxuan** [comment]
不知道为何，JCenter的审核速度还是有待改进。目前仅上线了一个工程，剩下三个还再审。我们已发邮件催促，还请耐心等待，之后就可以去掉了。

谢谢理解！
