### ISSUE TITLE
生成的dex文件为什么这么大？

### ISSUE THREAD

**Issue by monty8800** [Qihoo360/RePlugin#612]
#### 问题详细描述 Detailed description of the problem
一共四个插件，作为外置插件的方式安装，运行之后查看应用信息，发现有90多M
![image](https://user-images.githubusercontent.com/10119633/41950570-37bede50-79f9-11e8-9f43-518a2e93157b.png)
通过Device File Explorer 查看，app_p_od这个目录下有四个dex文件，加起来差不多70多M
![image](https://user-images.githubusercontent.com/10119633/41950536-0f4a87c6-79f9-11e8-91db-8f1aca999f68.png)
这种情况是正常的吗？是否有优化的方法

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by cundong** [comment]
兄弟，这是Android 本身 dex2oat 过程生成的产物，用不用插件化，都这样的。
