### ISSUE TITLE
PluginProcessMain 的ALL内存值不对

### ISSUE THREAD

**Issue by jaydon** [Qihoo360/RePlugin#614]
#### 问题详细描述 Detailed description of the problem
关闭插件后，增加了代码杀掉插件进程，待一段时间后，发现打不开插件，debug到guard进程里的进程信息不对，只有主进程信息，没有p0信息，也就是-100，导致无法启动插件

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by hyongbai** [comment]
@jaydon 

因为RePlugin里面的进程可能是共用的，不建议自己管理进程的声明周期。移除杀插件进程的代码这个问题还存在吗? 

> 另：
> - 杀进程的逻辑是在什么场景下执行的呢
> - 可否告知方便看下杀插件进程的代码吗

**Comment by bnotebook** [comment]
坑位进程有自己的进程管理机制，报错销毁等操作。不建议自行进行kill等操作。
