### ISSUE TITLE
安卓7.0-8.0版本，插件activity中包含webview时崩溃

### ISSUE THREAD

**Issue by xiaoli-style** [Qihoo360/RePlugin#616]
#### 问题详细描述 Detailed description of the problem
目前测试了三星系列和VIVO系列的安卓7.0-8.0版本手机，均有闪退发生，在插件的activity中放入webview，载入网页后只要长按网页，或者选择网页上的下拉列表，就会闪退，并且闪退的代码定位是安卓系统内部。插件作为apk独立运行时没有任何问题。这个情况只在作为插件的时候出现

#### 复现问题步骤 Steps to reproduce the problem
1. 举例VIVO Xplay6,安卓7.1.1版本
2. 插件中载入网页https://www.jibaqiu.com/shuoshuo/
3.此时长按网页，会闪退
4.此时点击网页中的下拉框，会闪退
（请输入个QQ号84788558然后点击获取，下拉列表会出现内容，这个时候再测试）

@cundong 望查看该问题，非常感谢

**Comment by cundong** [comment]
https://github.com/Qihoo360/RePlugin/tree/dev/replugin-sample/plugin/plugin-webview

很久之前就已经解决了。
