### ISSUE TITLE
安装插件apk时崩溃，提示Not a valid apk

### ISSUE THREAD

**Issue by wuxinrong1981415** [Qihoo360/RePlugin#618]
#### 问题详细描述 Detailed description of the problem
采用“外置式”配置application，已经保证attachBaseContext和onCreate正确顺序调用。

安装插件时崩溃，提示：Not a valid apk
（独立安装插件apk是正常运行的）

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.4
rePlugin-plugin-lib/gradle Version:2.2.4

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 
三星 S8 edge & Android 8.0
#### Logcat上下文 Logcat context

D/plugin: 插件 /sdcard/plugins/privatemessage.apk 存在, 准备安装...
D/RePlugin.ws001: MP.pluginDownloaded ... path=/sdcard/plugins/privatemessage.apk
D/RePlugin.ws001: pluginDownloaded： path=/sdcard/plugins/privatemessage.apk
E/RePlugin.PluginManagerServer: installLocked: Not a valid apk. path=/sdcard/plugins/privatemessage.apk

**Comment by bnotebook** [comment]
sd卡的读取和存储权限是必须要具备的。
