### ISSUE TITLE
插件的一些请教

### ISSUE THREAD

**Issue by Traveler0908** [Qihoo360/RePlugin#620]
#### 问题详细描述 Detailed description of the problem
1.宿主打开一个类似于插件管理的插件，可以在此插件里面完成下载，升级，安装，打开其他插件吗？
2.上述过程，下载后的插件存在于插件里，还是在宿主里？
3.麻烦各位大佬解答一波，谢谢

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by cundong** [comment]
1.可以；
2.取决于你使用谁的上下文获取存储路径，使用宿主的上下文，就会存储到宿主的目录中，使用该“管理插件”的上下文，就会存储到插件的目录中。
