### ISSUE TITLE
如果调用插件app中的接口

### ISSUE THREAD

**Issue by Simonzhuqi** [Qihoo360/RePlugin#621]
#### 问题详细描述 Detailed description of the problem
我把插件app打包成apk,然后重命名为jar文件放到宿主app的assets下。 插件中的activity能正常启动，但是我想调用插件中写的接口，请指教 谢谢

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by cundong** [comment]
Demo 中有例子。
