### ISSUE TITLE
宿主是否可以调用插件的类

### ISSUE THREAD

**Issue by Anzhi-Meiying** [Qihoo360/RePlugin#623]
如我有一个需求需要宿主使用插件中的自定义View还有Fragment，请问 RePlugin 可以帮助我实现吗

**Comment by 15198184721** [comment]
可以的。官方的dome中有这个示例的。你可以看下

**Comment by kylinchen** [comment]
我看官方QA上说的可以支持jar，但是不支持aar？ 想问问现在支持aar的功能实现了嘛？ 还是说这个功能不会支持
