### ISSUE TITLE
RePlugin 支持先卸载当前版本然后在安装老版本么?

### ISSUE THREAD

**Issue by leishengwei** [Qihoo360/RePlugin#624]
#### 问题详细描述 Detailed description of the problem
如题,我想做版本回退,所以试着卸载老版本,然后安装新版本,提示成功了,但是打开插件的Activity提示找不到
t
#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by bnotebook** [comment]
只支持同版本覆盖，版本升级，不支持旧版本覆盖

**Comment by leishengwei** [comment]
我知道不支持旧版本覆盖, 但是我想的是先卸载新版插件,然后安装老版本插件. 这个感觉还是很有需求的啊.
