### ISSUE TITLE
插件使用JobScheduler 报错“No such service ComponentInfo”

### ISSUE THREAD

**Issue by nbhuzan** [Qihoo360/RePlugin#625]
#### 问题详细描述 Detailed description of the problem
插件里使用了JobScheduler，使用的时候报错“java.lang.IllegalArgumentException: No such service ComponentInfo”，但是单品运行正常

**Comment by Timper-yang** [comment]
没人回答么？

**Comment by OOMROO** [comment]
同问  java.lang.IllegalArgumentException: No such service ComponentInfo

**Comment by bnotebook** [comment]
插件包在打包的文件中，应该不包含JobScheduler，导致报错。解决该问题可以把报错的类打包到插件中即可。单独应用不报错是因为宿主环境可以访问到该类，而插件没有共享宿主中的特定类。
