### ISSUE TITLE
app\build\intermediates\transforms\desugar\release\39 does not exist.

### ISSUE THREAD

**Issue by sdgSnow** [Qihoo360/RePlugin#628]
#### 问题详细描述 Detailed description of the problem
我添加插件依赖进去后打包就会出现这个，不添加是正常的
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWith___ReClass___ForRelease'.
> E:\workspace\weiduQuestion\WDQuestion\app\build\intermediates\transforms\desugar\release\39 does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 27s

#### 复现问题步骤 Steps to reproduce the problem
1. 插件工程打包
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.1
rePlugin-plugin-lib/gradle Version:2.2.1

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context
      [zip] Building zip: E:\workspace\weiduQuestion\WDQuestion\app\build\intermediates\transforms\desugar\release\37.jar
      [zip] Building zip: E:\workspace\weiduQuestion\WDQuestion\app\build\intermediates\transforms\desugar\release\38.jar
:app:transformClassesWith___ReClass___ForRelease FAILED

**Comment by sdgSnow** [comment]
我添加插件的时候打包就出现了，请教下除了修改源码，还有什么方法吗

**Comment by yangxiaoge** [comment]
同问+

**Comment by huangqichao** [comment]
同问+1

**Comment by terrywlb** [comment]
同问+1

**Comment by hyongbai** [comment]
同 #627
