### ISSUE TITLE
发现一个制作插件的时候Gradle版本的问题

### ISSUE THREAD

**Issue by maning0303** [Qihoo360/RePlugin#63]
当我把插件工程的 --- 项目根目录的 build.gradle：
gradle版本使用2.2.0就编译不通过报错：Failed to apply plugin [id 'replugin-plugin-gradle']。
gradle版本使用Demo中的2.1.3就编译通过了。

```
dependencies {
        //编译不通过
        classpath 'com.android.tools.build:gradle:2.2.0'
        //Demo 使用的版本编译通过
        //classpath 'com.android.tools.build:gradle:2.1.3'
        classpath 'com.qihoo360.replugin:replugin-host-gradle:2.1.0'
}
```

**Comment by flynihao53** [comment]
去看问题61和53，或者参照demo中host的配置

**Comment by maning0303** [comment]
@flynihao53  和问题61和53不一样，配置全部配全了，我都看了的。只改gradle版本就可以编译通过！

**Comment by flynihao53** [comment]
这个具体的原因不是很清楚，不过现在我的2.3.3的也可以啊，通过配置

**Comment by maning0303** [comment]
@flynihao53  有可能是Gradle的版本差异性导致的！

**Comment by lvtanxi** [comment]
我现在是主程序在2.3.3可以。插件就不可以，修改Gradle到2.1.3就可以了

**Comment by maning0303** [comment]
是的，主程序都可以，就是插件的不行！

**Comment by aBenVip** [comment]
host可以正常跑，插件跑不起来，Gradle版本为2.3.3，同报错Failed to apply plugin [id 'replugin-plugin-gradle'，已参照61,53

**Comment by maning0303** [comment]
@aBenVip  你把插件项目的  版本改成 classpath 'com.android.tools.build:gradle:2.1.3' 应该就可以了！

**Comment by erhu** [comment]
这个问题在最新版本已经修复，大家可以更新 master 代码测试。
