### ISSUE TITLE
外置插件同版本覆盖内置插件

### ISSUE THREAD

**Issue by AKMaS** [Qihoo360/RePlugin#636]
#### 问题详细描述 Detailed description of the problem
文档中说:不支持“插件降级”，但可以“同版本覆盖”（在 RePlugin 2.1.5版本中开始支持)。
假如内置插件版本为1，外置插件版本也为1的话，是不是外置插件安装不上?

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.4
rePlugin-plugin-lib/gradle Version:2.2.4

Android API Version：26
Android 手机型号&ROM(Phone model & ROM):

**Comment by bnotebook** [comment]
这里所说的同版本覆盖是指“同一个插件的同版本“可以覆盖安装。
一个插件如果是内置的，怎么可能同时又是外置插件呢，你的问题描述不太理解。
