### ISSUE TITLE
内置插件问题咨询

### ISSUE THREAD

**Issue by guhihi2007** [Qihoo360/RePlugin#637]
#### 问题详细描述 Detailed description of the problem
问题一：用插件版本2.2.4时，可以正常编译通过，但是启动内置插件时报错，如下图：
![image](https://user-images.githubusercontent.com/24834849/44082333-750c2a0a-9fe3-11e8-9a3a-c3fa81ca346a.png)
请问这个是为什么呢，
问题二：在上面的基础上，我以为是版本问题，升级最新版本2.3.0，但是编译不通过，如下图
![image](https://user-images.githubusercontent.com/24834849/44082452-de13457e-9fe3-11e8-9280-a4276a5242ce.png)

#### 其它重要信息 Other important information
![image](https://user-images.githubusercontent.com/24834849/44082928-42288faa-9fe5-11e8-9e52-f0eaa83aa24d.png)
![image](https://user-images.githubusercontent.com/24834849/44082948-545f5460-9fe5-11e8-8440-579119685ec3.png)

replugin-host-lib/gradle Version:

rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by huangqichao** [comment]
请问问题二已经解决了吗？我也遇到这个问题了？

**Comment by bnotebook** [comment]
问题2已经解决了，问题1请检查插件中是否有Entry类，或者context是否使用正确。
