### ISSUE TITLE
使用java1.8 插件打包失败

### ISSUE THREAD

**Issue by taoszu** [Qihoo360/RePlugin#641]
#### 问题详细描述 Detailed description of the problem
使用java1.8的配置  插件打包失败

#### 复现问题步骤 Steps to reproduce the problem
1.   app gradle 改为    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }，即提示下方的打包错误信息 \build\intermediates\transforms\desugar\release\15 does not exist.
2.  如果去掉java1.8的配置，即可打包成功

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.2.4
rePlugin-plugin-lib/gradle Version: 2.2.4

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 错误发生在打包期间，所以无手机记录

#### Logcat上下文 Logcat context
#  \build\intermediates\transforms\desugar\release\15 does not exist.

**Comment by huangqichao** [comment]
请问解决了吗？也遇到这个问题

**Comment by taoszu** [comment]
没解决，等官方回答吧

**Comment by hsdfeng** [comment]
同样遇到这个问题

**Comment by hyongbai** [comment]
同 #627
