### ISSUE TITLE
使用demo1的内置插件方式，编译失败

### ISSUE THREAD

**Issue by huangqichao** [Qihoo360/RePlugin#644]
gradle版本为4.1
运行sample时报错：

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:rpGenerateDebugBuiltinJson'.
> net/dongliu/apk/parser/ApkFile

使用外部插件的方式引入，没有问题。换成jar包的内部插件，就不行了。

**Comment by bnotebook** [comment]
已修复该问题，重试下

**Comment by zeuscode** [comment]
还是有问题
