### ISSUE TITLE
No signature of method: com.android.build.gradle.internal.scope.VariantScopeImpl.getMergeAssetsTask() is applicable for argument types: () values: []

### ISSUE THREAD

**Issue by xuningForAndroid** [Qihoo360/RePlugin#646]
#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Caused by: groovy.lang.MissingMethodException: No signature of method: com.android.build.gradle.internal.scope.VariantScopeImpl.getMergeAssetsTask() is applicable for argument types: () values: []
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 
请问怎么解决？？

**Comment by wanliLiu** [comment]
Android build tool gradle 3.2.0做了相关调整，修改项目中的：
1.
variant.getVariantData().getScope().getGenerateBuildConfigTask().name
为：
variant.getVariantData().getTaskContainer().getGenerateBuildConfigTask().name

2.variant.getVariantData().getScope().getMergeAssetsTask().name
为
variant.getVariantData().getTaskContainer().getMergeAssetsTask().name

就可以了，可以用我自己的地址
 maven{url "https://dl.bintray.com/soli/maven"}

然后所有的版本改成：2.3.1就可以用了

**Comment by liangchaojie** [comment]
我也是因为Gradle 4.6   BuildTool 3.2.0遇到的这个问题的

解决如下：
 classpath 'com.android.tools.build:gradle:3.1.4'
distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip

**Comment by PicoScott** [comment]
@wanliLiu    修改的replugin代码能提供一份吗？我的项目中已经对replugin进行了修改，所以不能直接用你提供的版本。

**Comment by hyongbai** [comment]
#640 duplicated
