### ISSUE TITLE
安装外部插件调用 RePlugin.install(path) 此方法无任何反应

### ISSUE THREAD

**Issue by tokiii** [Qihoo360/RePlugin#65]
确定文件存在  外部apk 是集成replugin之后打包的apk， 用提供的sample 打包得到的demo1.apk 也是如此，改成demo1.jar放在内置目录里面就可以。

**Comment by 154034532** [comment]
同样有这个问题，求解决

**Comment by ouer1994** [comment]
同样有这个问题，求解决.没发现有报错，没发现log输出

**Comment by chenzhiwei-github** [comment]
sample demo1 build出现
Error:(53, 0) Failed to apply plugin [id 'replugin-plugin-gradle']
你们怎么解决

**Comment by Zhaoyy** [comment]
@chenzhiwei-github 
classpath 'com.android.tools.build:gradle:2.1.3'
distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip

貌似目前支持的版本，高版本会存在你的问题

**Comment by wangyupeng1-iri** [comment]
@chenzhiwei-github 看#53问题解决方案

**Comment by chenzhiwei-github** [comment]
@Zhaoyy 解决了我的问题，但是打包出错了
使用的是plugin Tasks 插件打包错误如下
< replugin-plugin > please config the adbFilePath !!!
< replugin-plugin > $ null push F:\code\example\RePlugin\replugin-sample\plugin\plugin-demo1\app\build\outputs\apk\app-debug.apk /sdcard/
< replugin-plugin > the cmd run error !!!
< replugin-plugin > java.io.IOException: Cannot run program "null": CreateProcess error=2, 系统找不到指定的文件。
:app:rpInstallAndRunPlugin
< replugin-plugin > you must to config the pluginName !!!
BUILD SUCCESSFUL
Total time: 2.332 secs

**Comment by aBenVip** [comment]
@tokiii 同问题，解决了吗

**Comment by tokiii** [comment]
没解决

**Comment by maning0303** [comment]
同问题，外置插件安装无反应！

**Comment by oubowu** [comment]
一样，调用install方法后返回null

**Comment by aBenVip** [comment]
因为Replugin做了签名校验，需要在Application中设置忽略签名校验
 @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        //-------------- 开发的时候不验证签名 -----------
        RePluginConfig config = new RePluginConfig();
        config.setVerifySign(!BuildConfig.DEBUG);
        RePlugin.App.attachBaseContext(this, config);
        // ========================
    }
@tokiii @oubowu @maning0303  你们可以试一下

**Comment by oubowu** [comment]
没用@aBenVip

**Comment by maning0303** [comment]
@aBenVip  试了，没有用，一样返回null

**Comment by aBenVip** [comment]
那可能是你的配置问题，方便的话可以上传到github，给你看看

**Comment by oubowu** [comment]
![调试](http://ww3.sinaimg.cn/large/006HJ39wgy1fh8tj1c3zcj30qs0cw75a.jpg)
_reply.readInt = 0 导致的返回结果为null

**Comment by maning0303** [comment]
@aBenVip  感谢，我刚刚又重新编译了下插件工程，成功了！

**Comment by lvtanxi** [comment]
@aBenVip 感谢。

**Comment by oubowu** [comment]
你们可以了？ @maning0303 @lvtanxi  改了host工程的签名认证 插件工程的也要改什么吗？ 完全无解这东西

**Comment by maning0303** [comment]
@oubowu 改了host的工程签名认证，插件工程Manifest中插件名字和版本设置了吗？
`
        <meta-data
            android:name="com.qihoo360.plugin.name"
            android:value="plugin01"/>
        <meta-data
            android:name="com.qihoo360.plugin.version.ver"
            android:value="100"/>
`

**Comment by oubowu** [comment]
可以了 想问下为什么要改成plugin01?之前这个是demo1 @maning0303

**Comment by maning0303** [comment]
@oubowu 我没有用demo里面的插件工程，我是自己新建了一个新的工程当做插件工程的，这个名字随便取吧，无所谓了！

**Comment by aBenVip** [comment]
@oubowu 名字随便起

**Comment by aBenVip** [comment]
@oubowu 但是host  install(别名)调用的是这个别名

**Comment by oubowu** [comment]
所以是第一次调install成功后，有返回PluginInfo，后面因为已经安装过了，PluginInfo返回就为null了？@aBenVip

**Comment by maning0303** [comment]
@oubowu  第一次调用后，你的外部放的APK已经被删除了，你安装之前判断一下APK是否存在就知道了
```
File externalStorageDirectory = Environment.getExternalStorageDirectory();
                String path = externalStorageDirectory.toString() + "/RepluginTest/plugin01.apk";
                if (fileIsExists(path)) {
                    Log.i(TAG, "存在:" + path);
                } else {
                    showToast("外置插件不存在");
                    return;
                }
                PluginInfo pi = RePlugin.install(path);
                if (pi != null) {
                    showToast("插件的描述信息:" + pi.toString());
                    boolean preload = RePlugin.preload(pi);
                    showToast("预加载插件:" + preload);
                } else {
                    showToast("插件的描述信息Null");
                }
```

**Comment by aBenVip** [comment]
调用install方法时会把apk文件move到data/data/packagename文件夹下，并改为jar文件，更新插件时旧的版本没有自动删除，所以Replugin'不支持同版本覆盖，更改下插件的版本才能重新安装，否则PluginInfo在jar存在时会返回null @oubowu

**Comment by aBenVip** [comment]
apk只是Move到data/data/packagename文件夹下，并改为jar文件，并没有删除，可以到ddms看下 @maning0303 @oubowu

**Comment by maning0303** [comment]
@aBenVip 是的，我的意思就是在开始外部放APK的地方没有了！

**Comment by aBenVip** [comment]
@maning0303 对的，你试过卸载方法了吗？卸载成功但是jar没有删除，只能改插件的版本才能重新安装

**Comment by maning0303** [comment]
@aBenVip 试了卸载方法，jar确实没有删除，我试的也是同版本插件无法覆盖安装！只能升级插件版本才能重新安装！

**Comment by lvtanxi** [comment]
这样很麻烦的。应该会修复吧

**Comment by jiongxuan** [comment]
非常感谢 @aBenVip 的耐心又仔细的回答。看来您对RePlugin已经很了解了:)。

@maning0303 @lvtanxi 这个问题我们正在抓紧解决。预计在下一版本（有一定的改动，需经过测试）才能体现，这样就可以支持同版本覆盖了。

感谢大家理解！

**Comment by maning0303** [comment]
👍

**Comment by qq634421026** [comment]
@oubowu  请问您怎么成功的啊，我改了gradle为2.1.3 
然后application忽略签名还是不好使啊

**Comment by lvtanxi** [comment]
@qq634421026 在Application中(我是继承的RePluginApplication)然后重写createConfig方法。把verifySign设置成false

**Comment by qq634421026** [comment]
@lvtanxi  你是自己写的demo还是官方的啊，我照着你的方法改了 可是install方法还是返回空，但是吧apk改成jar放在assest里面就好使，不知到怎么回事，弄了一天了

**Comment by lvtanxi** [comment]
@qq634421026 自己写的Demo。我也遇见些其他的问题。现在Toast弹不出。都弄的没办法了。你那个问题是不是你没在清单文件中配置你的插件名称和版本呢？

**Comment by qq634421026** [comment]
@lvtanxi 是在插件中设置名称和版本吗 插件中设置了，宿主没有

**Comment by lvtanxi** [comment]
@qq634421026 宿主设置了verifySign=false之后，就不再设置什么了。都按步奏操作了，还是不行的话，建议吧宿主卸载了再重新安装一下。或者看看的文件路径是不是正确

**Comment by qq634421026** [comment]
@lvtanxi 我在试试吧还是不行啊

**Comment by qq634421026** [comment]
@lvtanxi 你插件打包是怎么打得？能不能把你demo发给我我看看

**Comment by lvtanxi** [comment]
@qq634421026 代码在公司的，明天给你？

**Comment by qq634421026** [comment]
@好的

**Comment by qq634421026** [comment]
@lvtanxi 好的 谢谢了 634421026 我qq

**Comment by tokiii** [comment]
ok，解决我的问题了，谢谢回复，问题我close了
