### ISSUE TITLE
主程序替换applicationId后和之前用自己的applicationId申请的第三方sdk的key不匹配

### ISSUE THREAD

**Issue by OOMROO** [Qihoo360/RePlugin#655]
#### 问题详细描述 Detailed description of the problem
我们的主程序的applicationId 改为
 android {
    // ATTENTION!!! Must CONFIG this to accord with Gradle's standard, and avoid some error
    defaultConfig {
        applicationId "com.qihoo360.replugin.sample.host"
        ...
    }
    ...
}

高德地图 文档中说 
获取build.gradle文件中的ApplicationId作为PackageName；如果没有设置ApplicationId，请以AndroidManifest.xml配置文件的package 属性为准。

现在遇到的问题是 之前用自己的applicationId申请的key 和replugin 的applicationId 不匹配 。请问这个问题应该怎么解决
#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.4
rePlugin-plugin-lib/gradle Version: 2.2.4

Android API Version：5.0
Android 手机型号&ROM(Phone model & ROM):

**Comment by OOMROO** [comment]
android {
// ATTENTION!!! Must CONFIG this to accord with Gradle's standard, and avoid some error
defaultConfig {
applicationId "com.qihoo360.replugin.sample.host"
...
}
...
}
文档中的applicationId 修改为自己的应用的包名，sdk 可以使用了，应该是对文档中的applicationId 误解了

**Comment by withyi9223** [comment]
我的问题依然存在，一直提示的是用户key不正确或过期，什么回事
