### ISSUE TITLE
无法用 RePlugin.startActivityForResult() 开启插件中的 Activity

### ISSUE THREAD

**Issue by kaoheiay** [Qihoo360/RePlugin#657]
#### 问题详细描述 Detailed description of the problem
同一个插件中的Activity, 用 RePlugin.startActivity() 可正常开启，但用 RePlugin.startActivityForResult() 确无法开启~

#### 复现问题步骤 Steps to reproduce the problem
Intent intent = RePlugin.createIntent("soft_world.mycard.paymentapp", "soft_world.mycard.paymentapp.ui.MainActivity");
        intent.putExtra(ParamTitle.Ver, "" + RePlugin.getPluginVersion("soft_world.mycard.paymentapp"));
        intent.putExtra(ParamTitle.AuthCode, getIntent().getStringExtra(ParamTitle.AuthCode));
        intent.putExtra(ParamTitle.isTest, getIntent().getBooleanExtra(ParamTitle.isTest, true));
        intent.putExtra(ParamTitle.Other, getIntent().getStringExtra(ParamTitle.Other));
        RePlugin.startActivityForResult(this, intent, Config.Payment_RequestCode);

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.3.0
rePlugin-plugin-lib/gradle Version: 2.3.0

Android API Version：28
Android 手机型号&ROM(Phone model & ROM): 小米5

#### Logcat上下文 Logcat context
09-06 16:09:49.113 12288-12288/tw.com.mycard.mycardsdksample.debug D/RePlugin.ws001: startActivityForResult: intent=Intent { cmp=MycardPaymentApp/soft_world.mycard.paymentapp.ui.MainActivity (has extras) } requestCode=9999 options=null
    start activity with startActivityForResult: intent=Intent { cmp=MycardPaymentApp/soft_world.mycard.paymentapp.ui.MainActivity (has extras) }
09-06 16:09:49.114 12288-12288/tw.com.mycard.mycardsdksample.debug D/RePlugin.ws001: PACM: bindActivity: may be invalid plugin name or load plugin failed: plugin=null
    PACM: bindActivity: activity not found
09-06 16:12:14.153 12288-12305/tw.com.mycard.mycardsdksample.debug I/ws001: p.p d, p.h s n
09-06 16:25:33.080 12288-12293/tw.com.mycard.mycardsdksample.debug I/zygote64: Do partial code cache collection, code=250KB, data=186KB
09-06 16:25:33.081 12288-12293/tw.com.mycard.mycardsdksample.debug I/zygote64: After code cache collection, code=250KB, data=186KB
    Increasing code cache capacity to 1024KB

**Comment by xunhaifeng** [comment]
现在解决了吗 朋友

**Comment by kaoheiay** [comment]
没有 Orz...

**Comment by bnotebook** [comment]
目前没有碰到过类似的情况。根据日志应该是插件加载失败了，没有获得插件中相应的activity信息，具体可以看下PluginCommImpl的getActivityInfo方法。
