### ISSUE TITLE
AndroidStudio 3.2 RC3 编译报错

### ISSUE THREAD

**Issue by logney** [Qihoo360/RePlugin#661]
AndroidStudio 3.2 RC3 、 gradle:3.2.0-rc03 编译时
No signature of method: com.android.build.gradle.internal.scope.VariantScopeImpl.getMergeAssetsTask() is applicable for argument types: () values: []

**Comment by CTO1987** [comment]
是不是签名有错误呢？

**Comment by angcyo** [comment]
see https://github.com/Qihoo360/RePlugin/issues/640

**Comment by hyongbai** [comment]
#640 duplicated
