### ISSUE TITLE
关于子插件编译慢的问题，子插件无法编译的问题--都看过来，我已解决

### ISSUE THREAD

**Issue by CTO1987** [Qihoo360/RePlugin#662]
#### 问题详细描述 Detailed description of the problem
1，子插件编译慢：
先在**开发**时，把**360插件注掉**，等到整合插件时，在开启360插件功能

2，关闭无法编译插件
我每次生成子插件都报，**Unable to delete directory** D 536cda0b32e69782e48b8fcff33b1a001f8dd2f\class\android\support\v4.  导致**无法生成插件**，
预计这个问题，是因为**应用在调用你的这个文件**,谢谢@cundong 大老的提示,我发**现每次生成时，TortoiseGit status cache都会启动**，应该是**他占用了我生成的文件**，我**把他结束进程**后，每次都能打包成功，也不在报这个错误了
**感谢360**了，给我们带来那么好的插件，我也是360的忠实粉丝，好多年了，电脑上都是装360软件，360加油，你若不离，我则不弃

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by hyde190** [comment]
升级gradle,gradle tool, 到7以上就快了
