### ISSUE TITLE
手动替换内置插件，运行闪退

### ISSUE THREAD

**Issue by aqiansunboy** [Qihoo360/RePlugin#663]
#### 问题详细描述 Detailed description of the problem
同一个主插件，我希望编译一次后，动态替换不同的内置插件，变成不同的应用。采用**apktool**解压后，手动替换**assets/plugins**目录下的插件和修改**plugins-builtin.json**文件后，采用**apktool**重新打包和签名后，安装完启动闪退（解包修改前可正常启动）。启动插件的代码为：
```java
RePlugin.startActivity(this, RePlugin.createIntent(pluginName, "固定包名"));
```
其中，**pluginName**为动态读取**assets/plugins**目录下插件文件名，并且内置插件只有**一个**。

#### 复现问题步骤 Steps to reproduce the problem
1. 通过Android Studio打一个包含一个内置插件的包，运行正常
2. apktool d 解压打出来的包，手动替换**assets/plugins**目录下的插件和修改**plugins-builtin.json**文件内容
3. apktool b重新打包，并签名
4. 将包含新插件的包安装到手机，运行闪退，捕获不到异常日志

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.3.0
rePlugin-plugin-lib/gradle Version:2.3.0

Android API Version：25
Android 手机型号&ROM(Phone model & ROM): 
华为荣耀8

#### Logcat上下文 Logcat context
```java
09-15 15:17:00.395 16142-16142/? D/RePlugin.ws001: start activity: intent=Intent { cmp=plugin/com.Lottry.query.controllers.UserGuidingActivity } plugin=plugin activity=com.Lottry.query.controllers.UserGuidingActivity process=-2147483648
    start activity: intent=Intent { cmp=plugin/com.Lottry.query.controllers.UserGuidingActivity } plugin=plugin activity=com.Lottry.query.controllers.UserGuidingActivity process=-2147483648 download=true
    plugin=plugin not found, start download ...
    isNeedToDownload(): V5 file not exists. Plugin = plugin
```

**Comment by CTO1987** [comment]
360是做安全的，不会给你这样玩的，别想了吧

**Comment by aqiansunboy** [comment]
> 360是做安全的，不会给你这样玩的，别想了吧

为什么呢。都是我们自己的插件，或者说要校验签名？

**Comment by alvince** [comment]
扯淡的 issue，replugin 设计出来是为了解决插件化的问题，你这种操作是正常的需求？

**Comment by bnotebook** [comment]
插件运行时会进行安全校验的，应该是没校验通过。
