### ISSUE TITLE
Didn't find class "com.qihoo360.replugin.Entry" on path: DexPathList

### ISSUE THREAD

**Issue by w819244599** [Qihoo360/RePlugin#669]
#### 问题详细描述 Detailed description of the problem
manifest已经解析出来了，log日志显示解析插件 耗时等 连插件manifest 里面的配置文件都打印出来了

#### 复现问题步骤 Steps to reproduce the problem
1. 在官网看到类似的问题 ，但是我已经加入依赖等还是出现
2. 

#### 其它重要信息 Other important information

replugin-host-lib/   host-lib:2.2.1
rePlugin-plugin-lib/ plugin-lib:2.2.4'

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 三星  A6+

**Comment by w819244599** [comment]
我已经把这个错误解决啦；直接把官网上的工程中的“replugin-plugin-library”导入到自己的工程中不使用依赖方式加载；但是现在出现一个新的问题
![image](https://user-images.githubusercontent.com/43236412/45911417-92d12100-be45-11e8-8a0b-726e0e2dad32.png)

**Comment by bnotebook** [comment]
按照官方demo检查一下自己的配置吧。看日志应该是插件包有问题，不能正常加载解析导致的。
