### ISSUE TITLE
Gradle配置错误

### ISSUE THREAD

**Issue by zhaolei9527** [Qihoo360/RePlugin#67]
![image](https://user-images.githubusercontent.com/23435676/27781730-ddc9af86-6001-11e7-9db8-fdabe51b033a.png)

**Comment by wangyupeng1-iri** [comment]
看问题#53解答

**Comment by ncguobiao** [comment]
**
![image](https://user-images.githubusercontent.com/20988969/27782794-839df3a0-6006-11e7-8648-2180f8333f86.png)
**

**Comment by zhaolei9527** [comment]
![image](https://user-images.githubusercontent.com/23435676/27782828-aaab1c20-6006-11e7-89b5-038f29426e83.png)
放在末尾，也还是相同错误提示

**Comment by ncguobiao** [comment]
研究了一天鸟，还是坑

**Comment by zhaolei9527** [comment]
就Demo运行的挺6，赶紧完善文档吧

**Comment by ncguobiao** [comment]
demo里面的插件都是现成搞好的，当然没问题。但是单独导入demo1一样报上面的错误
![image](https://user-images.githubusercontent.com/20988969/27783075-564b3cb8-6007-11e7-9157-c06c5a77fb55.png)

**Comment by ncguobiao** [comment]
放到最末尾鸟，这还是官方的demo,都报错。。。

**Comment by zhaolei9527** [comment]
我是自己配的主程序，导的demo1.demo2的jar进去，没有任何问题，自己创建插件放进去，json都生成出来了，就是调不起来，连个错误都没有。

**Comment by flynihao53** [comment]
demo1的话你要把你应该把apply plugin: 'replugin-plugin-gradle'放在apply plugin: 'com.android.application'之前就好了，我的就是这样好使的，你试试

**Comment by zhaolei9527** [comment]
![image](https://user-images.githubusercontent.com/23435676/27783294-39f3f0f4-6008-11e7-8818-02e9a9aeffff.png)
放前面就是这错了。。

**Comment by ncguobiao** [comment]
哥们我和你一样的问题哟！自己配的主程序，导的demo1.demo2的jar进去，没有任何问题，自己创建插件放进去，json都生成出来了，就是调不起来，连个错误都没有。坑了一天咯！

**Comment by ncguobiao** [comment]
确实好使！放最前面

**Comment by zhaolei9527** [comment]
我咋不好使。。

**Comment by ncguobiao** [comment]
你那主题有问题，换个

**Comment by ncguobiao** [comment]
我之前也碰到了，换了个主题

**Comment by zhaolei9527** [comment]
没换主题，，多同步几次就又没事了。。。

**Comment by ncguobiao** [comment]
能不能调起自己的插件？

**Comment by flynihao53** [comment]
我试不可用

**Comment by flynihao53** [comment]
你们可以试试

**Comment by ncguobiao** [comment]
确实调不起来啊
![image](https://user-images.githubusercontent.com/20988969/27783968-e4ab6b92-600a-11e7-98d3-b792bf87c6f9.png)

**Comment by xiangou** [comment]
Gradle 版本问题

**Comment by zhaolei9527** [comment]
![image](https://user-images.githubusercontent.com/23435676/27784562-16f4d0aa-600d-11e7-9c4b-2cbc57d1e063.png)
我的是这错，插件单独运行无错，调起报错

**Comment by xiangou** [comment]
从错误日志看  你的ACTIVITY没有主题  你试试加个主题上去

**Comment by zhaolei9527** [comment]
有主题，插件单独运行无错。。

**Comment by xiangou** [comment]
恩 我是吧Demo 的GRADLE 版本更新成最新 的 就错了

**Comment by zhaolei9527** [comment]
apply plugin: 'replugin-plugin-gradle'
我把这句去掉了，完美运行。。。。。我的天哪

**Comment by zhaolei9527** [comment]
不过所有样式都没有了。。

**Comment by xiangou** [comment]
去掉那句可以编译 无法跳转  但是有提示升级成功哈哈

**Comment by flynihao53** [comment]
你这个情况厉害了

**Comment by zhaolei9527** [comment]
![插件调起](https://user-images.githubusercontent.com/23435676/27785938-c101793c-6011-11e7-942d-6b5ff6dcd7c2.png)
插件调起
![插件单独运行](https://user-images.githubusercontent.com/23435676/27785958-dbd05634-6011-11e7-884f-3cbaff4e92ad.png)
插件单独运行

**Comment by flynihao53** [comment]
我的什么反应也没有，调用没反应，你说说你调起的详细步骤

**Comment by zhaolei9527** [comment]
按照文档正常配置，插件单独运行成功，调起报错activity没有主题样式<br>删除插件配置：apply plugin: 'replugin-plugin-gradle'，插件单独运行成功，调起成功，所有主题样式失效。<br>加上插件配置：apply plugin: 'replugin-plugin-gradle'，插件单独运行成功，调起成功，所有主题样式失效。

**Comment by zhaolei9527** [comment]
总结，，**一脸懵逼。。。**

**Comment by xiangou** [comment]
试试用内置插件看看

**Comment by flynihao53** [comment]
内置的可以

**Comment by zhaolei9527** [comment]
demo1跟demo2都正常

**Comment by xiangou** [comment]
乐视手机不行 华为的可以启动内置插件

**Comment by wangyupeng1-iri** [comment]
请切换到最新版本，具体查看wiki发行版本
