### ISSUE TITLE
宿主要调用插件的方法，插件也要调用宿主的方法，怎么解决

### ISSUE THREAD

**Issue by markingdom** [Qihoo360/RePlugin#676]
#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by bnotebook** [comment]
使用AIDL通信即可（如果是同进程会直接走调用，如果是跨进程会走Binder通信。）
