### ISSUE TITLE
插件中popwindow动画失效，只能在宿主中定义动画然后插件再引用吗？

### ISSUE THREAD

**Issue by markingdom** [Qihoo360/RePlugin#686]
#### 问题详细描述 Detailed description of the problem

#560 
#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.3.0
rePlugin-plugin-lib/gradle Version:2.3.0

Android API Version：6.0.1
Android 手机型号&ROM(Phone model & ROM): MUMU模拟器 最新版

**Comment by hyongbai** [comment]
**Yes**
