### ISSUE TITLE
请问宿主如何访问插件资源,比如多语言文字

### ISSUE THREAD

**Issue by starchen84** [Qihoo360/RePlugin#687]
#### 问题详细描述 Detailed description of the problem
请问宿主如何访问插件资源,比如多语言文字
能否举个列子说明

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by hyongbai** [comment]
** RePlugin本身不提供此种类型的API。**

也许一下可以给你一点启发：

- `RePlugin.fetchContext({pluginName})` 可以获取到插件的Context。

- `RePlugin.fetchClassLoader({pluginName})`可以获取到插件的ClassLoader。

有了ClassLoader你可以拿到插件的R文件，进而可以获取对应资源的ID，同时Context你也拿到了。

然后，就靠你了。
