### ISSUE TITLE
AS2.3.3不能调起插件

### ISSUE THREAD

**Issue by flynihao53** [Qihoo360/RePlugin#69]
我的宿主和插件存在于同一个工程中，问题存在如下：

1、一个很有意思的是在插件的build.gradle中配置插件信息时，apply plugin: 'replugin-host-gradle'
apply plugin: 'com.android.application'，只能是这样的顺序，即'replugin-host-gradle‘必须放在开头且放在
 'com.android.application'之前，放在其他位置会报错
2、在宿主（A）中使用 RePlugin.startActivity方法不能调起插件（B)，RePlugin.createIntent参数1我就传插件名（B），参数2传的插件中MainActivity的类引用路径，和demo中一样，但是调不起来

**Comment by ncguobiao** [comment]
+1

**Comment by fcott19** [comment]
遇到相同问题

**Comment by lizhanzhishang** [comment]
也遇到这样问题，RePlugin 不知道怎么也木有log日志提示原因

**Comment by kezhijie** [comment]
遇到相同问题

**Comment by Pengyi520** [comment]
同样的问题，，AS2.3.3

**Comment by wangyupeng1-iri** [comment]
请查看wiki发行版本，并切换到最新版本。
