### ISSUE TITLE
有个问题想咨询下,当插件里的activity在栈顶时,获取栈顶activityName不是想要的类名

### ISSUE THREAD

**Issue by asdf19910719** [Qihoo360/RePlugin#695]
#### 问题详细描述 Detailed description of the problem
有个问题想咨询下,当插件里的activity在栈顶时,获取栈顶activityName不是想要的类名,而是
loader.a.ActivityP0STNTS1;
#### 复现问题步骤 Steps to reproduce the problem
1. 插件中的activity在栈顶时
2. 在宿主中获取插件activity里的类名

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by wogenhaosini** [comment]
使用 `Application.ActivityLifecycleCallbacks` api 自己监听app内栈顶Activity类名 我就是这样么干的。

**Comment by hyongbai** [comment]
> 使用 `Application.ActivityLifecycleCallbacks` api 自己监听app内栈顶Activity类名 我就是这样么干的。

你获取到的只能坑的名称，也就是你看到的ActivityP0STNTS1。如果想拿到实例的具体实现类，可以参考楼上的方案。
