### ISSUE TITLE
插件更新怎么立即重启生效呢？

### ISSUE THREAD

**Issue by Mr-FB** [Qihoo360/RePlugin#698]
#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by cr1944** [comment]
我有同样的问题，插件更新了，使用：
android.os.Process.killProcess(android.os.Process.myPid());
这种方式重启进程似乎无效。还得我手动重启，有没有人分享下如何自动重启？总不能弹框让用户自己去重启吧？

**Comment by Mr-FB** [comment]
> 我有同样的问题，插件更新了，使用：
> android.os.Process.killProcess(android.os.Process.myPid());
> 这种方式重启进程似乎无效。还得我手动重启，有没有人分享下如何自动重启？总不能弹框让用户自己去重启吧？

你怎么重启的呢

**Comment by Sincerly** [comment]
对接unity3d写的apk的项目 我这边用replugin低版本4.4可以  8.1以上白屏

**Comment by Mr-FB** [comment]
> > > 我有同样的问题，插件更新了，使用：
> > > android.os.Process.killProcess(android.os.Process.myPid());
> > > 这种方式重启进程似乎无效。还得我手动重启，有没有人分享下如何自动重启？总不能弹框让用户自己去重启吧？
> > 
> > 
> > 你怎么重启的呢
> 
> 解决了，是因为我在重启前install导致的

哥们怎么解决的，可以分享一下吗

**Comment by cr1944** [comment]
> > > > 我有同样的问题，插件更新了，使用：
> > > > android.os.Process.killProcess(android.os.Process.myPid());
> > > > 这种方式重启进程似乎无效。还得我手动重启，有没有人分享下如何自动重启？总不能弹框让用户自己去重启吧？
> > > 
> > > 
> > > 你怎么重启的呢
> > 
> > 
> > 解决了，是因为我在重启前install导致的
> 
> 哥们怎么解决的，可以分享一下吗

我的描述不准确，应该是不能在插件运行时安装更新，更新完killProcess就行了

**Comment by Mr-FB** [comment]
> > > > > 我有同样的问题，插件更新了，使用：
> > > > > android.os.Process.killProcess(android.os.Process.myPid());
> > > > > 这种方式重启进程似乎无效。还得我手动重启，有没有人分享下如何自动重启？总不能弹框让用户自己去重启吧？
> > > > 
> > > > 
> > > > 你怎么重启的呢
> > > 
> > > 
> > > 解决了，是因为我在重启前install导致的
> > 
> > 
> > 哥们怎么解决的，可以分享一下吗
> 
> 我的描述不准确，应该是不能在插件运行时安装更新，更新完killProcess就行了

你不是插件运行时候更新的？

**Comment by hyongbai** [comment]
同 #735 

https://github.com/Qihoo360/RePlugin/issues/735#issuecomment-445640653
