### ISSUE TITLE
在插件中使用Log输出日志，控制台显示不出来

### ISSUE THREAD

**Issue by hehaitao074** [Qihoo360/RePlugin#705]
#### 问题详细描述 Detailed description of the problem
在插件中使用Log输出日志，控制台显示不出来，不知道是什么问题，

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.4
rePlugin-plugin-lib/gradle Version:2.2.4

Android API Version：7.0
Android 手机型号&ROM(Phone model & ROM): 华为nova

**Comment by hyongbai** [comment]
听下来是在插件里面输出了自己的LOG，但是不能打印。

部分手机厂商默认会关闭开发者的log，可以搜索相关手机的开启方式。

同RePlugin没逻辑关系。ISSUE先关闭了。
