### ISSUE TITLE
360移动开发者中心-插件管理功能无法使用

### ISSUE THREAD

**Issue by bravecheng** [Qihoo360/RePlugin#706]
#### 问题详细描述 Detailed description of the problem

注册了360移动开发者中心开发者账号，进入控制台，发现插件管理功能无法使用，点击下载SDK，调到一个新页面，出现500错误

#### 复现问题步骤 Steps to reproduce the problem
1. 进入 https://dc.360.cn/
2. 打开控制台，随便选择一个应用
3.进入插件管理，点击“设置”里面的SDK下载
4.跳转进入 https://dc.360.cn/console/service/downloadSdk?app_id=1364&pathname=replugin ，实际显示500错误

#### 其它重要信息 Other important information

期待能尽快修复此问题

**Comment by hyongbai** [comment]
已反馈给dc平台并已解决。可以再试一下。
