### ISSUE TITLE
压根用不了  全都被中国长城防火墙屏蔽了

### ISSUE THREAD

**Issue by yuliu312832473** [Qihoo360/RePlugin#707]
#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by hyongbai** [comment]
目前是上传到<http://jcenter.bintray.com/com/qihoo360/replugin/>的。

觉得慢的话，可以翻墙或者让别人翻墙帮你下载，然后使用mavenLocal。

只能帮你到这了。
