### ISSUE TITLE
加载插件式，无法获取插件的assets目录下的配置文件

### ISSUE THREAD

**Issue by changwilling** [Qihoo360/RePlugin#712]
#### 问题详细描述 Detailed description of the problem
插件应用在其Application中要初始化一个第三方的SDK，用到了其assets目录下的配置文件，插件单独运行时，可以成功加载并初始化完成，但是当作插件使用时，没有获取到assets目录下的文件，并因此报了空指针的异常，如何解决？

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by SuperChandler** [comment]
同样遇到了你这个问题
