### ISSUE TITLE
宿主provider提供给插件依赖，宿主混淆后，插件找不到，如何处理？

### ISSUE THREAD

**Issue by cr1944** [Qihoo360/RePlugin#719]
#### 问题详细描述 Detailed description of the problem
比如，插件A类继承宿主B类，B类含有一个C类成员变量，怎么处理比较好？

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by hyongbai** [comment]
@keep
