### ISSUE TITLE
插件调起 ：You need to use a Theme.AppCompat theme (or descendant) with this activity

### ISSUE THREAD

**Issue by zhaolei9527** [Qihoo360/RePlugin#72]
插件单独运行无错，主程序中调起报错

![image](https://user-images.githubusercontent.com/23435676/27784510-f562e10c-600c-11e7-9e5d-034ca882595c.png)

**Comment by zhaolei9527** [comment]
apply plugin: 'replugin-plugin-gradle'
我把这局去掉了，完美运行。。。

**Comment by aBenVip** [comment]
@zhaolei9527 去掉这个applay有什么意义呢？求解答

**Comment by zhaolei9527** [comment]
意义在于表示，正确配置报错，错误配置却通过了。

**Comment by aBenVip** [comment]
我这边也卡在这个问题上，暂时还没解决

**Comment by zhaolei9527** [comment]
我也是，等文档再详细点吧。

**Comment by maning0303** [comment]
@zhaolei9527  我也遇到这个问题报错，最后是在插件的每个Acitivty单独配置一个主题，不要application统一配置！就可以了！

**Comment by zhaolei9527** [comment]
@maning0303 正解，成功，完美无误运行。

**Comment by xiangou** [comment]
不行 最正确的姿势是 把插件的VERCODE改成100  并且只能是100
