### ISSUE TITLE
插件继承宿主Activity时，插件内访问不到插件layout资源

### ISSUE THREAD

**Issue by Vove7** [Qihoo360/RePlugin#723]
#720 ### 问题详细描述 Detailed description of the problem

- 在插件Activity 继承 宿主一个重写Activity后，插件中的`setContentView(R.layout.activity_main)`会报错，找不到资源(这个资源位于插件项目res/layout中)
- 取消继承宿主Activity 则不会报错

#### 复现问题步骤 Steps to reproduce the problem
1. 宿主类：`ReturnableActivity`Toolbar带返回图标的Activity
```kotlin
@SuppressLint("Registered")
open class ReturnableActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        supportActionBar?.setDisplayHomeAsUpEnabled(true)
    }

    override fun onOptionsItemSelected(item: MenuItem?): Boolean {
        if (item?.itemId == android.R.id.home) {
            finish()
            return true
        }
        return super.onOptionsItemSelected(item)
    }
}
```
2. 插件`PluginMainActivity`继承`ReturnableActivity`
```kotlin
class PluginMainActivity : ReturnableActivity() {//继承宿主ReturnableActivity

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)//此处报错 找不到资源 ，这个资源位于插件项目res/layout中
   }
}

```
#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.3.1
rePlugin-plugin-lib/gradle Version:2.3.1

Android API Version：Android 8.0
Android 手机型号&ROM(Phone model & ROM): 一加5 氢OS

**Comment by w651441914** [comment]
楼主如何解决的  能说下吗？

**Comment by AddBean** [comment]
同问下，真是无语，被这个卡了好久
