### ISSUE TITLE
使用Gradle4.10.1

### ISSUE THREAD

**Issue by ShuaiXiu** [Qihoo360/RePlugin#724]
ERROR: No signature of method: com.android.build.gradle.internal.scope.VariantScopeImpl.getMergeAssetsTask() is applicable for argument types: () values: []

**Comment by zhrmghgws** [comment]
这个问题修复了吗?

**Comment by ShuaiXiu** [comment]
没有

**Comment by zhrmghgws** [comment]
你现在用的什么版本

**Comment by ShuaiXiu** [comment]
现在不急着用 也就没研究

**Comment by hyongbai** [comment]
#640 duplicated
