### ISSUE TITLE
Demo无法运行 运行直接崩溃 

### ISSUE THREAD

**Issue by Young1999** [Qihoo360/RePlugin#729]
Demo无法运行 运行直接崩溃
安卓5.1  API 22  OPPOA59S
Demo运行系统打印log
com.qihoo360.replugin.sample.host,13123142,java.lang.NullPointerException,Attempt to invoke virtual method 'java.lang.Class[] java.lang.Class.getInterfaces()' on a null object reference,ReflectUtils.java,86]

**Comment by hyongbai** [comment]
@Young1999 可以将完整的栈贴出来吗? 如果有添加代码的话,希望一并贴一下. Thx

**Comment by hyongbai** [comment]
#718 duplicated
