### ISSUE TITLE
如何手动关闭一个正在运行的插件呢？

### ISSUE THREAD

**Issue by androidxiayu** [Qihoo360/RePlugin#730]
#### 问题详细描述 Detailed description of the problem

遇到一个问题，就是插件更新的问题，发现一个插件在运行中的时候，更新了插件，此时去获取插件的PluginInfo 还是老版本的不是最新版本的，在这过程中试过了 在插件更新前，先调用卸载插件，或者是关闭GuardService常驻进程等，均发现没有作用，插件依旧是运行状态，因为应用不允许在当前状态下重启主进程，但是又要保持插件实时能够更新
#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by bnotebook** [comment]
目前的插件化框架包括Replugin都是冷启动更新，现在还不支持热更新操作，想要新版本生效，必须要等到（插件管理进程）常驻进程重启后才可生效。
