### ISSUE TITLE
关于replugin的插件 与宿主 共享库问题

### ISSUE THREAD

**Issue by fengbenpaao** [Qihoo360/RePlugin#733]
#### 问题详细描述 Detailed description of the problem
 1.问题：我的插件与宿主apk都公用一些公共基础库的， 那插件打包的时候或者运行的时候，那些基础包可以与 宿主公用吗？  这样我的插件dex打包就会变小好多；

2.问题：有些中间件， 宿主与插件都同时使用的时候，如何维护这个状态的统一性呢？  比如数据库的增删该查操作？   创建的 操作的数据库对象，可以维持相同的一个吗？  如果是，插件 是通过反射去调用吗？

**Comment by bnotebook** [comment]
问题1：我们近期正在考虑增加“公共库插件”，运行插件之间或者插件与宿主之间共享公共库。或者你也可以通过修改初始化配置，允许插件在找不到类时使用宿主ClassLoader查找来实现。
问题2：公共API，要考虑版本升级，及新旧版本等的兼容性问题，具体如何实现看你自己的设计了，是放到宿主还是插件中，如果是提供公共访问的，建议可以放在插件中，该插件对其他插件和宿主提供服务，这样公共API升级什么的都可以保证唯一。

**Comment by cfJand** [comment]
@bnotebook  请问近期考虑增加“公共库插件” 的进度如何？

**Comment by wangqiang58** [comment]
@bnotebook 公共基插件 目前能解决了吗？
