### ISSUE TITLE
RePlugin.startActivityForResult() 无法打开外置插件中的Activity

### ISSUE THREAD

**Issue by lyongfly** [Qihoo360/RePlugin#734]
#### 复现问题步骤 ：
1. 将插件1（plugin1.apk）作为外置插件进行安装，RePlugin.startActivityForResult() 无法跳转
2. 如果将插件1（plugin1.apk）更改后缀名作为内置插件（plugin1.jar）放到宿主assets目录下的plugins目录，再次运行宿主，同样的代码可以跳转

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:  2.3.1
rePlugin-plugin-lib/gradle Version: 2.3.1

Android API Version：24
Android 手机型号&ROM(Phone model & ROM): 红米4X

#### Logcat上下文 Logcat context
12-06 11:23:31.692 4149-4149/com.cnksi.replugin D/RePlugin.ws001: startActivityForResult: intent=Intent { cmp=com.cnksi.plugin1/.MainActivity } requestCode=100 options=null
    start activity with startActivityForResult: intent=Intent { cmp=com.cnksi.plugin1/.MainActivity }
12-06 11:23:31.693 4149-4149/com.cnksi.replugin D/RePlugin.ws001: PACM: bindActivity: may be invalid plugin name or load plugin failed: plugin=null
    PACM: bindActivity: activity not found

**Comment by hyongbai** [comment]
> 12-06 11:23:31.693 4149-4149/com.cnksi.replugin D/RePlugin.ws001: PACM: bindActivity: may be invalid plugin name or load plugin failed: plugin=null

@lyongfly 外置插件安装成功了没有?  根据这个log情况来看, RePlugin找不到你需要打开的插件.

**Comment by lyongfly** [comment]
已解决，通过在Manifest文件中配置插件别名可以打开，谢谢！
________________________________
发件人: @hyongbai <notifications@github.com>
发送时间: 2018年12月10日 2:52
收件人: Qihoo360/RePlugin
抄送: lyongfly; Mention
主题: Re: [Qihoo360/RePlugin] RePlugin.startActivityForResult() 无法打开外置插件中的Activity (#734)


12-06 11:23:31.693 4149-4149/com.cnksi.replugin D/RePlugin.ws001: PACM: bindActivity: may be invalid plugin name or load plugin failed: plugin=null

@lyongfly<https://github.com/lyongfly> 外置插件安装成功了没有? 根据这个log情况来看, RePlugin找不到你需要打开的插件.

―

**Comment by lookingforwt** [comment]
看源码发现是RePlugin的bug，只要插件名包含.就会被当作宿主处理
```java
 /**
     * 获取插件名称
     */
    private static String getPluginName(Activity activity, Intent intent) {
        String plugin = "";
        if (intent.getComponent() != null) {
            plugin = intent.getComponent().getPackageName();
        }
        // 如果 plugin 是包名，则说明启动的是本插件。
        if (TextUtils.isEmpty(plugin) || plugin.contains(".")) {
            plugin = RePlugin.fetchPluginNameByClassLoader(activity.getClassLoader());
        }
        // 否则是其它插件
        return plugin;
    }
```
