### ISSUE TITLE
插件升级不成功，提示新传入的纯APK插件网优百宝箱版本号还没有内置的大

### ISSUE THREAD

**Issue by yeyutianya** [Qihoo360/RePlugin#735]
#### 问题详细描述 Detailed description of the problem

插件升级不成功，提示新传入的纯APK插件网优百宝箱版本号还没有内置的大；

但是插件中的versionCode和versionName都比原来的大啊。。

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.3.0
rePlugin-plugin-lib/gradle Version:2.2.4

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by markingdom** [comment]
检查一下是否是对比插件那一块写的有问题，打印日志看看

**Comment by yeyutianya** [comment]
> 检查一下是否是对比插件那一块写的有问题，打印日志看看

集成了百度so和jar包的插件会出现，其他插件没出现；
步骤是：
1、先安装成功插件然后启动插件；
2、退出插件和主程序；
3、再次启动主程序检查到插件升级，然后升级插件，发现仍是老插件；

第一次安装成功，不启动插件，然后再升级插件没有问题；或第一次安装完后启动插件，退出后清理进程，再进入也能升级成功

**Comment by hyongbai** [comment]
**正在运行中**的插件是不能直接升级成功的.

安装只会写入到pending当中去., 你可以把install返回的pluginInfo给打印出来.

插件升级需要重新启动APP(并不是说关闭Activity再打开), 你可以把APP杀死再打开.  根据后面的描述复合这一逻辑.

> 第一次安装成功，不启动插件，然后再升级插件没有问题；或第一次安装完后启动插件，退出后清理进程，再进入也能升级成功
