### ISSUE TITLE
EventBus 通信

### ISSUE THREAD

**Issue by fengbenpaao** [Qihoo360/RePlugin#736]
#### 问题详细描述 Detailed description of the problem
    请教一下，插件与宿主之间，好像eventbus 通不了，  宿主与插件是分别在不同的内存空间吗？
因为宿主与插件eventbus注册的内存空间，可能无法查找到对象；

**Comment by hyongbai** [comment]
宿主和插件本身是完全隔离的.  类似于EventBus这种方案的话, 原则是没法进行通信的.

就目前而言:

- 建议使用provided的方式在插件中引入eventbus的库,

-然后在宿主的RePluginConfig注册RePluginCallbacks, 重新createPluginClassLoader.

- 给插件插入一个自己的classloader: 出现eventbus相关的class的时候使用宿主的classloader进行加载.

但你还需要解决发送的对象在插件和宿主中可能来自不同的classloader从而不属于同一个类的问题.

**Comment by fengbenpaao** [comment]
我现在用反射已经找到 宿主的 eventbus   事件xxxEvent，  但是发出去之后，宿主不认；   应该是注册处与发出处，不在一个空间内造成的；   目前看来要实现通信，只有aidl，广播，还有intent了

**Comment by liupeng110** [comment]
饿了么开源跨进程的eventbus可以通信

**Comment by SchafferWang0818** [comment]
> 

这个方案有没有样例代码可以参考啊
