### ISSUE TITLE
插件ClassLoader无法加载layout文件中的控件类

### ISSUE THREAD

**Issue by lihehub** [Qihoo360/RePlugin#738]
#### 问题详细描述 Detailed description of the problem
首次打开插件时，报错ClassNotFoundException，无法加载layout文件中的控件类，例如LinearLayout、Button

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/4705101/49802639-67950880-fd88-11e8-83fa-82418f893e69.png">

#### 复现问题步骤 Steps to reproduce the problem
1. 首次打开某一插件，示例代码：
`RePlugin.startActivity(MainActivity.this,
                        RePlugin.createIntent("com.lihe.homeplugin",
                                "com.lihe.homeplugin.MainActivity"));`

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.3.1
rePlugin-plugin-lib/gradle Version:2.3.1

Android API Version：5.0.1
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context
[RePlugin-插件ClassLoader无法加载layout文件中的控件类.txt](https://github.com/Qihoo360/RePlugin/files/2667676/RePlugin-.ClassLoader.layout.txt)

#### 初步分析 
初步分析，这个问题是由于在 PluginContext 类的 handleCreateView 方法中，也就是 LayoutInflater 创建View时：
loadClass执行加载layout中的控件类，仅传递了控件名，例如“LinearLayout”，“Button”，而不是传递控件类名“android.widget.LinearLayout"、”android.widget.Button“，导致无法找到相应类。如图
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/4705101/49803309-6664db00-fd8a-11e8-9290-914b27d51334.png">

另外，经过分析原生代码中的处理，增加了"prefix"参数，用来拼接完整的类名：
<img width="591" alt="image" src="https://user-images.githubusercontent.com/4705101/49803458-dbd0ab80-fd8a-11e8-9173-0051c85ac300.png">

**Comment by lihehub** [comment]
该问题似乎不影响程序运行，那么该问题是否是真正的"问题"呢？

**Comment by hyongbai** [comment]
这个问题不影响插件运行也是合理的.

PluginContext会在LayoutInflater中插入一个Factory, 用于拦截插件布局中自定义View的加载.  否则直接交给PhoneLayoutInflater, 也就是你说的这段代码了.

```java
    View createViewFromTag(View parent, String name, Context context, AttributeSet attrs,
            boolean ignoreThemeAttr) {
/// ...
        try {
            View view;
            if (mFactory2 != null) {
                view = mFactory2.onCreateView(parent, name, context, attrs);
            } else if (mFactory != null) {
                view = mFactory.onCreateView(name, context, attrs);
            } else {
                view = null;
            }

            if (view == null && mPrivateFactory != null) {
                view = mPrivateFactory.onCreateView(parent, name, context, attrs);
            }

            if (view == null) {
                final Object lastContext = mConstructorArgs[0];
                mConstructorArgs[0] = context;
                try {
                    if (-1 == name.indexOf('.')) {
                        view = onCreateView(parent, name, attrs);
                    } else {
                        view = createView(name, null, attrs);
                    }
                } finally {
                    mConstructorArgs[0] = lastContext;
                }
            }

            return view;
        } catch (InflateException e) {
            throw e;

        } catch (ClassNotFoundException e) {
            final InflateException ie = new InflateException(attrs.getPositionDescription()
                    + ": Error inflating class " + name, e);
            ie.setStackTrace(EMPTY_STACK_TRACE);
            throw ie;

        } catch (Exception e) {
            final InflateException ie = new InflateException(attrs.getPositionDescription()
                    + ": Error inflating class " + name, e);
            ie.setStackTrace(EMPTY_STACK_TRACE);
            throw ie;
        }
    }
```
