### ISSUE TITLE
接入RepluginSDK后下载的插件如何安装？

### ISSUE THREAD

**Issue by zhangbaogithub** [Qihoo360/RePlugin#745]
#### 问题详细描述 Detailed description of the problem
接入了RepluginSDK，下载是正常的，下载之后安装插件是自动安装吗，如果是自动安装的话，我使用RePlugin.getPluginInfoList()方法获取的plugin列表是空的，手动安装的话，我按照文件名安装也没有成功

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.3.1
rePlugin-plugin-lib/gradle Version:2.3.1

Android API Version：27
Android 手机型号&ROM(Phone model & ROM): Xiaomi Redmi 5

#### Logcat上下文 Logcat context
D/RePlugin.ws001: initial local cookie=0
D/LocationUtil: isProviderEnabled=true
D/LocationUtil: locTime = 1545210264302pastTime = 1312974
D/a: no plugin installed
D/a: starting log upload monitor ...
D/PluginManager: replugin sdk start time：30
D/b: read event form disk path
D/b: read events use time :8

**Comment by zhangbaogithub** [comment]
已自行解决，直接启动插件activity，会走自动下载

**Comment by fishyuyu** [comment]
这边遇到SDK无法更新插件的问题
com.qihoo360.plugin.version.ver 的版本号设置的比应用内的高
插件不自动下载，能请教下你的操作么
