### ISSUE TITLE
插件不支持widget

### ISSUE THREAD

**Issue by xiabinger** [Qihoo360/RePlugin#746]
#### 问题详细描述 Detailed description of the problem
请问插件中不能支持widget么？
我在插件中添加了一个widget，但是在laucher中添加widget时找不到我在插件中定义的widget

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by hyongbai** [comment]
不支持。类似的还有TileService等也不支持。
