### ISSUE TITLE
replugin-plugin-gradle:2.1.0无法下载

### ISSUE THREAD

**Issue by Hiram-Y** [Qihoo360/RePlugin#75]
1、新建个插件工程
2、跟目录build.gradle引入classpath 'com.qihoo360.replugin:replugin-plugin-gradle:2.1.0'
3、同步
问题：External Libraries里没有replugin-plugin-lib-2.1.0
![image](https://user-images.githubusercontent.com/7044188/27785828-5e2c16e6-6011-11e7-8771-f78228066c92.png)

**Comment by PengJunJun** [comment]
要在根目录下的build.gradle文件里加上  maven { url "https://dl.bintray.com/qihoo360/replugin" }

**Comment by PengJunJun** [comment]
app目录下build.gradle文件有加上依赖的库吗？

**Comment by Hiram-Y** [comment]
如果app目录下build.gradle文件有加上依赖的库，就会出现#53的问题了

**Comment by PengJunJun** [comment]
#53问题已经解决了，
