### ISSUE TITLE
启动崩溃

### ISSUE THREAD

**Issue by sam-long-li** [Qihoo360/RePlugin#754]
#### 问题详细描述 Detailed description of the problem
启动宿主应用时候在部分手机上打开应该应用后即崩溃
日志如下：

#00     pc 000ebe78    /system/lib/libart.so (void  std::__1::__tree_balance_after_insert<std::__1::__tree_node_base<void*>*>(std::__1::__tree_node_base<void*>*,  std::__1::__tree_node_base<void*>*)+115) [armeabi-v7a]
--
2 #01     pc 001eeb71    /system/lib/libart.so  (std::__1::pair<std::__1::__tree_iterator<std::__1::__value_type<art::MethodReference,  art::SafeMap<unsigned int, std::__1::set<unsigned int,  std::__1::less<unsigned int>, std::__1::allocator<unsigned  int> >, std::__1::less<unsigned int>,  art::TrackingAllocator<std::__1::pair<unsigned int const,  std::__1::set<unsigned int, std::__1::less<unsigned int>,  std::__1::allocator<unsigned int> > >,  (art::AllocatorTag)6> > >,  std::__1::__tree_node<std::__1::__value_type<art::MethodReference,  art::SafeMap<unsigned int, std::__1::set<unsigned int,  std::__1::less<unsigned int>, std::__1::allocator<unsigned  int> >, std::__1::less<unsigned int>,  art::TrackingAllocator<std::__1::pair<unsigned int const,  std::__1::set<unsigned int, std::__1::less<unsigned int>,  std::__1::allocator<unsigned int> > >,  (art::AllocatorTag)6> > >, void*>*, int>, bool>  std::__1::__tree<std::__1::__value_type<art::MethodReference,  art::SafeMap<unsigned int, std::__1::set<unsigned int,  std::__1::less<unsigned int>, std::__1::allocator<unsigned  int> >, std::__1::less<unsigned int>,  art::TrackingAllocator<std::__1::pair<unsigned int const,  std::__1::set<unsigned int, std::__1::less<unsigned int>,  std::__1::allocator<unsigned int> > >,  (art::AllocatorTag)6> > >,  std::__1::__map_value_compare<art::MethodReference,  std::__1::__value_type<art::MethodReference, art::SafeMap<unsigned  int, std::__1::set<unsigned int, std::__1::less<unsigned int>,  std::__1::allocator<unsigned int> >,  std::__1::less<unsigned int>,  art::TrackingAllocator<std::__1::pair<unsigned int const,  std::__1::set<unsigned int, std::__1::less<unsigned int>,  std::__1::allocator<unsigned int> > >,  (art::AllocatorTag)6> > >, art::MethodReferenceComparator,  true>,  std::__1::allocator<std::__1::__value_type<art::MethodReference,  art::SafeMap<unsigned int, std::__1::set<unsigned int,  std::__1::less<unsigned int>, std::__1::allocator<unsigned  int> >, std::__1::less<unsigned int>,  art::TrackingAllocator<std::__1::pair<unsigned int const,  std::__1::set<unsigned int, std::__1::less<unsigned int>,  std::__1::allocator<unsigned int> > >,  (art::AllocatorTag)6> > > >  >::__insert_unique<std::__1::pair<art::MethodReference,  art::SafeMap<unsigned int, std::__1::set<unsigned int,  std::__1::less<unsigned int>, std::__1::allocator<unsigned  int> >, std::__1::less<unsigned int>,  art::TrackingAllocator<std::__1::pair<unsigned int const,  std::__1::set<unsigned int, std::__1::less<unsigned int>,  std::__1::allocator<unsigned int> > >,  (art::AllocatorTag)6> > >  >(std::__1::pair<art::MethodReference, art::SafeMap<unsigned  int, std::__1::set<unsigned int, std::__1::less<unsigned int>,  std::__1::allocator<unsigned int> >, std::__1::less<unsigned  int>, art::TrackingAllocator<std::__1::pair<unsigned int  const, std::__1::set<unsigned int, std::__1::less<unsigned  int>, std::__1::allocator<unsigned int> > >,  (art::AllocatorTag)6> > >&&)+216) [armeabi-v7a]
3 #02     pc 001eebdf    /system/lib/libart.so (bool  art::interpreter::DoFieldGet<(art::FindFieldType)4,  (art::Primitive::Type)0, true>(art::Thread*, art::ShadowFrame&,  art::Instruction const*, unsigned short)+70) [armeabi-v7a]
4 #03     pc 001ef0e5    /system/lib/libart.so (bool  art::interpreter::DoCall<false, false>(art::ArtMethod*,  art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned  short, art::JValue*)+1220) [armeabi-v7a]
5 #04     pc 000b2ccd    /system/lib/libart.so (art::JValue  art::interpreter::ExecuteGotoImpl<false, false>(art::Thread*,  art::DexFile::CodeItem const*, art::ShadowFrame&,  art::JValue)+27172) [armeabi-v7a]
6 #05    pc 001d4eef    /system/lib/libart.so (artInterpreterToInterpreterBridge+126) [armeabi-v7a]
7 #06     pc 001eed67    /system/lib/libart.so (bool  art::interpreter::DoCall<false, false>(art::ArtMethod*,  art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned  short, art::JValue*)+326) [armeabi-v7a]
8 #07     pc 001f0f29    /system/lib/libart.so (bool  art::interpreter::DoFieldPut<(art::FindFieldType)3,  (art::Primitive::Type)2, true, true>(art::Thread*, art::ShadowFrame  const&, art::Instruction const*, unsigned short)+148) [armeabi-v7a]
9 #08     pc 000b2e0d    /system/lib/libart.so (art::JValue  art::interpreter::ExecuteGotoImpl<false, false>(art::Thread*,  art::DexFile::CodeItem const*, art::ShadowFrame&,  art::JValue)+27492) [armeabi-v7a]
10 #09    pc 001d4eef    /system/lib/libart.so (artInterpreterToInterpreterBridge+126) [armeabi-v7a]
11 #10     pc 001eed67    /system/lib/libart.so (bool  art::interpreter::DoCall<false, false>(art::ArtMethod*,  art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned  short, art::JValue*)+326) [armeabi-v7a]
12 #11     pc 000b28a9    /system/lib/libart.so (art::JValue  art::interpreter::ExecuteGotoImpl<false, false>(art::Thread*,  art::DexFile::CodeItem const*, art::ShadowFrame&,  art::JValue)+26112) [armeabi-v7a]
13 #12    pc 001d4eef    /system/lib/libart.so (artInterpreterToInterpreterBridge+126) [armeabi-v7a]
14 #13     pc 001eed67    /system/lib/libart.so (bool  art::interpreter::DoCall<false, false>(art::ArtMethod*,  art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned  short, art::JValue*)+326) [armeabi-v7a]
15 #14     pc 001f2bc5    /system/lib/libart.so (bool  art::interpreter::DoFieldPut<(art::FindFieldType)7,  (art::Primitive::Type)4, true, true>(art::Thread*, art::ShadowFrame  const&, art::Instruction const*, unsigned short)+468) [armeabi-v7a]
16 #15     pc 000b2949    /system/lib/libart.so (art::JValue  art::interpreter::ExecuteGotoImpl<false, false>(art::Thread*,  art::DexFile::CodeItem const*, art::ShadowFrame&,  art::JValue)+26272) [armeabi-v7a]
17 #16    pc 001d4eef    /system/lib/libart.so (artInterpreterToInterpreterBridge+126) [armeabi-v7a]
18 #17     pc 001eed67    /system/lib/libart.so (bool  art::interpreter::DoCall<false, false>(art::ArtMethod*,  art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned  short, art::JValue*)+326) [armeabi-v7a]
19 #18     pc 000b2ccd    /system/lib/libart.so (art::JValue  art::interpreter::ExecuteGotoImpl<false, false>(art::Thread*,  art::DexFile::CodeItem const*, art::ShadowFrame&,  art::JValue)+27172) [armeabi-v7a]
20 #19    pc 001d4eef    /system/lib/libart.so (artInterpreterToInterpreterBridge+126) [armeabi-v7a]
21 #20     pc 001eed67    /system/lib/libart.so (bool  art::interpreter::DoCall<false, false>(art::ArtMethod*,  art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned  short, art::JValue*)+326) [armeabi-v7a]
22 #21     pc 000b28a9    /system/lib/libart.so (art::JValue  art::interpreter::ExecuteGotoImpl<false, false>(art::Thread*,  art::DexFile::CodeItem const*, art::ShadowFrame&,  art::JValue)+26112) [armeabi-v7a]
23 #22    pc 001d4eef    /system/lib/libart.so (artInterpreterToInterpreterBridge+126) [armeabi-v7a]
24 #23     pc 001eed67    /system/lib/libart.so (bool  art::interpreter::DoCall<false, false>(art::ArtMethod*,  art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned  short, art::JValue*)+326) [armeabi-v7a]

#### 复现问题步骤 Steps to reproduce the problem
1. 打开宿主应用

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.3.0
rePlugin-plugin-lib/gradle Version:2.3.0

Android API Version：android 6.0.1
Android 手机型号&ROM(Phone model & ROM): oppo A57

**Comment by bnotebook** [comment]
RePlugin在常见Rom中不会存在该类问题，建议使用Demo在该机型上运行，然后对比你的应用和Demo配置有什么不同。

**Comment by sonuan** [comment]
> #### 问题详细描述 Detailed description of the problem
> 启动宿主应用时候在部分手机上打开应该应用后即崩溃
> 日志如下：
> 
> ## #00 pc 000ebe78 /system/lib/libart.so (void std::__1::__tree_balance_after_insert<std::__1::__tree_node_base<void*>_>(std::__1::__tree_node_base<void_>_, std::__1::__tree_node_base<void_>*)+115) [armeabi-v7a]
> 2 #1 pc 001eeb71 /system/lib/libart.so (std::__1::pair<std::__1::__tree_iterator<std::__1::__value_type<art::MethodReference, art::SafeMap<unsigned int, std::__1::set<unsigned int, std::__1::less, std::__1::allocator >, std::__1::less, art::TrackingAllocator<std::__1::pair<unsigned int const, std::__1::set<unsigned int, std::__1::less, std::__1::allocator > >, (art::AllocatorTag)6> > >, std::__1::__tree_node<std::__1::__value_type<art::MethodReference, art::SafeMap<unsigned int, std::__1::set<unsigned int, std::__1::less, std::__1::allocator >, std::__1::less, art::TrackingAllocator<std::__1::pair<unsigned int const, std::__1::set<unsigned int, std::__1::less, std::__1::allocator > >, (art::AllocatorTag)6> > >, void*>_, int>, bool> std::__1::__tree<std::__1::__value_type<art::MethodReference, art::SafeMap<unsigned int, std::__1::set<unsigned int, std::__1::less, std::__1::allocator >, std::__1::less, art::TrackingAllocator<std::__1::pair<unsigned int const, std::__1::set<unsigned int, std::__1::less, std::__1::allocator > >, (art::AllocatorTag)6> > >, std::__1::__map_value_compare<art::MethodReference, std::__1::__value_type<art::MethodReference, art::SafeMap<unsigned int, std::__1::set<unsigned int, std::__1::less, std::__1::allocator >, std::__1::less, art::TrackingAllocator<std::__1::pair<unsigned int const, std::__1::set<unsigned int, std::__1::less, std::__1::allocator > >, (art::AllocatorTag)6> > >, art::MethodReferenceComparator, true>, std::__1::allocator<std::__1::__value_type<art::MethodReference, art::SafeMap<unsigned int, std::__1::set<unsigned int, std::__1::less, std::__1::allocator >, std::__1::less, art::TrackingAllocator<std::__1::pair<unsigned int const, std::__1::set<unsigned int, std::__1::less, std::__1::allocator > >, (art::AllocatorTag)6> > > > >::__insert_unique<std::__1::pair<art::MethodReference, art::SafeMap<unsigned int, std::__1::set<unsigned int, std::__1::less, std::__1::allocator >, std::__1::less, art::TrackingAllocator<std::__1::pair<unsigned int const, std::__1::set<unsigned int, std::__1::less, std::__1::allocator > >, (art::AllocatorTag)6> > > >(std::__1::pair<art::MethodReference, art::SafeMap<unsigned int, std::__1::set<unsigned int, std::__1::less, std::__1::allocator >, std::__1::less, art::TrackingAllocator<std::__1::pair<unsigned int const, std::__1::set<unsigned int, std::__1::less, std::__1::allocator > >, (art::AllocatorTag)6> > >&&)+216) [armeabi-v7a] 3 #2 pc 001eebdf /system/lib/libart.so (bool art::interpreter::DoFieldGet<(art::FindFieldType)4, (art::Primitive::Type)0, true>(art::Thread_, art::ShadowFrame&, art::Instruction const*, unsigned short)+70) [armeabi-v7a]
> 4 #3 pc 001ef0e5 /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+1220) [armeabi-v7a]
> 5 #4 pc 000b2ccd /system/lib/libart.so (art::JValue art::interpreter::ExecuteGotoImpl<false, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue)+27172) [armeabi-v7a]
> 6 #5 pc 001d4eef /system/lib/libart.so (artInterpreterToInterpreterBridge+126) [armeabi-v7a]
> 7 #6 pc 001eed67 /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+326) [armeabi-v7a]
> 8 #7 pc 001f0f29 /system/lib/libart.so (bool art::interpreter::DoFieldPut<(art::FindFieldType)3, (art::Primitive::Type)2, true, true>(art::Thread*, art::ShadowFrame const&, art::Instruction const*, unsigned short)+148) [armeabi-v7a]
> 9 #8 pc 000b2e0d /system/lib/libart.so (art::JValue art::interpreter::ExecuteGotoImpl<false, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue)+27492) [armeabi-v7a]
> 10 #9 pc 001d4eef /system/lib/libart.so (artInterpreterToInterpreterBridge+126) [armeabi-v7a]
> 11 #10 pc 001eed67 /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+326) [armeabi-v7a]
> 12 #11 pc 000b28a9 /system/lib/libart.so (art::JValue art::interpreter::ExecuteGotoImpl<false, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue)+26112) [armeabi-v7a]
> 13 #12 pc 001d4eef /system/lib/libart.so (artInterpreterToInterpreterBridge+126) [armeabi-v7a]
> 14 #13 pc 001eed67 /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+326) [armeabi-v7a]
> 15 #14 pc 001f2bc5 /system/lib/libart.so (bool art::interpreter::DoFieldPut<(art::FindFieldType)7, (art::Primitive::Type)4, true, true>(art::Thread*, art::ShadowFrame const&, art::Instruction const*, unsigned short)+468) [armeabi-v7a]
> 16 #15 pc 000b2949 /system/lib/libart.so (art::JValue art::interpreter::ExecuteGotoImpl<false, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue)+26272) [armeabi-v7a]
> 17 #16 pc 001d4eef /system/lib/libart.so (artInterpreterToInterpreterBridge+126) [armeabi-v7a]
> 18 #17 pc 001eed67 /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+326) [armeabi-v7a]
> 19 #18 pc 000b2ccd /system/lib/libart.so (art::JValue art::interpreter::ExecuteGotoImpl<false, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue)+27172) [armeabi-v7a]
> 20 #19 pc 001d4eef /system/lib/libart.so (artInterpreterToInterpreterBridge+126) [armeabi-v7a]
> 21 #20 pc 001eed67 /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+326) [armeabi-v7a]
> 22 #21 pc 000b28a9 /system/lib/libart.so (art::JValue art::interpreter::ExecuteGotoImpl<false, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue)+26112) [armeabi-v7a]
> 23 #22 pc 001d4eef /system/lib/libart.so (artInterpreterToInterpreterBridge+126) [armeabi-v7a]
> 24 #23 pc 001eed67 /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+326) [armeabi-v7a]
> 
> #### 复现问题步骤 Steps to reproduce the problem
> 1. 打开宿主应用
> 
> #### 其它重要信息 Other important information
> replugin-host-lib/gradle Version:2.3.0
> rePlugin-plugin-lib/gradle Version:2.3.0
> 
> Android API Version：android 6.0.1
> Android 手机型号&ROM(Phone model & ROM): oppo A57
> 
> #### Logcat上下文 Logcat context

你的问题解决了吗？我这也出现了。 如果解决了，麻烦分享下问题所在？谢谢！

**Comment by tangpeng** [comment]
有没有新的进展,我的也出现了,都是在android 6.0.1系统上面

**Comment by louzhen** [comment]
大佬, 能否同步下解决方式
