### ISSUE TITLE
使用com.android.tools.build:gradle:3.2.1编译不过

### ISSUE THREAD

**Issue by wangbo4020** [Qihoo360/RePlugin#761]
#### 问题详细描述 Detailed description of the problem
使用com.android.tools.build:gradle:3.2.1编译不过，Build时报错

#### 复现问题步骤 Steps to reproduce the problem
1. 根目录build.gradle使用以下配置
buildscript {
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
    }
}

#### 其它重要信息 Other important information
错误信息：
No signature of method: com.android.build.gradle.internal.scope.VariantScopeImpl.getMergeAssetsTask() is applicable for argument types: () values: []

replugin-host-lib/gradle Version: 2.3.1
rePlugin-plugin-lib/gradle Version: 2.3.1

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by SheepYang1993** [comment]
https://github.com/Qihoo360/RePlugin/pull/737
这个issue已经解决了，麻烦发布下新的version

**Comment by ltyhome** [comment]
等2.3.2么？现在很多用androidx的只能gradle plugin3.2以上

**Comment by liunewshine** [comment]
求尽快发布，越到同样的问题，降级gradle plugin不是好方式

**Comment by mflk007** [comment]
尽快升级sample项目的gradle plugin啊  classpath 'com.android.tools.build:gradle:3.3.2' 无法使用

**Comment by hyongbai** [comment]
> #737
> 这个issue已经解决了，麻烦发布下新的version

done
