### ISSUE TITLE
插件加固

### ISSUE THREAD

**Issue by xiguanxingxiahuaxian** [Qihoo360/RePlugin#762]
宿主加载加固后的APP，无法找到插件的启动路径报错，如果不加固，可以正常启动情况如下：
E/ws001: Didn't find class "ad.origin.com.ddyypayproject.view.SlashActivity" on path: DexPathList[[zip file "/data/user/0/dy.neusoft.com.dyproject/app_p_a/-1660103925.jar"],nativeLibraryDirectories=[/data/user/0/dy.neusoft.com.dyproject/app_p_n/-1660103925, /system/lib64, /vendor/lib64]]
         java.lang.ClassNotFoundException: Didn't find class "ad.origin.com.ddyypayproject.view.SlashActivity" on path: DexPathList[[zip file "/data/user/0/dy.neusoft.com.dyproject/app_p_a/-1660103925.jar"],nativeLibraryDirectories=[/data/user/0/dy.neusoft.com.dyproject/app_p_n/-1660103925, /system/lib64, /vendor/lib64]]
请问，现在有没有好的办法启动360加固过的插件app?

**Comment by mason-Wang** [comment]
插件加固目前支持吗？

**Comment by bnotebook** [comment]
RePlugin是可以适配360加固保的。你的这个问题可以联系下加固团队，应该和插件化框架没多大关系。

**Comment by drachuojin** [comment]
请问插件能用360加固宝加固吗？

**Comment by drachuojin** [comment]
@bnotebook
