### ISSUE TITLE
内置插件升级成外置插件成功后，重启app打印来的插件版本号还是内置插件的版本号而不是升级后的版本号

### ISSUE THREAD

**Issue by qq1728744610** [Qihoo360/RePlugin#763]
#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by bnotebook** [comment]
首先确认下是否升级成功。如果升级成功了，可以查下自己的插件版本配置的地方是否有问题。我们目前没遇到过类似的问题，你可以先确认下是否是设置的问题导致的吧。

**Comment by qq1728744610** [comment]
> 首先确认下是否升级成功。如果升级成功了，可以查下自己的插件版本配置的地方是否有问题。我们目前没遇到过类似的问题，你可以先确认下是否是设置的问题导致的吧。

貌似当时用的是2.3.1版本的，然后gradle用的是4.x，后面升级到2.3.2就没有遇到这样的问题了

**Comment by chinaShawn** [comment]
我现在遇到的问题是，内置插件升级成功，能看到app_p_a 文件夹下面有对应的p.l文件和对应的jar，能看到版本号是3，但是重启host后读取内容的时候，还是读取的app_plugins_v3这个文件夹下面的。app_plugins_v3这个文件夹下面还是版本号为3的插件，有没有大神知晓原因的
