### ISSUE TITLE
较低概率在启动时installProvider/instantiate service出现ClassNotFoundException

### ISSUE THREAD

**Issue by fupSZ** [Qihoo360/RePlugin#764]
#### 问题详细描述 Detailed description of the problem
crash1：
java.lang.RuntimeException: Unable to get provider com.exam.oaps.api.host.CallbackProvider: java.lang.ClassNotFoundException: Didn't find class "com.exam.oaps.api.host.CallbackProvider" on path: DexPathList[[zip file "/data/app/com.android.browser-ECQZc9uEWl5wV8F4-Tprlw==/base.apk"],nativeLibraryDirectories=[/data/app/com.android.browser-ECQZc9uEWl5wV8F4-Tprlw==/lib/arm, /data/app/com.android.browser-ECQZc9uEWl5wV8F4-Tprlw==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
at android.app.ActivityThread.installProvider(ActivityThread.java:6676)
at android.app.ActivityThread.installContentProviders(ActivityThread.java:6174)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6091)
at android.app.ActivityThread.-wrap1(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1828)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:197)
at android.app.ActivityThread.main(ActivityThread.java:6977)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:514)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.exam.oaps.api.host.CallbackProvider" on path: DexPathList[[zip file "/data/app/com.android.browser-ECQZc9uEWl5wV8F4-Tprlw==/base.apk"],nativeLibraryDirectories=[/data/app/com.android.browser-ECQZc9uEWl5wV8F4-Tprlw==/lib/arm, /data/app/com.android.browser-ECQZc9uEWl5wV8F4-Tprlw==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
at com.qihoo360.replugin.RePluginClassLoader.findClass(RePluginClassLoader.java:172)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at com.qihoo360.replugin.RePluginClassLoader.loadClass(RePluginClassLoader.java:163)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
at android.app.ActivityThread.installProvider(ActivityThread.java:6661)
... 10 more

crash2：
java.lang.ClassNotFoundException
android.app.ActivityThread.installProvider(ActivityThread.java:6733)
android.app.ActivityThread.installContentProviders(ActivityThread.java:6231)
android.app.ActivityThread.handleBindApplication(ActivityThread.java:6139)
android.app.ActivityThread.-wrap1(Unknown Source:0)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1840)
android.os.Handler.dispatchMessage(Handler.java:106)
android.os.Looper.loop(Looper.java:200)
android.app.ActivityThread.main(ActivityThread.java:7038)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:521)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: DexPathList[[zip file "/data/app/com.coloros.yoli-2dhR4r-s6Ifr_LRfM2M0VQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.coloros.yoli-2dhR4r-s6Ifr_LRfM2M0VQ==/lib/arm, /data/app/com.coloros.yoli-2dhR4r-s6Ifr_LRfM2M0VQ==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
com.qihoo360.replugin.e.findClass(RePluginClassLoader.java:172)
java.lang.ClassLoader.loadClass(ClassLoader.java:379)
com.qihoo360.replugin.e.loadClass(RePluginClassLoader.java:163)
java.lang.ClassLoader.loadClass(ClassLoader.java:312)
android.app.ActivityThread.installProvider(ActivityThread.java:6718) ... 10 more

crash3:
java.lang.ClassNotFoundException
Didn't find class "com.qihoo360.replugin.component.service.server.PluginPitServiceUI" on path: DexPathList[[zip file "/data/app/com.coloros.yoli-1/base.apk"],nativeLibraryDirectories=[/data/app/com.coloros.yoli-1/lib/arm, /data/app/com.coloros.yoli-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
java.lang.RuntimeException:Unable to instantiate service com.qihoo360.replugin.component.service.server.PluginPitServiceUI: java.lang.ClassNotFoundException: Didn't find class "com.qihoo360.replugin.component.service.server.PluginPitServiceUI" on path: DexPathList[[zip file "/data/app/com.coloros.yoli-1/base.apk"],nativeLibraryDirectories=[/data/app/com.coloros.yoli-1/lib/arm, /data/app/com.coloros.yoli-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
2 android.app.ActivityThread.handleCreateService(ActivityThread.java:2862)
3 ......
4 Caused by:
5 java.lang.ClassNotFoundException:Didn't find class "com.qihoo360.replugin.component.service.server.PluginPitServiceUI" on path: DexPathList[[zip file "/data/app/com.coloros.yoli-1/base.apk"],nativeLibraryDirectories=[/data/app/com.coloros.yoli-1/lib/arm, /data/app/com.coloros.yoli-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
6 dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:59)
7 com.qihoo360.replugin.e.findClass(RePluginClassLoader.java:172)
8 java.lang.ClassLoader.loadClass(ClassLoader.java:511)
9 com.qihoo360.replugin.e.loadClass(RePluginClassLoader.java:163)
10 java.lang.ClassLoader.loadClass(ClassLoader.java:469)
11 android.app.ActivityThread.handleCreateService(ActivityThread.java:2859)
12 android.app.ActivityThread.-wrap4(ActivityThread.java)
13 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
14 android.os.Handler.dispatchMessage(Handler.java:104)
15 android.os.Looper.loop(Looper.java:148)
16 android.app.ActivityThread.main(ActivityThread.java:5417)
17 java.lang.reflect.Method.invoke(Native Method)
18 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
19 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

上述crash均为偶发，且出现概率较低，看起来好像是host的classLoader没有加载到该类，但事实上这些类都是存在于apk中的，且出现机型在android 5.0以上

**Comment by bnotebook** [comment]
请提供详细的复现步骤及信息

**Comment by fupSZ** [comment]
> 请提供详细的复现步骤及信息

是通过类似bugly这样的平台搜集上来的，所以没有复现步骤。

**Comment by wangxp423** [comment]
我也出现类似的问题。我是将我原本的apk接入host想让他作为宿主。然后就依赖了replugin然后就直接运行崩溃，跑都跑不起来了。

**Comment by wangxp423** [comment]
我昨天又出现类似问题了。但是我这个是必现的，后来发现是我在Application没有接入replugin的application

**Comment by bnotebook** [comment]
这个看起来像是Provider的配置出错导致的，找不到对应的类对象。你可以查看下类的继承关系或者插件/宿主的apk是否有相应的类来处理下吧。
