### ISSUE TITLE
Application.ActivityLifecycleCallbacks 的onActivityCreated 取到的activity instanceof fragmentActivity 结果错了

### ISSUE THREAD

**Issue by skyer518** [Qihoo360/RePlugin#766]
#### 问题详细描述 Detailed description of the problem
我在插件中有一个activity继承自FragmentActivty
但是我在插件的中的 Application.ActivityLifecycleCallbacks 的onActivityCreated 取到的activity instanceof fragmentActivity 的结果却是 false.
在这个activity的oncreate中，得到的结果是true
请问大神，这个是哪用错了？

#### 复现问题步骤 Steps to reproduce the problem
1. 
![v5n 9i _ e q1uhj5for375](https://user-images.githubusercontent.com/10769494/52775830-890dbb80-307b-11e9-921f-5b1bf18a1a1f.png)

2. 
![image](https://user-images.githubusercontent.com/10769494/52775732-4d72f180-307b-11e9-9fc2-8f01076c93ea.png)

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.3.1
rePlugin-plugin-lib/gradle Version:2.3.1

Android API Version：21
Android 手机型号&ROM(Phone model & ROM): oneplus one,  H2Os Rom

**Comment by bnotebook** [comment]
你在Activity内部强转是没有问题的，但是你在Application中强转就可能会出问题，是不安全的。Application中识别的是Activity，而不是FragmentActivty。建议不要使用你目前的方式强转，非常危险！

**Comment by houzirui** [comment]
因为你插件中的activity的classLoader和你宿主中application的lifcyclecallback中的FragmentActivity的classLoader不一致！
