### ISSUE TITLE
低概率异常

### ISSUE THREAD

**Issue by yyfBlog** [Qihoo360/RePlugin#769]
#### 问题详细描述 Detailed description of the problem
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.xxx/com.xxx.xxx}: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.gzytgk.model_advertisement.AdverAudioFragment: make sure class name exists, is public, and has an empty constructor that is public

#### 复现问题步骤 Steps to reproduce the problem
1. 重Android的进程菜单中，杀死进程，然后重启app，偶尔会出现上述异常

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.2.4
rePlugin-plugin-lib/gradle Version:2.2.4

Android API Version：
Android 4.4

**Comment by bnotebook** [comment]
当app在后台因内存不足被杀后 在最近任务中打开该app会重建被杀前的页面  由于是反射创建而这时被创建的组件如果没有默认构造函数或不是静态的就会抛该异常。构造函数必须被public修饰   必须有默认构造函数、必须是静态类、能通过反射创建对象。

**Comment by yyfBlog** [comment]
有构造函数,并且构造函数时public的
