### ISSUE TITLE
Wiki中高级话题里面的演讲和视频链接失效了

### ISSUE THREAD

**Issue by FeatherHunter** [Qihoo360/RePlugin#774]
https://github.com/Qihoo360/RePlugin/wiki/%E9%AB%98%E7%BA%A7%E8%AF%9D%E9%A2%98

《RePlugin，让插件化“飞入寻常应用家”》 —— @开源中国
《360手机卫士插件化RePlugin今日开源，官方全面解读》 —— @CSDN

**Comment by bnotebook** [comment]
这个是第三方的行为，视频可能下架了，非常抱歉~
