### ISSUE TITLE
插件中使用动态库so文件无法加载问题&临时解决

### ISSUE THREAD

**Issue by rabbitknight** [Qihoo360/RePlugin#776]
#### 问题详细描述 Detailed description of the problem
插件中使用.so文件无法加载。
会抛出java.lang.UnsatisfiedLinkError 异常

#### <font color='red'>暂时解决办法 Temp Solution</font>
1. 如果UnsatisfiedLinkError 异常中有system/lib64 要确认下插件中使用so是32位还是64位。
2. 如果是32位的so，**在宿主中**，建一个jniLibs 并 引入一个32位的so。
3. 宿主和插件中都设置一下eabi过滤。
4. 重新试一下。

#### 复现问题步骤 Steps to reproduce the problem
1.  插件中使用 .so文件
2.  宿主中不适用.so

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.3.1
rePlugin-plugin-lib/gradle Version:2.3.1

Android API Version：Andorid 7
Android 手机型号&ROM(Phone model & ROM): 
华为PAD 5

#### Logcat上下文 Logcat context
不列。

**Comment by wangxp423** [comment]
你好，我这边也出现了这个问题。我这边是这样的。我在插件和宿主中都调用了System.load 加载so库文件，结果跟我说宿主已经load了。插件不能再load了 然后就异常了。

**Comment by heiguigui** [comment]
> 你好，我这边也出现了这个问题。我这边是这样的。我在插件和宿主中都调用了System.load 加载so库文件，结果跟我说宿主已经load了。插件不能再load了 然后就异常了。

哥们，这个问题我也遇到了，有什么解决办法么

**Comment by rabbitknight** [comment]
@heiguigui 一般来同名so在同一个app进程只应该load一次。
如果宿主已经加载过的so，理论插件不需要加载，就可以直接使用。
除非二者有冲突。（仅是名称一样内容有差异）。
可以考虑把插件的so移除或者把异常catch住，看看能不能正常调用。
如果还不行。贴具体的异常问题。

**Comment by sushineguo** [comment]
> @heiguigui 一般来同名so在同一个app进程只应该load一次。
> 如果宿主已经加载过的so，理论插件不需要加载，就可以直接使用。
> 除非二者有冲突。（仅是名称一样内容有差异）。
> 可以考虑把插件的so移除或者把异常catch住，看看能不能正常调用。
> 如果还不行。贴具体的异常


单独插件的话，不加载so包会报错啊，如果so都放在宿主加载。
