### ISSUE TITLE
install外部apk，pluginInfo == null，重启插件也是旧的插件无法替换，或者成功安装新的插件版本

### ISSUE THREAD

**Issue by Wish1820** [Qihoo360/RePlugin#778]
#### 问题详细描述

 install外部apk，pluginInfo == null，重启插件也是旧的插件无法替换，或者成功安装新的插件版本

#### 复现问题步骤 Steps to reproduce the problem
1. 插件A，内置在app中，版本号为50
2. app通过install，安装插件A的新版本100，install返回null，重启app，也未成功安装新的插件版本

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.3.0
rePlugin-plugin-lib/gradle Version:2.3.0

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 
小米5 8.0
#### Logcat上下文 Logcat context
通过源码分析，我写了以下文章，有兴趣同学的可以一起研究下
https://blog.csdn.net/Wish1820/article/details/88664975

**Comment by bnotebook** [comment]
这个应该是install没有成功导致的。如果install过程会通过各种安全校验等逻辑，应该是某一步失败了。可以把RePlugin的源码下载下来，调试下，找到出错位置来解决。
