### ISSUE TITLE
如何让宿主使用登录插件的功能

### ISSUE THREAD

**Issue by FeatherHunter** [Qihoo360/RePlugin#785]
有多个宿主apk，有一个登录插件。
宿主如何通过插件模块检测到现在是否处于登陆状态？
我知道如何startActivity跳转到登录模块的登录页面，但是不知道宿主如何在进行操作时，能检查到登录状态？有什么好的设计思路吗？
感谢大神们指导！

**Comment by bnotebook** [comment]
跨插件或者进程进行通信，可以使用AIDL，在插件中提供AIDL接口查询即可，或者使用Provider也可以实现数据共享。
