### ISSUE TITLE
宿主APP（桌面应用）无法启动，请各位帮忙看看，谢谢

### ISSUE THREAD

**Issue by xiaoliang2016** [Qihoo360/RePlugin#786]
#### 问题详细描述 Detailed description of the problem
宿主APP（桌面应用）无法启动，请各位帮忙看看，谢谢

#### 复现问题步骤 Steps to reproduce the problem
1. 将宿主APP安装到机顶盒上，通过弹出的桌面选择框，选择后可以正常启动
2. 启动后进入系统设置，将宿主APP设置为默认桌面重启机顶盒，无法启动APP

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.3.1
rePlugin-plugin-lib/gradle Version:2.3.1

Android API Version：7.0
Android 手机型号&ROM(Phone model & ROM): 机顶盒

怀疑播放器启动时，系统还没有完全启动完的情况下，桌面启动后在初始化插件过程中出错，而如果手动选择桌面启动，没有改问题。

#### Logcat上下文 Logcat context
无法启动的情况下循环打印如下日志信息：

ActivityManager: Start proc 5504:cn.xxxx.launcher/u0a28 for activity cn.xxxx.launcher/.MainActivity
03-26 12:12:21.935  5504  5504 D RePlugin.ws001: plugin process checker: default, index=0
03-26 12:12:21.949  5504  5504 D RePlugin.ws001: PACM: restore table: size=0
03-26 12:12:21.949  5504  5504 D RePlugin.ws001: list plugins from persistent process
03-26 12:12:21.951  5504  5504 E ActivityThread: Failed to find provider info for cn.xxxx.launcher.loader.p.main
03-26 12:12:21.951  5504  5504 D RePlugin.ws001: proxy fetch binder: cursor is null
03-26 12:12:21.951  5504  5504 D RePlugin.ws001: host binder = null
03-26 12:12:21.951  5504  5504 E ws001   : p.p fhb fail
03-26 12:12:21.952  5504  5504 I art     : System.exit called, status: 1
03-26 12:12:21.952  5504  5504 I AndroidRuntime: VM exiting with result code 1, cleanup skipped.
03-26 12:12:21.965  2067  2752 I ActivityManager: Process cn.xxxx.launcher (pid 5504) has died
03-26 12:12:21.965  2067  2752 D ActivityManager: cleanUpApplicationRecord -- 5504
03-26 12:12:21.966  2067  2752 D PackageManager: Package cn.xxxx.launcher is not encryption aware!
03-26 12:12:21.966  1668  1668 I Zygote  : Process 5504 exited cleanly (1)
03-26 12:12:21.974  5522  5522 I art     : Late-enabling -Xcheck:jni

**Comment by bnotebook** [comment]
art : System.exit called, status: 1，系统退出了把，这个可能跟你的启动时机有关系，或者系统错误导致的。
