### ISSUE TITLE
Socket服务端作为插件，客户端连接失败。单独安装，客户端能够连接成功。

### ISSUE THREAD

**Issue by zuzhao** [Qihoo360/RePlugin#787]
#### 问题详细描述 Detailed description of the problem
Socket服务端作为插件，客户端连接失败。单独安装，客户端能够连接成功。

#### 复现问题步骤 Steps to reproduce the problem
1. 使用androidSocketClient框架，作为服务端，并作为插件。
2. 成功启动插件后，客户端无法连接。
3. 单独安装，能够成功连接。

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by bnotebook** [comment]
RePlugin不会影响网络请求的。失败原因猜测：请检查Context是否一致，或者其他多进程相关原因导致的。
