### ISSUE TITLE
单独编译插件demo 1 报错：Failed to apply plugin [id 'replugin-plugin-gradle']， 看了评论没找到有效的解决方案， help！，谢谢

### ISSUE THREAD

**Issue by YanJerry97** [Qihoo360/RePlugin#79]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:

**Android compile SDK version**:

**Android ROM**:

**Comment by wangyupeng1-iri** [comment]
看#53解决方案

**Comment by wangyupeng1-iri** [comment]
或者看我为解决这个问题提交的[commit历史](https://github.com/wangyupeng1-iri/TestRePlugin_plugin/commits/master)

**Comment by wangyupeng1-iri** [comment]
请切换到最新版本，具体请查看wiki发行版本
