### ISSUE TITLE
复写createCallbacks白屏

### ISSUE THREAD

**Issue by yeqinfu** [Qihoo360/RePlugin#792]
#### 问题详细描述 Detailed description of the problem

createCallbacks 想要复写这个方法返回自己定义的一个MyRepluginCallback 只要复写就会导致
白屏。通过调试发现，只要复写这个方法，就会导致PluginProviderStub这个类的proxyFetchHostBinder方法中
 cursor = context.getContentResolver().query(uri, PROJECTION_MAIN, selection, (String[])null, (String)null);
返回一个null。如果不复写就没问题。
#### 复现问题步骤 Steps to reproduce the problem
1. 复写app中createCallbacks方法
2. 运行白屏

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.3.1
rePlugin-plugin-lib/gradle Version:2.3.1

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 
红米note7 或者as模拟器

**Comment by yeqinfu** [comment]
后面发现写成内部类，就没有问题

**Comment by hyongbai** [comment]
@yeqinfu 

RePluginCallbacks被RePluginConfig以强引用的方式保存起来的，跟内部类/匿名内部类应该没关系。

这个问题，可能不是这里发生的，比如你们有没有重写哪些方法？

可否协助查看有没有相关的错误信息？

如无问题，劳烦将 issue 关闭。
