### ISSUE TITLE
RePlugin.PluginInfoList: load: Read Json error!

### ISSUE THREAD

**Issue by rookie001** [Qihoo360/RePlugin#793]
#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by hyongbai** [comment]
#811 与这个 BUG 类似。
