### ISSUE TITLE
插件化后，找不到okhttp.MediaType类

### ISSUE THREAD

**Issue by rookie001** [Qihoo360/RePlugin#794]
#### 问题详细描述 Detailed description of the problem
Caused by : java.lang.ClassNotFoundException: Didn't find class "okhttp3.MediaType" on path DexPathList[......]

#### 复现问题步骤 Steps to reproduce the problem
每次必现

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by bnotebook** [comment]
请检查一下context是否正确，没有该类，应该是context环境中没有相应的类文件，看下自己的设置是否正确。
