### ISSUE TITLE
主程序跳转到插件程序时，插件程序无法加载到资源文件

### ISSUE THREAD

**Issue by panyiyiyi** [Qihoo360/RePlugin#796]
#### 问题详细描述 Detailed description of the problem
主程序跳转到插件程序时，插件程序无法加载到资源文件，只显示黑屏

#### 复现问题步骤 Steps to reproduce the problem
1. 按照快速上手配置
2. 插件程序只配置了 classpath 'com.qihoo360.replugin:replugin-plugin-gradle:2.3.2'，
apply plugin: 'replugin-plugin-gradle'， 
implementation 'com.qihoo360.replugin:replugin-plugin-lib:2.3.2'
着三项
3.我直接将demo1的jar放在我主程序是可以直接显示的，而我自己写的插件就是一个黑屏

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by hyongbai** [comment]
demo1可以正常运行，那么很大概率是插件本身有逻辑上面的错误。

如果是黑屏并且无响应那么可能是 ANR。

如果仅仅黑屏而为发生崩溃那么可能是插件Activity 本身逻辑问题。

无更多细节 log 的前提下，先行关闭这个 issue。
