### ISSUE TITLE
进程

### ISSUE THREAD

**Issue by json-pu** [Qihoo360/RePlugin#816]
#### 问题详细描述 Detailed description of the problem
有多个进程的应用，比如有主进程，Push进程，RePlugin.App.attachBaseContext(this);可以只在主进程执行，而忽略其他非主进程吗？

**Comment by json-pu** [comment]
貌似只需要关注主进程和:GuardService进程

**Comment by hyongbai** [comment]
理论上来说，如果在所在的进程中不想执行任何 RePlugin 代码，可以设定不在当前进程初始化 RePlugin 问题。

但是，一定要确保当前进程中不会有任何与 RePlugin 管理的逻辑。

RePlugin自己生成的用于分配给插件使用的进程，务必初始化。

原则上不会有太多性能损耗，修改需谨慎。

此 issue 无问题产生。先行关闭。
