### ISSUE TITLE
看了180+个 issues,感觉RePlugin的使用问题还是很大的

### ISSUE THREAD

**Issue by mrme2014** [Qihoo360/RePlugin#817]
这不是一个问题issue。是一个问题总结的issues。
从目前众多的 issue的反馈来看RePlugin在运行阶段 存在不少资源使用，类加载的问题。慎重使用

**Comment by chinacuizichao** [comment]
团队维护力度下降，issuse关闭速度变慢了。

**Comment by mrme2014** [comment]
那意思也就是不建议 使用了咯？

**Comment by Alvin917** [comment]
有更好的推荐吗？
