### ISSUE TITLE
插件中使用fragment

### ISSUE THREAD

**Issue by like5188** [Qihoo360/RePlugin#818]
#### 问题详细描述 Detailed description of the problem
内置插件1怎样才能使用内置插件2中的fragment

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by hyongbai** [comment]
获取插件2的 classloader并使用此 classloader实例化插件2中的你要的 Fragment即可。
