### ISSUE TITLE
在PluginApp中导入aar，启动aar中的Activity（启动Activity被封装到了aar中），此时会出现android.content.ActivityNotFoundException

### ISSUE THREAD

**Issue by ww3mm4** [Qihoo360/RePlugin#819]
#### 问题详细描述 Detailed description of the problem
在PluginApp中导入aar，启动aar中的Activity（启动Activity被封装到了aar中），此时会出现android.content.ActivityNotFoundException

**Comment by hyongbai** [comment]
Activity 在 aar 中的 Manifest 注册了吗？

RePlugin 在启动插件的时候会预读取插件的 Manifest，并将其按照 Activity、Service、Provider 类别解析出来并缓存。

启动时，如果插件的Manifest中并没有相应的 Activity 信息，则认为此Activity 不是对应插件内部，此时交给系统就会出现android.content.ActivityNotFoundException。
