### ISSUE TITLE
作为插件的模块，本身能作为其他子插件的宿主么

### ISSUE THREAD

**Issue by lynn01247** [Qihoo360/RePlugin#826]
作为插件A的模块，本身能作为其他子插件B的宿主么？

A本身是主工程的插件模块（生成apk模式），作为插件需要配置replugin-plugin-gradle 依赖
但同时是子插件B的宿主，作为宿主又要配置eplugin-host-gradle 依赖，同时引用会造成冲突么？

发现引入双重依赖的情况下，“非继承式”配置Application报错：
RePlugin.App.attachBaseContext(this);  // .App报红，主工程提示该行错误

**Comment by bnotebook** [comment]
这种方式编译阶段应该就会出问题，运行阶段也会有类冲突等问题。
