### ISSUE TITLE
有没有讨论群啊，官方给的qq群已经满员加不了了

### ISSUE THREAD

**Issue by SuperChandler** [Qihoo360/RePlugin#827]
#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by bnotebook** [comment]
群1已满，可以加群2。wiki里有。
