### ISSUE TITLE
插件支持接收宿主发送的广播么，我这边宿主确实发送了广播，但是插件就是接收不到··

### ISSUE THREAD

**Issue by SuperChandler** [Qihoo360/RePlugin#828]
#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by bnotebook** [comment]
确认是否注册。插件化里面是支持宿主-插件，插件-插件之间的广播的。
