### ISSUE TITLE
坑位是个什么样的概念？

### ISSUE THREAD

**Issue by DespairK** [Qihoo360/RePlugin#833]
在gradle文件中配置的坑位是个什么概念?
 // 背景不透明的坑的数量
    countNotTranslucentStandard 
    countNotTranslucentSingleTop 
    countNotTranslucentSingleTask 
    countNotTranslucentSingleInstance 

    // 背景透明的坑的数量
    countTranslucentStandard
    countTranslucentSingleTop 
    countTranslucentSingleTask 
    countTranslucentSingleInstance 
这些参数具体指代了什么，相关wiki在哪里

**Comment by bnotebook** [comment]
https://github.com/Qihoo360/RePlugin/wiki/%E9%AB%98%E7%BA%A7%E8%AF%9D%E9%A2%98
https://www.jianshu.com/p/74a70dd6adc9

**Comment by DespairK** [comment]
这个坑位的数量，包括透明坑和不透明坑该如何分配，这两点该如何确定
