### ISSUE TITLE
文档是不是还没全？？

### ISSUE THREAD

**Issue by pzfa** [Qihoo360/RePlugin#84]
声明一个插件的Activity
打开一个插件的Activity
运行插件

这些是不是都没整理好 好像看不了？？

**Comment by wangyupeng1-iri** [comment]
正在整理中 ......

**Comment by jiongxuan** [comment]
@pzfa 好的，我们预计明天上传这些文档。其实已经写了一半多了，只是老想着完善，所以一直没有放上去。

感谢您的关注。敬请期待。
