### ISSUE TITLE
覆盖安装插件不生效

### ISSUE THREAD

**Issue by Hiram-Y** [Qihoo360/RePlugin#85]
app 覆盖安装后，杀死进程，切换到后台，都是加载的旧的插件，必须把app卸载重新安装才生效，不知道为什么？

**Comment by jiongxuan** [comment]
您好，我们目前“覆盖安装插件”仅支持升级（也即——版本必须+1）。

我们已有App反馈这么做不太方便（虽然也能调试，只不过每次都要+1而已）。我们会在2.1.2解决这个事儿，在保证稳定的前提下，允许App覆盖安装插件。

**Comment by jiongxuan** [comment]
这个已经在2.1.5及以上版本解决了。请升级到最新版本试试。

**Comment by 13621877812** [comment]
我的2.2.4  还是遇到同样的问题

**Comment by 13621877812** [comment]
内直插件版本更新，新的版本覆盖老的版本，但插件的内容还是老的内容
