### ISSUE TITLE
每升级一个版本能否在wiki上写一下更新的内容呢？方便使用，谢谢啦

### ISSUE THREAD

**Issue by Hiram-Y** [Qihoo360/RePlugin#86]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:

**Android compile SDK version**:

**Android ROM**:

**Comment by wangyupeng1-iri** [comment]
稍后会写进wiki.
