### ISSUE TITLE
找不到loader.p.main

### ISSUE THREAD

**Issue by fanrenyi** [Qihoo360/RePlugin#87]
07-03 22:45:44.804 20538-20538/? E/ActivityThread: Failed to find provider info for com.ss.android.auto.loader.p.main
07-03 22:45:44.805 20538-20538/? E/ws001: p.p fhb fail
07-03 22:45:44.975 20558-20558/com.ss.android.auto E/ActivityThread: Failed to find provider info for com.ss.android.auto.loader.p.main
07-03 22:45:44.976 20558-20558/com.ss.android.auto E/ws001: p.p fhb fail
07-03 22:45:45.118 20576-20576/com.ss.android.auto E/ActivityThread: Failed to find provider info for com.ss.android.auto.loader.p.main
07-03 22:45:45.119 20576-20576/com.ss.android.auto E/ws001: p.p fhb fail

**RePlugin version**:
2.1.0
**Android compile SDK version**:
15
**Android ROM**:
any rom

**Comment by fanrenyi** [comment]
这个问题我找到原因了，打包脚本里面，占位用的包名是com.qihoo360.mobilesafe.core.loader.p.main，而java代码里面，用的是当前项目的package name，希望脚本能改下。

**Comment by erhu** [comment]
是不是 Host 的 Application 没有初始化 RePlugin .

**Comment by fanrenyi** [comment]
这个问题最终解决方案是，gradle配置applicationId，之前没配置，所以脚本用的是360的默认包名，希望接入文档里面，把这点注明。

**Comment by closedevice** [comment]
是在宿主中配置还是插件中配置?

**Comment by jiongxuan** [comment]
@fanrenyi 感谢您的提醒。如果您的ApplicationID是配置自AndroidManifest.xml而非build.gradle的话，那么确实有可能出现这个问题。关于此点 @erhu 兄和 @wangyupeng1-iri 兄可以看下。

目前现阶段，我会将其补充到“主程序接入指南”中，让后面的人能更清晰。
再次感谢大家的建议。

**Comment by jiongxuan** [comment]
文档已补充:)

**Comment by windyfrank** [comment]
2019-05-06 10:47:06.939 4696-4696/com.hxxxxx.hxxexxxion.smarthome E/ActivityThread: Failed to find provider info for com.hxxxxx.hxxexxxion.smarthome.loader.p.main
2019-05-06 10:47:06.939 4696-4696/com.hxxxxx.hxxexxxion.smarthome D/RePlugin.ws001: proxy fetch binder: cursor is null
2019-05-06 10:47:06.939 4696-4696/com.hxxxxx.hxxexxxion.smarthome D/RePlugin.ws001: host binder = null
2019-05-06 10:47:06.940 4696-4696/com.hxxxxx.hxxexxxion.smarthome E/ws001: p.p fhb fail
2019-05-06 10:47:06.943 4696-4696/com.hxxxxx.hxxexxxion.smarthome I/ision.smarthom: System.exit called, status: 1

我还是有这个问题，目前已经确认applicationId配置在gradle文件中，applicationId为com.hxxxxx.hxxexxxion.smarthome，能够帮忙看下，多谢

**Comment by Luckflower** [comment]
> 2019-05-06 10:47:06.939 4696-4696/com.hxxxxx.hxxexxxion.smarthome E/ActivityThread: Failed to find provider info for com.hxxxxx.hxxexxxion.smarthome.loader.p.main
> 2019-05-06 10:47:06.939 4696-4696/com.hxxxxx.hxxexxxion.smarthome D/RePlugin.ws001: proxy fetch binder: cursor is null
> 2019-05-06 10:47:06.939 4696-4696/com.hxxxxx.hxxexxxion.smarthome D/RePlugin.ws001: host binder = null
> 2019-05-06 10:47:06.940 4696-4696/com.hxxxxx.hxxexxxion.smarthome E/ws001: p.p fhb fail
> 2019-05-06 10:47:06.943 4696-4696/com.hxxxxx.hxxexxxion.smarthome I/ision.smarthom: System.exit called, status: 1
> 
> 我还是有这个问题，目前已经确认applicationId配置在gradle文件中，applicationId为com.hxxxxx.hxxexxxion.smarthome，能够帮忙看下，多谢

我也遇到这问题，你那边解决了吗？
