### ISSUE TITLE
一直报You need to use a Theme.AppCompat theme (or descendant) with this activity.的错误

### ISSUE THREAD

**Issue by JackMask** [Qihoo360/RePlugin#878]
#### 问题详细描述 Detailed description of the problem
在插件的activity 一直报You need to use a Theme.AppCompat theme (or descendant) with this activity.的错误 ，我照着配置了**useAppCompat**属性。但一直会报这个错，我也偿试着替换成普通 的activity也会出现这样的错，我把主题全删除了也会出现，甚至在每个activity上加主题 ，也是一样。现在我非常着急，不知道为什么会出现这样的情况

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.3.3
rePlugin-plugin-lib/gradle Version:2.3.3

Android API Version：28
Android 手机型号&ROM(Phone model & ROM):

**Comment by rt-wong** [comment]
这个问题你是怎么解决的呢？
