### ISSUE TITLE
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f08005a

### ISSUE THREAD

**Issue by techinsight** [Qihoo360/RePlugin#884]
#### 问题详细描述 Detailed description of the problem
插件化改造后，宿主中可以调用显示插件fragment。但在fragment中再想启动插件内Activity时就出现错误了。

排查分析两天，依然无果。急求解决！！！！

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.3.3
rePlugin-plugin-lib/gradle Version: 2.3.3

Android API Version：28
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context
09-25 14:17:22.342  1633 27786 E ActivityManager: check screen state before start activity screen STATE = true
09-25 14:17:22.342  1633 27786 D ---framework--DeviceControlManager---: isAppLegal packageName = com.xx.host
09-25 14:17:22.343  2034  2045 D DeviceControlService: isAppLegal packageNamexxx = com.xx.host
09-25 14:17:22.343  1633 27786 D ---framework--DeviceControlManager---: getRunAppPolicies
09-25 14:17:22.343  2034  2430 I ApplicationUtil: getRunAppPolicies mode = 0
09-25 14:17:22.343  1633 27786 I ActivityManager: START u0 {cat=[plugin:com.xx.androidteam.policeportalapp,process:-2147483648,activity:com.xx.androidteam.policeportalapp.ui.activity.PluginTargetActivity,container:com.xx.host.loader.a.ActivityN1NRNTS5,counter:0] cmp=com.xx.host/.loader.a.ActivityN1NRNTS5 (has extras)} from uid 10185 on display 0
09-25 14:17:22.344  1633 27786 D ActivityManager: sAllowedServices  length= 0
09-25 14:17:22.344  1633 27786 W ActivityManager: startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { cat=[plugin:com.xx.androidteam.policeportalapp,process:-2147483648,activity:com.xx.androidteam.policeportalapp.ui.activity.PluginTargetActivity,container:com.xx.host.loader.a.ActivityN1NRNTS5,counter:0] cmp=com.xx.host/.loader.a.ActivityN1NRNTS5 (has extras) }
09-25 14:17:22.346   710  1090 I audio_hw_primary: select_devices Selected apptype: 69937
09-25 14:17:22.346   710  1090 D soundtrigger: audio_extn_sound_trigger_update_stream_status: uc_id 1 of type 0 for Event 3, with Raise=0
09-25 14:17:22.347   710  1090 I audio_hw_utils: audio_extn_utils_send_app_type_cfg PLAYBACK app_type = 69937, acdb_dev_id = 135, sample_rate = 48000
09-25 14:17:22.347   710  1090 D msm8916_platform: platform_can_split_snd_device: snd_device(6) num devices(1) new_snd_devices(-237501320)
09-25 14:17:22.347   710  1090 D ACDB-LOADER: ACDB -> send_audio_cal, acdb_id = 135, path = 0, app id = 0x11131, sample rate = 48000
09-25 14:17:22.347   710  1090 D ACDB-LOADER: ACDB -> send_asm_topology
09-25 14:17:22.347   710  1090 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
09-25 14:17:22.347   710  1090 D ACDB-LOADER: ACDB -> send_adm_topology
09-25 14:17:22.347   710  1090 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
09-25 14:17:22.347   710  1090 D ACDB-LOADER: ACDB -> send_audtable
09-25 14:17:22.347   710  1090 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE_SIZE
09-25 14:17:22.347   710  1090 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
09-25 14:17:22.347   710  1090 D ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_CAL
09-25 14:17:22.347   710  1090 D ACDB-LOADER: ACDB -> send_audvoltable
09-25 14:17:22.347   710  1090 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE, vol index 0
09-25 14:17:22.347   710  1090 D ACDB-LOADER: ACDB -> AUDIO_SET_VOL_CAL cal type = 12
09-25 14:17:22.347   710  1090 D ACDB-LOADER: ACDB -> send_audstrmtable
09-25 14:17:22.347   710  1090 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TABLE_V2
09-25 14:17:22.347   710  1090 D ACDB-LOADER: ACDB -> audstrm_cal->cal_type.cal_data.cal_size = 16
09-25 14:17:22.347   710  1090 D ACDB-LOADER: ACDB -> send_afe_topology
09-25 14:17:22.347   710  1090 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_TOPOLOGY_ID
09-25 14:17:22.347   710  1090 D ACDB-LOADER: ACDB -> GET_AFE_TOPOLOGY_ID for adcd_id 135, Topology Id 1025e
09-25 14:17:22.347   710  1090 D ACDB-LOADER: ACDB -> send_afe_cal
09-25 14:17:22.347   710  1090 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
09-25 14:17:22.347   710  1090 D ACDB-LOADER: ACDB -> AUDIO_SET_AFE_CAL
09-25 14:17:22.347   710  1090 D ACDB-LOADER: ACDB -> send_hw_delay : acdb_id = 135 path = 0
09-25 14:17:22.347   710  1090 D ACDB-LOADER: ACDB -> ACDB_AVSYNC_INFO: ACDB_CMD_GET_DEVICE_PROPERTY
09-25 14:17:22.348   710  1090 D audio_hw_primary: enable_audio_route: apply mixer and update path: low-latency-playback
09-25 14:17:22.348   710  1090 D audio_hw_primary: select_devices: done
09-25 14:17:22.350  1633 27786 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
09-25 14:17:22.358   710  1090 D msm8916_platform: platform_set_channel_map mixer_ctl_name:Playback Channel Map12
09-25 14:17:22.358   710  1090 D msm8916_platform: platform_set_channel_map: set mapping(1 2 0 0 0 0 0 0) for channel:2
09-25 14:17:22.366  1633 25960 I ActivityManager: Killing 32088:com.android.printspooler/u0a57 (adj 906): empty #4
09-25 14:17:22.377 32137 32137 D RePlugin.ws001: found: ActivityState {container=com.xx.host.loader.a.ActivityN1NRNTS5 state=restored plugin=com.xx.androidteam.policeportalapp activity=com.xx.androidteam.policeportalapp.ui.activity.PluginTargetActivity size=0}
09-25 14:17:22.377 32137 32137 D RePlugin.ws001: PACM: loadActivityClass in=com.xx.host.loader.a.ActivityN1NRNTS5 target=com.xx.androidteam.policeportalapp.ui.activity.PluginTargetActivity plugin=com.xx.androidteam.policeportalapp
09-25 14:17:22.378 32137 32137 D RePlugin.ws001: PStatusC.getStatus(): ps is null. pn=com.xx.androidteam.policeportalapp
09-25 14:17:22.378 32137 32137 I RePlugin.ws000: loadLocked(): Initialized, is loaded = true
09-25 14:17:22.378 32137 32137 D RePlugin.ws001: PACM: loadActivityClass, plugin activity loader: in=com.xx.host.loader.a.ActivityN1NRNTS5 activity=com.xx.androidteam.policeportalapp.ui.activity.PluginTargetActivity
09-25 14:17:22.378 32137 32137 D RePlugin.ws001: PACM: loadActivityClass, plugin activity loader: c=class com.xx.androidteam.policeportalapp.ui.activity.PluginTargetActivity, loader=com.qihoo360.replugin.PluginDexClassLoader[DexPathList[[zip file "/data/user/0/com.xx.host/app_p_a/-1607123362.jar"],nativeLibraryDirectories=[/data/user/0/com.xx.host/app_p_n/-1607123362, /system/lib64, /vendor/lib64]]]
09-25 14:17:22.392  1633 27790 D ActivityManager: cleanUpApplicationRecordLocked -- app = 32088:com.android.printspooler/u0a57
09-25 14:17:22.410 32137 32137 W ResourceType: For resource 0x7f08005a, entry index(90) is beyond type entryCount(5)
09-25 14:17:22.410 32137 32137 W ResourceType: Failure getting entry for 0x7f08005a (t=7 e=90) (error -75)
09-25 14:17:22.410 32137 32137 D AndroidRuntime: Shutting down VM
09-25 14:17:22.411 32137 32137 W System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xx.host/com.xx.host.loader.a.ActivityN1NRNTS5}: android.content.res.Resources$NotFoundException: Resource ID #0x7f08005a
09-25 14:17:22.411 32137 32137 W System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2681)
09-25 14:17:22.411   710  1090 D audio_hw_primary: start_output_stream: exit
09-25 14:17:22.411 32137 32137 W System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2744)
09-25 14:17:22.411 32137 32137 W System.err: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
09-25 14:17:22.411 32137 32137 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1481)
09-25 14:17:22.411 32137 32137 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-25 14:17:22.411 32137 32137 W System.err: 	at android.os.Looper.loop(Looper.java:154)
09-25 14:17:22.411 32137 32137 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6144)
09-25 14:17:22.411 32137 32137 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
09-25 14:17:22.411 32137 32137 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
09-25 14:17:22.411 32137 32137 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
09-25 14:17:22.411 32137 32137 W System.err: Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f08005a
09-25 14:17:22.411 32137 32137 W System.err: 	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:190)
09-25 14:17:22.411 32137 32137 W System.err: 	at android.content.res.Resources.getValue(Resources.java:1290)
09-25 14:17:22.411 32137 32137 W System.err: 	at android.support.v7.widget.AppCompatDrawableManager.createDrawableIfNeeded(AppCompatDrawableManager.java:235)
09-25 14:17:22.411 32137 32137 W System.err: 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:200)
09-25 14:17:22.411 32137 32137 W System.err: 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191)
09-25 14:17:22.412 32137 32137 W System.err: 	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:753)
09-25 14:17:22.412 32137 32137 W System.err: 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:196)
09-25 14:17:22.412 32137 32137 W System.err: 	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:86)
09-25 14:17:22.412 32137 32137 W System.err: 	at android.support.v7.app.AppCompatDelegateImpl.<init>(AppCompatDelegateImpl.java:260)
09-25 14:17:22.412 32137 32137 W System.err: 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:182)
09-25 14:17:22.412 32137 32137 W System.err: 	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:520)
09-25 14:17:22.412 32137 32137 W System.err: 	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
09-25 14:17:22.412 32137 32137 W System.err: 	at com.xx.androidteam.policeportalapp.ui.activity.PluginTargetActivity.onCreate(PluginTargetActivity.kt:9)
09-25 14:17:22.412 32137 32137 W System.err: 	at android.app.Activity.performCreate(Activity.java:6727)
09-25 14:17:22.412 32137 32137 W System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
09-25 14:17:22.412 32137 32137 W System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2634)
09-25 14:17:22.412 32137 32137 W System.err: 	... 9 more
09-25 14:17:22.420 32137 32137 W System.err: java.io.IOException: Permission denied
09-25 14:17:22.421 32137 32137 W System.err: 	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
09-25 14:17:22.421 32137 32137 W System.err: 	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)
09-25 14:17:22.421 32137 32137 W System.err: 	at java.io.File.createNewFile(File.java:948)
09-25 14:17:22.421 32137 32137 W System.err: 	at com.xx.androidteam.policeportalapp.ui.CrashHandler._dumpExceptionToSDCard(CrashHandler.java:149)
09-25 14:17:22.421 32137 32137 W System.err: 	at com.xx.androidteam.policeportalapp.ui.CrashHandler._handleException(CrashHandler.java:117)
09-25 14:17:22.421 32137 32137 W System.err: 	at com.xx.androidteam.policeportalapp.ui.CrashHandler.uncaughtException(CrashHandler.java:63)
09-25 14:17:22.421 32137 32137 W System.err: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
09-25 14:17:22.421 32137 32137 W System.err: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
09-25 14:17:25.442 32137 32137 D RePlugin.ws001: start context: intent=Intent { flg=0x10000000 cmp=com.xx.host/com.xx.androidteam.policeportalapp.ui.activity.WelcomeActivity }
09-25 14:17:25.443 32137 32137 D RePlugin.ws001: start context: custom context=com.qihoo360.loader2.PluginContext@9dd9ac9
09-25 14:17:25.443 32137 32137 D RePlugin.loadClass: isHookingClass(null,com.xx.androidteam.policeportalapp.ui.activity.WelcomeActivity) = false
09-25 14:17:25.443 32137 32137 D RePlugin.ws001: start context: custom plugin is empty, query plugin=null
09-25 14:17:25.443 32137 32137 D RePlugin.ws001: start activity: intent=Intent { flg=0x10000000 cmp=com.xx.host/com.xx.androidteam.policeportalapp.ui.activity.WelcomeActivity } plugin=com.xx.androidteam.policeportalapp activity=com.xx.androidteam.policeportalapp.ui.activity.WelcomeActivity process=-2147483648
09-25 14:17:25.444 32137 32137 D RePlugin.ws001: start activity: intent=Intent { flg=0x10000000 cmp=com.xx.host/com.xx.androidteam.policeportalapp.ui.activity.WelcomeActivity } plugin=com.xx.androidteam.policeportalapp activity=com.xx.androidteam.policeportalapp.ui.activity.WelcomeActivity process=-2147483648 download=true
09-25 14:17:25.444 32137 32137 D RePlugin.loadClass: isHookingClass(com.xx.androidteam.policeportalapp , com.xx.androidteam.policeportalapp.ui.activity.WelcomeActivity) = false
09-25 14:17:25.444 32137 32137 D RePlugin.ws001: PStatusC.getStatus(): ps is null. pn=com.xx.androidteam.policeportalapp
09-25 14:17:25.446 32137 32137 D RePlugin.ws001: PStatusC.getStatus(): ps is null. pn=com.xx.androidteam.policeportalapp
09-25 14:17:25.446 32137 32137 I RePlugin.ws000: loadLocked(): Initialized, is loaded = true
09-25 14:17:25.447 32137 32137 D RePlugin.theme: intent.putExtra(com.xx.androidteam.policeportalapp.ui.activity.WelcomeActivity, 2131755320);
09-25 14:17:25.448 32612 32624 D RePlugin.ws001: start plugin process: plugin=com.xx.androidteam.policeportalapp info=com.qihoo360.loader2.PluginBinderInfo@32e1b13
09-25 14:17:25.449 32612 32624 D PluginProcessMain: com.qihoo360.loader2.PluginProcessMain.probePluginClient(PluginProcessMain.java:344)(1ms@Thread[Binder:32612_1,5,main]) READING
09-25 14:17:25.451 32612 32624 D PluginProcessMain: com.qihoo360.loader2.PluginProcessMain.probePluginClient(PluginProcessMain.java:344)(2ms@Thread[Binder:32612_1,5,main]) READING DONE
09-25 14:17:25.451 32612 32624 D RePlugin.ws001: start plugin process: probe client ok, already running, plugin=com.xx.androidteam.policeportalapp client=com.qihoo360.loader2.IPluginClient$Stub$Proxy@b3dc602
09-25 14:17:25.453 32137 32137 D RePlugin.ws001: PStatusC.getStatus(): ps is null. pn=com.xx.androidteam.policeportalapp
09-25 14:17:25.453 32137 32137 I RePlugin.ws000: loadLocked(): Initialized, is loaded = true
09-25 14:17:25.453 32137 32137 D RePlugin.task-affinity: originTaskAffinity is com.xx.androidteam.policeportalapp
09-25 14:17:25.453 32137 32137 D RePlugin.ws001: PACM: alloc registered container=com.xx.host.loader.a.ActivityN1NRNTS0
09-25 14:17:25.453 32137 32137 D RePlugin.ws001: PACM: bindActivity: lookup activity container: container=com.xx.host.loader.a.ActivityN1NRNTS0
09-25 14:17:25.454 32137 32137 D RePlugin.ws001: PACM: eval plugin com.xx.androidteam.policeportalapp, target=com.xx.androidteam.policeportalapp.ui.activity.WelcomeActivity, container=com.xx.host.loader.a.ActivityN1NRNTS0
09-25 14:17:25.454 32137 32137 I RePlugin.ws001: alloc success: container=com.xx.host.loader.a.ActivityN1NRNTS0 plugin=com.xx.androidteam.policeportalapp activity=com.xx.androidteam.policeportalapp.ui.activity.WelcomeActivity
09-25 14:17:25.455 32137 32137 D RePlugin.ws001: start activity: real intent=Intent { cat=[plugin:com.xx.androidteam.policeportalapp,process:-2147483648,activity:com.xx.androidteam.policeportalapp.ui.activity.WelcomeActivity,container:com.xx.host.loader.a.ActivityN1NRNTS0,counter:0] flg=0x10000000 cmp=com.xx.host/.loader.a.ActivityN1NRNTS0 (has extras) }
09-25 14:17:25.455 32137 32137 D RePlugin.ws001: start context: intent=Intent { cat=[plugin:com.xx.androidteam.policeportalapp,process:-2147483648,activity:com.xx.androidteam.policeportalapp.ui.activity.WelcomeActivity,container:com.xx.host.loader.a.ActivityN1NRNTS0,counter:0] flg=0x10000000 cmp=com.xx.host/.loader.a.ActivityN1NRNTS0 (has extras) }
09-25 14:17:25.455 32137 32137 D RePlugin.ws001: start context: custom context=com.qihoo360.loader2.PluginContext@9dd9ac9
09-25 14:17:25.455 32137 32137 D RePlugin.ws001: start context: context is container, direct start
09-25 14:17:25.457  1633 25960 E ActivityManager: check screen state before start activity screen STATE = true
09-25 14:17:25.457  1633 25960 D ---framework--DeviceControlManager---: isAppLegal packageName = com.xx.host
09-25 14:17:25.458  2034  9922 D DeviceControlService: isAppLegal packageNamexxx = com.xx.host
09-25 14:17:25.458  1633 25960 D ---framework--DeviceControlManager---: getRunAppPolicies

**Comment by techinsight** [comment]
宿主，插件gradle-plugin 2.3.3，gradle  5.3.1版本一致。单独运行都可以。
fragment内使用了主程序调用插件activity方式进行调用。

**Comment by ljd1996** [comment]
@techinsight 请问你是怎么解决这个问题的呢？我这边是只要插件Activity设置了setContentView就会报错android.content.res.Resources$NotFoundException
