### ISSUE TITLE
编译失败：Execution failed for task ':app:transformClassesWith___ReClass___ForProdRelease' >  java.io.IOException: Unable to delete file:

### ISSUE THREAD

**Issue by techinsight** [Qihoo360/RePlugin#893]
10:38:44.777 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
10:38:44.777 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
10:38:44.777 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
10:38:44.777 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
10:38:44.777 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':app:transformClassesWith___ReClass___ForProdRelease'.
10:38:44.777 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > java.io.IOException: Unable to delete file: C:\Program Files (x86)\Jenkins\workspace\PolicePortal\caches\modules-2\files-2.1\com.android.databinding\baseLibrary\3.1.4\df1e7638ba852152abe964e86f60fa4ce12e6a6a\baseLibrary-3.1.4.jar
10:38:44.777 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
10:38:44.777 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
10:38:44.777 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]  Run with --scan to get full insights.
10:38:44.778 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
10:38:44.778 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
10:38:44.778 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWith___ReClass___ForProdRelease'.
10:38:44.778 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
10:38:44.778 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
10:38:44.778 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
10:38:44.778 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
10:38:44.778 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
10:38:44.778 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
10:38:44.778 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
10:38:44.778 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.RuntimeException: java.io.IOException: Unable to delete file: C:\Program Files (x86)\Jenkins\workspace\PolicePortal\caches\modules-2\files-2.1\com.android.databinding\baseLibrary\3.1.4\df1e7638ba852152abe964e86f60fa4ce12e6a6a\baseLibrary-3.1.4.jar
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:212)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
10:38:44.779 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	... 31 more
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.io.IOException: Unable to delete file: C:\Program Files (x86)\Jenkins\workspace\PolicePortal\caches\modules-2\files-2.1\com.android.databinding\baseLibrary\3.1.4\df1e7638ba852152abe964e86f60fa4ce12e6a6a\baseLibrary-3.1.4.jar
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2381)
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.apache.commons.io.FileUtils$forceDelete.call(Unknown Source)
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.qihoo360.replugin.gradle.plugin.inner.Util$_getProjectClassPath_closure2$_closure5.doCall(Util.groovy:112)
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.qihoo360.replugin.gradle.plugin.inner.Util$_getProjectClassPath_closure2.doCall(Util.groovy:78)
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.qihoo360.replugin.gradle.plugin.inner.Util.getProjectClassPath(Util.groovy:68)
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.qihoo360.replugin.gradle.plugin.inner.Util.getClassPaths(Util.groovy:49)
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.qihoo360.replugin.gradle.plugin.inner.Util$getClassPaths$0.call(Unknown Source)
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.qihoo360.replugin.gradle.plugin.inner.ReClassTransform.initClassPool(ReClassTransform.groovy:214)
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.qihoo360.replugin.gradle.plugin.inner.ReClassTransform$initClassPool$1.callCurrent(Unknown Source)
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.qihoo360.replugin.gradle.plugin.inner.ReClassTransform.doTransform(ReClassTransform.groovy:124)
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.qihoo360.replugin.gradle.plugin.inner.ReClassTransform$doTransform$0.callCurrent(Unknown Source)
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.qihoo360.replugin.gradle.plugin.inner.ReClassTransform.transform(ReClassTransform.groovy:94)
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.android.build.api.transform.Transform.transform(Transform.java:288)
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:221)
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:217)
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	... 44 more
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
10:38:44.780 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] 
10:38:44.781 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 8m 39s
10:38:44.781 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] 135 actionable tasks: 128 executed, 7 up-to-date
10:38:44.791 [DEBUG] [org.jetbrains.kotlin.gradle.plugin.KotlinGradleBuildServices] [KOTLIN] Deleted session-is-alive flag file: build\kotlin\sessions\kotlin-compiler-9207611389234904963.salive
10:38:44.792 [DEBUG] [org.jetbrains.kotlin.gradle.plugin.KotlinGradleBuildServices] [KOTLIN] Disposed KotlinGradleBuildServices
10:38:44.792 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1 completed (0 worker(s) in use)
10:38:44.792 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker: released lock on root.1

**Comment by ll201lw** [comment]
分享一下怎么解决的，谢谢啦！
