### ISSUE TITLE
请问该方案与DroidPlugin有何不同？

### ISSUE THREAD

**Issue by Mrxxy** [Qihoo360/RePlugin#9]
目前项目在使用DroidPlugin实现插件化，而且它的介绍也是你们开源的，所以想问下这两者有什么不同

**Comment by jiongxuan** [comment]
好的。其实最主要的区别就一个：Hook点的多少。
DroidPlugin要Hook的点非常多，代价是失去了一定的稳定性（这点非常关键），而好处是APK可以“直接运行在主程序中”。
相反，RePlugin只Hook了ClassLoader，所以极为稳定，且同样支持绝大多数单品的特性。而APK只需要通过我们的Gradle编译，无需开发者修改Java Code，即可运行在主程序中。但出于稳定性考虑，我们不支持（也不打算支持）“直接将APK，不经修改就放到主程序中”。

此外，DroidPlugin是360手机助手团队做的，和我们不是一个Team，且**比我们要晚一年半**，才用于自己的产品，我们是2014年中旬做的（完整占坑类方案），相对更早。还有，我们的插件数量很多，总计达102个。

哦，再顺便说一句，现在助手已经将DroidPlugin切换到RePluign上了。

不知道这样回答是否解决了您的疑惑？

**Comment by krmao** [comment]
请问 内/外置插件可以引用 主apk 的资源部，就是插件自己不重复打包进主apk已有的资源

**Comment by Mrxxy** [comment]
十分感谢
