### ISSUE TITLE
WebView 加载插件中assets中的html资源，webview中提示无法加载ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by ghhbgtf** [Qihoo360/RePlugin#907]
#### 问题详细描述 Detailed description of the problem
WebView 加载插件中assets中的html资源，webview中提示无法加载ERR_FILE_NOT_FOUND

#### 复现问题步骤 Steps to reproduce the problem
1. 将样例插件webview的MainActivity中testUrl改为“file:///android_asset/test.html”，并在assets文件夹中新建一个test.html文件
2. test.html为任意合法的html文件
3.替换host的webview.jar
4.启动host，点击“Start plugin webview”

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by yeqiling** [comment]
项目wiki中提到过：https://github.com/Qihoo360/RePlugin/wiki/FAQ#q%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3webview%E5%8A%A0%E8%BD%BDasserts%E4%B8%AD%E7%9A%84html%E7%AD%89%E8%B5%84%E6%BA%90%E6%96%87%E4%BB%B6%E5%A4%B1%E8%B4%A5%E7%9A%84%E9%97%AE%E9%A2%98%E5%85%B7%E4%BD%93%E5%A6%82webviewloadurlfileandroid_assetxxxhtml%E6%97%B6%E6%8F%90%E7%A4%BArr_file_not_found
