### ISSUE TITLE
在AS2.3.3中Gradlew配置插件2.1.1不成功

### ISSUE THREAD

**Issue by flynihao53** [Qihoo360/RePlugin#92]
我在AS 2.3.3版本中配置最新的插件版本2.1.1，无论根据文档或者是在repositories、allprojects中 添加mavenCentral()
maven { url "https://dl.bintray.com/qihoo360/replugin" }
这两句都不能配置成功，提示Failed to resolve: com.qihoo360.replugin:replugin-host-lib:2.1.1

**Comment by wangyupeng1-iri** [comment]
你好， @flynihao53 请依赖2.1.0
