### ISSUE TITLE
发布一个支持AndroidX的Replugin分支

### ISSUE THREAD

**Issue by froyohuang** [Qihoo360/RePlugin#933]
#### 问题详细描述 Detailed description of the problem
RePlugin现在不支持AndroidX，我新建了一个Repo，帮助大家进行兼容。
https://github.com/froyohuang/replugin-androidx

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by wardenlzr** [comment]
@froyohuang  大佬，请问你发布的这个com.android.tools.build:gradle支持3.4.0吗？ 可以的话怎么使用哇？
