### ISSUE TITLE
Didn't find class "com.qihoo360.plugin.app2.Entry"

### ISSUE THREAD

**Issue by zhaolei9527** [Qihoo360/RePlugin#94]
报错：Didn't find class "com.qihoo360.plugin.app2.Entry"
插件调起成功，但是界面不对。

**Comment by aBenVip** [comment]
@zhaolei9527 可能是你host工程和插件工程gradle版本不一致，改为完全一致就行了

**Comment by zhaolei9527** [comment]
classpath 'com.android.tools.build:gradle:2.3.3'
gradle版本倒是一致的呀。

**Comment by aBenVip** [comment]
classpath 'com.android.tools.build:gradle:2.1.3'
gradle-wrapper.properties中：
distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip

**Comment by zhaolei9527** [comment]
这个插件是我自己创建的，跟主程序配置环境一致，不是官方demo1或者demo2。所以应该不是这个问题吧？

**Comment by zhaolei9527** [comment]
demo1，demo2倒是很正常。

**Comment by aBenVip** [comment]
貌似是现在只支持上述环境，你可以换一下试试

**Comment by zhaolei9527** [comment]
把插件的gradle版本换了，但是没什么用，还是一样的效果。插件的mainActivity里的方法都执行了，但是显示的插件界面不对，报错Didn't find class "com.qihoo360.plugin.app2.Entry"

**Comment by aBenVip** [comment]
我这边是这样解决的，已经能正常跑了

**Comment by zhaolei9527** [comment]
o(︶︿︶)o 唉

**Comment by zhaolei9527** [comment]
尝试后有效解决方法，需要对每个activity单独设置主题样式，统一的样式无效。

**Comment by LightFan0814** [comment]
这个问题怎么解决的
