### ISSUE TITLE
安装外置插件需要放在工作线程中吗？Replugin.install()

### ISSUE THREAD

**Issue by aBenVip** [Qihoo360/RePlugin#97]

**Comment by lvtanxi** [comment]
RePlugin.install(path) 后也没反应。 RePlugin.createIntent(String pluginName, String cls) 中的pluginName在哪里产生呢？

**Comment by aBenVip** [comment]
RePlugin.install(path) 会返回PluginInfo，这是插件的所有信息，但我调用了install方法没有反应

**Comment by lvtanxi** [comment]
RePlugin.install(path) 我返回的一直是null。我的插件直接放在assets下面就可以

**Comment by aBenVip** [comment]
外置插件没有相关的Sample，估计都卡在这儿了

**Comment by qq634421026** [comment]
@aBenVip  嗯 确实 外置的没成功

**Comment by lvtanxi** [comment]
@qq634421026 加你qq没有反应
