### ISSUE TITLE
是否支持加载插件后，直接调用插件中的某个静态方法? 

### ISSUE THREAD

**Issue by fangding** [Qihoo360/RePlugin#98]
例如:
前提： 宿主A 加载插件B后，已知插件B中存在 Utils.class    ，此class中存在 init(Context context)函数（static）。
问：是否可以直接调用 Utils.init(MainActivity.this)?

**Comment by fangding** [comment]
补充：
前提： 
  存在接口：
  interface CallBack{
         void onResule(); 
  }
宿主A 加载插件B后，已知插件B中存在 Utils.class ，此class中存在 init(Callback callback)函数（static）。

问：如果可以直接调用 Utils.init(MainActivity.this)?  那么init 静态函数中 是否可以直接 调用如下代码：
callback.onResule();

**Comment by fangding** [comment]
@jiongxuan

**Comment by jiongxuan** [comment]
您可以参考下Sample中的源码，里面有类似的用法

**Comment by longkehuawei** [comment]
怎么用啊

**Comment by longkehuawei** [comment]
解决了吗？
