### ISSUE TITLE
android 9、10、11 版本都可以正常使用replugin吗，谷歌规定的 hide ApI 对 replugin有影响吗 

### ISSUE THREAD

**Issue by gaoleicoding** [Qihoo360/RePlugin#997]
android 9、10、11 版本都可以正常使用replugin吗，谷歌规定的 hide ApI 对 replugin有影响吗

**Comment by loverxp** [comment]
我试了一下，API 29可以使用，但是Gradle只能使用2.3.3版本，新版本的Gradle无法使用

**Comment by loverxp** [comment]
我试了一下，API 29可以使用，但是Gradle只能使用2.3.3版本，新版本的Gradle无法使用

**Comment by krubo** [comment]
可以使用，无影响
